FBCTAU2 ; ;10/25/18
 D DE G BEGIN
DE S DIE="^FBAAA(D0,1,",DIC=DIE,DP=161.01,DL=2,DIEL=1,DU="" K DG,DE,DB Q:$O(^FBAAA(D0,1,DA,""))=""
 I $D(^(0)) S %Z=^(0) S %=$P(%Z,U,4) S:%]"" DE(5)=% S %=$P(%Z,U,14) S:%]"" DE(2)=% S %=$P(%Z,U,19) S:%]"" DE(8)=% S %=$P(%Z,U,20) S:%]"" DE(9)=%
 I $D(^(100)) S %Z=^(100) S %=$P(%Z,U,1) S:%]"" DE(6)=%
 I $D(^("C")) S %Z=^("C") S %=$P(%Z,U,1) S:%]"" DE(10)=%,DE(13)=%
 K %Z Q
 ;
W W !?DL+DL-2,DLB_": "
 Q
O D W W Y W:$X>45 !?9
 I $L(Y)>19,'DV,DV'["I",(DV["F"!(DV["K")) G RW^DIR2
 W:Y]"" "// " I 'DV,DV["I",$D(DE(DQ))#2 K X S X("FIELD")=DIFLD,X("FILE")=DP W "  ("_$$EZBLD^DIALOG(710,.X)_")" K X S X="" Q  ;**
TR Q:DV["K"&(DUZ(0)'="@")  R X:DTIME E  S (DTOUT,X)=U W $C(7)
 Q
A K DQ(DQ) S DQ=DQ+1
B G @DQ
RE G A:DV["K"&(DUZ(0)'["@"),PR:$D(DE(DQ)) D W,TR
N I X="" G NKEY:$D(^DD("KEY","F",DP,DIFLD)),A:DV'["R",X:'DV,X:D'>0,A
RD G QS:X?."?" I X["^" D D G ^DIE17
 I X="@" D D G Z^DIE2
 I X=" ",DV["d",DV'["P",$D(^DISV(DUZ,"DIE",DLB)) S X=^(DLB) I DV'["D",DV'["S" W "  "_X
T G M^DIE17:DV,^DIE3:DV["V",P:DV'["S" I X?.ANP D SET^DIED I 'DDER G V
 K DDER G X
P I DV["P" S DIC=U_DU,DIC(0)=$E("EN",$D(DB(DQ))+1)_"M"_$E("L",DV'["'") S:DIC(0)["L" DLAYGO=+$P(DV,"P",2) G:DV["*" AST^DIED D NOSCR^DIED S X=+Y,DIC=DIE G X:X<0
 G V:DV'["N" D D I $L($P(X,"."))>24 K X G Z
 I $P(DQ(DQ),U,5)'["$",X?.1"-".N.1".".N,$P(DQ(DQ),U,5,99)["+X'=X" S X=+X
V D @("X"_DQ) K YS
UNIQ I DV["U",$D(X),DIFLD=.01 K % M %=@(DIE_"""B"",X)") K %(DA) K:$O(%(0)) X
Z K DIC("S"),DLAYGO I $D(X),X'=U D:$G(DE(DW,"INDEX")) SAVEVALS G:'$$KEYCHK UNIQFERR^DIE17 S DG(DW)=X S:DV["d" ^DISV(DUZ,"DIE",DLB)=X G A
X W:'$D(ZTQUEUED) $C(7),"??" I $D(DB(DQ)) G Z^DIE17
 S X="?BAD"
QS S DZ=X D D,QQ^DIEQ G B
D S D=DIFLD,DQ(DQ)=DLB_U_DV_U_DU_U_DW_U_$P($T(@("X"_DQ))," ",2,99) Q
Y I '$D(DE(DQ)) D O G RD:"@"'[X,A:DV'["R"&(X="@"),X:X="@" S X=Y G N
PR S DG=DV,Y=DE(DQ),X=DU I $D(DQ(DQ,2)) X DQ(DQ,2) G RP
R I DG["P",@("$D(^"_X_"0))") S X=+$P(^(0),U,2) G RP:'$D(^(Y,0)) S Y=$P(^(0),U),X=$P(^DD(X,.01,0),U,3),DG=$P(^(0),U,2) G R
 I DG["V",+Y,$P(Y,";",2)["(",$D(@(U_$P(Y,";",2)_"0)")) S X=+$P(^(0),U,2) G RP:'$D(^(+Y,0)) S Y=$P(^(0),U) I $D(^DD(+X,.01,0)) S DG=$P(^(0),U,2),X=$P(^(0),U,3) G R
 X:DG["D" ^DD("DD") I DG["S" S %=$P($P(";"_X,";"_Y_":",2),";") I %]"" S Y=$S($G(DUZ("LANG"))'>1:%,'DIFLD:%,1:$$SET^DIQ(DP,DIFLD,Y))
RP D O I X="" S X=DE(DQ) G A:'DV,A:DC<2,N^DIE17
I I DV'["I",DV'["#" G RD
 D E^DIE0 G RD:$D(X),PR
 Q
SAVEVALS S @DIEZTMP@("V",DP,DIIENS,DIFLD,"O")=$G(DE(DQ)) S:$D(^("F"))[0 ^("F")=$G(DE(DQ))
 I $D(DE(DW,"4/")) S @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")=""
 E  K @DIEZTMP@("V",DP,DIIENS,DIFLD,"4/")
 Q
NKEY W:'$D(ZTQUEUED) "??  Required key field" S X="?BAD" G QS
KEYCHK() Q:$G(DE(DW,"KEY"))="" 1 Q @DE(DW,"KEY")
BEGIN S DNM="FBCTAU2",DQ=1
1 S D=0 K DE(1) ;.021
 S Y="^W^^0;1^Q" S $P(Y,U)=$$LABEL^DIALOGZ(DP,.021) S DG="2",DC="^161.06" D DIEN^DIWE K DE(1) G A
 ;
2 S DW="0;14",DV="S",DU="",DIFLD=2,DLB=$$LABEL^DIALOGZ(DP,DIFLD)
 S DU="1:C&P;2:OPT NSC;3:OPT SC;"
 G RE
X2 Q
3 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=3 D X3 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X3 S:'$D(FBAAASKV) FBAAASKV="N"
 Q
4 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=4 D X4 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X4 S:FBAAASKV'="y" Y=100
 Q
5 S DW="0;4",DV="P161.2",DU="",DIFLD=.04,DLB=$$LABEL^DIALOGZ(DP,DIFLD)
 S DE(DW)="C5^FBCTAU2"
 S DU="FBAAV("
 G RE
C5 G C5S:$D(DE(5))[0 K DB
 S X=DE(5),DIC=DIE
 K ^FBAAA("ACV",$E(X,1,30),DA(1),DA)
C5S S X="" G:DG(DQ)=X C5F1 K DB
 S X=DG(DQ),DIC=DIE
 S ^FBAAA("ACV",$E(X,1,30),DA(1),DA)=""
C5F1 Q
X5 Q
6 D:$D(DG)>9 F^DIE17,DE S DQ=6,DW="100;1",DV="P200'",DU="",DIFLD=100,DLB=$$LABEL^DIALOGZ(DP,DIFLD)
 S DU="VA(200,"
 S X=DUZ
 S Y=X
 S X=Y,DB(DQ)=1,DE(DW,"4/")="" G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD:X="@",Z
X6 Q
7 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=7 D X7 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X7 W !!
 Q
8 S DW="0;19",DV="FXO",DU="",DIFLD=.096,DLB=$$LABEL^DIALOGZ(DP,DIFLD)
 S DQ(8,2)="S Y(0)=Y D OUTYN^FBAAUTL3"
 S DE(DW)="C8^FBCTAU2"
 G RE
C8 G C8S:$D(DE(8))[0 K DB
 S X=DE(8),DIC=DIE
 K ^FBAAA("AA",X,$P(^FBAAA(DA(1),1,DA,0),U,1),DA(1),DA)
C8S S X="" G:DG(DQ)=X C8F1 K DB
 S X=DG(DQ),DIC=DIE
 S ^FBAAA("AA",X,$P(^FBAAA(DA(1),1,DA,0),U,1),DA(1),DA)=""
C8F1 Q
X8 I $D(X) D YN^FBAAUTL3
 I $D(X),X'?.ANP K X
 Q
 ;
9 D:$D(DG)>9 F^DIE17,DE S DQ=9,DW="0;20",DV="RFXO",DU="",DIFLD=.097,DLB=$$LABEL^DIALOGZ(DP,DIFLD)
 S DQ(9,2)="S Y(0)=Y D OUTYN^FBAAUTL3"
 S DE(DW)="C9^FBCTAU2"
 S X="NO"
 S Y=X
 G Y
C9 G C9S:$D(DE(9))[0 K DB
 S X=DE(9),DIC=DIE
 K ^FBAAA("AC",X,$P(^FBAAA(DA(1),1,DA,0),U,1),DA(1),DA)
 S X=DE(9),DIC=DIE
 K:$P(^FBAAA(DA(1),1,DA,0),U) ^FBAAA("AIC",DA(1),-($P(^FBAAA(DA(1),1,DA,0),U)),X,DA)
C9S S X="" G:DG(DQ)=X C9F1 K DB
 S X=DG(DQ),DIC=DIE
 S ^FBAAA("AC",X,$P(^FBAAA(DA(1),1,DA,0),U,1),DA(1),DA)=""
 S X=DG(DQ),DIC=DIE
 S:$P(^FBAAA(DA(1),1,DA,0),U) ^FBAAA("AIC",DA(1),-($P(^FBAAA(DA(1),1,DA,0),U)),X,DA)=""
C9F1 Q
X9 I $D(X) D YN^FBAAUTL3
 I $D(X),X'?.ANP K X
 Q
 ;
10 D:$D(DG)>9 F^DIE17,DE S DQ=10,DW="C;1",DV="FX",DU="",DIFLD=1,DLB=$$LABEL^DIALOGZ(DP,DIFLD)
 S DE(DW)="C10^FBCTAU2"
 S X="YES"
 S Y=X
 G Y
C10 G C10S:$D(DE(10))[0 K DB
 S X=DE(10),DIC=DIE
 D KILL^FBAAUTL2
 S X=DE(10),DIC=DIE
 K ^FBAAA("AF",$P(^FBAAA(DA(1),1,DA,0),U,3),DT,DA(1),DA)
C10S S X="" G:DG(DQ)=X C10F1 K DB
 S X=DG(DQ),DIC=DIE
 D ADD^FBAAUTL2
 S X=DG(DQ),DIC=DIE
 S ^FBAAA("AF",$P(^FBAAA(DA(1),1,DA,0),U,3),DT,DA(1),DA)=""
C10F1 Q
X10 I $D(X) D YN^FBAAUTL3
 I $D(X),X'?.ANP K X
 Q
 ;
11 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=11 D X11 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X11 S FBAAP79=$S(X["Y":"Y",1:"")
 Q
12 D:$D(DG)>9 F^DIE17,DE S Y=U,DQ=12 D X12 D:$D(DIEFIRE)#2 FIREREC^DIE17 G A:$D(Y)[0,A:Y=U S X=Y,DIC(0)="F",DW=DQ G OUT^DIE17
X12 I X["Y" S Y=""
 Q
13 D:$D(DG)>9 F^DIE17,DE S DQ=13,DW="C;1",DV="FX",DU="",DIFLD=1,DLB=$$LABEL^DIALOGZ(DP,DIFLD)
 S DE(DW)="C13^FBCTAU2"
 S X="@"
 S Y=X
 S X=Y,DB(DQ)=1 G:X="" N^DIE17:DV,A I $D(DE(DQ)),DV["I"!(DV["#") D E^DIE0 G A:'$D(X)
 G RD
C13 G C13S:$D(DE(13))[0 K DB
 S X=DE(13),DIC=DIE
 D KILL^FBAAUTL2
 S X=DE(13),DIC=DIE
 K ^FBAAA("AF",$P(^FBAAA(DA(1),1,DA,0),U,3),DT,DA(1),DA)
C13S S X="" G:DG(DQ)=X C13F1 K DB
 S X=DG(DQ),DIC=DIE
 D ADD^FBAAUTL2
 S X=DG(DQ),DIC=DIE
 S ^FBAAA("AF",$P(^FBAAA(DA(1),1,DA,0),U,3),DT,DA(1),DA)=""
C13F1 Q
X13 I $D(X) D YN^FBAAUTL3
 I $D(X),X'?.ANP K X
 Q
 ;
14 G 1^DIE17
