A1AAE2 ;1/18/89;ECF;ALBANY ISC
PRINTC ;PRINT CONDENSED
 I '$D(^DIZ(500009,N1,1,N2,0)) W !,"PROBLEM WITH XREF FOR THIS KEYWORD!" Q
 S ZZSTR=^DIZ(500009,N1,1,N2,0) W !,?4,$P(ZZSTR,U,1),!?6,"(" F I=2:1:4  S ZZKY=$P(ZZSTR,U,I) I ZZKY]"" I $D(^DIZ(500002,ZZKY,0)) W:I>2 ", " W ^(0)  
 W ")" S ZZLCT=ZZLCT+2 D LCK
 Q
PRINTE ;EXTENDED PRINT
 I '$D(^DIZ(500009,N1,1,N2,0)) W !"PROBLEM WITH XREF FOR THIS KEYWORD" Q
 S ZZSTR=^DIZ(500009,N1,1,N2,0) W !,?4,$P(ZZSTR,U,1) W:$P(ZZSTR,U,2)]"" ?42,^DIZ(500002,$P(ZZSTR,U,2),0) S ZZLCT=ZZLCT+1
 W !,?4,"FILED BY: ",$P(^DIC(3,$P(ZZSTR,U,5),0),U,1) W:$P(ZZSTR,U,3)]"" ?42,^DIZ(500002,$P(ZZSTR,U,3),0) S ZZLCT=ZZLCT+1
 S Y=$P(ZZSTR,U,6) X ^DD("DD") W !,?4,"FILED ON: ",$P(Y,"@",1) W:$P(ZZSTR,U,4)]"" ?42,^DIZ(500002,$P(ZZSTR,U,4),0) W ! S ZZLCT=ZZLCT+1
 D LCK
 Q
FLHD ;FIELD HEADING
 W !!,?2,$P(^DIZ(500009,N1,0),U,1),! S ZZLCT=ZZLCT+3
 Q
NWPG ;PRINT NEW PAGE
 I $E(IOST)="C" R !!,"HIT RETURN TO CONTINUE,'^' TO EXIT",ZZRET:DTIME I ZZRET["^"!('$T) G EXIT
 W @IOF S ZZLCT=1
PGHD ;HEADING FOR EXTENDED PRINT
 I ZZMODE["E" W !,?2,"FOLDER",!,?4,"DOCUMENT ID",?43,"KEYWORDS",?(IOM-20),"DATE: ",DTE,!,ZZLI S ZZLCT=5
CON ;HEADING FOR CONDENSED PRINT
 I ZZMODE["C" S ZZLEN=(IOM\4)-3 W !,?2,"FOLDER: ",!,?4,"DOCUMENT ID.",?ZZLEN+4,"KEYWORDS",?(IOM-20),"DATE: ",DTE,!,ZZLI S ZZLCT=ZZLCT+5
 Q
LCK ;LINE NUMBER CHECK
 S NN=$O(^UTILITY($J,$S(ZZKD:"KW",1:"ID"),N1,N2))  I NN'="" Q:IOSL-ZZLCT-$S(ZZMODE["E":4,1:2)>0  D NWPG D FLHD Q
 I NN="" Q:$O(^UTILITY($J,$S(ZZKD:"KW",1:"ID"),N1))=""  Q:IOSL-ZZLCT-$S(ZZMODE["E":9,1:6)>0  D NWPG Q
 Q
SETLOP ;SET UP UTILITY GLOBAL
 S ZZSTR=$P(^DIZ(500009,N1,1,N2,0),U,2,4) F ZZI=1:1:3 Q:'$D(ZZKW(ZZI))  F ZZJ=1:1:3 I $P(ZZSTR,U,ZZJ)=+ZZKW(ZZI) S ^UTILITY($J,"KW",N1,N2)="" D:ZZSM["E" SETLP1
 Q
SETLP1 ;
 S J="" F K=0:0 S J=$O(ZZIW(J)) Q:J=""  S ZZID=ZZIW(J) D SETLP2
 Q
SETLP2 ;
 S ZZIWS=$E(ZZID,1,2) F K=0:0 S ZZID=$O(^DIZ(500009,"FID",ZZID)) Q:$E(ZZID,1,2)'=ZZIWS  D SETLP3
 Q
SETLP3 ;
 F F=0:0 S F=$O(^DIZ(500009,"FID",ZZID,F)) Q:F=""  F D=0:0 S D=$O(^DIZ(500009,"FID",ZZID,F,D)) Q:D=""  I $D(^DIZ(500009,F,1,D,0)) I '$D(^UTILITY($J,"KW",F,D)) S ^UTILITY($J,"ID",F,D)=^DIZ(500009,F,1,D,0)
 Q
EN ;Entry point for taskmanager
SEARCH ;SET UP UTILITY GLOBAL
 F ZZDT=STDT-1:0 S ZZDT=$O(^DIZ(500009,"DT",ZZDT)) Q:ZZDT=""!(ZZDT>ENDT)  F N1=0:0 S N1=$O(^DIZ(500009,"DT",ZZDT,N1)) Q:N1=""  F N2=0:0 S N2=$O(^DIZ(500009,"DT",ZZDT,N1,N2)) Q:N2=""  D SETLOP
 I IO(0)'=IO O IO U IO
 I '$D(^UTILITY($J)) W @IOF W !,"Nothing on file for these dates with these keywords!" G EXIT
 S $P(ZZLI,"=",(IOM-3))="=",ZZLCT=0 S:ZZMODE["C" ZZLEN=(IOM\4)-3
 W @IOF D PGHD F N1=0:0 S N1=$O(^UTILITY($J,"KW",N1)) Q:N1=""  D FLHD F N2=0:0 S N2=$O(^UTILITY($J,"KW",N1,N2)) Q:N2=""  D @$S(ZZMODE["E":"PRINTE",1:"PRINTC")
 I ZZSM="E" S ZZKD=0 D NWPG W !,$S('$D(ZZIW):"No Document ID words selected",1:"No document ID words selected") G EXIT ;$D(^UTILITY($J,"ID")) D NOID
 I ZZSM="E" F N1=0:0 S N1=$O(^UTILITY($J,"ID",N1)) Q:N1=""  D FLHD F N2=0:0 S N2=$O(^UTILITY($J,"ID",N1,N2)) Q:N2=""  D @$S(ZZMODE["E":"PRINTE",1:"PRINTC")
EXIT ;EXIT POINT
 I IO(0)'=IO X ^%ZIS("C")
 K ZZDT,ZZI,ZZIX,ZZJ,ZZKW,ZZKY,ZZLCT,ZZLEN,ZZLI,ZZMODE,ZZNN,ZZRET,ZZSTR,ZZIWZZID,ZZIWS,ZZKD,ZZSM Q
QUEUE ;QUEUEING
 Q
NOID ;
 W !,$S('$D(ZZIW):"No Document ID words selected",1:"No documents with similar words") Q
