A1CBSET(ZTSK,ZTRTN,ZTDTH,ZTDESC,ZTC1) ;ISC1/JAS;PARAMETER PASSING ROUTINE ;[ 11/24/92  1:14 PM ]
 ;;V0.1;;
 S ^A1CB(ZTSK)=ZTRTN_"^^^"_$P(^%ZTSK(ZTSK,0),"^",5)_"^"_ZTDTH_"^"_ZTDESC_"^"_ZTC1
 S COUNT=0
 S %H=ZTDTH D YMD^%DTC S DATE1=X_%
 S ZT1="" F ZT=0:0 S ZT1=$O(^%ZTSCH("JOB",ZT1)),ZT2="" Q:ZT1=""  D CONVRT Q:ZTC<DATE1  F ZT=0:0 S ZT2=$O(^%ZTSCH("JOB",ZT1,ZT2)) Q:'ZT2  D COUNT
 S ZT1="" F ZT=0:0 S ZT1=$O(^%ZTSCH(ZT1)),ZT2="" Q:'ZT1  D CONVRT Q:ZTC<DATE1  F ZT=0:0 S ZT2=$O(^%ZTSCH(ZT1,ZT2)) Q:'ZT2  D COUNT
 S ZT1="" F ZT=0:0 S ZT1=$O(^%ZTSCH("IO",ZT1)),ZT2="" Q:ZT1=""  F ZT=0:0 S ZT2=$O(^%ZTSCH("IO",ZT1,ZT2)),ZT3="" Q:'ZT2  D CONVRT Q:ZTC<DATE1  F ZT=0:0 S ZT3=$O(^%ZTSCH("IO",ZT1,ZT2,ZT3)) Q:ZT3=""  D COUNT
 S ZT1="" F ZT=0:0 S ZT1=$O(^%ZTSCH("LINK",ZT1)),ZT2="" Q:ZT1=""  F ZT=0:0 S ZT2=$O(^%ZTSCH("LINK",ZT1,ZT2)),ZT3="" Q:'ZT2  D CONVRT Q:ZTC<DATE1  F ZT=0:0 S ZT3=$O(^%ZTSCH("LINK",ZT1,ZT2,ZT3)) Q:ZT3=""  D COUNT
 S $P(^A1CB(ZTSK),"^",9)=COUNT
 Q
COUNT ;
 S COUNT=COUNT+1
 Q
CONVRT ;
 S %H=ZT1 D YMD^%DTC S ZTC=X_%
 Q
 ;
