A1CBSET ;ISC1/JAS;CREATE NODE-COUNT FUTURE TASK DATA ;[ 12/15/92  2:45 PM ]
 ;;V1.0;;
 S ^%A1CB(ZTSK)=ZTRTN_"^^^"_$P(^%ZTSK(ZTSK,0),"^",5)_"^"_ZTDTH_"^"_ZTDESC_"^"_ZTC1
ADD N COUNT,X,%,ZT1,ZT,ZT2,ZT3 S COUNT=0
 S %H=ZTDTH D YMD^%DTC S DATE1=X_%
T1 S ZT1="" F ZT=0:0 S ZT1=$O(^%ZTSCH("JOB",ZT1)),ZT2="" Q:ZT1=""  D CONVRT Q:DATE1<ZTC  F ZT=0:0 S ZT2=$O(^%ZTSCH("JOB",ZT1,ZT2)) Q:'ZT2  D COUNT
T2 S ZT1="" F ZT=0:0 S ZT1=$O(^%ZTSCH(ZT1)),ZT2="" Q:'ZT1  D CONVRT Q:DATE1<ZTC  F ZT=0:0 S ZT2=$O(^%ZTSCH(ZT1,ZT2)) Q:'ZT2  D COUNT
T3 S ZT1="" F ZT=0:0 S ZT1=$O(^%ZTSCH("IO",ZT1)),ZT2="" Q:ZT1=""  F ZT=0:0 S ZT2=$O(^%ZTSCH("IO",ZT1,ZT2)),ZT3="" Q:'ZT2  D CONVRT Q:DATE1<ZTC  F ZT=0:0 S ZT3=$O(^%ZTSCH("IO",ZT1,ZT2,ZT3)) Q:ZT3=""  D COUNT
T4 S ZT1="" F ZT=0:0 S ZT1=$O(^%ZTSCH("LINK",ZT1)),ZT2="" Q:ZT1=""  F ZT=0:0 S ZT2=$O(^%ZTSCH("LINK",ZT1,ZT2)),ZT3="" Q:'ZT2  D CONVRT Q:DATE1<ZTC  F ZT=0:0 S ZT3=$O(^%ZTSCH("LINK",ZT1,ZT2,ZT3)) Q:ZT3=""  D COUNT
T5 S $P(^%A1CB(ZTSK),"^",9)=COUNT,$P(^%A1CB(ZTSK),"^",11)=0
 K ZTC
 Q
COUNT ;
 S COUNT=COUNT+1
 Q
CONVRT ;
 S %H=ZT1 D YMD^%DTC S ZTC=X_%
 Q
