VEC8104 ;AISC/KK-BEST BUY	;9-26-93
 ;;1
 ;	VARIABLE LIST
 ;
 ;	STORE1		=SAMS
 ;	STORE2		=PACE
 ;	RETPRICE1	=SAMS RETAIL PRICE
 ;	RETPRICE2	=PACE RETAIL PRICE
 ;	DISPERCENT1	=SAMS DISCOUNT PERCENT
 ;	DISPERCENT2	=PACE DISCOUNT PERCENT
 ;	DISCOUNT1	=SAMS DISCOUNT DOLLAR AMOUNT
 ;	DISCOUNT2	=PACE DISCOUNT DOLLAR AMOUNT
 ;	PURCOST1	=SAMS PURCHASE COST
 ;	PURCOST2	=PACE PURCHASE COST
 ;	ANSWER		=ANSWER TO "ANOTHER?" PROMPT
 ;
STORE1 ;
 WRITE !,"SAMS BEST PRICE"
 READ !!,"ENTER RETAIL PRICE:  ",RETPRICE1
 READ !,"ENTER SAMS DISCOUNT PERCENT:  ",DISPERCENT1
 SET DISCOUNT1=RETPRICE1*DISPERCENT1
 SET PURCOST1=RETPRICE1-DISCOUNT1
 WRITE !!," THE TOTAL SAMS PURCHASE COST IS $",PURCOST1
 ;
STORE2 ;
 WRITE !,"PACE BEST PRICE"
 READ !!,"ENTER RETAIL PRICE:  ",RETPRICE2
 READ !,"ENTER PACE DISCOUNT PERCENT:  ",DISPERCENT2
 SET DISCOUNT2=RETPRICE2*DISPERCENT2
 SET PURCOST2=RETPRICE2-DISCOUNT2
 WRITE !!," THE TOTAL PACE PURCHASE COST IS $",PURCOST2
 ;
DECISION ;
 IF PURCOST1>PURCOST2 WRITE !!,"BUY FROM PACE"
 IF PURCOST2>PURCOST1 WRITE !!,"BUY FROM SAMS"
 IF PURCOST1=PURCOST2 WRITE !!,"BUY WHICHEVER IS CLOSER TO YOU"
 ;
CHECK ;
 READ !,"DO YOU WANT TO DO ANOTHER? YES//",ANSWER
 IF ANSWER="" GOTO STORE1
 IF ANSWER="YES" GOTO STORE1
 IF ANSWER="Y" GOTO STORE1
EXIT ;
 KILL STORE1,STORE2,RETPRICE1,RETPRICE2,DISPERCENT1,DISPERCENT2
 KILL PURCOST1,PURCOST2,DISCOUNT1,DISCOUNT2,ANSWER
 QUIT
