VECSG7
 ;;1
 ;MISCELLANEOUS ROUTINE
 ;
 ;VARIABLE LIST
 ;
 ;RECORD....CURRENT RECORD
 ;RECNR.....RECORD NUMBER OF CURRENT RECORD
 ;NAMES.....THE ARRAY THAT HOLDS THE NAME AND ADDRESS DATA
 ;NAMES(0)..WHENTHE ARRAY HAS BEEN LOADED, THIS VARIABLE CONTAINS
 ;          THE NUMBER OF RECORDS LOADED INTO THE ARRAY
 ;
LOAD ;
 ;WE PUT THE NEXT TWO LINES IN TO SIMULATE WHAT YOU MIGHT WANT TO DO
 ;IF YOUR ROUTINE WILL BE ENGAGING IN A PROCESS THAT MAY DELAY THE
 ;REST OF THE PROCESSING.
 ;SINCE THIS ROUTINE DOESN'T ACTUALLY TAKE ANY EXTRA TIME, WE'VE
 ;ADDED THE HANG.
START ;
 W ?20,"...",$P($T(MSG+($R(5)+1)),";;",2)
 H 3
 F RECNR=1:1 D INPUT Q:RECORD=""
 S NAMES(0)=RECNR-1
 K RECORD,RECNR
 Q
INPUT ;
 S RECORD=$P($T(DATA+RECNR),";;",2)
 Q:RECORD=""
 S NAMES(RECNR)=RECORD
 Q
DATA ;
 ;;MOORE,LINDA^123 MAIN ST.^ATHENS,GA 15312
 ;;SMITH,BILL^530 MAPLE ST.^SANDIEGO,CA 93215
 ;;SMITH,MARY^530 MAPLE ST.^SANDIEGO,CA 93215
 ;;MILLER,JOE^4 FOURTH AVE.^PITTSBURGH,PA 15222
 ;;MOORE,RALPH^5 MAIN ST.^ATHENS,GA 15312
 ;;MILLER,MAGGIE^4 FOURTH AVE.^PITTSBURGH,PA 15222
 ;;MILLER,NED^4 FOURTH AVE.^PITTSBURGH,PA 15222
MSG ;
 ;;HOLD ON...I'M THINKING
 ;;BEAM ME UP JAVIER(SCOTTY)!
 ;;BE BACK IN A LITTLE WHILE
 ;;TOOK A COFFEE BREAK
 ;;SOME THINGS TAKE LONGER THAN OTHERS
 ;
 ;
WRREC ; DISPLAY OUTPUT FROM ANY SEARCH
 W !!,$P(RECORD,"^",1),?30,$P(RECORD,"^",2)
 W !,?30,$P(RECORD,"^",3)
 Q
  
