 ;ATL/ACE PROGRAMMER-MAILING LIST SYSTEM VECSG18
 ;;1
 ;       VARIABLE LIST
 ;
 ;       OPT     =       OPTIONAL NUMBER AS ENTERED BY USER
 ;       IOF     =       CONTROL CHARACTERS TO CLEAR SCREEN (NOT TO BE KILLED)
 ;       DTIME   =       DELAY TIME FOR READS (NOT TO BE KILLED)
 ;       II      =       LOOP COUNTER TO DISPLAY MENU TEXT
 ;
MAIN ;
 D DISMENU
 I OPT=""!(OPT["^") G EXIT
 D ^VECSG19:OPT=1,^VECSG20:OPT=2,^VECSG21:OPT=3,^VECSG22:OPT=4
 G MAIN
DISMENU ;
 W @IOF
 W !!!,"MAILING LIST SYSTEM"
 W !!,"OPTIONS     FUCTIONS"
 F II=1:1:4 D DISMENU2
DISMENU1 ;
 R !!,"ENTER OPTION NUMBER: ",OPT:DTIME
 I '$T!(OPT["^")!(OPT="") Q
 I (OPT<1)!(OPT>4)!(OPT="?") W !!,"OPTION MUST BE "
 I  W "BETWEEN 1 AND 4" G DISMENU1
 Q
DISMENU2 ;
 W !!,II,$P($T(OPTIONS+II),";",3)
 Q
EXIT ;
 K II,OPT
 Q
OPTIONS ;
 ;;.....CREATE MAILING LIST ENTRY
 ;;.....EDIT MAILING LIST ENTRY
 ;;.....DELETE MAILING LIST ENTRY
 ;;.....PRINT MAILING LIST ENTRY
