VECSG ;ATL/ACE PROGRAMMER-TEMPERATURE CONVERSION ;1/1/90
 ;;1
 ;       VARIABLE LIST
 ;
 ;       DTIME....DELAY TIME FOR READ (SINCE IT IS A SPECIAL VA
 ;       VARIABLE, IT IS NOT TO BE KILLED)
 ;       TEMP.....CONVERTED TEMPERATURE
 ;       XDEGREES..DEGREES INPUT BY USER
 ;       ANS........ANSWER TO "DO YOU WANT ANOTHER?"
 ;       CODE........USER'S MENU CHOICE NUMBER
 ;
BEGIN ;
 READ !!,"ENTER NUMBER OF DEGREES: ",XDEGREES:DTIME
 IF '$T!(XDEGREES["^") GOTO EXIT
MENU ;
 W !!,"ENTER 1 FOR FARENHEIT TO CELSIUS"
 W !,"ENTER 2 FOR CELSIUS TO FARENHEIT"
 R !,CODE:DTIME IF '$T!(CODE["^") GOTO EXIT
 IF CODE<1!(CODE>2) W !,"ENTER 1 OR 2" GOTO MENU
PICK ;
 DO FTOC:CODE=1,CTOF:CODE=2
AGAIN ;
 ;BELOW WE HAVE USED THE LESSON 1 WAY OF ENDING
 ;A PROGRAM
 ;
 R !,"DO YOU WANT TO DO ANOTHER? YES//",ANS:DTIME
 IF '$T!(ANS["^") GOTO EXIT
 GOTO BEGIN:(ANS="")!(ANS="YES")!(ANS="Y")
 GOTO EXIT
FTOC ;
 S TEMP=(XDEGREES-32)*5/9
 W !!,"CELSIUS TEMPERATURE IS: ",TEMP
 QUIT
CTOF ;
 S TEMP=XDEGREES*(9/5)+32
 W !!,"FARENHEIT TEMPERATURE IS: ",TEMP
 QUIT
EXIT ;
 KILL TEMP,XDEGREES,ANS,CODE
 QUIT
  
  
  
  
  
  
  
  
  
