DJINM ;JA/WASH;INSERT AND LOOK UP ; 13 JAN 86  2:13 PM
 ;VERSION 1.33
 G T1:'$D(DJW),T1:DJW=0 S DJXX=X G:DJ4["P" P G:X["^" ER S (DJDIC,DIE)=DIC,DA=DJDN S DR=DJ3_"///"_$S(X["/"!(X[";"):"^S X=DJXX",1:X) X DJCP W ! D ^DIE S DIC=DJDIC D KILL^DJINJ I $D(Y) S DJY=Y G:Y Q1 G:'$D(X) Q1
 I DJ4["D" S Y=X X ^DD("DD") S X=Y
 I DJ4["S" S X1=$P(DJ0,U,3) F I=1:1 I X=$P($P(X1,";",I),":",1) S X=$P($P(X1,";",I),":",2) Q
 I '$D(DJY) S V(V)=$E(X,1,+DJJ(V)) S @$P(DJJ(V),U,2) X XY W @DJHIN X XY W V(V),@DJLIN X:$D(^DJR(DJN,1,$N(^DJR(DJN,1,"A",V,0)),1)) ^(1) G NXT^DJINJ
P I DJ4["P" D P^DJINQ S @$P(DJJ(V),U,2) X XY G NXT^DJINJ:$D(Y)=0,TK^DJINJ
 S V(V)=$S(X="@":"",1:X) S DX=0,DY=16 X XY W @DJEOP I $D(^DJR(DJN,1,$N(^DJR(DJN,1,"A",V,0)),1)) S DX=0,DY=16 X XY W @DJEOP X ^(1) S @$P(DJJ(V),U,2) X XY
 G:DJAT=.01&(V(V)="") Q^DJINJ G T4^DJINJ
Q1 S:'$D(X) X=DJXX D ^DJINQ G TK^DJINJ
T1 I $D(^DJR(DJN,1,$N(^DJR(DJN,1,"A",V,0)),1)) S DX=0,DY=16 X XY W @DJEOP X ^(1) S @$P(DJJ(V),U,2) X XY
 G:DJAT=.01&($D(DJDN)=0) K1
 G:DJAT=.01&(DJP) K1
 I V(V)'="" S @$P(DJJ(V),U,2) X XY W @DJHIN X XY W V(V),@DJLIN G NXT^DJINJ
 I V(V)="" S @$P(DJJ(V),U,2) X XY W @DJLIN S $P(DJDB,".",DJJ(V))="." W DJDB K DJDB G NXT^DJINJ
 G LH^DJINJ
K1 G NXT^DJINJ:X=""&($D(DJDN)),LST^DJINJ:X=""&('$D(DJDN)) I $D(DJST),DJST=1 K ^DJST($J),DJST
 S:X'=" " DIC(0)="LMEQZ" S:X=" " DIC(0)="Z" X DJCP W X S:$D(DJDICS) DIC("S")=DJDICS D ^DIC K DIC("S") S DIC(0)="LMEQZ"
 I Y<0&($Y<23) S X="",DY=16,DX=0 X XY
 I Y<0&($Y>23) S X="" R !,"Type CR to continue",X:DTIME S DJSV=V,DJFF=0 D N^DJDPL S V=DJSV
 I $Y>23 D N^DJDPL
 I Y<0 S @$P(DJJ(V),U,2) X XY G TK^DJINJ
 S (X,V(V))=$P(Y(0),U,1),(DA,W(V))=+Y,DJDNM=V(V) X DJCP S:'$D(DJST) DJST=1,D0=DA I DJST=1 G LOCK
C S:'DJP DJDN=+Y X XY W @DJEOP K Y,DJLK D ^DJC2 X XY S DJW=1 G EN2^DJINJ
ER K X W *7 G Q1
WP ;PRINT WORD PROCESSOR FIELD
 S DJDIC=DIC_DA_","_+$P(DJ0,"^",4)_"," S DJXX=X Q:'$D(@(DJDIC_"0)"))  S DJZ1=0,DJX=0,DIWL=0,DIWR=79,DIWF="" K ^UTILITY($J,"W")
 F I=1:1 S DJZ1=$O(@(DJDIC_DJZ1_")")) Q:DJZ1'?1N.N  S X=^(DJZ1,0) D ^DIWP X DJCP
 S DJZ1=0 F I=1:1 S DJZ1=$O(^UTILITY($J,"W",DIWL,DJZ1)) Q:DJZ1=""  D:$Y>21 CONT Q:DJX[U  W !,^(DJZ1,0)
 K DJZ1,I,^UTILITY($J,"W",DIWL),DIWL,DIWR,DIWF S X=DJXX Q:DJX'[U
 Q
CONT W !,"Type CR to continue, uparrow to exit: " R DJX:DTIME X DJCP W ! Q
EN ;COMPUTE AND DISPLAY
 S @$P(DJJ(DJVV),U,2) X XY W @DJHIN X XY W V(DJVV) Q
LOCK ;LOCK GLOBAL THAN IS BEING ACCESSED BY ANOTHER USER
 L @(DIC_+Y_"):1") S DJLK=$T G:DJLK'=0 C I DJLK=0 X XY K DJLK X DJCL W "THIS ENTRY IS BEING EDITED BY ANOTHER USER. TRY LATER.",*7 G TK^DJINJ
