DJINJ ;JA/WASH;INPUT TO SCREEN ; 04 Sep 86  11:05 AM
 ;VERSION 1.36
 K DJDN
 I '$D(DJDN)&($P(DJJ,U,2)'="") G EN2^DJINJ1
 ;
 S:'$D(DJDPL) DJDPL=""
EN ;
 I $D(DJDN)=0 S:$D(DJKEY) DJNX=DJKEY
 S DJQ=0,DJP=0,DJMU=0 I DJDPL'=DJNM D ^DJDPL G TK
EN2 S V=DJF-.01 I '$D(DJDN),'$D(DJW) D FUNC^DJINQ
NXT S V=$N(DJJ($S($D(DJNX):DJNX-.001,1:V))) G LST:V<0,TK:$P(DJJ(V),U,5)&($P(DJJ(V),U,3)=.01)&('$D(DJDN)),NXT:$P(DJJ(V),U,4)["C" I $P(DJJ(V),U,5),$P(DJJ(V),U,4)'["W" G NXT
TK K DJNX S DJMU=0,@$P(DJJ(V),U,2),DJAT=$P(DJJ(V),U,3),DJ0=^DD(DJDD,DJAT,0),DJ4=$P(DJJ(V),U,4),DJ3=$P(DJJ(V),U,3) S:DJ4["M" DJMU=1 G LH:DJAT<0,NXT:DJAT=.001 X XY G LST:'DJJ(V)
 I DJ4["W" I '($D(DJDIS)!($P(DJJ(V),U,5))) X DJCP S DA=DJDN,DR=DJ3,DIE=DIC D ^DIE D:$D(Y) EN3^DJINJ1 S DJSV=V D:$Y>23 N^DJDPL S V=DJSV G NXT
 I DJ4["W" I $D(DJDIS)!($P(DJJ(V),U,5)=1) D WP^DJINJ1 G NXT
 G:$D(DJDIS)&($D(DJDN)&(DJMU=0)) LST I $D(^DJR(DJN,1,$N(^DJR(DJN,1,"A",V,0)),2)),^(2)'="" X DJCP X ^(2) S @$P(DJJ(V),U,2) X XY G:$D(DJNX) NXT
 I DJAT'=.01,$D(^DJR(DJN,1,$N(^DJR(DJN,1,"A",V,0)),3)),V(V)="" S V(V)=^(3),DIE=DIC,DA=DJDN,DR=DJAT_"///"_V(V) D ^DIE D EN3^DJINJ1
R D:'$D(DJNX) HL,^DJRD I X="",DJ4["R",DJAT'=.01,V(V)="" G Q1
 S DJXX=$E(X,1) G TK:X="^D"&($P(DJJ,U,4)=""),TK:X="^U"&($P(DJJ,U,2)=""),LS1:(X="^D"!(X="^U"))&($D(DJDN)) I X="^C" D FUNC^DJINQ G TK
 G T4:(DJSM!(DJXX="<")!(DJXX=">")!(X?1"^"))&($D(DJDN)),OUT:X=U&(DJAT=.01)&('$D(DJDN)),TK:X?1"^".A
 S:$D(DJSW1) DJDIS=1 K DJSW1 G:DJMU ^DJMUL
EN3 G T4:DJSM,OUT:X=""&(DJAT=.01)&('$D(DJDN)),OUT:X="^"&(DJAT=.01)&('$D(DJDN)),T1^DJINJ1:X="" X XY S $P(DJDB," ",DJJ(V))=" " W DJDB K DJDB
 S DJXX=$E(X,1) G U:X?1"^"&(DJAT=.01),T4:DJXX="^"!(DJXX="<")!(DJXX=">"),K1^DJINJ1:X?1"?".E&(DJAT[".01")&('$D(DJDN)),Q1:X?1"?".E
 I X["^" W *7 G TK
 I X="@" D:DJAT>0 ^DJINK G T3
 G ^DJINJ1
T3 S V(V)=$S(X="@":"",1:X)
 G:DJAT=.01&(V(V)="") Q G T4
Q1 D ^DJINQ S @$P(DJJ(V),U,2) X XY G R
 ;HI-LIGHT
HL I '$D(V(V)) X XY W @DJHIN X XY S $P(DJDB,".",DJJ(V))="." W DJDB,@DJLIN K DJDB G HLQ
 I V(V)="" X XY W @DJHIN S $P(DJDB,".",DJJ(V))="." X XY W DJDB,@DJLIN K DJDB G HLQ
HLQ X XY Q
 ;ANS IS NULL
LH I DJ4["R" X DJCL W @DJHIN X XY W "DATA REQUIRED",@DJLIN,*7 S @$P(DJJ(V),U,2) X XY G TK
T4 G:'($D(DJDN)) TK S @$P(DJJ(V),U,2) X XY
 I '$D(V(V)) S $P(DJDB,".",DJJ(V))="." W @DJLIN,DJDB K DJDB G T5
 I V(V)="" S $P(DJDB,".",DJJ(V))="." W @DJLIN,DJDB K DJDB G T5
U I V(V)'="" S @$P(DJJ(V),U,2) X XY W @DJHIN X XY S $P(DJDB," ",DJJ(V)-$L(V(V)))=" " W V(V) W:$D(DJDB) DJDB K DJDB
T5 Q:X?1"^"&($P(DJJ,U,2)="")&('$D(DJDN))  G LST:X?1"^",NX:X'?1"^".N
 S DJY=$P(X,U,2) I X?1"^".N,$D(DJJ(DJY)),'$P(DJJ(DJY),U,5),$P(DJJ(DJY),U,4)'["C" S V=DJY-.01 G NXT
 E  X DJCL W *7,"Number is out of range or field is read only or computed." S V=V-.01 G NXT
NX G NXT:X=">" I X="<" S DJ0=V G EN2:V<2 F V=-1:0 S V=$N(DJJ(V)) I $N(DJJ(V))=DJ0 G NX:DJ4["C" S V=V-.001 G NXT
 G Q1:X["^",NXT
PREV G LST:$P(DJJ,U,2)="" S DJN=$P(DJJ,U,2) S:DJN'=+DJN DJN=$N(^DJR("B",DJN,0)) S DJFF=0 D REST D N^DJDPL G EN2
Q I $P(^DJR(DJN,0),U,3)'="" F DJK=0:0 S (DJDPL,DJNM)=$P(^DJR(DJN,0),U,3),DJN=$N(^DJR("B",DJNM,0)) Q:$P(^DJR(DJN,0),U,3)=""
 K V,DJ0,DJAT,DJDN,DJ3,DJ4,DJQ I '$D(DJW1) D ^DJDPL G EN2
OUT K DJSV,DJ0,DJAT,DJK,DJDN,DJ3,V,DJJ,DJQ,DIC,DJDD,DX,DY,DJSM,DJDIC,DJKEY S DJFF=0 Q
LST ;OPTION LINE
 D FUNC1^DJINQ
LS X DJCL W "FUNCTION: ",$S($P(DJJ,U,4)="":"N",1:"D"),"//" R X:DTIME S:'$T X="^" S:X=""!(X["D") X="D" G MOD:X?1"^"1N.N G Q:X["N"&(DJP=0) Q:X["N"&(DJP=1)
LS1 G:X?1"^" OUT I X["D"&($P(DJJ,U,4)]"")&($D(DJDN)) D SAVE S DJN=$P(DJJ,U,4) S DJN=$N(^DJR("B",DJN,0)) S DJFF=0 D N^DJDPL Q:$D(DJY)  S (DA,W(V))=DJDN D ^DJC2 G EN2
 I X["D"&($P(DJJ,U,4)="") S:$P(DJJ,U,2)'="" DJFF=0 G Q
 G:X["U" PREV
 I X?1"M" D FUNC^DJINQ G LS
 G LST
MOD I $D(DJJ($P(X,U,2))) S V=$P(X,"^",2) S:DJ4["M"&($D(DJDIS)) DJSW1=1,DJDIS=0 S V=V-.001 G NXT
 E  W *7 G LS
KILL K DB,DC,DE,DG,DH,DI,DK,DL,DM,DP,DR,DW Q
SAVE S %X="V(",%Y="^UTILITY($J,""DJ"",DJN," D %XY^%RCR K V Q
REST K V S %X="^UTILITY($J,""DJ"",DJN,",%Y="V(" D %XY^%RCR Q
