DJINMG ;JA/WASH;INSERT AND LOOK UP ; 05 NOV 85  4:22 PM
 ;VERSION 1.33
 I DJDPL="DJ.DEF2"&(DJAT=1) X $P(^DD(2001.07,1,0),U,5,6) G:$D(X)=0 Q1 S ^DJR(DA(1),1,DA,1)=X X XY S V(V)=X W @DJHIN,V(V),@DJLIN G NXT^DJINJG
 I DJDPL="DJ.DEF2"&(DJAT=2) X $P(^DD(2001.07,2,0),U,5,6) G:$D(X)=0 Q1 S ^DJR(DA(1),1,DA,2)=X X XY S V(V)=X W @DJHIN,V(V),@DJLIN G NXT^DJINJG
 S:DIC["DJRM" DIC=$P(DIC,"M",1)_$P(DIC,"M",2)
 S DJS2=0 G T1:'$D(DJW),T1:DJW=0 S DJXX=X G:DJ4["P" P S DIE=DIC,DA=DJDA S:X["/"!(X[";") DJS1=X,DJS2=1 S:'DJS2 DR=DJ3_"///"_X S:DJS2 DR=DJ3_"///^S X=DJS1" X DJLF D ^DIE D KILL^DJINJG I $D(Y) G:Y Q1 G:'$D(X) Q1
 I DJ4["D" S X=$E(X,4,5)_"-"_$E(X,6,7)_"-"_$E(X,2,3)
 I DJ4["S",DJAT=.07 S X=DJXX
 I '$D(Y) S V(V)=$E(X,1,+DJJ(V)) S @$P(DJJ(V),U,2) X XY W @DJHIN X XY W V(V),@DJLIN X:$D(^DJRM(DJN,1,$N(^DJRM(DJN,1,"A",V,0)),1)) ^(1) G NXT^DJINJG
P I DJ4["P" D P^DJINQ S @$P(DJJ(V),U,2) X XY G NXT^DJINJG:$D(Y)=0,TK^DJINJG
 S V(V)=$S(X="@":"",1:X) X:$D(^DJRM(DJN,1,$N(^DJRM(DJN,1,"A",V,0)),1)) ^(1)
 G:DJAT=.01&(V(V)="") Q^DJINJG G T4^DJINJG
Q1 D ^DJINQ G TK^DJINJG
T1 X:$D(^DJRM(DJN,1,$N(^DJRM(DJN,1,"A",V,0)),1)) ^(1) G:DJAT=.01&($D(DJDN)=0) K1 G:X=""&('$D(V(V))) LH^DJINJG
 G:DJAT=.01&(DJP) K1
 I V(V)'="" X XY W @DJHIN X XY W V(V),@DJHIN G NXT^DJINJG
 I V(V)="" X XY W @DJLIN S $P(DJDB,".",DJJ(V))="." W DJDB K DJDB G NXT^DJINJG
 G LH^DJINJG
K1 G NXT^DJINJG:X=""&($D(DJDN)),LST^DJINJG:X=""&('$D(DJDN)) I $D(DJST),DJST=1 K ^DJST($J),DJST
 S DIC="^DJR(" S:X'=" " DIC(0)="LMEQZ",DLAYGO=2000 S:X=" " DIC(0)="Z" S DX=0,DY=16 X XY W @DJEOP W X S:$D(DJDICS) DIC("S")=DJDICS D ^DIC K DIC("S"),DLAYGO S DIC(0)="LMEQZ"
 I Y<0&($Y<23) S X="",DY=16,DX=0 X XY
 I Y<0&($Y>23) S X="" R !,"Type CR to continue",X:DTIME S DJSV=V,DJFF=0 D N^DJDPLS S V=DJSV
 I $Y>23 D N^DJDPLS
 I Y<0 S @$P(DJJ(V),U,2) X XY G TK^DJINJG
 S (X,V(V))=$P(Y(0),U,1),(DJDA,W(V))=+Y,DJDNM=V(V),DX=0,DY=16 S:'DJP DJDN=+Y X XY W @DJEOP K Y D ^DJC2 X XY S DJW=1 G EN2^DJINJG
