DJPARAM ;JA/WASH;INITIATE SCREEN VARIABLES; 24 APR 85  9:13 AM ; 05 Dec 86  9:45 AM
 ;VERSION 1.36
 ;DJEOP-ERASE FROM CURRENT XY TO END OF SCREEN
 ;DJHIN-HIGH INTENSITY
 ;DJLIN-LOW INTENSITY
 S U="^",DJRJ="" S:'$D(DUZ(0)) DUZ(0)="" S:'$D(DTIME) DTIME=60 D DT^DICRW
 S IOP=$I D ^%ZIS K IOP I $D(^%ZIS(2)) S IOST(0)=$N(^%ZIS(2,"B",IOST,0)) S:$D(^%ZIS(2,IOST(0),7)) DJHIN=$P(^(7),U,1),DJLIN=$P(^(7),U,2),XY="" S:$D(^(1)) XY=$P(^(1),U,5)
 S:$D(^(5)) DJEOP=$P(^(5),U,7) I $D(DJHIN),($D(DJLIN)),($D(DJEOP)),DJHIN'="",DJLIN'="",DJEOP'="",XY'="" S XY=XY_" "_^%ZOSF("XY") S:^%ZOSF("OS")["DSM-" XY=$P(XY,"(",1)_"(0::::::256*DY+DX)" G BD
 W !,"'HIGH/LOW INTENSITY', 'ERASE TO END OF PAGE' OR 'XY CRT' ATTRIBUTES"
 W:'$D(DJPAR) !,"HAVE NOT BEEN PROPERLY DEFINED FOR YOUR TERMINAL. SEE YOUR SITE MANAGER.",*7
 K DJRJ Q
BD ;
 S DJCL="S DY=23,DX=0 X XY W @DJEOP"
 S DJCP="S DY=16,DX=0 X XY W @DJEOP"
 S DJRJ=1 K DJJ0
 Q
