EVETV13 ;;DALOI/DS - Extraction procedures for ALL lab extracts data to be s ; 10/18/02 10:05am
 ;;1.0;HEALTH EVET;**1**;Nov 05, 2002
GET(EVETDFN,EVDAT,EVREQID) ;
 D GET^EVETV10(EVETDFN,EVDAT,EVREQID)
 D GET^EVETV12(EVETDFN,EVDAT,EVREQID)
 D GET^EVETV11(EVETDFN,EVDAT,EVREQID)
 Q
