PRCATP51 ; GENERATED FROM 'PRCA 3RD PROFILE' PRINT TEMPLATE (#859) ; 05/03/96 ; (continued)
 G BEGIN
N W !
T W:$X ! I '$D(DIOT(2)),DN,$D(IOSL),$S('$D(DIWF):1,$P(DIWF,"B",2):$P(DIWF,"B",2),1:1)+$Y'<IOSL,$D(^UTILITY($J,1))#2,^(1)?1U1P1E.E X ^(1)
 S DISTP=DISTP+1,DILCT=DILCT+1 D:'(DISTP#100) CSTP^DIO2
 Q
DT I $G(DUZ("LANG"))>1,Y W $$OUT^DIALOGU(Y,"DD") Q
 I Y W $P("JAN^FEB^MAR^APR^MAY^JUN^JUL^AUG^SEP^OCT^NOV^DEC",U,$E(Y,4,5))_" " W:Y#100 $J(Y#100\1,2)_"," W Y\10000+1700 W:Y#1 "  "_$E(Y_0,9,10)_":"_$E(Y_"000",11,12) Q
 W Y Q
M D @DIXX
 Q
BEGIN ;
 S:'$D(DN) DN=1 S DISTP=$G(DISTP),DILCT=$G(DILCT)
 W ?29 S Y=$P(X,U,20) S Y=$S(Y="":Y,$D(^DIC(36,Y,0))#2:$P(^(0),U,1),1:Y) W $E(Y,1,30)
 W ?61 D EN3^PRCADR K DIP K:DN Y
 D T Q:'DN  D N D N:$X>0 Q:'DN  W ?0 W "TRANSACTIONS: "
 W ?16 D EN2^PRCADR K DIP K:DN Y
 W ?27 Q:$D(PRCA("HALT"))  W "" K DIP K:DN Y
 D T Q:'DN  D N D N:$X>0 Q:'DN  W ?0 W "BILL RESULTING FROM: "
 W ?23 X DXS(1,9) K DIP K:DN Y
 W ?34 D PRCOMM^PRCAUT3 K DIP K:DN Y
 W ?45 Q:'$D(PRCA("WROFF"))  W "" K DIP K:DN Y
 W ?56 K DXS S D0=PRCA("WROFF") D ^PRCATW1 K DXS K DIP K:DN Y
 K Y
 Q
HEAD ;
 W !,"--------------------------------------------------------------------------------",!!
