PRYXPOST ;CIOFO@ALTOONA/RB-DELETE CHARGE CATEGORY FROM FILE 350.1
 ;;2.0; INTEGRATED BILLING ;**79**; 21-MAR-94
 ;Deletes charge category from DG CHAMPVA PER DIEM NEW file entry
 N DA,DIE,DR S DA=$O(^IBE(350.1,"B","DG CHAMPVA PER DIEM NEW",0))
 I +DA>0 S DIE="^IBE(350.1,",DR=".03////@" D ^DIE W !,"...Done",*7
 Q
