IBYPPC5 ;ALB/ARH - IB*2*52 POST INIT:  CM REFERENCE DATA ; 22-MAY-1996
 ;;Version 2.0 ; INTEGRATED BILLING ;**52,86**; 21-MAR-94
 ;;Per VHA Directive 10-93-142, this routine should not be modified.
 ;
 ;
BSF ; billable services (399.1)
 ;; 
 ;;INPATIENT^INPT
 ;;OUTPATIENT VISIT^OPT VST
 ;;PRESCRIPTION^RX
 ;;PROSTHETICS^PROSTH
 ;;1
 ;
BEF ; billable events (399.1)
 ;; 
 ;;INPATIENT BEDSECTION STAY^INPT BEDS
 ;;OUTPATIENT VISIT DATE^OPT VST DT
 ;;PRESCRIPTION FILL^RX FILL
 ;;PROCEDURE^PROC
 ;;PROSTHETICS ITEM^PROS ITEM
 ;;1
 ;
BRF ; Billing Rates (363.3)
 ;; 
 ;;TORTIOUSLY LIABLE^TORT^1^1^1
 ;;INTERAGENCY^IA^1^1^1
 ;;VA COST^VA COST^1^^2
 ;; 
 ;;AVERAGE WHOLESALE PRICE^AWP^2^3^3
 ;;AMBULATORY SURGERY^ASC^2^2^1
 ;;CMAC^CMAC^2^2^1
 ;;1
 ;
CSF ; Charge Sets (363.1)
 ;; 
 ;;TL-INPT (INCLUSIVE)^TORTIOUSLY LIABLE^INPATIENT BEDSECTION STAY^^1
 ;;TL-INPT (NPF)^TORTIOUSLY LIABLE^INPATIENT BEDSECTION STAY^1
 ;;TL-INPT (PF)^TORTIOUSLY LIABLE^INPATIENT BEDSECTION STAY^2^960
 ;;TL-OPT VST^TORTIOUSLY LIABLE^OUTPATIENT VISIT DATE^^500
 ;;TL-RX FILL^TORTIOUSLY LIABLE^PRESCRIPTION FILL^^250
 ;;TL-OPT DENTAL^TORTIOUSLY LIABLE^OUTPATIENT VISIT DATE^^512
 ;;TL-CAT C OPT COPAY^TORTIOUSLY LIABLE^OUTPATIENT VISIT DATE^^500
 ;; 
 ;;IA-INPT^INTERAGENCY^INPATIENT BEDSECTION STAY^^1
 ;;IA-OPT VST^INTERAGENCY^OUTPATIENT VISIT DATE^^500
 ;;IA-RX FILL^INTERAGENCY^PRESCRIPTION FILL^^250
 ;;IA-OPT DENTAL^INTERAGENCY^OUTPATIENT VISIT DATE^^512
 ;;1
 ;
RSF ; Rate Schedules (363)
 ;; 
 ;;RI-INPT^REIMBURSABLE INS.^1^INPATIENT^^^:TL-INPT (NPF):TL-INPT (PF)
 ;;RI-OPT^REIMBURSABLE INS.^3^^^^:TL-OPT VST:TL-RX FILL
 ;; 
 ;;CV-INPT^CRIME VICTIM^1^INPATIENT^^^:TL-INPT (NPF):TL-INPT (PF)
 ;;CV-OPT^CRIME VICTIM^3^^^^:TL-OPT VST:TL-RX FILL
 ;; 
 ;;NF-INPT^NO FAULT INS.^1^INPATIENT^^^:TL-INPT (NPF):TL-INPT (PF)
 ;;NF-OPT^NO FAULT INS.^3^^^^:TL-OPT VST:TL-RX FILL
 ;; 
 ;;TF-INPT^TORT FEASOR^1^INPATIENT^^^:TL-INPT (NPF):TL-INPT (PF)
 ;;TF-OPT^TORT FEASOR^3^^^^:TL-OPT VST:TL-RX FILL
 ;; 
 ;;WC-INPT^WORKERS' COMP.^1^INPATIENT^^^:TL-INPT (NPF):TL-INPT (PF)
 ;;WC-OPT^WORKERS' COMP.^3^^^^:TL-OPT VST:TL-RX FILL
 ;; 
 ;;HMN-INPT^HUMANITARIAN^1^INPATIENT^^^:TL-INPT (INCLUSIVE)
 ;;HMN-OPT^HUMANITARIAN^3^^^^:TL-OPT VST:TL-RX FILL
 ;; 
 ;;DNTL-OPT DENTAL^DENTAL^3^^^^:TL-OPT DENTAL
 ;; 
 ;;IA-INPT^INTERAGENCY^1^INPATIENT^^^:IA-INPT
 ;;IA-OPT^INTERAGENCY^3^^^^:IA-OPT VST:IA-RX FILL
 ;;1
 ;
RTF ; New Rate Types (399.3)
 ;; 
 ;;CHAMPUS REIMB. INS.^REIMBURSABLE INS.^^REIM INS^1^CHAMPUS THIRD PARTY^^1^1
 ;;CHAMPUS^CHAMPUS^^CHAMPUS^1^CHAMPUS^^1^1
 ;;1
 Q
