IBYPPS1 ;ALB/ARH - IB*2*119 POST INIT: UPDATE REVENUE CODES AND LINKS (CONT) ; 09/07/99
 ;;2.0;INTEGRATED BILLING;**119**;21-MAR-94
 ; 
 Q
 ;
FRVA ;  Revenue Codes to (3) Activate (399.2,2)
 ;;762,771,904,
 ;;
 ;
FRVI ; Inactivated Revenue Codes:  no longer defined or are now reserved (10)
 ;;175^                               ; 175^NURSERY/ICU^NEONATAL ICU
 ;;630^ reserved effective 1/1/98     ; 630^DRUGS^GENERAL CLASSIFICATION (HOME IV THER.)
 ;;815^                               ; 815^HEART/CADAVER^CADAVER DONOR-HEART
 ;;816^                               ; 816^HEART/OTHER^OTHER HEART ACQUISITION
 ;;817^                               ; 817^LIVER ACQUISIT^DONOR-LIVER
 ;;890^ 89x Reserved for National Use ; 890^DONOR BANK^GENERAL CLASSIFICATION
 ;;891^                               ; 891^DONOR BANK/BONE^BONE
 ;;892^                               ; 892^DONOR BANK/ORGN^ORGAN (OTHER THAN KIDNEY)
 ;;893^                               ; 893^DONOR BANK/SKIN^SKIN
 ;;899^                               ; 899^OTHER DONOR BANK^OTHER DONOR BANK
 ;;
 ;
FRVL ; revenue code - CPT links for Observation Care (1 entry, 4 links)
 ;;762^99217^99220
 ;;
 ;
FRVU ; Updated Revenue Codes  (44)
 ;;171^NURSERY/LEVELI^NEWBORN - LEVEL I
 ;;172^NURSERY/LEVELII^NEWBORN - LEVEL II
 ;;179^NURSERY/OTHER^OTHER NURSERY
 ;;200^INTENSIVE CARE (OR ICU)^GENERAL CLASSIFICATION
 ;;206^ICU/INTERMEDIATE^INTERMEDIATE ICU
 ;;210^CORONARY CARE (OR CCU)^GENERAL CLASSIFICATION
 ;;214^CCU/INTERMEDIATE^INTERMEDIATE CCU
 ;;232^NUR INCR/OB^OB
 ;;249^ALL INCL ANCIL/OTHER^OTHER ALL INCLUSIVE ANCILLARY
 ;;254^DRUGS/INCIDENT ODX^DRUGS INCIDENT TO OTHER DIAGNOSTIC SERVICES
 ;;257^DRGS/NONPSCRPT^NON-PRESCRIPTION
 ;;275^PACE MAKER^PACEMAKER
 ;;319^PATHOL/OTHER^OTHER LABORATORY PATHOLOGICAL
 ;;329^DX X-RAY/OTHER^OTHER RADIOLOGY - DIAGNOSTIC
 ;;339^RX X-RAY/OTHER^OTHER RADIOLOGY - THERAPEUTIC
 ;;349^NUC MED/OTHER^OTHER NUCLEAR MEDICINE
 ;;359^CT SCAN/OTHER^OTHER CT SCAN
 ;;399^BLOOD/OTHER STOR^OTHER BLOOD STORAGE AND PROCESSING
 ;;404^PET SCAN^POSITRON EMISSION TOMOGRAPHY
 ;;409^OTHER IMAG SVS^OTHER IMAGING SERVICE
 ;;509^OUTPATIENT/OTHER^OTHER OUTPATIENT SERVICE
 ;;523^FR/STD FAMILY CLINIC^FAMILY PRACTICE CLINIC
 ;;569^MED SOC SERV/OTHER^OTHER MED. SOCIAL SERVICE
 ;;589^VISIT/HOME HLTH/OTHER^OTHER HOME HEALTH VISIT
 ;;610^MRT^GENERAL CLASSIFICATION
 ;;611^MRI - BRAIN^MRI - BRAIN (INCLUDING BRAINSTEM)
 ;;612^MRI - SPINE^MRI - SPINAL CORD (INCLUDING SPINE)
 ;;619^MRT - OTHER^OTHER MRT
 ;;631^DRUG/SNGLE^SINGLE SOURCE DRUG
 ;;640^IV THERAPY SVC^GENERAL CLASSIFICATION
 ;;647^TRNG/PT/CARGVR/PERIPHRL^TRAINING, PATIENT/ CAREGIVER, PERIPHERAL LINE
 ;;659^HOSPICE/OTHER^OTHER HOSPICE SERVICE
 ;;760^TREATMENT/OBSERVATION RM^GENERAL CLASSIFICATION
 ;;769^OTHER TREAT/OBSERV RM^OTHER TREATMENT/OBSERVATION ROOM
 ;;803^DIALY/INPT/CAPD^INPATIENT CONTINUOUS AMBULATORY PERITONEAL DIALYSIS (CAPD)
 ;;811^LIVING DONOR^LIVING DONOR
 ;;812^CADAVER DONOR^CADAVER DONOR
 ;;813^UNKNOWN DONOR^UNKNOWN DONOR
 ;;814^UNSUCCESSFUL SEARCH^UNSUCCESSFUL ORGAN SEARCH - DONOR BANK CHARGES
 ;;819^OTHER DONOR^OTHER DONOR
 ;;889^DIALY/MISC/OTHER^OTHER MISCELLANEOUS DIALYSIS
 ;;909^OTHER PSYCH RX^OTHER PSYCHIATRIC/PSYCHOLOGICAL TREATMENT
 ;;912^PSYCH/PARTIAL HOSP^PARTIAL HOSPITALIZATION - LESS INTENSIVE
 ;;913^PSYCH/PARTIAL INTENSIVE^PARTIAL HOSPITALIZATION - INTENSIVE
 ;;919^PSYCH/OTHER^OTHER PSYCHIATRIC/PSYCHOLOGICAL SERVICE
 ;;945^ALCOHOL REHAB^ALCOHOL REHABILITATION
 ;;946^CMPLX MED EQUIP-ROUT^COMPLEX MEDICAL EQUIPMENT - ROUTINE
 ;;962^PRO FEE/EYE^OPHTHALMOLOGY
 ;;969^OTHER PRO FEE^OTHER PROFESSIONAL FEE
 ;;999^PT CONVENCE/OTH^OTHER PATIENT CONVENIENCE ITEM
 ;;
 ;
FRVN ; New Revenue Codes (38)
 ;;022^SNF PPS (RUG)^SKILLED NURSING FACILITY PROSPECTIVE PAYMENT SYSTEM
 ;;173^NURSERY/LEVELIII^NEWBORN - LEVEL III
 ;;174^NURSERY/LEVELIV^NEWBORN - LEVEL IV
 ;;190^SUBACUTE^GENERAL CLASSIFICATION
 ;;191^SUBACUTE/LEVELI^SUBACUTE CARE - LEVEL I
 ;;192^SUBACUTE/LEVELII^SUBACUTE CARE - LEVEL II
 ;;193^SUBACUTE/LEVELIII^SUBACUTE CARE - LEVEL III
 ;;194^SUBACUTE/LEVELIV^SUBACUTE CARE - LEVEL IV
 ;;199^SUBACUTE/OTHER^OTHER SUBACUTE CARE
 ;;241^ALL INCL BASIC^BASIC
 ;;242^ALL INCL COMP^COMPREHENSIVE
 ;;243^ALL INCL SPECIAL^SPECIALTY
 ;;451^ER/EMTALA^EMTALA EMERGENCY MEDICAL SCREENING SERVICES
 ;;452^ER/BEYOND EMTALA^ER BEYOND EMTALA SCREENING
 ;;456^URGENT CARE^URGENT CARE
 ;;483^ECHOCARDIOLOGY^ECHOCARDIOLOGY
 ;;516^URGENT CLINIC^URGENT CARE CLINIC
 ;;517^FAMILY CLINIC^FAMILY PRACTICE CLINIC
 ;;526^FR/STD URGENT CLINIC^URGENT CARE CLINIC
 ;;609^O2 - OTHER^OTHER OXYGEN
 ;;614^MRI - OTHER^MRI - OTHER
 ;;615^MRA - HEAD AND NECK^MRA - HEAD AND NECK
 ;;616^MRA - LOWER EXT^MRA - LOWER EXTREMITIES
 ;;618^MRA - OTHER^MRA - OTHER
 ;;623^SURG DRESSING^SURGICAL DRESSINGS
 ;;624^FDA INVEST DEVICE^FDA INVESTIGATIONAL DEVICES
 ;;637^DRUGS/SELF ADMIN^SELF-ADMINISTRABLE DRUGS
 ;;669^RESPITE OTHER^OTHER RESPITE CARE
 ;;670^OP SPEC RES^GENERAL CLASSIFICATION
 ;;671^OP SPEC RES/HOSP BASED^HOSPITAL BASED
 ;;672^OP SPEC RES/CONTRACTED^CONTRACTED
 ;;679^OP SPEC RES/OTHER^OTHER SPECIAL RESIDENCE CHARGE
 ;;770^PREVENT CARE SVS^GENERAL CLASSIFICATION
 ;;771^VACCINE ADMIN^VACCINE ADMINISTRATION
 ;;779^OTHER PREVENT^OTHER PREVENTIVE CARE SERVICES
 ;;780^TELEMEDICINE^GENERAL CLASSIFICATION
 ;;789^TELEMEDICINE/OTHER^OTHER TELEMEDICINE
 ;;904^ACTIVITY THERAPY^ACTIVITY THERAPY
 ;;
 ;
 Q
