IBYQCFC ;ALB/ARH - CONDITION CODES:  FILE IN 399.1 - COB POST INIT ; 5/1/97
 ;;2.0;INTEGRATED BILLING;**80**;21-MAR-94
 ;
CC ; Add Condition Codes to 399.1 (#.22 - p15)
 ; due to the conversion the condition codes must have IFNs greater than 79
 N DINUM,DLAYGO,DIC,DIE,DD,DO,DA,DR,X,Y,IBA,IBI,IBLN,IBCNT,IBJ,IBFN,IBDNM S IBCNT=0
 ;
 S IBDNM=$O(^DGCR(399.1,200),-1) I IBDNM'>79 S IBDNM=79
 ;
 F IBI=1:1 S IBLN=$P($T(CCF+IBI),";;",2) Q:IBLN=""  I $E(IBLN,1)'=" " D
 . ;
 . I +$$MCCRUTL($P(IBLN,U,1),15) Q
 . ;
 . F IBJ=1:1 S IBDNM=IBDNM+1 Q:'$D(^DGCR(399.1,IBDNM,0))
 . ;
 . K DD,DO S DLAYGO=399.1,DINUM=IBDNM,DIC="^DGCR(399.1,",DIC(0)="L",X=$P(IBLN,U,2) D FILE^DICN K DIC I Y<1 K X,Y Q
 . S IBFN=+Y,IBCNT=IBCNT+1
 . ;
 . S DR=".02////"_$P(IBLN,U,1)_";.22////"_1
 . S DIE="^DGCR(399.1,",DA=+IBFN D ^DIE K DIE,DA,DR,X,Y
 ;
BSQ S IBA(1)="      *  "_IBCNT_" Condition Codes added (#399.1)"
 D MES^XPDUTL(.IBA)
 Q
 ;
MCCRUTL(X,P) ; returns IFN of item in 399.1 if Code is found and piece P is true
 ;
 N IBX,IBY S IBY=""
 I $G(X)'="" S IBX=0 F  S IBX=$O(^DGCR(399.1,"C",X,IBX)) Q:'IBX  I $P($G(^DGCR(399.1,IBX,0)),U,+$G(P)) S IBY=IBX
 Q IBY
 ;
CCF ; condition codes (399.1)
 ;; 
 ;;01^MILITARY SERVICE RELATED
 ;;02^CONDITION IS EMPLOYMENT RELATED
 ;;03^PATIENT COVERED BY INSURANCE NOT REFLECTED HERE
 ;;04^HMO ENROLLEE
 ;;05^LIEN HAS BEEN FILED
 ;;06^ESRD PATIENT IN 1ST 18 MONTHS OF ENTITLEMENT COVERED BY EGHP
 ;;07^TREATMENT OF NON-TERMINAL CONDITION FOR HOSPICE PATIENT
 ;;08^BENEFICIARY WOULD NOT PROVIDE INFO ON OTHER INS COVERAGE
 ;;09^NEITHER PATIENT NOR SPOUSE IS EMPLOYED
 ;;10^PATIENT AND/OR SPOUSE IS EMPLOYED BUT NO EGHP EXISTS
 ;;11^DISABLED BENEFICIARY BUT NO LGHP
 ;;17^PATIENT IS OVER 100 YEARS OLD
 ;;18^MAIDEN NAME RETAINED
 ;;19^CHILD RETAINS MOTHER'S NAME
 ;;20^BENEFICIARY REQUESTED BILLING
 ;;21^BILLING FOR DENIAL NOTICE
 ;;22^PATIENT ON MULTIPLE DRUG REGIMEN
 ;;23^HOMECAREGIVER AVAILABLE
 ;;24^HOME IV PATIENT ALSO RECEIVING-HHA SERVICES
 ;;26^VA ELIGIBLE PATIENT CHOOSES A MEDICARE CERTIFIED FACILITY
 ;;27^PATIENT REFERRED TO A SOLE COMMUNITY HOSP FOR DIAGNOSTIC LAB
 ;;28^PATIENT AND/OR SPOUSE'S EGHP IS SECONDARY TO MEDICARE
 ;;29^DISABLED BENEFICIARY/FAMILY MEMBER LGHP SECONDARY TO MEDICAR
 ;;31^PATIENT IS STUDENT (FULL TIME - DAY)
 ;;32^PATIENT IS STUDENT (COOPERATIVE/WORK STUDY PROGRAM)
 ;;33^PATIENT IS STUDENT (FULL TIME - NIGHT)
 ;;34^PATIENT IS STUDENT (PART TIME)
 ;;36^GENERAL CARE PATIENT IN A SPECIAL UNIT
 ;;37^WARD ACCOMMODATION AT PATIENT REQUEST
 ;;38^SEMI-PRIVATE ROOM NOT AVAILABLE
 ;;39^PRIVATE ROOM MEDICALLY NECESSARY
 ;;40^SAME DAY TRANSFER
 ;;41^PARTIAL HOSPITALIZATION
 ;;46^NON-AVAILABILITY STATEMENT ON FILE
 ;;48^PSYCH RESIDENTIAL TREATMENT CENTERS CHILDREN AND ADOLESCENTS
 ;;55^SNF BED NOT AVAILABLE
 ;;56^MEDICAL APPROPRIATENESS
 ;;57^SNF READMISSION
 ;;60^DAY OUTLIER
 ;;61^COST OUTLIER
 ;;66^PROVIDER DOES NOT WISH COST OUTLIER PAYMENT
 ;;67^BENEFICIARY ELECTS NOT TO USE LIFE TIME RESERVE (LTR) DAYS
 ;;68^BENEFICIARY ELECTS TO USE LIFE TIME RESERVE (LTR) DAYS
 ;;70^SELF ADMINISTERED EPO
 ;;71^FULL CARE IN UNIT
 ;;72^SELF-CARE IN UNIT
 ;;73^SELF CARE TRAINING
 ;;74^HOME
 ;;75^HOME - 100% REIMBURSEMENT
 ;;76^BACK-UP IN FACILITY DIALYSIS
 ;;77^PROVIDER REQUIRED/ACCEPTS PAYMENT BY PRIMARY AS FULL PAYMENT
 ;;78^NEW COVERAGE NOT IMPLEMENTED BY HMO
 ;;79^CORF SERVICES PROVIDED OFFSITE SPEECH
 ;;A0^CHAMPUS EXTERNAL PARTNERSHIP PROGRAM
 ;;A1^EPSDT/CHAP
 ;;A2^PHYSICALLY HANDICAPPED CHILDREN'S PROGRAM
 ;;A3^SPECIAL FEDERAL FUNDING
 ;;A4^FAMILY PLANNING
 ;;A5^DISABILITY
 ;;A6^VACCINES/MEDICARE 100% PAYMENT
 ;;A7^INDUCED ABORTION DANGER TO LIFE
 ;;A8^INDUCED ABORTION VICTIM RAPE/INCEST
 ;;A9^SECONDARY OPINION SURGERY
 ;;C1^APPROVED AS BILLED
 ;;C2^AUTOMATIC APPROVAL AS BILLED BASED ON FOCUSED REVIEW
 ;;C3^PARTIAL APPROVAL
 ;;C4^ADMISSION/SERVICES DENIED
 ;;C5^POSTPAYMENT REVIEW APPLICABLE
 ;;C6^ADMISSION PREAUTHORIZATION
 ;;C7^EXTENDED AUTHORIZATION
 ;;D0^CHANGES TO SERVICE DATES
 ;;D1^CHANGES TO CHARGES
 ;;D2^CHANGES IN REVENUE CODES/HCPCS
 ;;D3^SECOND OR SUBSEQUENT INTERIM PPS BILL
 ;;D4^CHANGE IN GROUPER INPUT
 ;;D5^CANCEL TO CORRECT HICN OR PROVIDER ID
 ;;D6^CANCEL ONLY TO REPAY A DUPLICATE OR OIG OVERPAYMENT
 ;;D7^CHANGE TO MAKE MEDICARE THE SECONDARY PAYER
 ;;D8^CHANGE TO MAKE MEDICARE THE PRIMARY PAYER
 ;;D9^ANY OTHER CHANGE
 ;;E0^CHANGE IN PATIENT STATUS
 ;;
