IBDONIT ; ; 03-APR-1996
 ;;Version 2.1 ; AUTOMATED INFO COLLECTION SYS ;; 3-APR-96
 ;
 K DIF,DIK,DDF,DDT,DTO,D0,DLAYGO,DIC,DIR,DA,ORVROM,DFR,DTN,DIX,DZ
 S DIFQ=0,ORVROM=22 W !!,"This version of 'IBDONIT' was created on 03-APR-1996"
 W !?9,"(at ALBANY CAMPUS DEVELOPMENT, by OE/RR V.2.5)",!
 G Q:DIFQ D ^IBDONIT1 G Q:'$D(DIFQ) S DIK(0)="B"
 D ^IBDONIT2,^IBDONIT3
 L  W !,*7,"OK, Protocol Installation is Complete.",!
 K %ZW,%,%H,D0,DA,DIF,DIFQ,DIG,DIH,DIK,DIU,DIV,DSEC,I,J,KEY,DIY,N,NM,NO,ORVROM,R,X,X0
 Q
 ;
Q W *7,!!,"NO UPDATING HAS OCCURRED!" Q
 ;
IXF ;;IBD
