DSIVICIP ;DSS/SGM/CC - INITIALIZATION OF DSIV PARAMETERS ;05/17/2006 11:19
 ;;2.2;INSURANCE CAPTURE BUFFER;**1,4**;May 19, 2009;Build 7
 ;Copyright 1995-2010, Document Storage Systems, Inc., All Rights Reserved
 ;
 ; post-install for ICB PARAMETERS
 ; Integration Agreements
 ; 5323    MES^DSICXPDU
 ; 5322    $$ADD^DSICXPR,$$GET1^DSICXPR,ADD^DSICXPR
 ;
 Q
 ;
POST ;post-install, set parameter defaults for new sites
 N I,X,ENT,INST,PARAM,TAG,VAL,RET
 F I=1:1 S X=$P($T(@("VA+"_I)),";",3) Q:X=""  D
 .S PARAM="DSIV "_$P(X,U),VAL=$P(X,U,2),ENT=$P(X,U,3),INST=1
 .D SET
 .Q
 D MULT ;Multi-instance parameters
 Q
 ;
SET ;  add/update parameter for PACKAGE
 N I,J,X,Y,Z,DSIV,VEJX
 ;  does it exist? - dsicxpr returns 1 or -1^msg
 S DSIV="SYS~"_PARAM_"~"_INST_"~~~Q"
 S VEJX=$$GET1^DSICXPR(,DSIV,1) Q:VEJX'?1"-1^".E
 S $P(DSIV,"~",4)=VAL,Y=$$ADD^DSICXPR(,DSIV,1)
 Q
 ;
MULT ;;DSS/LM - Initialize [multi-instance] parameters
 ; Tag MP has data in the following format:
 ; First line has PARAMETER^ENTITY
 ; Following lines have INSTANCE^VALUE, one per line
 ; End of parameter indicated by one blank line (;;)
 ; End of initialization indicated by two blank lines
 ; 
 N DSIVI,DSIVPARM,DSIVENT,DSIVINST,DSIVVAL,DSIVQUIT,DSIVX
 S (DSIVPARM,DSIVQUIT)=""
 F DSIVI=1:1 S DSIVX=$P($T(@("MP+"_DSIVI)),";",3,99) D  Q:DSIVQUIT
 .I DSIVPARM="",DSIVX="" S DSIVQUIT=1 Q  ;All parameters done
 .I DSIVPARM=""!(DSIVX="") D  Q
 ..S DSIVPARM=$P(DSIVX,U),DSIVENT=$P(DSIVX,U,2)
 ..S:DSIVENT="" DSIVENT="SYS" ;Default entity
 ..Q
 .S DSIVINST=$P(DSIVX,U),DSIVVAL=$P(DSIVX,U,2) ;Instance value pair
 .D ADD^DSICXPR(,DSIVENT_"~"_DSIVPARM_"~"_DSIVINST_"~"_DSIVVAL)
 .Q
 Q
VA ;;
 ;;ALLOW EC FULL EDIT^1
 ;;ALLOW EC LIST VIEW^1
 ;;ALLOW GROUP PLAN EDIT^1
 ;;APPTS DAYS BACK^0
 ;;BUFFER DAYS BACK^7
 ;;ENABLE AUDIT^1
 ;;FORCE UPPERCASE^1
 ;;INDEX OPTION^0
 ;;REQUIRED EDIT COLOR^16777215
 ;;SOURCE DEFAULT^1
 ;;VER DAYS BACK^182
 ;;OCR THRESHHOLD^0.7
 ;;LOCAL EXCEL EXPORT^1
 ;;MAX NUM ENTRIES^100
 ;;
 ;;
MP ;;
 ;;DSIV REQUIRED EDIT FIELDS
 ;;CBOAMBCARECERT^GROUP POLICY|AMBULATORY CARE CERTIFICATION|0
 ;;CBOBENASSIGN^GROUP POLICY|BENEFITS ASSIGNABLE|0
 ;;CBOCOORDBEN^POLICY/SUBSCRIBER|COORDINATION OF BENEFITS|0
 ;;CBOELECPLANTYPE^GROUP POLICY|ELECTRONIC PLAN TYPE|0
 ;;CBOEMPSTATE^PROVIDER/EMPLOYER|EMPLOYER CLAIMS STATE|0
 ;;CBOEMPSTATUS^PROVIDER/EMPLOYER|EMPLOYMENT STATUS|0
 ;;CBOESGHP^POLICY/SUBSCRIBER|ESGHP|0
 ;;CBOEXCPREEXISTCOND^GROUP POLICY|EXCLUDE PRE-EXISTING CONDITION|0
 ;;CBOINSSEX^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=0|INSURED'S SEX|0
 ;;CBOINSUREDBRANCH^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=0|INSURED'S BRANCH|0
 ;;CBOINSUREDRANK^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=0|INSURED'S RANK|0
 ;;CBOPLANSTDFTF^GROUP POLICY|PLAN STANDARD FTF|0
 ;;CBOPRECERTREQ^GROUP POLICY|PRE-CERTIFICATION REQUIRED|0
 ;;CBOPTRELTOINS^POLICY/SUBSCRIBER|PT. RELATIONSHIP TO INSURED|0
 ;;CBOREIMBURSE^INSURANCE COMPANY|REIMBURSE|1
 ;;CBOSENDBILLTOEMP^PROVIDER/EMPLOYER|SEND BILL TO EMPLOYER|0
 ;;CBOSOURCE^INSURANCE COMPANY|SOURCE|1
 ;;CBOSTATE^INSURANCE COMPANY|STATE|0
 ;;CBOTYPEOFPLAN^GROUP POLICY|TYPE OF PLAN|0
 ;;CBOUTILREVREQ^GROUP POLICY|UTILIZATION REVIEW REQUIRED|0
 ;;CBOWHOSEINS^POLICY/SUBSCRIBER|WHOSE INSURANCE|0
 ;;CBOPOLNOTBILL^POLICY/SUBSCRIBER|POLICY NOT BILLABLE|0
 ;;EDTBANKIDNO^GROUP POLICY|BANKING ID NUMBER|0
 ;;EDTBILLPHONENO^INSURANCE COMPANY|BILLING PHONE NUMBER|0
 ;;EDTCITY^INSURANCE COMPANY|CITY|0
 ;;EDTEFFDATE^POLICY/SUBSCRIBER|EFFECTIVE DATE|0
 ;;EDTEMPCITY^PROVIDER/EMPLOYER|EMPLOYER CLAIMS CITY|0
 ;;EDTEMPSTREET1^PROVIDER/EMPLOYER|EMPLOYER CLAIMS STREET [1]|0
 ;;EDTEMPSTREET2^PROVIDER/EMPLOYER|EMPLOYER CLAIMS STREET [2]|0
 ;;EDTEMPSTREET3^PROVIDER/EMPLOYER|EMPLOYER CLAIMS STREET [3]|0
 ;;EDTEMPZIP^PROVIDER/EMPLOYER|EMPLOYER CLAIMS ZIP|0
 ;;EDTEMPPHONENO^PROVIDER/EMPLOYER|EMPLOYER CLAIMS PHONE|0
 ;;EDTEXPDATE^POLICY/SUBSCRIBER|EXPIRATION DATE|0
 ;;EDTGROUPNAME^GROUP POLICY|GROUP NAME|0
 ;;EDTGROUPNO^GROUP POLICY|GROUP NUMBER|0
 ;;EDTGROUPPOLCOMMENTS^GROUP POLICY|GROUP POLICY COMMENTS|0
 ;;EDTINSCONAME^INSURANCE COMPANY|INSURANCE COMPANY|1
 ;;EDTINSDOB^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=0|INSURED'S DOB|0
 ;;EDTINSSSN^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=0|INSURED'S SSN|0
 ;;EDTINSUREDSTREET1^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=1|INSURED'S STREET 1|0
 ;;EDTINSUREDSTREET2^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=1|INSURED'S STREET 2|0
 ;;EDTINSUREDCITY^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=1|INSURED'S CITY|0
 ;;EDTINSUREDSTATE^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=1|INSURED'S STATE|0
 ;;EDTINSUREDZIP^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=1|INSURED'S ZIP|0
 ;;EDTINSUREDPHONE^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=1|INSURED'S PHONE|0
 ;;EDTNAMEOFINS^POLICY/SUBSCRIBER|NAME OF INSURED|0
 ;;EDTPATIENTID^POLICY/SUBSCRIBER|PATIENT ID|0
 ;;EDTPATPOLCOMMENTS^POLICY/SUBSCRIBER|PATIENT POLICY COMMENTS|0
 ;;EDTPCN^GROUP POLICY|PROCESS CONTROL NO. (PCN)|0
 ;;EDTPCPROV^PROVIDER/EMPLOYER|PRIMARY CARE PROVIDER|0
 ;;EDTPCPROVPHONENO^PROVIDER/EMPLOYER|PROVIDER PHONE NUMBER|0
 ;;EDTPHONENO^INSURANCE COMPANY|PHONE NUMBER|0
 ;;EDTPLANFILETIMEFRAME^GROUP POLICY|PLAN FILE TIME FRAME|0
 ;;EDTPLANSTDFTFVALUE^GROUP POLICY|PLAN STANDARD FTF VALUE|0
 ;;EDTPRECERTPHONENO^INSURANCE COMPANY|PRE-CERT PHONE NUMBER|0
 ;;EDTRETDATE^PROVIDER/EMPLOYER|RETIREMENT DATE|0
 ;;EDTSPEMPNAME^PROVIDER/EMPLOYER|SPONSORING EMPLOYER NAME|0
 ;;EDTSTREET1^INSURANCE COMPANY|STREET ADDRESS [1]|0
 ;;EDTSTREET2^INSURANCE COMPANY|STREET ADDRESS [2]|0
 ;;EDTSTREET3^INSURANCE COMPANY|STREET ADDRESS [3]|0
 ;;EDTSUBSCRID^POLICY/SUBSCRIBER$$PGINSUREDSUBSCRIBER=0|SUBSCRIBER ID|0
 ;;EDTZIP^INSURANCE COMPANY|ZIP CODE|0
 ;;
 ;;DSIV PAGE SETUP
 ;;BOTTOM MARGIN^0.5
 ;;FONT NAME^COURIER NEW
 ;;FONT SIZE^10
 ;;LEFT MARGIN^0.25
 ;;PAGE NUMBER ON^1
 ;;PAGE ORIENTATION^0
 ;;RIGHT MARGIN^0.25
 ;;TOP MARGIN^0.5
 ;;
 ;;
