DSIV12 ;DSS/CAJ - POST INSTALL P12 ;12/16/2015 12:28
 ;;2.2;INSURANCE CAPTURE BUFFER;**12**;May 19, 2009;Build 13
 ;Copyright 1995-2015, Document Storage Systems, Inc., All Rights Reserved
 ;
 ;   ICR#  Description
 ;  -----  --------------------------------------
 ;   5322  $$GET1^DSICXPR,CHG^DSICXPR
 ;
 Q
POST ;Post Install Routine
 N DSIVINST,DSIVI,DSIVRET
 S DSIVINST(1)="CBOINSSEX"
 S DSIVINST(2)="CBOINSUREDBRANCH"
 S DSIVINST(3)="CBOINSUREDRANK"
 S DSIVINST(4)="CBOINSUREDSTATE"
 S DSIVINST(5)="CBOPTRELTOINS"
 S DSIVINST(6)="EDTINSDOB"
 S DSIVINST(7)="EDTINSSSN"
 S DSIVINST(8)="EDTINSUREDCITY"
 S DSIVINST(9)="EDTINSUREDPHONE"
 S DSIVINST(10)="EDTINSUREDSTREET1"
 S DSIVINST(11)="EDTINSUREDSTREET2"
 S DSIVINST(12)="EDTINSUREDZIP"
 S DSIVINST(13)="EDTNAMEOFINS"
 F DSIVI=1:1:13 D
 .N DSIV,DSIVLBL,DSIVCHAR,DSIVAL
 .D GET1^DSICXPR(.DSIV,"SYS~DSIV REQUIRED EDIT FIELDS~"_DSIVINST(DSIVI))
 .Q:+$G(DSIV)=-1
 .S DSIVLBL=$P(DSIV,"|",2)
 .S DSIVCHAR=$F(DSIVLBL,"INSURED")-1
 .S $E(DSIVLBL,DSIVCHAR-6,DSIVCHAR)="SUBSCRIBER"
 .S DSIVAL=$P(DSIV,"|")_"|"_DSIVLBL_"|"_$P(DSIV,"|",3)
 .D CHG^DSICXPR(.DSIVRET,"SYS~DSIV REQUIRED EDIT FIELDS~"_DSIVINST(DSIVI)_"~"_DSIVAL)
 Q
