VEJDHLR1 ;DCN/DSS RPC's FOR HL7 TOOL GUI (Cont.) MAR 24, 2005
 ;;3.5;VEJD DSS CORE RPCS;;Jan 03, 2006
 ;Copyright 1995-2006, Document Storage Systems, Inc., All Rights Reserved
 Q
DRAEGER(RET) ;GO TO HL7 FILES AND FIND STUFF FOR DRAEGER PROJECT.
 ;RPC IS: 'VEJD HL7 DRAEGER' 
 S CT=1,RET(CT)="Draeger setup files: ",CT=CT+1,RET(CT)="",CT=CT+1,RET(CT)="Protocols:"
 F I=1:1 S X=$P($T(TBL+I),";",2) Q:X="~"  S CT=CT+1,RET(CT)=$$PADN(X,45) D
 . ;NOW CHECK OUT THE PROTOCOLS
 . S RET(CT)=RET(CT)_"  IEN: "_$$STUFF($$EXISTS(X,101),5) ;CHECK THE PROTOCOL FILE 101
 . I $E($$SUBSC(IEN),1,3)'="Not" S RET(CT)=RET(CT)_" Has SUBSCRIBER: "_$$SUBSC(IEN)
 S CT=CT+1,RET(CT)="",CT=CT+1,RET(CT)="HL7 Applications"
 F I=1:1 S X=$P($T(TBL1+I),";",2) Q:X="~"  S CT=CT+1,RET(CT)=$$PADN(X,45) D
 . S RET(CT)=RET(CT)_"  IEN: "_$$STUFF($$EXISTS(X,771),5)_"  "_$$ACTIVE(IEN) ;CHECK THE HL7 FILE 771, CHECK FOR ACTIVE
 S CT=CT+1,RET(CT)="",CT=CT+1,RET(CT)="HL LOGICAL LINKS"
 F I=1:1 S X=$P($T(TBL2+I),";",2) Q:X="~"  S CT=CT+1,RET(CT)=$$PADN(X,45) D
 . S RET(CT)=RET(CT)_"  IEN: "_$$STUFF($$EXISTS(X,870),5)_"  "_$$GET1^DIQ(870,IEN,4)_" Port: "_$$GET1^DIQ(870,IEN,400.02)_" Addr: "_$$GET1^DIQ(870,IEN,400.01)
 S CT=CT+1,RET(CT)="~"
 Q
THERA(RET) ;GO TO HL7 FILES AND FIND STUFF FOR DRAEGER PROJECT.
 S CT=1,RET(CT)="TheraDoc setup files: ",CT=CT+1,RET(CT)="",CT=CT+1,RET(CT)="Protocols:"
 F II=1:1 S X=$P($T(THER+II),";",3) Q:X="Q"  D
 . ;NOW CHECK OUT THE PROTOCOLS
 . S IEN=$$EXISTS(X,101),XX=X,ZIEN=IEN ;CHECK THE PROTOCOL FILE 101
 . S DIS=$$GET1^DIQ(101,ZIEN_",",2),DISP=$S(DIS]"":$E(DIS,1,9),1:" <ENABLED> ")
 . S TYPE="SET"_IEN
 . S TYPE=$$GET1^DIQ(101,ZIEN_",","TYPE")
 . S STUFF=$$GET1^DIQ(101,ZIEN_",",.01)
 . S TYPED=$S($L(TYPE)>0:$E(TYPE,1,12),1:" <UNK> ")
 . S CT=CT+1,RET(CT)=$$PADN(IEN,10)_$$PADN(XX,40)_$$PADN(DISP,12)_$$PADN(TYPED,15)
 . I TYPED="extended act" K LIST10 S LIST10="" D ITEMS(IEN,.LIST10) I $D(LIST10)=11 D  K LIST10
 . . S I=0 F  S I=$O(LIST10(I)) Q:I=""  D
 . . . S CT=CT+1,RET(CT)=LIST10(I)
 . K LIS S LIS="" D SUBSCM(IEN,.LIS) I LIS(0)=0 Q
 . S I=0 F  S I=$O(LIS(I)) Q:I=""  D
 . . S CT=CT+1,RET(CT)=LIS(I)
 S CT=CT+1,RET(CT)="",CT=CT+1,RET(CT)="HL7 Applications"
 F I=1:1 S X=$P($T(THER1+I),";",3) Q:X="Q"  S CT=CT+1,RET(CT)=$$PADN(X,45) D
 . S RET(CT)=RET(CT)_"  IEN: "_$$STUFF($$EXISTS(X,771),5)_"  "_$$ACTIVE(IEN) ;CHECK THE HL7 FILE 771, CHECK FOR ACTIVE
 S CT=CT+1,RET(CT)="",CT=CT+1,RET(CT)="HL LOGICAL LINKS"
 F I=1:1 S X=$P($T(THER2+I),";",3) Q:X="Q"  S CT=CT+1,RET(CT)=$$PADN(X,45) D
 . S RET(CT)=RET(CT)_"  IEN: "_$$STUFF($$EXISTS(X,870),5)_"  "_$$GET1^DIQ(870,IEN,4)_" Port: "_$$GET1^DIQ(870,IEN,400.02)_" Addr: "_$$GET1^DIQ(870,IEN,400.01)
 S CT=CT+1,RET(CT)="~"
 Q
MEDREC(RET) ;VACC CHART COMPLETE CONFIG REPORT DCN/DSS MAR 24, 2005
 ;RPC IS: 'VEJD HL7 VACC'
 S CT=1,RET(CT)="<<MedRec Site Parameters: "
 ;GO OUT TO THE PARAMETER FILE AND GET THE DATA
 D GETS^DIQ(19607.2,1,"**","E","PARAM")
 D NOW^%DTC S CT=CT+1,RET(CT)="    on "_$$FMTE^XLFDT(%,1)
 I $G(DUZ(2)) S DIV=$$GET1^DIQ(4,DUZ(2),.01,"E") I DIV]"" S CT=CT+1,RET(CT)="    for Station: "_DIV
 S CT=CT+1,RET(CT)="NAME:                    "_$G(PARAM(19607.2,"1,",.01,"E"))
 S CT=CT+1,RET(CT)="FILE:                    "_$G(PARAM(19607.2,"1,",1,"E"))
 S CT=CT+1,RET(CT)="LAST INDEX:              "_$G(PARAM(19607.2,"1,",2,"E"))
 S CT=CT+1,RET(CT)="LOOK-BACK DAYS:          "_$G(PARAM(19607.2,"1,",3,"E"))
 S CT=CT+1,RET(CT)="H&P DOC CLASS NAME:      "_$G(PARAM(19607.2,"1,",5,"E"))
 S CT=CT+1,RET(CT)="BG JOB LAST RUN:         "_$G(PARAM(19607.2,"1,",6,"E"))
 S CT=CT+1,RET(CT)="Tracking Residents:      "_$G(PARAM(19607.2,"1,",7,"E"))
 S CT=CT+1,RET(CT)="ADM NOTE REQUIRED:       "_$G(PARAM(19607.2,"1,",8,"E"))
 S CT=CT+1,RET(CT)="SURGERY NOTE TRACKING:   "_$G(PARAM(19607.2,"1,",9,"E"))
 S CT=CT+1,RET(CT)="SURG NOTE LOOKBACK DAYS: "_$G(PARAM(19607.2,"1,",10,"E"))
 S CT=CT+1,RET(CT)="Observation Treating Specialties found: "
 I $D(PARAM(19607.24))=0 W " <NONE FOUND> " Q
 S L=0 F  S L=$O(PARAM(19607.24,L)) Q:L=""  S OT=PARAM(19607.24,L,.01,"E") S CT=CT+1,RET(CT)="          "_OT
 S CT=CT+1,RET(CT)="" ;PUT IN BLANK LINE
 S CT=CT+1,RET(CT)="<<Protocols:"
 S CT=CT+1,RET(CT)=$$PADN("IENS",10)_$$PADN("PROTOCOL NAME",40)_$$PADN("DISABLED",10)_$$PADN("TYPE",10)_$$PADN("SUBSCRIBER",10)
 F I=1:1 S XX=$P($T(AJRL+I),";",3) Q:XX="Q"  D
 . ;NOW CHECK IT OUT
 . S IEN=$$FIND1^DIC(101,,"X",XX) I IEN="" S IEN="NOT FOUND ==> " S CT=CT+1,RET(CT)=XX_"("_IEN_")" Q
 . S DIS=$$GET1^DIQ(101,IEN,2,"E"),DISP=$S(DIS]"":$E(DIS,1,9),1:" <ENABLED> ")
 . S TYPE=$$GET1^DIQ(101,IEN,4,"E"),TYPED=$S(TYPE]"":$E(TYPE,1,5),1:" <UNK> ")
 . S CT=CT+1,RET(CT)=$$PADN(IEN,10)_$$PADN(XX,40)_$$PADN(DISP,10)_$$PADN(TYPED,10)
 . I $D(^ORD(101,IEN,775))=0 S RET(CT)=RET(CT)_" No Subscribers" Q
 . S (SUB,CNT)=0 F  S SUB=$O(^ORD(101,IEN,775,SUB)) Q:+SUB<1  S SUBSC=^(SUB,0),CNT=CNT+1 D
 . . I CNT=1 S RET(CT)=RET(CT)_$$PADN($$GET1^DIQ(101,SUBSC,.01,"E"),30) Q
 . . S CT=CT+1,RET(CT)=$$STUFF("-",70)_$$PADN($$GET1^DIQ(101,SUBSC,.01,"E"),30)
 Q
PADD(NAME) ;PAD THE NAME IN 20 CHARACTERS AND RETURN IN ARRAY
 S SPACE="                                        "
 S PADD=$E((NAME_SPACE),1,20)
 Q PADD
PADN(NAME,NUM) ;PAD THE NAME IN NUM CHARACTERS AND RETURN IN ARRAY
 S SPACE="                                        "
 S PADD=$E((NAME_SPACE),1,NUM)
 Q PADD
STUFF(STR,LEN) ;RIGHT JUSTIFY DATA
 N STUFF
 I $L(STR)>LEN S STUFF=STR Q STUFF
 F  Q:$L(STR)=LEN  S STR=" "_STR
 K LEN
 Q STR
EXISTS(X,FILE) ;CHECK FILE 101, RETURN THE IEN
 S IEN=$$FIND1^DIC(FILE,,"X",X)
 Q IEN
ACTIVE(IEN) ;DETERMINE IF ACTIVE FROM INTERNAL NUMBER INPUT
 S ACTIVE="NOT ACTIVE"
 S ACTIVE=$$GET1^DIQ(771,IEN,2)
 Q "("_ACTIVE_")"
SUBSC(IEN) ;USING INTERNAL NUMB OF PROTOCOL, CHECK FOR DRAEGER SUBSCRIPTON
 S EN=0,NAMEF="",SUBSC="Not Found" F  S EN=$O(^ORD(101,IEN,775,"B",EN)) Q:EN=""  S NAME=$$GET1^DIQ(101,EN,.01) I $E(NAME,1,4)="VEJD" S NAMEF=NAMEF_NAME_";"
 S LEN=$L(NAMEF) I LEN>0 S SUBSC=$E(NAMEF,1,(LEN-1))
 Q SUBSC
SUBSCM(IEN,LIS) ;USING INTERNAL NUM OF PROTOCOL, RETURN LIST OF SUBSCRIBERS
 S CNT=0
 I $D(^ORD(101,IEN,775))=0 S LIS(0)=0 Q  ;No Subscribers
 S (SUB,CNT)=0 F  S SUB=$O(^ORD(101,IEN,775,SUB)) Q:+SUB<1  S SUBSC=^(SUB,0),CNT=CNT+1 D
 . ;I CNT=1 S LIS(CNT)=$$PADN($$GET1^DIQ(101,SUBSC,.01,"E"),30) Q
 . S LIS(CNT)=$$STUFF("SUBSC--> ",50)_$$PADN($$GET1^DIQ(101,SUBSC,.01,"E"),30)
 . S LIS(0)=CNT
 Q
ITEMS(IEN,LIST10) ;RETURN A LIST FOR ITEMS ON EXTENDED ACTION
 N EN S EN=0
 D GETS^DIQ(101,IEN_",","10*","E","LIST1")
 ;NOW TAKE THE .01 OUT OF IT
 S CNT=0 F  S EN=$O(LIST1(101.01,EN)) Q:EN=""  S DATA=$G(LIST1(101.01,EN,.01,"E")) Q:DATA=""  D
 . S CNT=CNT+1,LIST10(CNT)=$$STUFF("Item:--> ",50)_$$PADN(DATA,15)
 K LIST1
 Q
TBL ;TABLE OF PROTOCOLS FOR DRAEGER PROJECT
 ;SR Notification of Appointment Booking
 ;SR Notification of Appointment Cancellation
 ;SR Notification of Appointment Modification
 ;VEJD DRAEGER SIU-S12 CLIENT
 ;VEJD DRAEGER SIU-S12 ROUTER
 ;VEJD DRAEGER SIU-S12 SERVER
 ;VEJD DRAEGER SIU-S14 CLIENT
 ;VEJD DRAEGER SIU-S14 ROUTER
 ;VEJD DRAEGER SIU-S14 SERVER
 ;VEJD DRAEGER SIU-S15 CLIENT
 ;VEJD DRAEGER SIU-S15 ROUTER
 ;VEJD DRAEGER SIU-S15 SERVER
 ;LA7 LAB RESULTS AVAILABLE (EVN)
 ;VEJD DRAEGER LAB CLIENT
 ;VEJD DRAEGER LAB ROUTER
 ;VEJD DRAEGER LAB SERVER
 ;~
TBL1 ;TABLE OF APPLICATIONS
 ;VEJD DRAEGER CL
 ;VEJD DRAEGER SR
 ;SR SURGERY
 ;SR AAIS
 ;~
TBL2 ;TABLE OF HL LOGICAL LINKS
 ;VEJD DR-CL
 ;VEJDR-LAB
 ;~
AJRL ;LIST OF KNOWN AJR PROTOCOLS IN THE CAIRO CODE
 ;;AJR QUAD A01 INPT CLIENT
 ;;AJR QUAD A01 INPT SERVER
 ;;AJR QUAD A02 INPT CLIENT
 ;;AJR QUAD A02 INPT SERVER
 ;;AJR QUAD A03 INPT CLIENT
 ;;AJR QUAD A03 INPT SERVER
 ;;AJR QUAD A04 OUTPT CLIENT
 ;;AJR QUAD A04 OUTPT SERVER
 ;;AJR QUAD A08 INPT CLIENT
 ;;AJR QUAD A08 INPT SERVER
 ;;AJR QUAD A08 OUTPT CLIENT
 ;;AJR QUAD A08 OUTPT SERVER
 ;;AJR QUAD A11 INPT CLIENT
 ;;AJR QUAD A11 INPT SERVER
 ;;AJR QUAD A12 INPT CLIENT
 ;;AJR QUAD A12 INPT SERVER
 ;;AJR QUAD A13 INPT CLIENT
 ;;AJR QUAD A13 INPT SERVER
 ;;AJRQIADT
 ;;AJRQOADT
 ;;VEJDDEF A01
 ;;VEJDDEF A03
 ;;VEJD DEFICIENCY IADT
 ;;VEJD DEFICIENCY OADT
 ;;VEJD DEFICIENCY QUAD A01 INPT CLIENT
 ;;VEJD DEFICIENCY QUAD A01 INPT SERVER
 ;;VEJD DEFICIENCY QUAD A02 INPT CLIENT
 ;;VEJD DEFICIENCY QUAD A02 INPT SERVER
 ;;VEJD DEFICIENCY QUAD A03 INPT CLIENT
 ;;VEJD DEFICIENCY QUAD A03 INPT SERVER
 ;;VEJD DEFICIENCY QUAD A04 OUTPT CLIENT
 ;;VEJD DEFICIENCY QUAD A04 OUTPT SERVER
 ;;VEJD DEFICIENCY QUAD A08 INPT CLIENT
 ;;VEJD DEFICIENCY QUAD A08 INPT SERVER
 ;;VEJD DEFICIENCY QUAD A08 OUTPT CLIENT
 ;;VEJD DEFICIENCY QUAD A08 OUTPT SERVER
 ;;VEJD DEFICIENCY QUAD A11 INPT CLIENT
 ;;VEJD DEFICIENCY QUAD A11 INPT SERVER
 ;;VEJD DEFICIENCY QUAD A12 INPT CLIENT
 ;;VEJD DEFICIENCY QUAD A12 INPT SERVER
 ;;VEJD DEFICIENCY QUAD A13 INPT CLIENT
 ;;VEJD DEFICIENCY QUAD A13 INPT SERVER
 ;;Q
THER ;LIST OF THERADOC PROTOCOLS
 ;;DSID LA7 ROUTER
 ;;DSID LR7O CAPTURE
 ;;LA7 LAB RESULTS AVAILABLE (EVN)
 ;;DSID ORM-O01 CLIENT LAB
 ;;DSID ORM-O01 CLIENT PHARM
 ;;DSID ORM-O01 SERVER LAB
 ;;DSID ORM-O01 SERVER PHARM
 ;;DSID ORU-R01 ALERTS PROCESSOR
 ;;DSID ORU-R01 ALERTS SERVER
 ;;RA RPT 2.3
 ;;DSID ORU-R01 CLIENT
 ;;DSID ORU-R01 ROUTER
 ;;DSID ORU-R01 SERVER
 ;;PS EVSEND OR
 ;;DSID PS CAPTURE
 ;;VAFC ADT-A01 SERVER
 ;;VAFC ADT-A02 SERVER
 ;;VAFC ADT-A03 SERVER
 ;;VAFC ADT-A04 SERVER
 ;;VAFC ADT-A08-TSP SERVER
 ;;VAFC ADT-A11 SERVER
 ;;VAFC ADT-A12 SERVER
 ;;VAFC ADT-A13 SERVER
 ;;DSIDHL ADT-A01 CLIENT
 ;;DSIDHL ADT-A01 ROUTER
 ;;DSIDHL ADT-A01 SERVER
 ;;DSIDHL ADT-A02 CLIENT
 ;;DSIDHL ADT-A02 ROUTER
 ;;DSIDHL ADT-A02 SERVER
 ;;DSIDHL ADT-A03 CLIENT
 ;;DSIDHL ADT-A03 ROUTER
 ;;DSIDHL ADT-A03 SERVER
 ;;DSIDHL ADT-A04 CLIENT
 ;;DSIDHL ADT-A04 ROUTER
 ;;DSIDHL ADT-A04 SERVER
 ;;DSIDHL ADT-A08 CLIENT
 ;;DSIDHL ADT-A08 ROUTER
 ;;DSIDHL ADT-A08 SERVER
 ;;DSIDHL ADT-A11 CLIENT
 ;;DSIDHL ADT-A11 ROUTER
 ;;DSIDHL ADT-A11 SERVER
 ;;DSIDHL ADT-A12 CLIENT
 ;;DSIDHL ADT-A12 ROUTER
 ;;DSIDHL ADT-A12 SERVER
 ;;DSIDHL ADT-A13 CLIENT
 ;;DSIDHL ADT-A13 ROUTER
 ;;DSIDHL ADT-A13 SERVER
 ;;Q
THER1 ;THERADOC APPLICATIONS
 ;;DSID THERADOC
 ;;DSID VISTA
 ;;DSIDHL-INP-ADT
 ;;Q
THER2 ;THERADOC LOGICAL LINKS
 ;;DSIDHL_GEN
 ;;DSID_ADT
 ;;DSID_ALERT
 ;;DSID_LAB
 ;;DSID_PHARM
 ;;DSID_RAD
 ;;DSID_TCP
 ;;Q
