VEJDSYSU ;DSS/DBB - RPC TO CHECK/FIX VEJD SYSTEM USERS FILE (19619.1)
 ;;3.5;VEJD DSS CORE RPCS;;Jan 03, 2006
 ;Copyright 1995-2006, Document Storage Systems, Inc., All Rights Reserved
 ;DBB/3-18-04/ADDED IP TRACKING RPCs
 ;DBB/3-21-05/ADDED FILE CHECKS AND RE-INDEX
TEST K AXY  S DUZ=2,XWBTIP="101.101.101.888" D DT^DICRW D LOG(.AXY,"T","COMMENT")
 Q
TESTS K AXY D DT^DICRW D SRCH(.AXY,"","",2) ;10000000036)
 Q
 ;VEJDSYS USER SEARCH APP
 ;ADUZ = DUZ FROM FILE 200 TO limit SEARCH TO THIS USER
 ;APP = APP to limit search to, NULL = ALL
 ;FLAG = "L" for ONLY 'logged in" users, = "O" for offline users
SRCH(AXY,APP,FLAG,ADUZ) K AXY N VEJDFDA,VEJDMES N COUNT,I,X,APP2
 S COUNT=0,IEN=0
 I ADUZ S IEN=$O(^VEJD(19619.1,"B",ADUZ,"")) I 'IEN S AXY="-1^USER: "_ADUZ_",does not exist in file" Q
 ;I IEN,$O(^(IEN))="" G SRCH2
 ;S APP2=$G(APP) D SRCH2 F  S IEN=$O(^VEJD(19619.1,"B",ADUZ,IEN)) Q:'IEN  S APP=APP2 D SRCH2
 ;Q
SRCH2 I ADUZ S X2=$$GET1^DIQ(19619.1,+IEN_",",.01,"E","","VEJDMES") I $D(VEJDMES) D MES Q
 S ADUZ22=ADUZ
 I APP'="" D IEN G SQ
 I APP="" F  S APP=$O(^VEJD(19619.1,"AB",APP)) Q:APP=""  D IEN
SQ I 'COUNT S AXY="-1^No records match search criteria" Q
 S AXY(0)=COUNT
 Q
IEN I IEN D IEN2 Q
 I 'IEN S IEN=0 F  S IEN=$O(^VEJD(19619.1,"AB",APP,IEN)) Q:'IEN  D IEN2
 Q
IEN2 S IEN2=0  F  S IEN2=$O(^VEJD(19619.1,"AB",APP,IEN,IEN2)) Q:'IEN2  D
 . S ADUZ2=+$G(^VEJD(19619.1,IEN,0)),IENX=IEN2_","_IEN_","
 . D GETDATA
 . ;S X1=$$GET1^DIQ(19619.1,+IENX,.01,"I","","VEJDMES") I $D(VEJDMES) D MES Q
 . ;S X2=$$GET1^DIQ(19619.1,+IENX,.01,"E","","VEJDMES") I $D(VEJDMES) D MES Q
 . I FLAG'[X2,FLAG'="" Q
 . D GETDAT2
 . S COUNT=COUNT+1,AXY(COUNT)=X
 Q
GETDATA S X0=$G(^VEJD(19619.1,IEN,3,IEN2,0)) S X1=$P(X0,"^") ;Q:X1'=APP
 S X1=X1_":"_$$EXTERNAL^DILFD(19619.132,.01,"",X1,"VEJDMES") I $D(VEJDMES) D MES Q
 S X2=$P(X0,"^",4),X3=$P(X0,"^",3),X4=$P(X0,"^",2) ; X2=STATUS, X3=IP, X4=LAST DATE LOGGEN IN
 S X2=X2_":"_$$EXTERNAL^DILFD(19619.132,3,"",X2,"VEJDMES") I $D(VEJDMES) D MES Q
 S X4=X4_":"_$$EXTERNAL^DILFD(19619.132,1,"",X4,"VEJDMES") I $D(VEJDMES) D MES Q
 ;S X=X1_":"_$$EXTERNAL^DILFD(19619.132,.01,"",X1,"VEJDMES") I $D(VEJDMES) D MES Q
 Q
GETDAT2 S X5=$$GET1^DIQ(19619.1,+IEN_",",.01,"E","","VEJDMES") I $D(VEJDMES) D MES Q
 S X=IEN_"^"_ADUZ2_":"_X5_"^"_X3_"^"_X4_"^"_X1_"^"_X2_"^"_$E($G(^VEJD(19619.1,IEN,3,IEN2,1)),1,80)
 Q
 ;VEJD SYS USER LOG
 ;ADUZ = DUZ from file 200
 ;IP = IP address
 ;FLAG= "U" (I.E. UPDATE) TO create (if necessary)
 ;= "O" to set user to OFFLINE mode
 ;= "" TO LOOKUP & RETURN:
 ;RETURN = "-1^ ERROR MESSAGE"; 0=OK; 
 ;   DUZ^IP^STATUS  (STATUS = L if logged in; "O" or null if offline)
 ;   APP = APPLICATION
 ;       T=TRM, R=ROI, D=DRM
 ;   COMMENT = FREE TEXT COMMENT, <= 80 CHARACTERS
LOG(AXY,APP,COMMENT) K AXY N DA,IP,VEJDFDA,VEJDMES,IEN,IEN2 S AXY=0
 I $G(ADUZ)="" S ADUZ=$G(DUZ)
 S IP=$G(XWBTIP) ;(VARIABLE FROM BROKER)
 ;K ^DBB2 S ^DBB2=DUZ_"^"_APP_"^"_IP_"^"_COMMENT
 ;I "UO"'[FLAG S AXY="-1^FLAG must be either 'U'pdate or 'O'ffline" Q
 I APP="" S APP="O" ;S AXY="-1^No APPLICATION specified" Q
 S IEN=$O(^VEJD(19619.1,"B",DUZ,"")) I 'IEN S AXY="-^USER: "_ADUZ_",does not exist in file" Q
 I IEN S DA=IEN F  S DA=$O(^(DA)) Q:'DA  S DIK="^VEJD(19619.1," D ^DIK ;ELIMINATE DUPLICATE DUZ ENTRIES
 S IEN2=$O(^VEJD(19619.1,"AB",APP,IEN,0)) I IEN2 S IENX=IEN2_","_IEN_","
 ;I 'IEN2 S AXY="-1^USER#"_ADUZ_", has no LOGIN DATA IP address" Q
 ;I FLAG="U" D CHKSYS("","F")
 ;I IEN,IEN2 S ADUZ2=ADUZ D GETDATA,GETDAT2 Q:$L($D(AXY))>1  S AXY(0)=X Q
 ;I IEN2 D  Q  ;" D  Q
 ;. S VEJDFDA(19619.132,IENX,3)="O"
 ;. D FILE^DIE("K","VEJDFDA","VEJDMES")  I $D(VEJDMES) D MES Q
 ;. D GETDATA,GETDAT2 S AXY=X
 I 'IEN2 S IENX="+1,"_IEN_","
 D NOW^%DTC
 ;*** I 'IEN Q:$D(VEJDMES)  Q  ;NO MAIN FILE ENTRY FOR THIS DUZ, SO CREATE ONE
 S VEJDFDA(19619.1,"+1,",.01)="`"_DUZ
 D UPDATE^DIE("E","VEJDFDA","IEN","VEJDMES") I $D(VEJDMES) D MES
 K FDA S VEJDFDA(19619.132,IENX,1)=% ;D/T
 S VEJDFDA(19619.132,IENX,2)=IP
 ;S VEJDFDA(19619.132,IENX,3)="L" ;STATUS
 I COMMENT'="" S VEJDFDA(19619.132,IENX,4)=COMMENT
 I APP'="" S VEJDFDA(19619.132,IENX,.01)=APP
 I IENX'["+" D FILE^DIE("KE","VEJDFDA","VEJDMES") I $D(VEJDMES) D MES Q
 I IENX["+" D
 . ;S VEJDFDA(19619.1,"+1,",.01)="`"_ADUZ
 . S VEJDFDA(19619.132,IENX,.01)=APP
 . D UPDATE^DIE("E","VEJDFDA","IEN2","VEJDMES") I $D(VEJDMES) D MES Q
 . I $D(IEN2(1)) S IEN2=IEN2(1)
 D GETDATA,GETDAT2 S AXY=X
 Q
MES N X K AXY
 S X="-1^" F I=1 S X=X_"^ "_VEJDMES("DIERR",I,"TEXT",1) Q:$L(X)>500
 S AXY(0)=X
 Q
CHKSYS(SUCCESS,FLAG) ; CHECK/FIX VEJD SYSTEM USERS FILE (19619.1): RPC: VEJD SYSTEM USER FIX
 ; SUCCESS(0) = 0^ if OK
 ;         = >0^ and count of failed records if errors
 ; subsequent lines are record #s in error (MAX 50)
 N COUNT,I,X,DIK
 K ^TMP("VEJDSYSU",$J) ; TEMP TALLY GLOBAL
 ;CHECK FOR DUPS
 S I=0,COUNT=0 F  S I=$O(^VEJD(19619.1,I)) Q:'I  D
 . S X=$G(^VEJD(19619.1,I,0)) S J=+X I 'X S COUNT=COUNT+1,SUCCESS(COUNT)=I_"^"_J Q
 . I $D(^TMP("VEJDSYSU",$J,J)) S COUNT=COUNT+1,SUCCESS(COUNT)=I_"^"_J Q  ;DUPLICATE ENTRY - DELETE ALL BUT FIRST ONE
 . S ^TMP("VEJDSYSU",$J,J)=""
 . Q:$D(^VA(200,J,0))  S COUNT=COUNT+1,SUCCESS(COUNT)=I_"^"_J Q  ;CHECK FOR IN FILE 200
 S SUCCESS(0)=COUNT_"^"
 Q:$TR(FLAG,"f","F")'["F"  S DIK="^VEJD(19619.1," ;FIRST DELETE BAD ENTRIES
 F I=1:1:COUNT S DA=+SUCCESS(I) D ^DIK S SUCCESS(I)=SUCCESS(I)_"^1"
 S DIK="^VEJD(19619.1,",DIK(1)=".01^B"
 K DA,^VEJD(19619.1,"B") D ENALL^DIK ; NOW KILL & RE-INDEX "B" INDEX
 K ^XTMP("VEJDSYSU",$J)
 Q
 ;RPC:VEJD SYS EMAIL
EMAIL(AXY) ;EMAIL ADDR BOOK FOR DSS
 F I=1:1 S X=$P($T(PHOBK+I),";",3) Q:X=""  S AXY(I)=X
 Q
PHOBK ;APP(TRM,ROI,DOC,DEN;address
 ;;support@docstorsys.com
 ;;developers@docstorsys.com
 ;;sales@docstorsys.com
