LAZCX7C ;SLC/DLG/FHS - BECKMAN CX7 UNI AND BIDIRECTIONAL ;4/29/91  07:25 ; [ 01/16/97  1:38 PM ]
 ;;5.02;LAB;;10/30/90 10:51
 ;CROSS LINK BY ID OR IDE
 ;;LOCAL MODIFIED DCN/BUF ACCESSION METHOD 11/22/91
LA1 S LANM=$T(+0),TSK=$O(^LAB(62.4,"C",LANM,0)) Q:TSK<1
 Q:'$D(^LA(TSK,"I",0))
 K LATOP D ^LASET Q:'TSK  S X="TRAP^"_LANM,@^%ZOSF("TRAP")
TEST B  S I=0 F J=0:0 S I=$O(TC(I)) Q:I<1  S:$D(TC(I,4))#2 TEST(TC(I,4))=I
 ; THIS BUILDS A FIX ARRY WHICH IS PARAM 1
F S I=0 F  S I=$O(TC(I)) Q:I=""  S FIX(TC(I,4))=TC(I,2)
LA2 K TV,Y S (BAD,TRAY,CUP,ID,IDE)="",TOUT=0,A=1 D IN G QUIT:TOUT,LA2:$P(IN,",",2)'="702"
 I $P(IN,",",3)="01" G LA2 ;D QC,IN,QC,HDR G:BAD LA2 G LA3
 I $P(IN,",",3)="03" D QC,RES G:BAD LA2 G LA3
 G LA2
LA3 G:ID<1 LA2 X LAGEN G LA2:'ISQN ;Can be changed by the cross-link code
 F I=0:0 S I=$O(TV(I)) Q:I<1  S:TV(I,1)]"" ^LAH(LWL,1,ISQN,I)=V
 G LA2
QC S Y(A)=IN,A=A+1 Q
HDR S:$P(Y(1),",",12)="NO" BAD=1 Q:BAD  S V=$P(Y(1),",",6) D NUM S IDE=+V,V=$P(Y(1),",",10) D NUM S ID=+V,V=$P(Y(1),",",8) D NUM S TRAY=V,V=$P(Y(1),",",9) D NUM S CUP=V
 Q
RES S V=$P(Y(1),",",6) D NUM S IDE=+V,V=$P(Y(1),",",8) D NUM S TRAY=+V,V=$P(Y(1),",",9) D NUM S CUP=+V,V=$P(Y(1),",",10) S:V["-" V=$P(V,"-",2) D NUM S ID=+V
 I $P(Y(1),",",22)'="NR" S BAD=1 Q:BAD
 S V=$P(Y(1),",",11) D NUM S TEST=V,V=$P(Y(1),",",16) D NUM,FIX S:"*#"[V V="" I X>0,($D(TEST(TEST))#2) S @TC(TEST(TEST),1)=+V
 Q
NUM S X="" F JJ=1:1:$L(V) S:$A(V,JJ)>32 X=X_$E(V,JJ)
 S V=X Q
IN S CNT=^LA(TSK,"I",0)+1 IF '$D(^(CNT)) S TOUT=TOUT+1 Q:TOUT>9  H 5 G IN
 S ^LA(TSK,"I",0)=CNT,IN=^(CNT),TOUT=0
 S:IN["~" CTRL=$P(IN,"~",2),IN=$P(IN,"~",1)
 Q
OUT S CNT=^LA(TSK,"O")+1,^("O")=CNT,^("O",CNT)=OUT
 LOCK ^LA("Q") S Q=^LA("Q")+1,^("Q")=Q,^("Q",Q)=TSK LOCK
 Q
QUIT LOCK ^LA(TSK) H 1 K ^LA(TSK),^LA("LOCK",TSK) I $D(ZTSK) D KILL^%ZTLOAD K ZTSK
 Q
TRAP D ^LABERR S T=TSK D SET^LAB G @("LA2^"_LANM) ;ERROR TRAP
 ;
FIX ; USE FOR PARAM 1 $SELECTS FOR POS/NEG RESULTS
 I $D(FIX(TEST)) X FIX(TEST)
 Q
