A4AADP1 ;HINES-CIOFO/JJM - PROGRAM TO AUDIT DEBTOR 7/29/99 20:30
 ;;1.0;**** CLASS III ****;;JUN 30, 1998
START ;;
DEBTOR ;; RETURNS DEBTOR
 N ERRCNT,OK,I,ICS,BN,TN,RCNT,DCNT,BCNT,TCNT,TERRCNT
 D INIT
 D DEBTOR^A4AARPT I Y=-1 D EXIT Q
 K DIC
 S DEBTOR=+Y
 W ?10,"DEBTOR",?20,"BILL NO.",?30,"TRANSACTION",?45,"ERROR  MESSAGES"
 D LOOPBN
 W !,$J(RCNT,10)," RECORDS CHECKED (",+$P(^PRCA(430,0),U,3),")"
 D:ERRCNT>0 ERRLIST^A4AADP2
 D EXIT
 W !,"EOJ"
 QUIT
 ;;
GETBILLS ;
 N END,DEBTOR
 S END=0
 F  D GETBILL Q:Y<1  D PBILL1^A4AARPT1
 QUIT
GETBILL ;
 S DIC="^PRCA(430,",DIC(0)="AEMNQZ" D ^DIC
 S BILL=+Y
 K DIC
 QUIT
SETUP ;
 D NOW^%DTC
 S RBAL=0,NATOTAL=0,TAO=0,SRBAL=0,END=0
 S (LST1,LST2,LST3,LST4,LST5,LST6,SRBAL)=0
 QUIT
BCHK1 ;; CHECK BILLS BY DEBTOR
 N ERRCNT,OK,I,ICS,BN,TN,RCNT,DCNT,BCNT,TCNT,TERRCNT,NATOTAL,SRBAL,DEBTOR
 S (ERRCNT,OK,I,ICS,BN,TN,RCNT,DCNT,BCNT,TCNT,TERRCNT,NATOTAL,SRBAL,DEBTOR)=0
 S DEBTOR=0,TEAMT=0
 D INIT,SETUP
 W "CHECKING FILE 430 FOR BAD BILLS "
 D HDR1
BLOOP1 S DEBTOR=0,DCNT=0,RCNT=0,ERRCNT=0
 F  S DEBTOR=$O(^PRCA(430,"C",DEBTOR)) W:(DCNT#10)=0 "." Q:'DEBTOR  D BLOOP2
 W !,?65,"__________",!,?65,$J(TEAMT,10,2)
 W !,$J(ERRCNT,10)," ERRORS FOUND"
 W !,$J(DCNT,10)," DEBTORS CHECKED (",+$P(^RCD(340,0),U,3),")"
 W !,$J(RCNT,10)," BILLS CHECKED (",+$P(^PRCA(430,0),U,3),")"
EBCHK1 ;
 ; N ERRCNT,OK,I,ICS,BN,TN,RCNT,DCNT,BCNT,TCNT,TERRCNT,NATOTAL,SRBAL,DEBTOR
 D EXIT
 QUIT
BLOOP2 ;
 D SETUP^A4AARPT
 S BN=0,DCNT=DCNT+1
 F  S BN=$O(^PRCA(430,"C",DEBTOR,BN)) Q:'BN  W:(RCNT#1000)=0 "-" D
    . S BILL=BN
    . S RCNT=RCNT+1
    . D PBILLSS
 QUIT
PBILL ;
 Q:'$G(BILL)
 S:'$D(DEBTOR) DEBTOR=+$P($G(^PRCA(430,BILL,0)),U,9)
 Q:'DEBTOR
 D SETUP
 D GETDAT^A4AARPT2
 ; S FLAG1=0
 S FLAG1=1
 D PRTBILL^A4AARPT1
 K DATE1,DATE2,DATE3,LST1,LST2,LST3,LST4,LST5,LST6,NAME,PAT,PG,SDAY,SRBAL
 K SSN,U1N4,X,DATE,F433N0,F433N1,F433N8,SFLAG,XDATE,BN,FLAG1,RBAL,TAO
 QUIT
PBILLS ;
 Q:'$G(BILL)
 S:'$D(DEBTOR) DEBTOR=+$P($G(^PRCA(430,BILL,0)),U,9)
 D SETUP
 D ^A4AARPT7
 I (BAL'=RBAL)!(CS=40)!((BAL'=0)&(CS=39))!((RBAL<0)&(CAT'=26))!((BAL'=0)&(CS=22)) D
   . S FLAG1=1
   . W !,"****  INCORRECT BILL BALANCE  ****"
 D PRTBILL^A4AARPT1
 S FLAG1=1
 QUIT
PBILLSS  ;
 D ^A4AARPT7
 I ((RBAL'=0)&(CS=23))!((BAL'=RBAL)&(CS'=23))!((BAL'=0)&(CS=39))!((RBAL<0)&(CAT'=26))!((BAL'=0)&(CS=22)) D
   . Q:'((CS=16)!(CS=28)!(CS=32)!(CS=33)!(CS=40)!(CS=42)!(CS=43))
   . S ERRCNT=ERRCNT+1
   . W !,ERRCNT,?10,DEBTOR,?20,BILL,"  ",CAT,"  ",CS,?40,$J(BAL,10,2)," -",$J(RBAL,10,2),?65,$J((BAL-RBAL),10,2)
   . S TEAMT=TEAMT+(BAL-RBAL)
 QUIT
HDR1 ; HEADER FOR SUMMARY BILL ERROR REPORT - 1
 W @IOF
 W !,?45," BILL  ",?53,"TRANSACTION"
 W !," COUNT",?10,"DEBTOR",?20,"BILL/CATEGORY/STATUS",?45,"BALANCE",?55,"BALANCE",?67,"DISCREPANCY"
 W !
 QUIT
PERROR1 ;;
 Q:'ERRCODE
 S ERRCNT=$G(ERRCNT)+1
 W !,$J(ERRCNT,8),$J($G(DEBTOR),8),$J($G(BN),8),$J($G(FAN0P8),3),$J($G(TN),8),?40,"ERROR # ",ERRCODE
 S ERRCODE=0
 QUIT
EXIT ;;
 QUIT
 D EOR^A4AARPT
CLEANUP ;;
 K ERRCNT,OK,RCNT,DCNT,TERRCNT,AT2,BCNT,BN,BN433,DAT,DCNT,DPT,ERRCNT
 K ERRCODE,NATD,RBAL,TAO,BAL,CAT,BILL,CS,DIC,FAN0P2,FLAG1,TEAMT
 K FAN0,FAN0P1,FAN0P8,FAN0P9,FAN6,FAN6P21
 K FBN0,FBN0P1,FBN0P10,FBN0P2,FBN0P4,FBN1,FBN1P2,FBN1P9
 K NAC,NACTDT,NAS,NAT,NAW,NB,NC,ND,OK,RCNT,TCNT,TDT,TERRCNT,TN,XTN
 K DAT,I,TN
 K X,Y
 QUIT
INIT ;; 
 S ERRCNT=0,OK=0,RCNT=0,DCNT=0,BCNT=0,TCNT=0,TERRCNT=0
 QUIT
LOOPAT2 ;;
 S DAT=0
 F  S DAT=$O(^PRCA(433,"AT",AT2,DAT)) Q:'DAT  D LOOPAT1
 QUIT
LOOPAT1 ;; LOOP THRU TRANSACTIONS
 S TN=0
 F  S TN=$O(^PRCA(433,"AT",AT2,DAT,TN)) Q:'TN  D
   . D GET433D^A4AADP3
   . S BN=BN433
   . D GET430D^A4AADP3
   . S DEBTOR=+FAN0P9
   . D CHK433
 ; D C430XR^A4AADP3
 QUIT
LOOPDAT ;; LOOP THRU DATES
 S DAT=0
 F  S DAT=$O(^PRCA(433,"ATD",DEBTOR,DAT)) Q:'DAT  D LOOPDTN
 QUIT
LOOPDTN ;; LOOP THRU TRANSACTIONS
 ; D C430XR^A4AADP3
 S TN=0
 F  S TN=$O(^PRCA(433,"ATD",DEBTOR,DAT,TN)) Q:'TN  D CHK433
 QUIT
LOOPBN ;;
 S BN=0
 F  S BN=$O(^PRCA(430,"C",DEBTOR,BN)) Q:'BN  D CHK430,LOOPBTN
 QUIT
LOOPBTN ;;
 S TN=0
 F  S TN=$O(^PRCA(433,"C",BN,TN)) Q:'TN  D CHK433
 QUIT
CHK433 ;
 Q:'TN
 S RCNT=RCNT+1,ERRCODE=0
 D GET433D^A4AADP3
 S BN=BN433
 D GET430D^A4AADP3
 D CHK1^A4AADP3
 I ERRCODE=1 D PERROR1 QUIT
 D CHK10^A4AADP3,PERROR1
 I (FBN0P10'=1)&(FBN0P4=2) D
   . D CHK11^A4AADP3,PERROR1
   . D CHK12^A4AADP3,PERROR1
   . D CHK13^A4AADP3,PERROR1
 D C433XR^A4AADP3,PERROR1
 QUIT
CHK430 ;
 Q:'BN
 D GET430D^A4AADP3
 D CHK2^A4AADP3
  I ERRCODE=2 D PERROR1 QUIT
 D CHK20^A4AADP3,PERROR1
 D CHK21^A4AADP3,PERROR1
 IF (FAN0P8'=15)&(FAN0P8'=26)&(FAN0P8'=27)&(FAN0P8'=40)&(FAN0P8'=49) D
   . D CHK22^A4AADP3,PERROR1
   . D:(FAN0P8'=21)&(FAN0P8'=31)&(FAN0P8=39) CHK23^A4AADP3,PERROR1
   . D CHK32^A4AADP3,PERROR1
 D C430XR^A4AADP3
 QUIT
PRTBILLS ;
 F  S BILL=0 D GETBILL Q:Y<1  D PRTBILL
 K A4AFRB,A4ANAT,A4APSB,A4ATNA,AB,BAL,BILL,BS,C,CA,CC,CS,DAT,DEBTOR,DMC,DMCAMT
 K DMCBD,END,EP,F430N6,FLAG1,I,IB,ITF,MF,NAF,NATOTAL,PB,PFLAG,PRCA4307
 K RBAL,RFLAG,SC,STATUS,TAMT,TAO,TDATE,TIME1,TIME2,TRANS,TYPE,X,Y
 QUIT
PRTBILL ;
 Q:'BILL
 N A4ADEV,POP,%ZIS,ZTRTN,ZTSAVE,A4AIOSV K IOP
 S ZTRTN="PBILL1^A4AARPT1"
 S ZTDESC="CLASS III AUDIT BILL"
 S ZTSAVE("BILL")=""
 D CHKDEV
 Q
CHKBILLS ; CHECK BILLS
 N A4ADEV,POP,%ZIS,ZTRTN,ZTSAVE,A4AIOSV K IOP
 S ZTRTN="^A4AARPT4"
 S ZTDESC="CLASS III CHECK BALANCE OF BILLS"
 D CHKDEV
 Q
 ;
CHKDEV ;check device for queueing or local
 S %ZIS="QM",%ZIS("B")="" D ^%ZIS G:POP CLOSEDV S (IOP,A4ADEV)=ION_";"_IOST_";"_IOM_";"_IOSL,A4AIOSV=IO(0)
 I IO=IO(0) D @ZTRTN G CLOSEDV
 I $D(IO("Q")) D
  . D ^%ZTLOAD
 E  U IO D @ZTRTN
 W:$D(ZTSK) !,"TASK NUMBER ",ZTSK
 D CLOSEDV
 QUIT
 ;
CLOSEDV ;close device and exit routine
 W:IO'=IO(0) @IOF D ^%ZISC I '$D(ZTSK) S:$D(A4AIOSV) IO(0)=A4AIOSV U IO(0)
 K X,Y,ZTSK
