A4AARPT4 ;HINES-CIOFO/JJM - PROGRAM TO AUDIT BILLS 7/19/99 16:45
 ;;1.0;**** CLASS III ****;;JUN 30, 1998
START ;;
BCHK4 ;; CHECK BILLS 
 N ERRCNT,OK,I,ICS,BN,TN,RCNT,DCNT,BCNT,TCNT,TERRCNT,NATOTAL,SRBAL,DEBTOR
 S (ERRCNT,OK,I,ICS,BN,TN,RCNT,DCNT,BCNT,TCNT,TERRCNT,NATOTAL,SRBAL,DEBTOR)=0
 S DEBTOR=0,TEAMT=0
 D INIT,SETUP^A4AADP1
 D NOW^%DTC
 W "CHECKING FILE 430 FOR BAD BILLS (",%,")"
 D HDR1^A4AADP1
BLOOP1 S BN=0,DCNT=0,RCNT=0,ERRCNT=0
 F  S BN=$O(^PRCA(430,BN))  Q:'BN  D BLOOP2
 W !,?65,"__________",!,?65,$J(TEAMT,10,2)
 W !,$J(ERRCNT,10)," ERRORS FOUND"
 W !,$J($P(^PRCA(430,0),U,4),10)," RECORDS IN FILE 430"
 W !,$J(RCNT,10)," BILLS CHECKED (",+$P(^PRCA(430,0),U,3),")"
 D NOW^%DTC
 W !!,"EOJ (",%,")"
EBCHK4  ;
 ; N ERRCNT,OK,I,ICS,BN,TN,RCNT,DCNT,BCNT,TCNT,TERRCNT,NATOTAL,SRBAL,DEBTOR
 D EXIT
 D CLOSEDV^A4AADUQ
 QUIT
BLOOP2 ;
 D SETUP^A4AARPT
 S DCNT=DCNT+1
 S BILL=BN
 S DEBTOR=+($P($G(^PRCA(430,BN,0)),U,9))
 S RCNT=RCNT+1
 D PBILLSS
 QUIT
PBILLSS  ;
 D ^A4AARPT7
 I ((RBAL'=0)&(CS=23))!((BAL'=RBAL)&(CS'=23))!((BAL'=0)&(CS=39))!((RBAL<0)&(CAT'=26))!((BAL'=0)&(CS=22)) D
   . Q:'((CS=16)!(CS=28)!(CS=32)!(CS=33)!(CS=40)!(CS=42)!(CS=43))
   . S ERRCNT=ERRCNT+1
   . W !,ERRCNT,?10,DEBTOR,?20,BILL,"  ",CAT,"  ",CS,?40,$J(BAL,10,2)," -",$J(RBAL,10,2),?65,$J((BAL-RBAL),10,2)
   . S TEAMT=TEAMT+(BAL-RBAL)
 QUIT
EXIT ;;
 D EOR^A4AARPT
CLEANUP ;;
 K ERRCNT,OK,RCNT,DCNT,TERRCNT,AT2,BCNT,BN,BN433,DAT,DCNT,DPT,ERRCNT
 K ERRCODE,NATD,RBAL,TAO,BAL,CAT,BILL,CS,DIC,FAN0P2,FLAG1,TEAMT
 K FAN0,FAN0P1,FAN0P8,FAN0P9,FAN6,FAN6P21
 K FBN0,FBN0P1,FBN0P10,FBN0P2,FBN0P4,FBN1,FBN1P2,FBN1P9
 K NAC,NACTDT,NAS,NAT,NAW,NB,NC,ND,OK,RCNT,TCNT,TDT,TERRCNT,TN,XTN
 K DAT,I,TN
 K X,Y
 QUIT
INIT ;; 
 S ERRCNT=0,OK=0,RCNT=0,DCNT=0,BCNT=0,TCNT=0,TERRCNT=0
 QUIT
