ENLOG2 ;(WASH ISC)/DH ;Build temp equip file from LOG1 ;12-31-91
 ;;;;
 ;CLASS 3 SOFTWARE - Not officially supported by the ISC's
 W !!,"Routine to parse out the individual Equipment Records from a raw",!,"LOG1 tape.",!,"Input from ^ENZ(""LOG1"". Output to ^ENZ(6914.5 via ^ENZ(""NX""."
 R !!,"Station number (3 digits): ",STA:60 I STA'?3N G EXIT
 S NXI=1,(LN,WD)="",RECNUM=1,RECNUM(0)=0,X=^ENZ("LOG1",1),RECLEN=+$E(X,1,4)
 S (I,XI)=1
 W ! D ^%T
CONT S LN=LN_$E(X,XI),XI=XI+1,NXI=NXI+1
 I NXI>(RECLEN-5) G NEWNX
 I $L(LN)>49 S ^ENZ("NX",RECNUM,RECNUM(0))=LN,RECNUM(0)=RECNUM(0)+1,LN="" W:'(RECNUM(0)#10) "."
 I XI>100 S I=I+1,X=^ENZ("LOG1",I),XI=1
 G CONT
 ;
NEWNX I '$D(^ENZ("LOG1",I+3)) G LASTNX
NEWNX0 I $L(LN)>49 S ^ENZ("NX",RECNUM,RECNUM(0))=LN,RECNUM(0)=RECNUM(0)+1,LN=""
 I XI>100 S I=I+1,X=^ENZ("LOG1",I),XI=1
 S WD=$E(X,XI) I WD?1N G NEWNX1
 S LN=LN_WD,XI=XI+1,NXI=NXI+1
 G NEWNX0
NEWNX1 I XI<91 S WD=$E(X,XI,(XI+10))
 E  G NEWNX2
 I WD'?11N S LN=LN_$E(X,XI),XI=XI+1,NXI=NXI+1 G NEWNX0
 I $E(WD,9,11)'=STA S LN=LN_$E(X,XI),XI=XI+1,NXI=NXI+1 G NEWNX0
 S ^ENZ("NX",RECNUM,RECNUM(0))=LN,RECNUM=RECNUM+1,RECNUM(0)=0,LN="",NXI=1 W "."
 S RECLEN=+$E(WD,1,4)
 G CONT
NEWNX2 S WD=$E(X,XI,100),X1=^ENZ("LOG1",I+1)
 F J=1:1 S WD=WD_$E(X1,J) Q:$L(WD)>10
 I WD'?11N S LN=LN_$E(X,XI),XI=XI+1,NXI=NXI+1 G NEWNX0
 I $E(WD,9,11)'=STA S LN=LN_$E(X,XI),XI=XI+1,NXI=NXI+1 G NEWNX0
 S ^ENZ("NX",RECNUM,RECNUM(0))=LN,RECNUM=RECNUM+1,RECNUM(0)=0,LN="",NXI=1
 S RECLEN=+$E(WD,1,4)
 G CONT
 ;
LASTNX F J=0:1 S WD=$E(X,XI+J) Q:WD=""  S LN=LN_WD
 I $L(LN)>50 S ^ENZ("NX",RECNUM,RECNUM(0))=$E(LN,1,50),RECNUM(0)=RECNUM(0)+1,LN=$E(LN,51,100)
 S ^ENZ("NX",RECNUM,RECNUM(0))=LN
 S ^ENZ("NX",0)="BLOCKED LOG1 FILE^"_RECNUM
 W !,"Will now build File 6914.5 using '^ENZ(6914.5,' as root."
 K ^ENZ("LOG1")
 W ! D ^%T
 W ! D ^ENLOG3
 W ! D ^ENLOG6
 W ! D ^%T
EXIT W !,"DONE"
 K ^ENZ("NX")
 K STA,NXI,LN,WD,RECNUM,RECLEN,I,X,XI,J
 Q
 ;ENLOG2
