NURCCG ;HISC/RM-DRIVER FOR DATA TRANSFER FOR TG ;12/12/91
 ;;3.0;Nursing Clinical;;Jan 24, 1996
 ;;
 W !!,"THIS VERSION OF NURCCG (TEXT GENERATOR DATA TRANSFER UTILITY)",!?3,"WAS CREATED BY VERSION 3 OF THE TEXT GENERATOR",!?3,"AT HINES IRMFO ON DEC 12, 1991"
 S GMRGTXFR="0^0"
AGGY W !!,"THIS VERSION CONTAINS AGGREGATE TERM FILE ENTRIES",!?3,"SHALL I OVERWRITE MY DATA WITH YOURS" S %=1 D YN^DICN G:%<0 Q
 I '% W !?5,"Answer Yes if you wish to overwrite my data with yours, else answer No." G AGGY
 S $P(GMRGTXFR,"^")=2-%
 G:$P(GMRGTXFR,"^")+$P(GMRGTXFR,"^",2)=0 Q D ^NURCXCPX D WAIT^DICD F X="^GMRD(124.2,","^GMRD(124.25,","^GMRD(124.4," K ^UTILITY(X,$J)
 S NO="I "_$P("X[""^GMRD(124.4,""!(X[""^GMRD(124.2,"")!(X[""^GMRD(124.25,"")","!",2,3)
 S GMRGRNUM="00" F  Q:GMRGRNUM="HF"  D @("^NURCCG"_GMRGRNUM) W "." S GMRGRNUM=$S($E(GMRGRNUM,2)="Z":$S($E(GMRGRNUM)=9:"A",1:$C($A($E(GMRGRNUM))+1))_"0",1:$E(GMRGRNUM)_$S($E(GMRGRNUM,2)=9:"A",1:$C($A($E(GMRGRNUM,2))+1)))
 F GMRGREF="^GMRD(124.25,","^GMRD(124.2," S GMRGZNOD=$G(@(GMRGREF_"0)")) F GMRGD0=0:0 S GMRGD0=$O(^UTILITY(GMRGREF,$J,GMRGD0)) S:GMRGD0'>0 @(GMRGREF_"0)")=GMRGZNOD Q:GMRGD0'>0  W:'$R(12) "." D RESTORE^NURCCG1
 S GMRGXVER=2.8 F GMRGREF="^GMRD(124.25,","^GMRD(124.2," F GMRGD0=0:0 S GMRGD0=$O(^UTILITY(GMRGREF,$J,GMRGD0)) Q:GMRGD0'>0  W:'$R(12) "." D IX^NURCCG1
 F GMRGREF="^GMRD(124.2," F GMRGD0=0:0 S GMRGD0=$O(^UTILITY(GMRGREF,$J,GMRGD0)) Q:GMRGD0'>0  W:'$R(12) "." D RPTCHLD^NURCCG1
Q K %,DA,DIK,GMRGCHIL,GMRGCLAS,GMRGCNOD,GMRGD0,GMRGD1,GMRGD2,GMRGDATA,GMRGID,GMRGNOD,GMRGQ,GMRGQQ,GMRGREF,GMRGRNUM,GMRGTXFR,GMRGX,GMRGXVER,GMRGY,GMRGZ,GMRGZNEW,GMRGZNOD,NO
 F X="^GMRD(124.25,","^GMRD(124.2,","^GMRD(124.4," K ^UTILITY(X,$J)
 K ^UTILITY($J),X
 Q
