PRCIPR1A ;WISC/CLH/LEM-PRE INIT TO DELETE OLD FILES AND FIELDS ;4/14/95  08:27
V ;;5.0;IFCAP;;4/21/95
 ;
 N DIK,PRCFSITE,DA,L,I,X,MENU,PRCTMP,PRCFILE,OPTION
 D DT^DICRW
 K X,DIK,DA
 W !!,"The following menu options are obsolete and are being deleted:"
 S DIK="^DIC(19," F I=1:1 S OPTION=$P($T(OPTION+I),";;",2) Q:OPTION=""  S X=$O(^DIC(19,"B",OPTION,0)) I $G(X)>0,$D(^DIC(19,X,0)) S DA=X D ^DIK W !,OPTION,?40,"Deleted."
 K DIK,X,I
 ;This section deletes obsolete routines:
 ;I $G(^%ZOSF("DEL"))]"" W !!,"Checking for old Routines..." F I=1:1 S (X,RTN)=$P($T(RTN+I),";;",2) Q:RTN=""  I $G(^%ZOSF("TEST"))]"" X ^%ZOSF("TEST") I $T X ^%ZOSF("DEL") W !,"^"_RTN,?15,"Deleted."
 ;
 W !!,"Deleting obsolete input templates:"
 S DIK="^DIE("
 F I=1:1 S PRCTMP=$P($T(INPUT+I),";;",2,3) Q:$P(PRCTMP,";;")=""  D
 . S PRCFILE=$P(PRCTMP,";;",2),PRCTMP=$P(PRCTMP,";;"),X=0
 . F  S X=$O(^DIE("B",PRCTMP,X)) Q:X'?1.N  D
 . . Q:'$D(^DIE(X,0))
 . . I PRCFILE]"",PRCFILE'=$P(^DIE(X,0),U,4) Q
 . . S DA=X D ^DIK W !,PRCTMP,?40,"Deleted."
 K DIK,X,I,DA
 ;
 W !!,"Deleting obsolete print templates:"
 S DIK="^DIPT("
 F I=1:1 S PRCTMP=$P($T(PRINT+I),";;",2,3) Q:$P(PRCTMP,";;")=""  D
 . S PRCFILE=$P(PRCTMP,";;",2),PRCTMP=$P(PRCTMP,";;"),X=0
 . F  S X=$O(^DIPT("B",PRCTMP,X)) Q:X'?1.N  D
 . . Q:'$D(^DIPT(X,0))
 . . I PRCFILE]"",PRCFILE'=$P(^DIPT(X,0),U,4) Q
 . . S DA=X D ^DIK W !,PRCTMP,?40,"Deleted."
 K DIK,X,I,DA
 ;
 W !!,"Deleting obsolete sort templates:"
 S DIK="^DIBT("
 F I=1:1 S PRCTMP=$P($T(SORT+I),";;",2,3) Q:$P(PRCTMP,";;")=""  D
 . S PRCFILE=$P(PRCTMP,";;",2),PRCTMP=$P(PRCTMP,";;"),X=0
 . F  S X=$O(^DIBT("B",PRCTMP,X)) Q:X'?1.N  D
 . . Q:'$D(^DIBT(X,0))
 . . I PRCFILE]"",PRCFILE'=$P(^DIBT(X,0),U,4) Q
 . . S DA=X D ^DIK W !,PRCTMP,?40,"Deleted."
 K DIK,X,I,DA
 ;
 I $D(^PRCD(442.2)) D
 .W !!,"Deleting old data entries in 'TYPE OF AMENDMENT' file:"
 .K ^PRCD(442.2)
 ;
 W !!,"Pre-Init complete."
 Q
OPTION ;Menu options to be deleted:
 ;;PRCB CAP EDIT
 ;;PRCB CC LISTING/W SUBACCT
 ;;PRCB FCP SUB-ACCOUNT LIST
 ;;PRCB PRC, CC, SUBACCT MGMT.
 ;;PRCB SUBACCT ADD/EDIT
 ;;PRCB SUBACCT DEACTIVATE
 ;;PRCB SUBACCT LISTING
 ;;PRCB SUBACCT MGMT
 ;;PRCB SUBACCT REACTIVATE
 ;;PRCFD CAPPS ERROR PROCESSING
 ;;PRCFA 1358 PROCESSING
 ;;PRCFA SUB EDIT
 ;;PRCS 1358 MENU
 ;;PRCSPOPN1358
 ;;PRCFA CODE SHEETS
 ;;PRCFA KEYPUNCH OPTIONS
 ;;PRCFA KEYPUNCH A CODE SHEET
 ;;PRCFA EDIT KEYPUNCHED CS
 ;;PRCFA EDIT CODE SHEET
 ;;PRCFA MODIFY BATCH PRIORITY
 ;;PRCFA REPRINT BATCH
 ;;PRCFA GRAB A BATCH
 ;;PRCFA PURGE CODE SHEETS
 ;;PRCFA TRANSMIT OPTIONS
 ;;PRCFA TRANS ADD CS
 ;;PRCFA TRANS DELETE CS
 ;;PRCFA POST MSC CONFIRMATIONS
 ;;PRCFA TRANS/BATCH INQUIRY
 ;;PRCFA ERROR LIST REPRINT
 ;;PRCFA ERROR MESSAGE ADD/EDIT
 ;;PRCFA ERROR MESSAGE DISPLAY
 ;;PRCFA BATCH MANAGEMENT
 ;;PRCFA CREATE CODE SHEET
 ;;PRCFA DELETE CODE SHEET
 ;;PRCFA FCP BAL EDIT
 ;;PRCSENOD
 ;;PRCSENCAD
 ;;PRCB CAP EDIT
 ;;PRCB MANAGER
 ;;PRCEF END OF MONTH REPORT
 ;;PRCO EDI RE-TRAN
 ;;PRCHPM CS RETRANSMIT BATCH
 ;;
RTN ;Routines to be deleted:
 ;;
INPUT ;Input templates to be deleted:
 ;;PRCFA POST LIQUIDATION
 ;;PRCFD ENTER INVOICE
 ;;PRCHI BAL
 ;;PRCHI ISS
 ;;PRCHI OPX
 ;;PRCHI ORM
 ;;PRCHI PHA
 ;;PRCHI PO1
 ;;PRCHI RC1
 ;;PRCHI REP
 ;;PRCHI RET
 ;;PRCHL401
 ;;PRCHL431
 ;;PRCHL434
 ;;PRCF CI ACCOUNTING;;421.5
 ;;PRCF CI VOUCHER AUDIT-OLD;;421.5
 ;;PRCHAMITAV;;443.6
 ;;PRCHAMITZ;;443.6
 ;;PRCHDISCNT FMS;;442
 ;;PRCHDISCNT SAVE;;442
 ;;PRCHDISCNT TEST;;442
 ;;PRCHFEDVEN;;440.3
 ;;PRCHVENDOR;;440.3
 ;;PRCHVENDOR1;;440.3
 ;;PRCSCPOQR;;410
 ;;PRCSCPT;;410
 ;;PRCS1358EDDR;;424
 ;;PRCS1358ENDR;;424
 ;;PRCB CONTROL POINT EDIT;;420
 ;;PRCHI ADJ;;423
 ;;PRCHI NXD;;423
 ;;PRCHI NXX;;423
 ;;PRCHI IVD;;423
 ;;PRCFA POST MSC CONFIRMATIONS;;421.2
 ;;
PRINT ;Print templates to be deleted:
 ;;PRCFB CC LISTING
 ;;PRCFB CC LISTING W/SUBACCT
 ;;PRCFB SUBACCT LISTING
 ;;PRCFDSP
 ;;PRCFA BATCH TRANSMIT;;423
 ;;PRCFA BUDGET CODE SHEET;;423
 ;;PRCFA BUDGET HEADER;;423
 ;;
SORT ;Sort templates to be deleted:
 ;;PRCSCOM;;410
 ;;PRCFA BUDGET CODE SHEET;;423
 ;;
