PRCPSPA1 ;BOISE/TKW,WISC/AKS-assemble set packs (cont) ;6 Feb 92
 ;;4.0;IFCAP;;9/23/93
 ;
PROC ; INCREMENT THE QTY.ON HAND FOR THE SET/PACK ASSEMBLED, AND RECALCULATE WEIGHTED AVG.COST PER SET/PACK, UPDATE LAST COST, AVG.COST.
 S PRCPCOST=0,CASE=0 D CST S PRCPQTY=NSETS
 I $G(ORDERNO) K PRCPSPA1 S PRCPSPA1("QTY")=PRCPQTY,(PRCPSPA1("SELVAL"),PRCPSPA1("INVVAL"))=PRCPCOST D ADDTRAN^PRCPUTR(PRCP("I"),ITEMDA,"S",ORDERNO,.PRCPSPA1) K PRCPSPA1
 S PRCPQTY=NSETS,$P(^(0),U,7)=$P(^PRCP(445,PRCP("I"),1,ITEMDA,0),U,7)+PRCPQTY
 S PRCPAVG=((PRCPCOST*PRCPQTY)+(PRCPONH*PRCPOAVG))/(PRCPONH+PRCPQTY),PRCPAVG=+$J(PRCPAVG,0,3)
 S $P(^PRCP(445,PRCP("I"),1,ITEMDA,0),U,15)=PRCPCOST,$P(^(0),U,22)=PRCPAVG,$P(^(0),U,3)=PRCPDTI
PIC W !!,"Would you like to print the Set/Pack picking ticket " S %=1 D YN^DICN G:(%=-1)!(%=2) EXIT I %=0 W !,"Answer ""Yes"" or ""No""" G PIC
CAS W !!,"Is this a CASE CART ? " S %=2 D YN^DICN G:%=-1 EXIT I %=0 W !,"Answer ""Yes"" or ""No""" G CAS
 S:%=1 CASE=1
 D ^PRCPRPIC
 S CASE=0 Q
CST F I=0:0 S I=$O(^PRCP(445,PRCP("I"),1,ITEMDA,8,I)) Q:'I  S PRCPQTY=+$P(^(I,0),U,2) I $D(^PRCP(445,PRCP("I"),1,I,0)) S X=^(0),X=$S($P(X,U,15)>$P(X,U,22):$P(X,U,15),1:$P(X,U,22)),PRCPCOST=PRCPCOST+(PRCPQTY*X)
 Q
EXIT ;
 QUIT
