PRCPSPE1 ;BOISE/TKW,WISC/AKS-general item, inventory file edits ;6 Jan 93
 ;;4.0;IFCAP;;9/23/93
SS ; FORCE MANDATORY SOURCE INTO INVENTORY RECORD
 S $P(^PRCP(445,PRCP("I"),1,PRCPITEM,0),U,12)=PRCPPVNO,^PRCP(445,PRCP("I"),1,"AC",$E(PRCPPVNO,1,30),PRCPITEM)=""
ADDS ; ADD NEW SOURCE TO MULTIPLE FIELD WITHIN ITEM ON FILE 445
 S PRCPVPNT=$O(^PRCP(445,PRCP("I"),1,PRCPITEM,5,"B",PRCPPVNO,0)) I PRCPVPNT S $P(^PRCP(445,PRCP("I"),1,PRCPITEM,5,0),U,3)=PRCPVPNT Q
 S:'$D(^PRCP(445,PRCP("I"),1,PRCPITEM,5,0)) ^(0)="^445.07I^^" S PRCPVPNT=+$P(^(0),U,3),PRCPCNT=+$P(^(0),U,4),PRCPADD=""
 F I=0:0 S PRCPVPNT=PRCPVPNT+1 D ADDS2 Q:PRCPADD="Y"
 K PRCPADD,PRCPCNT Q
ADDS2 Q:$D(^PRCP(445,PRCP("I"),1,PRCPITEM,5,PRCPVPNT,0))  S ^(0)=PRCPPVNO
 S $P(^PRCP(445,PRCP("I"),1,PRCPITEM,5,0),U,3,4)=PRCPVPNT_U_(PRCPCNT+1),^PRCP(445,PRCP("I"),1,PRCPITEM,5,"B",PRCPPVNO,PRCPVPNT)="",PRCPADD="Y" Q
