PRCPRLOC ;WISC/RFJ-main storage location report ;22 July 91
 ;;4.0;IFCAP;;9/23/93
 D ^PRCPUSEL Q:'$G(PRCP("I"))
 N %,PRCPINV,X W !?2,"START WITH MAIN STORAGE LOCATION: FIRST// @    <<-- ENTER '@' TO PRINT ITEMS",!?49,"WITHOUT A MAIN STORAGE LOC."
 S PRCPINV=$$INVNAME^PRCPUX1(PRCP("I")),DIC="^PRCP(445,",L=0,FLDS="[PRCP REPORT:NSN]",BY=".01,1,5,1,@.01:5;""NSN""",FR=PRCPINV_",?,?",TO=PRCPINV_",?,?",DIOEND="D END^PRCPUREP" D EN1^DIP Q
