PRXKONIT ; ; 12-DEC-1995
 ;;5.0;IFCAP;**38**;4/21/95
 ;
 K DIF,DIK,DDF,DDT,DTO,D0,DLAYGO,DIC,DIR,DA,ORVROM,DFR,DTN,DIX,DZ
 S DIFQ=0,ORVROM=22 W !!,"This version of 'PRXKONIT' was created on 12-DEC-1995"
 W !?9,"(at WILMINGTON, by OE/RR V.2.5)",!
 G Q:DIFQ D ^PRXKONI1 G Q:'$D(DIFQ) S DIK(0)="B"
 D ^PRXKONI2,^PRXKONI3
 L  W !,*7,"OK, Protocol Installation is Complete.",!
 K %ZW,%,%H,D0,DA,DIF,DIFQ,DIG,DIH,DIK,DIU,DIV,DSEC,I,J,KEY,DIY,N,NM,NO,ORVROM,R,X,X0
 Q
 ;
Q W *7,!!,"NO UPDATING HAS OCCURRED!" Q
 ;
IXF ;;PRXK
