DGRPTX12 ; ;06/26/22
 S X=DE(30),DIC=DIE
 ;
 S X=DE(30),DIC=DIE
 ;
 S X=DE(30),DIC=DIE
 ;
 S X=DE(30),DIC=DIE
 D AUTOUPD^DGENA2(DA)
 S X=DE(30),DIC=DIE
 X "S DFN=DA D EN^DGMTR K DGREQF"
 S X=DE(30),DIC=DIE
 D EVENT^IVMPLOG(DA)
