DGSADAL ;ALB/MTC - SHARING AGREEMENTS UTILITY FUNCTIONS ;11/21/2012
 ;;5.3;Registration;**114,194,216,260003*****;Aug 13, 1993;Build 8
LSTSBCTG(RETURN,SEARCH,START,NUMBER) ;List sharing agreement sub-categories (file 35.2)
 N FILE,FIELDS,I,LST,ERR,CNT
 S FILE="35.2",FIELDS="@;.01"
 S:$D(START)=0 START="" S:$D(SEARCH)=0 SEARCH=""
 K RETURN
 D LIST^DIC(FILE,,FIELDS,"P",$G(NUMBER),.START,SEARCH,"B",,"","LST","ERR")
 S I=0,CNT=1
 F  S I=$O(LST("DILIST",I)) Q:I=""  D
 . S RETURN(CNT)=LST("DILIST",I,0)
 . S CNT=CNT+1
 S RETURN(0)=CNT-1
 Q
 ;
