DGYFONI2 ;
 ;;5.2;REGISTRATION;**13**;JUL 29,1992
 ;
 ;
 K ^UTILITY("ORVROM",$J),DIC S DIDUZ=0 S:$D(DUZ)#2 DIDUZ=DUZ S DUZ=.5
 Q
DT W ! S:$D(DUZ)#2-1 DUZ=0 S:$D(DUZ(0))#2-1 DUZ(0)="" S X=DUZ(0)="@" D 1
 I '$D(DTIME) S DTIME=999
 K %DT S:$D(IO(0))[0 IO(0)=$I D NOW^%DTC S DT=X
 K DIK,DIC,%I,DICS Q
1 I 'X,$D(^%ZOSF("NBRK")) X ^%ZOSF("NBRK")
 I X,$D(^%ZOSF("BRK")) X ^%ZOSF("BRK")
 Q
 ;
