PXICLN9A ;ISC/JVS - Clean up Auttimm global ;10/22/96
 ;;1.0;PCE PATIENT CARE ENCOUNTER;**9**;Aug 12, 1996
 ;
 ; This routine can be run to clean up the AUTTIMM and
 ;AUTTSK that were sent out with version 1.0 of PCE
 Q
EN1 ;--ENTRY POINT
NEW ;--NEW VARIABLES
 N PXIDO,DIK,DA,CNT
SET ;--SET PARAMETERS
 S PXIDO=0,CNT=0
EVAL ;--EVALUATE NEED TO DO CLEAN UP
 I $P(^AUTTIMM(0),"^",3)>37 D
 .I $D(^AUTTIMM(6,0)),$P(^AUTTIMM(6,0),"^")["SABIN TRIVALENT" S PXIDO=1
 .I $D(^AUTTIMM(7,0)),$P(^AUTTIMM(7,0),"^")["SALK" S PXIDO=1
 .I $D(^AUTTIMM(8,0)),$P(^AUTTIMM(8,0),"^")["A/NJ MONOVALENT" S PXIDO=1
 .I $D(^AUTTIMM(9,0)),$P(^AUTTIMM(9,0),"^")["A/VICT-A/NJ BIVA" S PXIDO=1
 I '$G(PXIDO) G EXIT
 ;
CHANGE ;--CHANGE ENTRIES IN FILE
 I $P(^AUTTIMM(6,0),"^",1)="SABIN TRIVALENT (OPV)" D
 .S DIK="^AUTTIMM(",DA=6 D ^DIK
 .S ^AUTTIMM(6,0)="ORAL POLIOVIRUS^SABIN/OPV"
 .S DIK="^AUTTIMM(",DA=6 D EN1^DIK
 ;
 I $P(^AUTTIMM(7,0),"^",1)="SALK" D
 .S DIK="^AUTTIMM(",DA=7 D ^DIK
 .S ^AUTTIMM(7,0)="POLIOMYELITIS^SALK"
 .S DIK="^AUTTIMM(",DA=7 D EN1^DIK
 ;
 I $P(^AUTTIMM(8,0),"^",1)="A/NJ MONOVALENT FLU" D
 .S DIK="^AUTTIMM(",DA=8 D ^DIK
 .S ^AUTTIMM(8,0)="SWINE FLU MONO^SWINE FLU"
 .S DIK="^AUTTIMM(",DA=8 D EN1^DIK
 ;
 I $P(^AUTTIMM(9,0),"^",1)="A/VICT-A/NJ BIVAL FLU" D
 .S DIK="^AUTTIMM(",DA=9 D ^DIK
 .S ^AUTTIMM(9,0)="SWINE FLU BIVAL^SWINE BIVA"
 .S DIK="^AUTTIMM(",DA=9 D EN1^DIK
 ;
 I $P(^AUTTIMM(10,0),"^",1)="HEPATITIS B VACCINE" D
 .S DIK="^AUTTIMM(",DA=10 D ^DIK
 .S ^AUTTIMM(10,0)="HEPATITIS B^HEP B"
 .S DIK="^AUTTIMM(",DA=10 D EN1^DIK
 ;
 I $P(^AUTTIMM(19,0),"^",1)="PNEUMO-VAC" D
 .S DIK="^AUTTIMM(",DA=19 D ^DIK
 .S ^AUTTIMM(19,0)="PNEUMOCOCCAL^PNEUMO-VAC"
 .S DIK="^AUTTIMM(",DA=19 D EN1^DIK
 ;
 I $P(^AUTTIMM(24,0),"^",1)="HIB PROJECT VACCINE" D
 .S DIK="^AUTTIMM(",DA=24 D ^DIK
 .S ^AUTTIMM(24,0)="INFLUENZA B^HIB"
 .S DIK="^AUTTIMM(",DA=24 D EN1^DIK
 ;
 ; TAKE OUT REST OF ENTRIES
 S DIK="^AUTTIMM("
 F DA=25:1:44 D ^DIK
 ;
 ;--SET IN THE REST OF THE ENTRIES
 S ^AUTTIMM(25,0)="HEPATITIS A^HEP A"
 S ^AUTTIMM(26,0)="MENINGOCOCCAL^MENING."
 S ^AUTTIMM(27,0)="ENCEPHALITIS^ENCEPH."
 S ^AUTTIMM(28,0)="CHICKENPOX^VARCELLA"
 S ^AUTTIMM(29,0)="DIP-TET-a/PERT^DTaP"
 S ^AUTTIMM(30,0)="RUBELLA, MUMPS^RUB-MUMPS"
 S ^AUTTIMM(31,0)="DIPHTHERIA^DIPHTHERIA"
 S ^AUTTIMM(32,0)="DTB/HIB^DTB/HIB"
 S ^AUTTIMM(33,0)="DTP, POLIO^DTP POLIO"
 S ^AUTTIMM(34,0)="MEA-MUMPS-RUB-VARCELLA^MMR&V"
 S ^AUTTIMM(35,0)="PLAGUE^PLAGUE"
 S ^AUTTIMM(36,0)="GAMMA GLOBULIN^ISG"
 S ^AUTTIMM(37,0)="UNLISTED^UNLISTED"
 ;--REINDEX ENTIRE FILE
 S DIK="^AUTTIMM(" D IXALL^DIK
 ;
FIND ;--FIND ENTRIES TO RE POINT
 N PXIIMM,PXIIEN,PXINEW
 F PXIIMM=25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44 D
 .S PXIIEN="" F  S PXIIEN=$O(^AUPNVIMM("B",PXIIMM,PXIIEN)) Q:PXIIEN=""  D
 ..I $G(JVS) W !,"IEN= "_PXIIEN,"  IMMUNIZATION= "_PXIIMM
 ..S CNT=CNT+1
 ..D SUB,POINT
 G EXIT
 Q
SUB ;--SUBROUTINE TO SET NEW VALUES
 I PXIIMM=25 S PXINEW=6 Q
 I PXIIMM=26 S PXINEW=7 Q
 I PXIIMM=27 S PXINEW=8 Q
 I PXIIMM=28 S PXINEW=9 Q
 I PXIIMM=29 S PXINEW=10 Q
 I PXIIMM=30 S PXINEW=19 Q
 I PXIIMM=31 S PXINEW=24 Q
 I PXIIMM=32 S PXINEW=25 Q
 I PXIIMM=33 S PXINEW=26 Q
 I PXIIMM=34 S PXINEW=27 Q
 I PXIIMM=35 S PXINEW=28 Q
 I PXIIMM=36 S PXINEW=29 Q
 I PXIIMM=37 S PXINEW=30 Q
 I PXIIMM=38 S PXINEW=31 Q
 I PXIIMM=39 S PXINEW=32 Q
 I PXIIMM=40 S PXINEW=33 Q
 I PXIIMM=41 S PXINEW=34 Q
 I PXIIMM=42 S PXINEW=35 Q
 I PXIIMM=43 S PXINEW=36 Q
 I PXIIMM=44 S PXINEW=37 Q
 Q
POINT ;--REPOINT ENTRIES
 S DA=PXIIEN,DIE="^AUPNVIMM(",DR=".01////^S X=PXINEW" D ^DIE
 K D,D0,DO,DI,DIC,DIE,DQ,DR,X
 S PXIIMM=1,PXBCNT=CNT
 Q
EXIT ;--EXIT
 K CNT
 Q
