PXPTNPOV ; SLC/DLT - Provider Narrative True Input Transform for Export ;1/22/94  14:48
 ;;1.0;PCE Patient/IHS Subset;;Nov 01, 1994
AUTNPOV ; IHS/LB - PROVIDER NARRATIVE TRUE INPUT TRANSFORM   
 ;;92.1;IHS STANDARD DICTIONARIES;;NOV 13, 1991
 ;
START ;
 Q:'$D(APCDOVRR)
 I X="=",$D(APCDTNQP) S X=APCDTNQP
 Q:X?.E1C.E
 I $L(X)>30,$D(^AUTNPOV("B",X)) S X="`"_$O(^(X,0)) Q
 S AUTNPOVX=$E(X,1,30)
 F AUTNPOVY=0:0 S AUTNPOVY=$O(^AUTNPOV("B",AUTNPOVX,AUTNPOVY)) Q:'AUTNPOVY  Q:$P(^AUTNPOV(AUTNPOVY,0),U,1)=X
 S X=$S(AUTNPOVY:"`"_AUTNPOVY,$E(X)="`":X,$E(X)="""":X,1:""""_X_"""")
 K AUTNPOVX,AUTNPOVY
 Q
