ZU ;GFT/SF ; 13DEC84 17:11 ;TIE ALL TERMINALS EXCEPT CONSOLE TO THIS ROUTINE!!
 ;4.23
 ;FOR DSM/VX......ZUDSMVAX
 S DEV=$N(^%ZIS(1,"C",$I,0))
 W !!,"DEVICE   ",$S(+DEV>1:DEV,1:$I),"     $I  ",$I,!
 S $ZT="ERR^ZUDSMVAX" K DEV G ^XUS
 ;
ERR ;
 U $I W !!,$ZE D C^XUS S:$ZE'["<INTERRUPT>" ^ERTRAP("ER",$H)=$ZE H
