ABSVDPRT ;EAP ALTOONA VOLUNTARY DONATIONS PROGRAM  ; 26 Sep 2001  2:04 PM
V ;;4.0;VOLUNTARY TIMEKEEPING;**25,26**;JULY 6, 1994
 ;VALUE PRINT ROUTINES-ASK FOR SITE INFO FIRST
ORG ;ORGANIZATION VALUE PRINT
 D ^ABSVSITE Q:'%
 N DIC,Y,BY,FR,TO,L,FLDS
 S DIC=503340
 S BY="[ABSV DON ORG VALUE SORT]"
 S FLDS="[ABSV DON ORG VALUE PRINT]"
 S L=0,(FR,TO)=ABSV("SITENAME")_",?,?"
 D EN1^DIP
 K DIC,BY,FLDS,L,FR,TO
 QUIT
DATEREC ;DATE RECEIVED VALUE PRINT
 D ^ABSVSITE Q:'%
 N DIC,Y,BY,FR,TO,L,FLDS
 S DIC=503340
 S BY="[ABSV DON RECEIVED SORT]"
 S FLDS="[ABSV DON RECEIVED PRINT]"
 S L=0,(FR,TO)=ABSV("SITENAME")_",?"
 D EN1^DIP
 K DIC,BY,FLDS,L,FR,TO
 QUIT
TYPE ;TYPE OF DONATION VALUE PRINT
 D ^ABSVSITE Q:'%
 N DIC,Y,BY,FR,TO,L,FLDS
 S DIC=503340
 S BY="[ABSV DON TYPE VALUE SORT]"
 S FLDS="[ABSV DON TYPE VALUE PRINT]"
 S L=0,(FR,TO)=ABSV("SITENAME")_",?,?"
 D EN1^DIP
 K DIC,BY,FLDS,L,FR,TO
 QUIT
FISCAL ;MONTHLY REPORT TO FISCAL VALUE PRINT
 D ^ABSVSITE Q:'%
 N DIC,Y,BY,FR,TO,L,FLDS
 S DIC=503340
 S BY="[ABSV DON FISCAL SORT]"
 S FLDS="[ABSV DON FISCAL PRINT]"
 S L=0,(FR,TO)=ABSV("SITENAME")_",?,?"
 D EN1^DIP
 K DIC,BY,FLDS,L,FR,TO
 QUIT
ACK ;DATE ACKNOWLEDGED VALUE PRINT
 D ^ABSVSITE Q:'%
 N DIC,Y,BY,FR,TO,L,FLDS
 S DIC=503340
 S BY="[ABSV DON ACK VALUE SORT]"
 S FLDS="[ABSV DON ACK VALUE PRINT]"
 S L=0,(FR,TO)=ABSV("SITENAME")_",?"
 D EN1^DIP
 K DIC,BY,FLDS,L,FR,TO
 QUIT
POST ;PRINT POST/UNIT/CHAPTER
 D ^ABSVSITE Q:'%
 N ANS,DIC,Y,ORG,BY,FR,TO,L,FLDS
 S DIC("A")="Select VOLUNTEER ORGANIZATION CODE: "
 S DIC=503334,DIC(0)="AEMNZ" D ^DIC Q:+Y<0
 S ORG=$P(Y,"^",2),DIC=503340,(BY,FLDS)="[ABSV DON POST]"
 W !,"Please Type in the Post // " R ANS:300 I ANS="" QUIT
 S L=0,(FR,TO)=ABSV("SITENAME")_","_ORG_","_ANS_",?,?"
 D EN1^DIP
 QUIT
END ;;;;;;;;;;;;;;;;;;;
 QUIT
