APGIDO ;PHX/GEH ;PATIENT IDENTIFIERS IN FILE 2
 ;;VERSION
EN() N IEN S IEN=""
 S IEN=$ZP(^SCPT(404.42,"B",Y,999999)) I IEN,$P(^SCPT(404.42,IEN,0),U,3) S IEN=$P(^SCTM(404.51,$P(^SCPT(404.42,IEN,0),U,3),0),U)
 N CODE S CODE=$P($G(^DPT(Y,"PHOENIX")),U) I CODE]"" S IEN=IEN_"  CODE: "_CODE W $C(7)
 N CODE S CODE=$P($G(^DPT(Y,"PHOENIX")),U,2) I CODE=1 S IEN=IEN_"  Warning! This Patient is a High Risk for Amputation."
 I $P($G(^DPT(Y,.15)),U,2) S IEN=IEN_" ***INELIGIBLE PATIENT***"
 Q IEN
 ;
EN1() S IEN=$ZP(^SCPT(404.42,"B",DFN,999999)) I IEN,$P(^SCPT(404.42,IEN,0),U,3) S IEN=$P(^SCTM(404.51,$P(^SCPT(404.42,IEN,0),U,3),0),U)
 Q IEN
 Q
FUTAP(DFN,DISPLAY,TARGET,LINE) ;PHX/GEH ;FUTURE APPOINTMENTS FOR TIU OBJECT
 S II=0
 D SDA^VADPT
 F  S II=$O(^UTILITY("VASD",$J,II)) Q:'II  D
 .S RESULTS=^UTILITY("VASD",$J,II,"E")
 .S LINE=LINE+1
 .S @TARGET@(LINE,0)=$P(RESULTS,U,1)_"     "_$P(RESULTS,U,2)
 I '$D(^TMP("APGIDO",$J)) D NODATA("No Scheduled Appointments at this time.")
 Q "~@"_$NA(@TARGET)
MEANS(DFN) ;MEANS TEST
 N VAEL
 D ELIG^VADPT
 Q $P(VAEL(9),U,2)
 Q
ELIG(DFN) ;ELGIBILITY
 N VAEL
 D ELIG^VADPT
 Q $P(VAEL(6),U,2)
 Q
NODATA(MSG) ;
 N II,RESULTS
 S LINE=LINE+1,@TARGET@(LINE,0)=MSG
 S LINE=LINE+1,@TARGET@(LINE,0)=""
 S @TARGET@(0)="^^"_LINE_U_LINE_U_DT_"^^"
 Q
NOK(DFN) ;NEXT OF KIN
 N VAOA
 D OAD^VADPT
 Q VAOA(9)_"   "_VAOA(10)
 Q
PRIV(DFN) ;
 S PRIV="",PRIV=$P($G(^DPT(DFN,.104)),U)
 Q:'PRIV "No Primary Provider"
 Q $P(^VA(200,PRIV,0),U)
 Q
