ICD184P6 ;BPOIFO/ESW - ICD/DIAGNOSIS ; 10/22/02 3:30pm
 ;;18.0;DRG Grouper;**4**;Oct 13,2000
 ;
 Q
 ;
ADDDIAG ; Add New Diagnoses - cont(info taken from Fed Reg Table 6A)
 ;;
 ;This is a continuation of the process started by ICD184P2.
 ;The number of new codes requires two routines.
 ;
 N DIC,LINE,X,Y,ICDDIAG,DIAG,DESC,MDC,IDENT,CC,SEX,DRG,DRG1,DRG2,DRG3,DRG4,DRG5,DRG6,ECODE,CNT S CNT=0
 D BMES^XPDUTL(">>>Additional 82 new diagnoses added-Please verify")
 F LINE=1:1 S X=$T(DIAG+LINE) S ICDDIAG=$P(X,";;",2) Q:ICDDIAG="EXIT"  D
 .S DIC="^ICD9(",DIC(0)="L"
 .S DIAG=$P(ICDDIAG,U,2) I DIAG="" S DIAG=$P(ICDDIAG,U,3)
 .S DESC=$P(ICDDIAG,U,3),MDC=$P(ICDDIAG,U,5)
 .S CC="" I $P(ICDDIAG,U,4)="Y" S CC=1
 .S ECODE=$P(ICDDIAG,U,8)
 .S DRG=$P(ICDDIAG,U,6),SEX=$P(ICDDIAG,U,7)
 .S (DRG1,DRG2,DRG3,DRG4,DRG5,DRG6)=""
 .S DRG1=$P(DRG,"~",1) I $P(DRG,"~",2) S DRG2=$P(DRG,"~",2) I $P(DRG,"~",3) S DRG3=$P(DRG,"~",3) I $P(DRG,"~",4) S DRG4=$P(DRG,"~",4) I $P(DRG,"~",5) S DRG5=$P(DRG,"~",5) I $P(DRG,"~",6) S DRG6=$P(DRG,"~",6)
 .S IDENT=""
 .S DIC("DR")="2///"_IDENT_";3///"_DIAG_";5///"_MDC_";9.5///"_SEX_";10///"_DESC_";60///"_DRG1_";61///"_DRG2_";62///"_DRG3_";63///"_DRG4_";64///"_DRG5_";65///"_DRG6_";70///"_CC_";101///"_ECODE
 .S X=$P(ICDDIAG,U)
 .; check for duplicates in case install being re-run
 .I +$O(^ICD9("BA",X_" ",0)) Q
 .K DO D FILE^DICN
 .I Y=-1 Q
 .S CNT=CNT+1
 D BMES^XPDUTL(">>> "_CNT_" diagnoses were added")
 Q
DIAG ;New Diagnoses- (necessary to depart from FedReg for 256.31 & 9)
 ;;779.81^^NEONATAL BRADYCARDIA^N^15^390
 ;;779.82^^NEONATAL TACHYCARDIA^N^15^390
 ;;779.89^OTHER COND ORIG IN PERINATAL^OTHER SPECIFIED CONDITIONS ORIGINATING IN THE PERINATAL PERIOD^N^15^390
 ;;780.91^^FUSSY INFANT (BABY)^N^23^463~464
 ;;780.92^EXCESSIVE CRYING OF INFANT^EXCESSIVE CRYING OF INFANT (BABY)^N^23^463~464
 ;;780.99^^OTHER GENERAL SYMPTOMS^N^23^463~464
 ;;781.93^^OCULAR TORTICOLLIS^N^8^243
 ;;795.00^NONSPEC ABN PAPA SMEAR CERVIX^NONSPECIFIC ABNORMAL PAPANICOLAOU SMEAR OF CERVIX, UNSPECIFIED^N^13^358~359~369^F
 ;;795.01^ATYP SQ CELL UNDET FAV BENING^ATYPICAL SQUAMOUS CELL CHANGES OF UNDETERMINED SIGNIFICANCE FAVOR BENIGN(ASCUS FAVOR BENIGN)^N^13^358~359~369^F
 ;;795.02^ATYP SQ CELLUNDET FAV DYSPL^ATYPICAL SQUAMOUS CELL CHANGES OF UNDETERMINED SIGNIFICANCE FAVOR DYSPLASIA(ASCUS FAVOR DYSPLASIA)^N^13^358~359~369^F
 ;;795.09^OTH ABNOR PAPAN SMEAR CERVIX^OTHER NONSPECIFIC ABNORMAL PAPANICOLAOU SMEAR OF CERVIX^N^13^358~359~369^F
 ;;795.31^NONSPEC POSIT FIND ANTRAX^NONSPECIFIC POSITIVE FINDINGS FOR ANTHRAX^N^18^423
 ;;795.39^OTHER POSIT CULTUR FINDINGS^OTHER NONSPECIFIC POSITIVE CULTURE FINDINGS^N^18^423
 ;;813.45^^TORUS FRACTURE OF RADIUS^N^8^250~251~252
 ;;823.40^^TORUS FRACTURE, TIBIA ALONE^N^8^253~254~255
 ;;823.41^^TORUS FRACTURE, FIBUL ALONE^N^8^253~254~255
 ;;823.42^^TORUS FRACTURE, FIBULA W/TIBIA^N^8^253~254~255
 ;;995.90^SYSTEM INFLAM RESPONSE SYNDROM^SYSTEMIC INFLAMMATORY RESPONSE SYNDROME,UNSPECIFIED^Y^18^416~417
 ;;995.91^INFL SYNDR INFEC W/O ORG DISF^SYSTEMIC INFLAMMATORY RESPONSE SYNDROME DUE TO INFECTIOUS PROCESS WITHOUT ORGAN DYSFUNCTION^Y^18^416~417
 ;;995.92^INFL SYNDR INFEC W/ORG DISF^SYSTEMIC INFLAMMATORY RESPONSE SYNDROME DUE TO INFECTIOUS PROCESS WITH ORGAN DYSFUNCTION^Y^18^416~417
 ;;995.93^INFL NON-INFEC W/O ORG DISF^SYSTEMIC INFLAMMATORY RESPONSE SYNDROME DUE TO NON-INFECTIOUS PROCESS WITHOUT ORGAN DYSFUNCTION^Y^18^416~417
 ;;995.94^INFL NON-INFEC W/ORGAN DISF^SYSTEMIC INFLAMMATORY RESPONSE SYNDROME DUE TO NON-INFECTIOUS PROCESS WITH ORGAN DYSFUNCTION.^Y^18^416~417
 ;;998.31^DISRUP OF INTER OPER WOUND^DISRUPTION OF INTERNAL OPERATION WOUND^Y^21^452~453
 ;;998.32^DISRUP OF EXTER OPER WOUND^DISRUPTION OF EXTERNAL OPERATION WOUND^Y^21^452~453
 ;;V01.81^CONTACT/EXPOSURE TO ANTRAX^CONTACT WITH OR EXPOSURE TO COMMUNICABLE DISEASES, ANTHRAX.^N^15^391
 ;;V01.89^CONT/EXP TO OTHER COMM DISEASE^CONTACT WITH OR EXPOSURE TO COMMUNICABLE DISEASES, OTHER COMMUNICABLE DISEASES^N^15^391
 ;;V13.21^PERSON HIST OF PRE-TERM LABOR^PERSONAL HISTORY OF PRE-TERM LABOR^N^23^467^F
 ;;V13.29^PERS HIST OF OTH GENIT&OBSTET^PERSONAL HISTORY OF OTHER GENITAL SYSTEM AND OBSTETRIC DISORDERS^N^23^467^F
 ;;V23.41^^ TERM LABOR.^N^14^469^F
 ;;V23.49^PREGNANCY W/POOR OBSTET HIST^PREGNANCY WITH OTHER POOR OBSTETRIC HISTORY^N^14^469^F
 ;;V46.2^OTHER DEPEND ON SUPLEM OXYG^OTHER DEPENDENCE ON MACHINES, SUPPLEMENTAL OXYGEN^N^23^467
 ;;V54.10^AFTER TRM FRACT ARM FRACTUR^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF ARM,UNSPECIFIED^N^8^249
 ;;V54.11^AFTER TRM FRACT UPPER ARM^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF UPPER ARM^N^8^249
 ;;V54.12^AFTER TRM FRACT OF LOWER ARM^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF LOWER ARM^N^8^249
 ;;V54.13^AFTER TRM TRAUM FRACT OF HIP^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF HIP^N^8^249
 ;;V54.14^AFTER TRM FRACT OF LEG, UNSCEC^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF LEG,UNSPECIFIED^N^8^249
 ;;V54.15^AFTER TRM FRACT OF UPPER LEG^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF UPPER LEG^N^8^249
 ;;V54.16^AFTER TRM FRACT OF LOWER LEG^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF LOWER LEG^N^8^249
 ;;V54.17^AFTER TRM FRACT OF VERTEBRAE^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF VERTEBRAE^N^8^249
 ;;V54.19^AFTER TRM FRACT OF OTHER BONE^AFTERCARE FOR HEALING TRAUMATIC FRACTURE OF OTHER BONE^N^8^249
 ;;V54.20^AFTER PATH FRACT OF ARM UNSPEC^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF ARM,UNSPECIFIED.^N^8^249
 ;;V54.21^AFTER PATH FRACT OF UPPER ARM^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF UPPER ARM.^N^8^249
 ;;V54.22^AFTER PATH FRACT OF LOWER ARM^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF LOWER ARM^N^8^249
 ;;V54.23^AFTER PATHOL FRACT OF HIP^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF HIP^N^8^249
 ;;V54.24^AFTER PATH FRACT OF LEG, UNSP^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF LEG, UNSPECIFIED.^N^8^249
 ;;V54.25^AFTER PATH FRACT OF UPPER LEG^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF UPPER LEG^N^8^249
 ;;V54.26^AFTER PATH FRACT OF LOWER LEG^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF LOWER LEG^N^8^249
 ;;V54.27^AFTER PATH FRACT OFVERTEBRAE^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF VERTEBRAE^N^8^249
 ;;V54.29^AFTER PATH FRACT OF OTHER BONE^AFTERCARE FOR HEALING PATHOLOGIC FRACTURE OF OTHER BONE^N^8^249
 ;;V54.81^AFTER FOLLOW JOINT REPLACEMENT^AFTERCARE FOLLOWING JOINT REPLACEMENT^N^8^249
 ;;V54.89^^OTHER ORTHOPEDIC AFTERCARE^N^8^249
 ;;V58.42^AFTER FOLLOW SURG FOR NEOPLASM^AFTERCARE FOLLOWING SURGERY FOR NEOPLASM^N^23^465~466
 ;;V58.43^AFTER FOLLOW SURG INJUR&TRAUMA^AFTERCARE FOLLOWING SURGERY FOR INJURY AND TRAUMA^N^23^465~466
 ;;V58.71^AFT FOLL SURG OF SENSE ORGANS^AFTERCARE FOLLOWING SURGERY OF THE SENSE ORGANS, NEC^N^23^465~466
 ;;V58.72^AFTER FOLL SURG OF NERV SYSTEM^AFTERCARE FOLLOWING SURGERY OF THE NERVOUS SYSTEM, NEC^N^23^465~466
 ;;V58.73^AFT FOLL SURG OF CERCUL SYSTEM^AFTERCARE FOLLOWING SURGERY OF THE CIRCULATORY SYSTEM, NEC^N^23^465~466
 ;;V58.74^AFT FOLL SURG OF RESPIR SYSTEM^AFTERCARE FOLLOWING SURGERY OF THE RESPIRATORY SYSTEM, NEC^N^23^465~466
 ;;V58.75^AFT FOLL SURG ORAL&DIGESTIVE^AFTERCARE FOLLOWING SURGERY OF THE TEETH, ORAL CAVITY AND DIGESTIVE SYSTEM, NEC^N^23^465~466
 ;;V58.76^AFT FOLL SURG OF GENIT SYSTEM^AFTERCARE FOLLOWING SURGERY OF THE GENITOURINARY SYSTEM, NEC^N^23^465~466
 ;;V58.77^AFT FOLL SURG OF SKIN&SUBCUT^AFTERCARE FOLLOWING SURGERY OF THE SKIN AND SUBCUTANEOUS TISSUE, NEC^N^23^465~466
 ;;V58.78^CARE FOLLOW SURG OF MUSCULOS^AFTERCARE FOLLOWING SURGERY OF THE MUSCULOSKELETAL SYSTEM, NEC^N^23^465~466
 ;;V71.82^OBS/EVAL FOR SUSP ANTHRAX^OBSERVATION AND EVALUATION FOR SUSPECTED EXPOSURE TO ANTHRAX^N^23^467
 ;;V71.83^OBS/EVAL OTHER BIOLOG AGENT^OBSERVATION AND EVALUATION FOR SUSPECTED EXPOSURE TO OTHER BIOLOGICAL AGENT^N^23^467
 ;;V83.81^^CYSTIC FIBROSIS GENE CARRIER^N^23^467
 ;;V83.89^^OTHER GENETIC CARRIER STATUS^N^23^467
 ;;E885.0^FALL FROM NONMOTOR SCOOTER^FALL FROM (NONMOTORIZED) SCOOTER^^^^^1
 ;;E922.5^ACCID BY FREARM & GUN MISSLE^ACCIDENT CAUSED BY FIREARM AND AIR GUN MISSLE, PAINBALL GUN^^^^^1
 ;;E955.7^SUISIDE SELF-INFL FIREARM^SUISIDE AND SELF-INFLICTED INJURY BY FIREARMS, AIR GUNS AND EXPLOSIVES, PAINBALL GUN^^^^^1
 ;;E979.^^TERRORISM^^^^^1
 ;;E979.0^TERR EXPLOS OF MARINE WEAPON^TERRORISM INVOLVING EXPLOSION OF MARINE WEAPONS^^^^^1
 ;;E979.1^TERROR DESTRUCT OF AIRCRAFT^TERRORISM INVOLVING DESTRUCTION OF AIRCRAFT^^^^^1
 ;;E979.2^TERROR OTHER EXPOS&FRAGMENTS^TERRORISM INVOLVING OTHER EXPLOSIONS AND FRAGMENTS^^^^^1
 ;;E979.3^TERR FIRES/CONFLAG/HOT SUBST^TERRORISM INVOLVING FIRES, CONFLAGRATION AND HOT SUBSTANCE^^^^^1
 ;;E979.4^^TERRORISM INVOLVING FIREARMS^^^^^1
 ;;E979.5^TERRORISM NUCLEAR WEAPONS^TERRORISM INVOLVING NUCLEAR WEAPONS^^^^^1
 ;;E979.6^TERRORISM BIOLOG WEAPON^TERRORISM INVOLVING BIOLOGICAL WEAPONS^^^^^1
 ;;E979.7^TERRORISM CHEMICAL WEAPON^TERORISM INVOLVING CHEMICAL WEAPONS^^^^^1
 ;;E979.8^TERROR OTHE MEANS^TERRORISM INVOLVING OTHER MEANS^^^^^1
 ;;E979.9^^TERRORISM, SECONDARY EFFECTS^^^^^1
 ;;E985.7^INJURY BY FIREARM/AIR GUNS^INJURY BY FIREARMS, AIR GUNS, WHETHER ACCIDENTALLY OR PURPOSELY INFLICTED, PAINBALL GUN
 ;;E999.0^LATE EFFECT OF INJURY WAR^LATE EFFECT INJURY DUE TO WAR OPERATIONS^^^^^1
 ;;E999.1^LATE EFFECT OF INJURY TERROR^LATE EFFECT OF INJURY DUE TO TERRORISM^^^^^1
 ;;EXIT
 Q
 ;
