A1AXCRST ;SLL/ALB ISC; CONTINGENCY REMOVED TRIGGERED MSG FOR FACILITY; 12/30/87
 ;;VERSION 1.0
 ;
 D TKL^A1AXCRRD
 S A1AXQ=$N(^XMB(3.8,"B","EXT REV FAC",0))
 S A1AXRC="" F A1AXI=0:0 S A1AXRC=$O(^XMB(3.8,A1AXQ,1,"B",A1AXRC)) Q:A1AXRC=""!(A1AXRC'?.N)  S A1AXFC=0 F A1AXJ=0:0 S A1AXFC=$O(^DIC(3,A1AXRC,2,A1AXFC)) Q:A1AXFC=""!(A1AXFC'?.N)  D:A1AXFC=^DIZ(11830,D0,"F") SENT
 K ^UTILITY($J,"CR"),P,S,R,Y,XMDUZ,XMY,XMSUB,XMTXT,A1AXNM,A1AXRC,A1AXI,A1AXJ,A1AXQ,A1AXR1,I
 Q
SENT ;
 K XMY S XMY(A1AXRC)="" S XMDUZ=.5,XMSUB="*CONTINGENCY REMOVED AT "_A1AXF_""
 D ^XMD K XMY
 Q
