PRMQUTL ;Chicago ISC/DDA- UTILITY ROUTINE FOR 513.8 DD ;5/14/90  11:05
 ;;1.2;Utilization Review;;
SET ; SET FOR 'STATUS (EPISODE)' TRIGGER TO 'STATUS (PATIENT)'
 Q:X=1
KILL ; CONCLUSION OF 'SET' AND KILL FOR 'STATUS (EPISODE)' TRIGGER TO 'STATUS (PATIENT)'
 S X=$S($D(^PRMQ(513.8,"AST",1,DA(1))):1,1:2)
 Q
