A1BFEX2 ;ALBANY ISC ; ECF ; 15DEC92
 ;;V1.0
EN ;
 D SETUP,HDR,WHO
 I $D(^UTILITY($J,"EXC")) D LOOP
 ;I '$D(^UTILITY($J,"EXC")) D NOEXC
 D LASTD,EXIT Q
SETUP ;
 S U="^",A1BFML=1
 Q
HDR ;
 S ^UTILITY($J,"EXCMSG",A1BFML)="                 RESPONSE TIME MONITOR REPORT FOR",A1BFML=A1BFML+1
 S ^UTILITY($J,"EXCMSG",A1BFML)="    MESSAGES RECEIVED BETWEEN "_A1BFFDTP_" AND "_A1BFLDTP,A1BFML=A1BFML+1
 S ^UTILITY($J,"EXCMSG",A1BFML)=" ",A1BFML=A1BFML+1
 Q
WHO ;
 F A1BFI=0:0 S A1BFI=$O(^A1BF(11604,1,2,A1BFI)) Q:A1BFI=""!(A1BFI'?.N)  S:$D(^A1BF(11604,1,2,A1BFI,0)) XMY($P(^(0),U,1))=""
 Q
LOOP ;
 Q:'$D(^UTILITY($J,"EXC"))  S A1BFPR=$O(^UTILITY($J,"EXC",0))-.00001
 S A1BFR=0 F  S A1BFR=$O(^UTILITY($J,"EXC",A1BFR)) Q:A1BFR=""  D
 .I A1BFR'=A1BFPR D DATELIN
 .S A1BFQ=0 F  S A1BFQ=$O(^UTILITY($J,"EXC",A1BFR,A1BFQ)) Q:A1BFQ=""  S ^UTILITY($J,"EXCMSG",A1BFML)=^UTILITY($J,"EXC",A1BFR,A1BFQ),A1BFML=A1BFML+1
 Q
DATELIN ;
 S Y=A1BFR D DD^%DT S A1BFDTLP=Y
 S ^UTILITY($J,"EXCMSG",A1BFML)=" ",^UTILITY($J,"EXCMSG",A1BFML+2)=" "
 S ^UTILITY($J,"EXCMSG",A1BFML+1)=$E(A1BFSPAC,1,22)_"    REPORT FOR "_A1BFDTLP
 S ^UTILITY($J,"EXCMSG",A1BFML+2)=" "
 S ^UTILITY($J,"EXCMSG",A1BFML+3)="   SITE                   RESPONSE TIME          AVERAGE            MAX "
 S ^UTILITY($J,"EXCMSG",A1BFML+4)="   NAME                   (IN SECONDS)           # USERS          # USERS"
 S ^UTILITY($J,"EXCMSG",A1BFML+5)=" ========                ================       ==========       ========="
 S ^UTILITY($J,"EXCMSG",A1BFML+6)=" "
 S A1BFML=A1BFML+7
 Q
NOEXC ;
 S ^UTILITY($J,"EXCMSG",A1BFML)=" "
 S ^UTILITY($J,"EXCMSG",A1BFML+1)=" ===   ALL REPORTING SITES HAD RESPONSE TIMES UNDER ONE SECOND  ==="
 S ^UTILITY($J,"EXCMSG",A1BFML+2)=" "
 S A1BFML=A1BFML+3
 Q
SEND ;
 S XMSUB="RESPONSE TIME EXCEPTION REPORT "_A1BFFDTP_" TO "_A1BFLDTP
 S XMDUZ=.5,XMTEXT="^UTILITY($J,""EXCMSG""," D ^XMD K XMY,XMTEXT,XMSUB,XMDUZ
 Q
LASTD ;
 K DD,DO S DIE="^A1BF(11604,",DA=1,DR="2///^S X=A1BFLDT" D ^DIE
 K DIE,DD,DO
 Q
EXIT ;
 K A1BFAU,A1BFI,A1BFMU,DR
 Q
