A4ARIG3 ;HINES CIOFO/JJM-IG REPORTS ; 12/8/98 11:45
V ;;1.0;CLASS III REPORTS
        I $D(ACCRUED) D BSRPT3 Q
PRPTS   ; PRINT ALL REPORTS
        D:'$G(^XTMP("A4ARIG",$J,"BILL",0)) EN1^A4ARIG
        D NOW^%DTC,YX^%DTC S DATE=Y
        D OPEN
        W @IOF
        D BSRPTS
        D CLOSE
        D EOR
        QUIT
BSRPTS  ; PRINT BILL STATUS REPORTS
 F ACCRUED=0:1:1 D BSRPT3
        QUIT
BSRPT3 ;
 S SITE=$$SITE^RCMSITE()
 W @IOF
 W !!,?41,"BILL DATA REPORT - BY FUND"
 W !,?43,DATE,!,?40,SITE," JOB NUMBER: ",$J,!
 S (STOTAL,CTOTAL,FTOTAL,RTOTAL,GTOTAL,RTOTAL,RTOTAL1,RTOTAL2,RTOTAL3,RTOTAL4,RTOTAL5,RTOTAL6)=0 S STAT=""
 F  S STAT=$O(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT)) Q:STAT=""  D
    . W !!!,?43,$S(ACCRUED=0:"NON-ACCRUED/",ACCRUED=1:"ACCRUED/",1:" "),$P($G(^PRCA(430.3,STAT,0)),U,1)," FUND REPORT - 3",!
    . W !!!,"BILL CATEGORY/FUND ",?40,"COUNT",?52,"TOTAL ",?60,"PRINCIPAL ",?76,"INT ",?85,"ADMIN ",?92,"MRSHL ",?102,"CRT ",!
    . S CAT=""
    . S (RTOTAL,RTOTAL1,RTOTAL2,RTOTAL3,RTOTAL4,RTOTAL5,RTOTAL6)=0
    . F  S CAT=$O(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT)) Q:CAT=""  D
      .. S FUND=""
      .. F  S FUND=$O(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND)) Q:FUND=""  D
         ... W !,$P($G(^PRCA(430.2,CAT,0)),U,1),"/",FUND,?35,$J(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,6),10)
         ... W ?45,$J(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,0),12,2),$J(^(1),12,2),$J(^(2),10,2),$J(^(3),10,2),$J(^(4),8,2),$J(^(5),8,2)
         ... S RTOTAL=RTOTAL+^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,0)
         ... S RTOTAL1=RTOTAL1+^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,1)
         ... S RTOTAL2=RTOTAL2+^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,2)
         ... S RTOTAL3=RTOTAL3+^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,3)
         ... S RTOTAL4=RTOTAL4+^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,4)
         ... S RTOTAL5=RTOTAL5+^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,5)
         ... S RTOTAL6=RTOTAL6+^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,6)
         ... S FTOTAL=FTOTAL+RTOTAL
         ... S CTOTAL=CTOTAL+RTOTAL
         ... S STOTAL=STOTAL+RTOTAL
         ... S GTOTAL=GTOTAL+RTOTAL
      . W !,"TOTALS:",?35,$J(RTOTAL6,10),?45,$J(RTOTAL,12,2),$J(RTOTAL1,12,2),$J(RTOTAL2,10,2),$J(RTOTAL3,10,2),$J(RTOTAL4,8,2),$J(RTOTAL5,8,2)
      . S (RTOTAL,RTOTAL1,RTOTAL2,RTOTAL3,RTOTAL4,RTOTAL5)=0
 QUIT
OPEN ; SELECT OUTPUT DEVICE
 S %ZIS="M" D ^%ZIS U IO
 QUIT
CLOSE ; CLOSE OUTPUT DEVICE
 D ^%ZISC
 QUIT
EOR ; END OF ROUTINE
 K CAT,FUND,RSC,RTOTAL,STAT,TT,SITE
 K ACCRUED,AMT,AMT1,AMT2,AMT3,AMT4,AMT5,CAT,FUND,RSC,STAT
 K RTOTAL,RTOTAL1,RTOTAL2,RTOTAL3,RTOTAL4,RTOTAL5
 K TAMT,TAMT1,TAMT2,TAMT3,TAMT4,TAMT5
