A4ARIGS1 ;HINES CIOFO/JJM-IG REPORTS ; 10/14/98 09:45
V ;;1.0;CLASS III REPORTS OCTOBER 15,1998
 ; "ACCRUED",ACCRUED,RSC,FUND,STATUS,CATEGORY TOTALS
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,0)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,0)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,1)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,1)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,2)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,2)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,3)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,3)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,4)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,4)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,5)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,5)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,6)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,6)=0
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,0)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,0)+(AMT/100)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,1)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,1)+(AMT1)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,2)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,2)+(AMT2)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,3)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,3)+(AMT3)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,4)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,4)+(AMT4)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,5)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,5)+(AMT5)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,6)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"CATEGORY",CAT,"FUND",FUND,"STATUS",STAT,"RSC",RSC,6)+1
 QUIT
