A4ARIGS ;HINES CIOFO/JJM-IG REPORTS ; 1/7/98 18:25
V ;;1.0;CLASS III REPORTS OCTOBER 15,1998
EN1 ;
 K ^XTMP("A4ARIG",$J,"BILL")
 S ^XTMP("A4ARIG",$J,"BILL",0)=DT
 D BILL^A4ARIG
 Q
EN2 ;
 K ^XTMP("A4ARIG",$J,"TRANS")
 S ^XTMP("A4ARIG",$J,"TRANS",0)=DT
 D TRANS^A4ARIG
 Q
BTOTALS ;
 S STAT=+STAT
 S CAT=+CAT
 S:STAT="" STAT=" "
 S:FUND="" FUND=" "
 S:RSC="" RSC=" "
 S CS=STAT_"^"
 S:(ACCRUED=1)&("16^28^32^33^40^42^43^"[CS) ^XTMP("A4ARIG",$J,"NDB",STAT,"IEN",BILL)=""
 ; "ACCRUED",ACCRUED,STATUS TOTALS
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,0)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,0)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,1)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,1)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,2)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,2)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,3)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,3)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,4)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,4)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,5)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,5)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,6)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,6)=0
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,0)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,0)+(AMT/100)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,1)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,1)+(AMT1)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,2)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,2)+(AMT2)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,3)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,3)+(AMT3)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,4)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,4)+(AMT4)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,5)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,5)+(AMT5)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,6)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,6)+1
 ; "ACCRUED",ACCRUED,STATUS,CATEGORY TOTALS
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,0)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,0)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,1)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,1)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,2)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,2)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,3)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,3)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,4)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,4)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,5)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,5)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,6)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,6)=0
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,0)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,0)+(AMT/100)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,1)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,1)+(AMT1)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,2)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,2)+(AMT2)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,3)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,3)+(AMT3)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,4)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,4)+(AMT4)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,5)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,5)+(AMT5)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,6)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,6)+1
 ; "ACCRUED",ACCRUED,STATUS,CATEGORY,FUND TOTALS
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,0)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,0)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,1)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,1)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,2)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,2)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,3)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,3)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,4)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,4)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,5)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,5)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,6)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,6)=0
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,0)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,0)+(AMT/100)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,1)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,1)+(AMT1)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,2)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,2)+(AMT2)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,3)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,3)+(AMT3)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,4)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,4)+(AMT4)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,5)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,5)+(AMT5)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,6)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,6)+1
 ; "ACCRUED",ACCRUED,STATUS,CATEGORY,FUND,RSC TOTALS
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,0)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,0)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,1)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,1)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,2)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,2)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,3)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,3)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,4)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,4)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,5)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,5)=0
 S:'$G(^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,6)) ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,6)=0
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,0)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,0)+(AMT/100)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,1)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,1)+(AMT1)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,2)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,2)+(AMT2)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,3)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,3)+(AMT3)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,4)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,4)+(AMT4)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,5)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,5)+(AMT5)
 S ^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,6)=^XTMP("A4ARIG",$J,"ACCRUED",ACCRUED,"STATUS",STAT,"CATEGORY",CAT,"FUND",FUND,"RSC",RSC,6)+1
 D ^A4ARIGS1
 D ^A4ARIGS2
 D ^A4ARIGS3
 QUIT
