AAHGEMA ;402,DJB,10/17/92**Set Up "%" Routines for ARR,AGL,EDD
 ;;GEM III;;
 ;David Bolduc - Augusta,ME
TOP ;
 D GL G:FLAGQ=2 EX D RR G:FLAGQ=2 EX D DD
EX ;
 Q
GL ;GEM Global Lister
 S FLAGQ=0
 W !!?2,"Everything seems in order. Let's run the initialization."
 W !!?2,"S T E P   1"
 D YESNO^AAHGEM("Convert 'GEM Global Lister' routines to '%' routines: YES// ") Q:FLAGQ  W !
 S %S="AAHGL^AAHGLA^AAHGLA1^AAHGLE^AAHGLH^AAHGLH1^AAHGLH2^AAHGLH3^AAHGLP^AAHGLP1^AAHGLP2^AAHGLP3^AAHGLPS^AAHGLPV^AAHGLR^AAHGLR1^AAHGLS^AAHGLS1^AAHGLS2^AAHGLSA^AAHGLU^AAHGLZ"
 S %D="%AAHGL^%AAHGLA^%AAHGLA1^%AAHGLE^%AAHGLH^%AAHGLH1^%AAHGLH2^%AAHGLH3^%AAHGLP^%AAHGLP1^%AAHGLP2^%AAHGLP3^%AAHGLPS^%AAHGLPV^%AAHGLR^%AAHGLR1^%AAHGLS^%AAHGLS1^%AAHGLS2^%AAHGLSA^%AAHGLU^%AAHGLZ"
 D MOVE^AAHGEM
 W !!?2,"All GL routines successfully converted."
 Q
RR ;GEM Routine Reader
 S FLAGQ=0
 W !!?2,"S T E P   2"
 D YESNO^AAHGEM("Convert 'GEM Routine Reader' routines to '%' routines: YES// ") Q:FLAGQ  W !
 S %S="AAHRR^AAHRRC^AAHRRE^AAHRRE1^AAHRREA^AAHRREB^AAHRREP^AAHRREU^AAHRRH^AAHRRH1^AAHRRH2^AAHRRP^AAHRRRD^AAHRRS^AAHRRSS^AAHRRU^AAHRRZ^AAHRRZ1^AAHRRZ2"
 S %D="%AAHRR^%AAHRRC^%AAHRRE^%AAHRRE1^%AAHRREA^%AAHRREB^%AAHRREP^%AAHRREU^%AAHRRH^%AAHRRH1^%AAHRRH2^%AAHRRP^%AAHRRRD^%AAHRRS^%AAHRRSS^%AAHRRU^%AAHRRZ^%AAHRRZ1^%AAHRRZ2"
 D MOVE^AAHGEM
 W !!?2,"All RR routines successfully converted."
 Q
DD ;GEM Data Dictionary
 S FLAGQ=0
 W !!?2,"S T E P   3"
 D YESNO^AAHGEM("Convert 'GEM Electronic Data Dictionary'  routines to '%' routines: YES// ") Q:FLAGQ  W !
 S %S="AAHDD^AAHDD1^AAHDDC^AAHDDD^AAHDDD1^AAHDDG^AAHDDH1^AAHDDH2^AAHDDH3^AAHDDH4^AAHDDH5^AAHDDI^AAHDDI1^AAHDDI2^AAHDDI3^AAHDDI4^AAHDDL^AAHDDL1^AAHDDL2^AAHDDM^AAHDDN^AAHDDPR^AAHDDPT^AAHDDT^AAHDDU^AAHDDU1^AAHDDZ"
 S %D="%AAHDD^%AAHDD1^%AAHDDC^%AAHDDD^%AAHDDD1^%AAHDDG^%AAHDDH1^%AAHDDH2^%AAHDDH3^%AAHDDH4^%AAHDDH5^%AAHDDI^%AAHDDI1^%AAHDDI2^%AAHDDI3^%AAHDDI4^%AAHDDL^%AAHDDL1^%AAHDDL2^%AAHDDM^%AAHDDN^%AAHDDPR^%AAHDDPT^%AAHDDT^%AAHDDU^%AAHDDU1^%AAHDDZ"
 D MOVE^AAHGEM
 W !!?2,"All DD routines successfully converted."
 Q
