ADXTGTST ;523/KC GET A STATE FROM USER ;; 15-SEP-1992
 ;;1.1;;
 ;       OUTPUT VARIABLES:
 ;       ADXTQUIT=1 IF DIDN'T ANSWER QUESTION, OR WRONG STATE
 ;       ADXTGTST=STATE CODE IF SELECTED A STATE
ASK ;
 K DIR,ADXTGTST,Y
 S DIR(0)="S^CT:CONNECTICUT;MA:MASS;ME:MAINE;NH:NEW HAMPSHIRE;NY:NEW YORK (except ALBANY);AL:ALBANY,NY;PR:PUERTO RICO;RI:RHODE ISLAND;VT:VERMONT;O:OTHER"
 S DIR("A")="Enter the your site's location"
 D ^DIR
 I $D(DIRUT)!$D(DIROUT) S ADXTQUIT=1 Q
 S ADXTGTST=Y
 W !!,"You have selected ",Y(0),"."
 S DIR(0)="Y",DIR("A")="IS THIS OK" D ^DIR
 I $D(DIRUT)!$D(DIROUT) G ASK
 I '+Y G ASK
 I (ADXTGTST="O") D
 .W !!,"Your site is not supported by this conversion."
 .R !,"Press any key...",X:DTIME K ADXTGTST S ADXTQUIT=1
 Q
