ADXTADI3 ;523/KC continuation of ADXTADI2 ; 13-MAY-1993
 ;;1.1;;
 ;
 ; INPUT VARIABLES:
 ;  everything that is setup within routine ADXTADI2
 ; OUTPUT VARIABLES: NONE
 ;
 N ADXTZ,ADXTI
 ;
UNUSED ; store unused items at end of comment w.p. field
 ;
 F ADXTI="DRD2","DRD2D","DSR2","DSR2D","DSTT","DCNT","DCSS","DCSST","DFT","DNF","DLF","DFRC","DCAUS","DOP","DRFNM","DRFAD","DRTNM","DRTAD","DATOP","DAMOR","DAGD","DAGCR","DSRVM","DMRC","DLT","DCRG","XDDA","XDPS","XDTBP","XDASA","XDMISC" D
 .Q:'$L($$TRIM^ADXTUT(ADXT(ADXTI)))
 .S ADXTZ=$$WP^ADXTWP(165.5,113,ADXTDA,"MRS VALUE ("_ADXTI_"): "_ADXT(ADXTI))
 ;
CT I $G(ADXTGTST)="CT" D
 .F ADXTI="XDDGVN","XDISTP","XDCHXRY","XDALPH","XDCTSCN","XDBNSCN","XDENDSC","XDGIXRY","XDULSND","XDOTHS","XDESTRC","XDPRORC" D
 ..Q:'$L($$TRIM^ADXTUT(ADXT(ADXTI)))
 ..S ADXTZ=$$WP^ADXTWP(165.5,113,ADXTDA,"=> CONNECTICUT SPECIAL MRS VALUE ("_ADXTI_"): "_ADXT(ADXTI))
 ;
ME I $G(ADXTGTST)="ME" D
 .S ADXTI="XDTOR"
 .Q:'$L($$TRIM^ADXTUT(ADXT(ADXTI)))
 .S ADXTZ=$$WP^ADXTWP(165.5,113,ADXTDA,"=> MAINE SPECIAL MRS VALUE ("_ADXTI_"): "_ADXT(ADXTI))
 .;
EXIT ;
 K ADXTZ,ADXTI
 Q
