ADXTMM ;523/KC send a mail message ; 1-SEP-1990
 ;;1.1;;
 ;
 N X,Y,ADXTSITE,ADXTTIME,XMDUZ,XMTEXT,ADXTBOST,ADXTUCI,XMSUB,XMY
 ;
 X ^%ZOSF("UCI") S ADXTUCI=Y
 U IO(0) W !,"Generating an installation mail message...",!
 K ^TMP("ADXT","MAILMAN")
 S ADXTSITE=$P($G(^DIC(4.2,$P($G(^XMB(1,1,0)),"^"),0)),"^")
 S ADXTTIME=$$TIME^ADXTUT()
 S ^TMP("ADXT","MAILMAN",1)="An MRS to DHCP conversion was completed at site "_ADXTSITE
 S ^TMP("ADXT","MAILMAN",2)="in UCI "_ADXTUCI_" at time "_ADXTTIME_"."
 ;
 S XMDUZ=.5,XMSUB="MRS CONVERSION PERFORMED"
 S XMTEXT="^TMP(""ADXT"",""MAILMAN"","
 S XMY(DUZ)=""
 S ADXTBOST=""
 S ADXTBOST=$O(^DIC(4.2,"B","BOSTON.VA.GOV",ADXTBOST)) Q:ADXTBOST=""
 S XMY("G.ADXTMM@BOSTON.VA.GOV")=ADXTBOST
 S XMY("G.CLIMAP@ISC-ALBANY.VA.GOV")=$O(^DIC(4.2,"B","ISC-ALBANY.VA.GOV",""))
 ;
 D ^XMD
EXIT ;
 K X,Y,ADXTSITE,ADXTTIME,XMDUZ,XMTEXT,ADXTBOST,XMSUB,XMY
 K ^TMP("ADXT","MAILMAN")
 Q
