AEGJTIB ;JET BKLYN 527  8-30-94
V ;TEMP ROUTINE TO FIND MAX # OF SC CONDITIONS
 K ^TMP("AEGJTIB") S U="^",J=""
 F I=0:0 S J=$O(^DIBT(14804,1,J)) Q:J'>0  S DFN=J D NEXT
 Q
NEXT S NUM=$P($G(^DPT(J,.372,0)),U,4) Q:NUM'>4
 S ^TMP("AEGJTIB",NUM,DFN)=""
 Q
L ;
 F I=0:0 S N=$O(^TMP("AEGJTIB",N)) Q:N'>0  W !,N
 Q
