AEKPMV ;PATCH MANAGEMENT VIEW DCN/BUF JAN 2000
 K DIR S DIR(0)="P^9.4:EMZ" D ^DIR Q:$D(DIRUT)  S PKG=$P(Y(0),"^",2),CV=$G(^DIC(9.4,+Y,"VERSION")) S SEED=PKG_"*"_CV W ?60,SEED
 S PATCH=SEED F  S PATCH=$O(^XPD(9.7,"B",PATCH)) Q:(PATCH=""!($P(PATCH,"*")'=PKG))  S EN=0 F  S EN=$O(^XPD(9.7,"B",PATCH,EN)) Q:EN=""  S ZERO=$G(^XPD(9.7,EN,0)) S LOAD=$P(ZERO,"^",3) S PM((10000000-LOAD),EN)=PATCH
 S (CT,L)=0 F  S L=$O(PM(L)) Q:L=""  S CT=CT+1 D  Q:$D(DIRUT)  
 . S EN=0 F  S EN=$O(PM(L,EN)) Q:EN=""  S PAT=PM(L,EN) W !,PAT S DATA=$G(^XPD(9.7,EN,0)),ID=$P(DATA,"^",3),WHO=$P(DATA,"^",11) W ?14,$E($$EXTERNAL^DILFD(9.7,2,"",ID),1,18),?34,$E($$EXTERNAL^DILFD(9.7,9,"",WHO),1,15) D
 .. S NODE2=$G(^XPD(9.7,EN,2)) I NODE2]"" W ?51,$E(NODE2,1,28)
 . I CT#11=0 K DIR S DIR(0)="Y",DIR("B")="NO",DIR("A")="See more patches" D ^DIR Q:$D(DIRUT)  I Y<1  S DIRUT=1
 K PATCH,SEED,ZERO,PM,L,EN,CT,PAT,DATA,LOAD
 G AEKPMV
