AJETIU3 ;DG REGISTRATION OBJECTS -- HINES/LCR -- 6/11/98
 ;1.0
PRICARE(DFN) ;PRIMARY CARE PHYSICIAN
 N VAIN
 D INP^VADPT
 Q $P(VAIN(2),U,2)
ADMDIAG(DFN) ;ADMITTING DIAGNOSIS
 N VAIN
 D INP^VADPT
 Q VAIN(9)
ATTPHY(DFN) ;ATTENDING PHYSICIAN
 N VAIN
 D INP^VADPT
 Q $P(VAIN(11),U,2)
WARD(DFN) ;WARD LOCATION
 N VAIN
 D INP^VADPT
 Q $P(VAIN(4),U,2)
ROOMBED(DFN) ;ROOM-BED
 N VAIN
 D INP^VADPT
 Q VAIN(5)
ADMTYPE(DFN) ;ADMISSION TYPE
 N VAIN
 D INP^VADPT
 Q $P(VAIN(8),U,2)
TYPELIG(DFN) ;TYPE OF ELIGIBILITY PATIENT
 N VAEL
 D ELIG^VADPT
 Q $P(VAEL(6),U,2)
VET(DFN) ;VET Y/N
 N VAEL
 D ELIG^VADPT
 Q $S(VAEL(4)=1:"YES",VAEL(4)=0:"NO")
CON(DFN) ;PERCENTAGE SERVICE CONNECTED
 N VAEL
 D ELIG^VADPT
 Q $P(VAEL(3),U,2)
CLAIM(DFN) ;CLAIM NUMBER
 N VAEL
 D ELIG^VADPT
 Q VAEL(7)
SERVICE(DFN) ;BRANCH OF SERVICE
 N VASV
 D SVC^VADPT
 Q $P(VASV(6,1),U,2)
SVCNUM(DFN) ;SERVICE NUMBER
 N VASV
 D SVC^VADPT
 Q VASV(6,2)
DISTYPE(DFN) ;SERVICE DISCHARGE TYPE
 N VASV
 D SVC^VADPT
 Q $P(VASV(6,3),U,2)
SVCENT(DFN) ;SERVICE ENTRY DATE
 N VASV
 D SVC^VADPT
 Q $P(VASV(6,4),U,2)
SVCSEP(DFN) ;SERVICE SEPARATION DATE
 N VASV
 D SVC^VADPT
 Q $P(VASV(6,5),U,2)
OCCUP(DFN) ;PATIENTS OCCUPATION
 N VAPD
 D OPD^VADPT
 Q VAPD(6)
EMPST(DFN) ;EMPLOYMENT STATUS
 N VAPD
 D OPD^VADPT
 Q $P(VAPD(7),U,2)
PERIOD(DFN) ;PERIOD OF SERVICE
 N VAEL
 D ELIG^VADPT
 N VASV,SVC D SVC^VADPT 
 S SVC=$S($P(VASV(6,4),U,2)]"":"("_$P(VASV(6,4),U,2)_" to "_$P(VASV(6,5),U,2)_")",1:"")
 Q "Period of Service: "_$P(VAEL(2),U,2)_" "_SVC
SVCCON(DFN) ;SERVICE CONNECTED
 N VAEL
 D ELIG^VADPT
 Q $P(VAEL(1),U,2)
MEANS(DFN) ;CURRENT MEANS TEST STATUS
 N VAEL
 D ELIG^VADPT
 Q $P(VAEL(9),U,2)
