AJK1UBQ ;580/MRL - Collections, Quit, Clean Variables; 22-Nov-97
 ;;2.0T8;AJK1UB;;Sep 15, 1999
 ;
 ;This routine is called to clean up variables, temporary globals,
 ;etc.
 ;
ALL ; --- kill everything
 ;
 K ^TMP($J)
 ;
 K %,%Y,A,AJK,AJK1,AJK1MSG,AJKAUTO,AJKC,AJKCP,AJKEC,AJKERR,AJKI,AJKOD
 K AJKP,AJKREC,AJKU,AR,B,BFY,BN,C,CT,CTR,D,DC,DD
 K DA,DDSFILE,DE,DEL,DFN,DIC,DIE,DIK,DIR,DIRUT,DLAYGO,DO,DR
 K DS,DUE,E,EDT,END,ERR,F,FLAG,G
 K GLOB,GO,I,IC,IEN,J,K,L,LDT,LINE,M,MAX,N,N1,NC,NEW,NOW,NR,NW,P,PR,Q
 K R,RC,RT,RUN,RVW,S,SC,SDT,SENT,ST,START,STATS,STR,T,TD,TEXT,TT,TXT
 K TYPE,V,VAL,W,X,X1,X2
 K XMSUB,XMTEXT,XMY,XMZ
 K Y
 K ZTDESC,ZTDTH,ZTIO,ZTRTN,ZTSAVE,ZTSK
 K ZZ
 Q
