ASFLO2 ;ROUTINE #2 - TO GATHER INFORMATION FOR LOCALLY CREATED OBJECTS - LOCAL COUNTERPART TO TIULO
 ;;V1.0 GDM/SYR 1/29/98
FUT30(TARGET,DFN) ;GETS FUTURE APPOINTMENTS
 K ^TMP($J) S LINE=0 S LINE=LINE+1 S @TARGET@(LINE,0)="          ** FUTURE APPOINTMENTS (NEXT 30 DAYS) **" S LINE=LINE+1,@TARGET@(LINE,0)="      DATE/TIME              CLINIC ( LOCATION )"
 S X1=DT,X2=30 D C^%DTC S ENDATE=X
 S XRF=DT_".9" I $N(^DPT(DFN,"S",XRF)) F I=0:0 S XRF=$O(^DPT(DFN,"S",XRF)) Q:XRF=""!(XRF>ENDATE)  S Y=XRF,(CLI,L)=$P(^DPT(DFN,"S",XRF,0),"^") I $S($P(^DPT(DFN,"S",XRF,0),"^",2)']"":1,$P(^(0),"^",2)="I":1,1:0) D LOC^ASFFUT D
 .S CLI=$P(^SC(CLI,0),"^") X ^DD("DD")
 .S CLI=$E(CLI,1,25)
 .S LINE=LINE+1 S @TARGET@(LINE,0)="   "_Y_"    "_CLI_"  "_"("_SDLOC_")"
 ;S M=SDM K SDN,SDI
 ;S L=+^DPT(DFN,"S",M,0) D LOC^ASFFUT S X=M D TM^ASFFUT S Y=M D DTS^SDUTL S LINE=LINE+1 S @TARGET@(LINE,0)="      "_Y_"   "_$J(X,8)_"      "_$P(^SC(L,0),"^",1)_"  "_SDLOC
 Q "~@"_$NA(@TARGET)
 
