ASFNODE ;PROGRAM TO CORRECT APPLICATION USE FIELD FOR INACTIVE DRUGS ;5/27/93  13:35
 ;;V1.0 GDM/SYR 5/93
 W !!?20,"Listing of Inactive Drugs with 'U' Flag removed",!!?5,"Generic Name",?30,"Old Data",?50,"New Data",?67,"Inact. Date",!?5,"------------",?30,"--------",?50,"--------",?67,"-----------"
 S FLAG=0 S XREF="" F ZZ=0:0 S XREF=$O(^PSDRUG(XREF)) Q:XREF="B"  I $D(^PSDRUG(XREF,"I")) D EDIT
 K FLAG,XREF,ZZ,NODE,DRUG,NODE1,NUM,NODE2 Q
EDIT S NODE=$P(^PSDRUG(XREF,2),"^",3) S DRUG=$P(^PSDRUG(XREF,0),"^",1) W !,$E(DRUG,1,25),"  ",?30,"OLD VALUE: ",NODE
 S CNT=$L(NODE) F I=1:1:CNT S NODE1(I)=$E(NODE,I,I) I NODE1(I)="U" K NODE1(I) S FLAG=1
 S:FLAG=1 CNT=CNT-1 S (NUM,NODE2)="" F I=1:1:CNT S NUM=$O(NODE1(NUM)),NODE2=NODE2_NODE1(NUM),$P(^PSDRUG(XREF,2),"^",3)=NODE2
 W ?46,"NEW VAL: ",NODE2,?60,XREF,?70,^PSDRUG(XREF,"I") S FLAG=0
