ASFRFUND ;THIS PROGRAM IS TO BE USED BY MCCR TO CREATE THE REFUND BILL FOR PATIENTS THAT DID NOT HAVE A BILL NUMBER ASSIGNED 	;DURING THE INSTALLATION OF PHARM CO-PAY EXEMPTION PATCH
 ;;V1.0 GDM/SYR 7/93
START S DIC=2,DIC(0)="AEMNQZ" D ^DIC G:Y=-1 END S DFN=+Y,BEG=2921029,END=DT R !,"Is This the correct patient? YES// ",ANS:DTIME S:ANS="" ANS="Y" I ANS="N"!(ANS="n") G START
 W !!,"Creating Refund Bill for ",$P(^DPT(DFN,0),"^"),!!
 D EN1^PRCAX(DFN,BEG,END) G START
END K DIC,BEG,ENDEND,ANS
