DSIFRPT1 ;DSS/AMC - CALCULATES NON-VA HOSP ACTIVITY ;01/07/2001
 ;;3.2;FEE BASIS CLAIMS SYSTEM;;Jun 05, 2009;Build 38
 ;Copyright 1995-2009, Document Storage Systems, Inc., All Rights Reserved
 ; 
 ; Integration Agreements
 ; 10000  D^%DTC
 ;  5329  DAYS^FBCHACT0
 ;
 Q
 ;
ASKDT ;
START(AXY,FBENDDT,FBK) ;RPC - DSIF INP NON-VA HOSP ACTIVITY
 ;Input Variables
 ;    FBENDDT - Last Day of the Month for the report (Required, FileMan format)
 ;    FBK - Report Hospital Type (Required, 1 = Public Hospital, 2 = Private Hospital, 3 = Federal Hospital)
 ;    
 ;Return Array
 ;    -1 ^ Invalid Input!
 ;    -1 ^ No Activity Found!
 ;    Record Ind ('M'edicine, 'S'urgery, 'P'sychiatry) ^ Admissions ^ Discharges ^ Deaths ^ Patients Remaining ^ Days of Care ^ Days of Unauth Care
 ;    
 S AXY=$NA(^TMP("DSIFRPT1",$J))
 I '$G(FBENDT)!(123'[+$G(FBK)) S AXY="-1^Invalid Input!" Q
 N ACNT,DCNT,RCNT,DUOUT,DTOUT,DIRUT,I,J,K,L,FBHED,X,Y,FBCHDT,ZZ,FBADMIT,FB,FBBED,PTYPE,VTYPE,DAYS,FBVENTP,XX,YY S YY=0
 S DCNT=0,FBTYPE=6 K ^TMP("FBCH",$J)
 F I=FBCHDT:0 S I=$O(^FB7078("AD",FBTYPE,I)) Q:I'>0!(I>FBENDDT)  F J=0:0 S J=$O(^FB7078("AD",FBTYPE,I,J)) Q:J'>0  D VENTYPE I FBVENTP S DCNT=DCNT+1,^TMP("FBCH",$J,"AD",FBVENTP,J,I)=""
 S ACNT=0
 F I=FBCHDT:0 S I=$O(^FB7078("AA",FBTYPE,I)) Q:I'>0!(I>FBENDDT)  F J=0:0 S J=$O(^FB7078("AA",FBTYPE,I,J)) Q:J'>0  D VENTYPE I FBVENTP S ACNT=ACNT+1,^TMP("FBCH",$J,"AA",FBVENTP,J,I)=""
 S RCNT=0
 F K=0:0 S K=$O(^FB7078("AA",FBTYPE,K)) Q:K'>0!(K>FBENDDT)  F J=0:0 S J=$O(^FB7078("AA",FBTYPE,K,J)) Q:J'>0  I $P(^FB7078(J,0),"^",5)]""&($P(^(0),"^",5)>FBENDDT) D VENTYPE I FBVENTP S RCNT=RCNT+1,^TMP("FBCH",$J,"AR",FBVENTP,J,K)=""
 I $D(^FB7078("AC","I")) F I=0:0 S I=$O(^FB7078("AC","I",I)) Q:I'>0  F J=0:0 S J=$O(^FB7078("AC","I",I,J)) Q:J'>0  D VENTYPE I FBVENTP S RCNT=RCNT+1
 D ACT1,ACT0
END ;
 I 'YY S @AXY@(YY)="-1^No Activity Found!"
 K ^TMP("FBCH",$J) Q
 ;
VENTYPE ;GET VENDOR TYPE
 S FBVENTP="" Q:'J  Q:'$D(^FB7078(J,0))
 Q:$P($G(^FB7078(J,0)),U,9)="DC"
 S FBVENTP=$S($P($P(^FB7078(J,0),"^",2),";",2)="FBAAV(":$P($P(^(0),"^",2),";",1),1:""),FBVENTP=$S(FBVENTP="":"",1:$S($D(^FBAAV(FBVENTP,0)):$P(^(0),"^",7),1:""))
 I FBVENTP="" S FBVENTP=1
 Q
ACT1 ;
 K ^TMP("FB",$J) F I="00",10,86 S DAYS(I)=0,^TMP("FB",$J,FBK,I)=0
 F I=FBCHDT:0 S I=$O(^FB583("AD",FBTYPE,I)) Q:I'>0  F J=0:0 S J=$O(^FB583("AD",FBTYPE,I,J)) Q:J'>0  I $D(^FB583(J,0)) S FB(0)=^(0) D VTYPE S:PTYPE="00"!(PTYPE=10)!(PTYPE=86) ^TMP("FB",$J,VTYPE,PTYPE)=DAYS(PTYPE)
 Q
VTYPE S VTYPE=$P(FB(0),"^",3),VTYPE=$S(VTYPE="":"",1:$S($D(^FBAAV(VTYPE,0)):$P(^(0),"^",7),1:""))
 I VTYPE="" S VTYPE=1
 S PTYPE=$P(FB(0),"^",10)
 S FBFRDT=$P(FB(0),"^",13),FBFRDT=$S(FBFRDT<(FBCHDT+1):FBCHDT+1,1:FBFRDT)
 S FBTODT=$P(FB(0),"^",14),FBTODT=$S(FBTODT>FBENDDT:FBENDDT,1:FBTODT-1)
 S FBDAYS=0
 D:FBFRDT'>FBENDDT DAYS^FBCHACT0
 Q:VTYPE'=FBK
 I PTYPE="00" S DAYS(PTYPE)=DAYS(PTYPE)+FBDAYS
 I PTYPE=10 S DAYS(PTYPE)=DAYS(PTYPE)+FBDAYS Q
 I PTYPE=86 S DAYS(PTYPE)=DAYS(PTYPE)+FBDAYS Q
 Q
ACT0 ;
 S (SCNT,MCNT,PCNT,SDED,MDED,PDED,ASCNT,AMCNT,APCNT,DSCNT,DMCNT,DPCNT,RSCNT,RMCNT,RPCNT,FBDAYS,FBMDAY,FBSDAY,FBPDAY)=0,FBBED=""
 F J="AA","AD","AR" F I=0:0 S I=$O(^TMP("FBCH",$J,J,FBK,I)) Q:I'>0  I $D(^FBAAA("AG",I_";FB7078(")) D 161
 D EN,WRT
 K AMCNT,APCNT,ASCNT,DMCNT,DPCNT,DSCNT,FBADDT,FBCHDT,FBDA,FBDAYS,FBDED,FBFRDT,FBMDAY,FBPDAY,FBSDAY,FBTODT,FBTYPE,I,J,MCNT,PCNT,PDED,Q,QQ,RMCNT,RPCNT,RSCNT,SCNT,SDED,X,Y,MDED Q
161 S FBDA(1)=$O(^FBAAA("AG",I_";FB7078(",0)),FBDA=$O(^FBAAA("AG",I_";FB7078(",FBDA(1),0)) Q:'$D(^FBAAA(FBDA(1),1,FBDA,0))  S FBADDT=$P(^(0),"^",18),FBFRDT=$P(^(0),"^"),FBTODT=$P(^(0),"^",2)
 S FBFRDT=$S(FBCHDT>FBFRDT:FBCHDT,1:FBFRDT),FBTODT=$S(FBTODT="":FBENDDT,FBTODT>FBENDDT:FBENDDT,1:FBTODT)
 I FBADDT="00" S SCNT=SCNT+1
 I FBADDT=10 S MCNT=MCNT+1
 I FBADDT=86 S PCNT=PCNT+1
 I J="AA" S ASCNT=ASCNT+SCNT,AMCNT=AMCNT+MCNT,APCNT=APCNT+PCNT D RESET Q
 I J="AD" S DSCNT=DSCNT+SCNT,DMCNT=DMCNT+MCNT,DPCNT=DPCNT+PCNT D RESET Q
 I J="AR" S RSCNT=RSCNT+SCNT,RMCNT=RMCNT+MCNT,RPCNT=RPCNT+PCNT D RESET Q
 Q
WRT D HED
 S XX="M^"_AMCNT_U_DMCNT-MDED_U_MDED_U_RMCNT_U_FBMDAY_U_^TMP("FB",$J,FBK,10),YY=YY+1,@AXY@(YY)=XX
 S XX="S^"_ASCNT_U_DSCNT-SDED_U_SDED_U_RSCNT_U_FBSDAY_U_^TMP("FB",$J,FBK,"00"),YY=YY+1,@AXY@(YY)=XX
 S XX="P^"_APCNT_U_DPCNT-PDED_U_PDED_U_RPCNT_U_FBPDAY_U_^TMP("FB",$J,FBK,86),YY=YY+1,@AXY@(YY)=XX
 Q
HED ;
 Q
RESET ;
 S (MCNT,SCNT,PCNT)=0 Q
DAYS ;
 S FBDAYS=0,X1=FBTODT,X2=FBFRDT D D^%DTC S FBDAYS=$S(X<1:1,1:X+1)
 Q
HED1 ;
 W !?41,"PATIENTS",?57,"DAYS OF",?70,"DAYS OF",!?1,"ADMISSIONS",?15,"DISCHARGES",?30,"DEATHS",?40,"REMAINING",?58,"CARE",?69,"UNAUTH CARE",! F QQ=1:1:80 W "-"
 W ! Q
EN ;
 F I=FBCHDT:0 S I=$O(^FB7078("AD",FBTYPE,I)) Q:I'>0  F J=0:0 S J=$O(^FB7078("AD",FBTYPE,I,J)) Q:J'>0  D VENTYPE I FBVENTP=FBK I $D(^FB7078(J,0)) S FBADMIT=$P(^(0),"^",4),FBTODT=I D GETBED,CHK
 Q
CHK ;
 Q:FBADMIT>FBENDDT  S FBFRDT=$S(FBADMIT<FBCHDT:FBCHDT,1:FBADMIT)
 S FBTODT=$S(FBTODT>FBENDDT:FBENDDT,1:FBTODT)
 D DAYS I FBTODT'=FBENDDT S FBDAYS=FBDAYS-1
 I FBBED="00" S FBSDAY=FBSDAY+FBDAYS I FBDED=2!(FBDED=3) S SDED=SDED+1 K FBDED
 I FBBED=10 S FBMDAY=FBMDAY+FBDAYS I FBDED=2!(FBDED=3) S MDED=MDED+1 K FBDED
 I FBBED=86 S FBPDAY=FBPDAY+FBDAYS I FBDED=2!(FBDED=3) S PDED=PDED+1 K FBDED
 S FBBED="" Q
GETBED ;
 S FB(1)=$O(^FBAAA("AG",J_";FB7078(",0)) Q:FB(1)=""  S FB=$O(^FBAAA("AG",J_";FB7078(",FB(1),0)) Q:FB=""  I $D(^FBAAA(FB(1),1,FB,0)) S FBBED=$P(^(0),"^",18),FBDED=$P(^(0),"^",15)
 Q
