PRMQDGPM ;Chicago ISC/DDA-  PATIENT MOVEMENT DRIVER ;7/22/90  15:32
 ;;1.2;Utilization Review;;
EN1 ; ENTRY TO CHECK FOR DELETED MOVEMENTS
 Q:'($D(DGPMP)#2)  Q:DGPMP=""  Q:DGPMA'=""
 S PRMQIEN=$O(^PRMQ(513.8,"B",DFN,0)),PRMQMT=0
 F PRMQ=0:0 S PRMQMT=$O(^UTILITY("DGPM",$J,2,PRMQMT)) Q:PRMQMT'>0  S PRMQDEL=$P(^UTILITY("DGPM",$J,2,PRMQMT,"P"),"^") I $D(^PRMQ(513.8,"C",PRMQDEL)),$D(^(PRMQDEL,PRMQIEN))=10 S PRMQIEN1=$O(^(PRMQIEN,0)),^UTILITY("PRMQDEL",$J,PRMQIEN,PRMQIEN1)=""
 S PRMQMT=0
 F PRMQ=0:0 S PRMQMT=$O(^UTILITY("DGPM",$J,1,PRMQMT)) Q:PRMQMT'>0  S PRMQDEL=$P(^UTILITY("DGPM",$J,1,PRMQMT,"P"),"^") I $D(^PRMQ(513.8,"C",PRMQDEL)),$D(^(PRMQDEL,PRMQIEN))=10 S PRMQIEN1=$O(^(PRMQIEN,0)),^UTILITY("PRMQDEL",$J,PRMQIEN,PRMQIEN1)=""
 N DA,DIK,RIEN D ENDEL^PRMQS2
 K PRMQ,PRMQIEN,PRMQIEN1,PRMQMT,PRMQDEL
 Q
