RJPTFCNT ;RJ WILM DE -STAT COUNT OF RECORD STATUS; 12-12-85
 ;;4.0
 S %DT="APE",%DT("A")="Start with Discharge Date: " D ^%DT G:Y=-1 Q S Z1=Y,%DT("A")="End with Discharge Date: " D ^%DT G:Y=-1 Q S Z2=Y
 W !!,"This report can be Queued by typing a ""Q"" at the DEVICE: prompt."
 S %IS="QM",%IS("B")="" K IOP D ^%ZIS G:POP Q I $D(IO("Q")) S PGM="QQ^RJPTFCNT" D ^RJPTFQ S ^%ZTSK(ZTSK,"ZTSK")=ZTSK,^%ZTSK(ZTSK,"Z1")=Z1,^%ZTSK(ZTSK,"Z2")=Z2 G Q
 W !,"This will take a few moments."
S S (RJCOD,RJCLO,RJREL,RJEAL,RJACC,RJTOT,I)=0 F RJCT=1:1 S I=$O(^DGPT(I)) Q:I'?.N  D LU
 U IO D O
Q X ^%ZIS("C") K %IS,%DT,Z1,Z2,I,IO("Q"),X,RJCOD,RJCLO,RJREL,RJEAL,RJACC,RJTOT,RJSTAT,RJCT,X1,X2,J,PGM,Y,ZTSK Q
LU Q:'$D(^DGPT(I,70))  S X1=Z1,(X2,D)=$P(^DGPT(I,70),"^",1) D ^%DTC Q:X>0  S X1=Z2,X2=D D ^%DTC Q:X<0
 S RJTOT=RJTOT+1 Q:'$D(^DGP(45.84,I,0))  S RJCOD=RJCOD+1
 S RJSTAT=^DGP(45.84,I,0) I $P(RJSTAT,"^",2) S RJCLO=RJCLO+1
 I $P(RJSTAT,"^",4) S RJREL=RJREL+1
 Q:'$D(^DGPT(I,460))  S RJSTAT=^DGPT(I,460) I $P(RJSTAT,"^",3) S RJACC=RJACC+1
 I $P(RJSTAT,"^",4) S RJEAL=RJEAL+1
 Q
O W @IOF,!,"DISCHARGES FROM ",$E(Z1,4,5),"-",$E(Z1,6,7),"-",$E(Z1,2,3),"  TO ",$E(Z2,4,5),"-",$E(Z2,6,7),"-",$E(Z2,2,3),!!
 W !,"COUNT OF RECORDS:",!,"CODED",?15,"CLOSED",?30,"RELEASED",?45,"WITH EAL's",?60,"ACCEPTED",! F J=1:1:79 W "-"
 W !,RJCOD,?15,RJCLO,?30,RJREL,?45,RJEAL,?60,RJACC,!!,"TOTAL PATIENTS: ",RJTOT
 Q
QQ S Z1=^%ZTSK(ZTSK,"Z1"),Z2=^%ZTSK(ZTSK,"Z2") G S
