RJPTFOU2 ;RJ WILM DE -LIST DRG'S PER DX PER MOVEMENT FROM DRG CALCULATOR; 12-12-85
 ;;4.0
 S Z(1)="Jan^Feb^Mar^Apr^May^Jun^Jul^Aug^Sep^Oct^Nov^Dec",(G,G1)=0
 ;checked but not released
 I $D(RJFLAG) D H^RJPTFOU1 S I=0 F P=1:1 S I=$O(^DGP(45.84,I)) G:I=""!(I'?.N) Q I $D(^DGPT(I,0)),$P(^DGP(45.84,I,0),U,4)="" S RJPTF=^DGPT(I,0),RJPAT=^DPT($P(RJPTF,U,1),0) D ^RJPTFOU1
 ;selection
 I $D(RJFLAG1) D H^RJPTFOU1 F RJPTFA=1:1 S I=$P(A,",",RJPTFA) G:I="" Q D ^RJPTFOU1
 ;batch
 I $D(ZZ) D H^RJPTFOU1 F I=ZZ:1:R I $D(^DGPT(I,0)) D ^RJPTFOU1
Q K A,DIC,DA,D,G,G1,I,K,L,P,R,X,Z,ZZ,RJDRG,RJPTF,RJPTFA,RJPAT,RJFLAG1,RJFLAG,RJIO W @IOF X ^%ZIS("C") Q
