SWCNHADD ;DLG/FARGO;ML/BHAM;ADD ENTRY TO CNH FILE;11/1/85
 ;VERSION 1.0;GET ENTRY NUMBER AND ADD FIELDS FOR NEW ENTRY NUMBER AND EDIT FIELDS FOR NEW ENTRY.
 S DIC=657,DIC(0)="ALEQM",DIC("S")="I $P(^(0),U,10)=""A""" D ^DIC G:+Y<0 DONE S DA=+Y,DIE="^SOWK(657,",DR="[SWCNHEDT]" K DIC("S") D ^DIE
 G:'$D(Y) SWCNHADD
DONE K DIE,DR,Y,DIC,DFN,DA,%DT,%X,%Y,DQ,I,X,D0,D Q
