ADDRESS
 ;;1
 ;VARIABLE LIST
 ;
 ;DTIME.....DELAY TIME FOR READ (NOT TO BE KILLED)
 ;OPT.......OPTION NUMBER ENTERED BY THE USER
 ;ITEMS.....NUMBER FOR EACH MENU OPTION
 ;
INIT ;
 D LOAD^VECSG7
START ;
 D DISMENU
 I OPT=""!(OPT["^") GOTO EXIT
 D ^VECSG8:OPT=1
 D ^VECSG9:OPT=2
 D ^VECSG10:OPT=3
 D ^VECSG12:OPT=4
 D ^VECSG11:OPT=5
 G START
DISMENU ;
 W !!,?20,"LET'S TRY SEARCHING..."
 W !!,"SEARCH BY..."
 F ITEMS=1:1:5 W !,ITEMS,?5,$P($T(OPTIONS+ITEMS),";;",2)
DISMENU1  ;
 R !!,"ENTER OPTION NUMBER: ",OPT:DTIME  Q:OPT=""
 I '$T!(OPT["^") QUIT
 I (OPT<1)!(OPT>5) W !!,"OPTION NUMBER MUST BE "
 I  W "BETWEEN 1 AND 5" G DISMENU1
 Q
EXIT ;
 K OPT,ITEMS,NAMES
 Q
OPTIONS  ;
 ;;NAME
 ;;STREET NAME
 ;;CITY
 ;;STATE
 ;;ZIP
  
  
  
