VECSG8
 ;;1
 ;VARIABLE LIST
 ;
 ;SNAME.......NAME USER WANTS TO SEARCH FOR
 ;NAME........FULL NAME OF THE CURRENT RECORD
 ;LNAME.......LAST NAME OF THE CURRENT RECORD
 ;FNAME.......FIRST NAME OF THE CURRENT RECORD
 ;RECNR.......RECORD NUMBER OF THE CURRENT RECORD
 ;RECORD......CURRENT
 ;ANS.........USER'S RESPONSE TO "PRESS ENTER TO RETURN TO THE MENU"
 ;
START ;
 R !!,"ENTER FIRST LETTER OR LAST NAME: ",SNAME:DTIME
 I '$T!(SNAME["^") G EXIT
 I SNAME'?1U.A W !,"ENTER A LETTER OR A LAST NAME" G START
 F RECNR=1:1:NAMES(0) D SEARCH
 G EXIT
SEARCH ;
 S RECORD=NAMES(RECNR)
 S NAME=$P(RECORD,"^",1)
 S LNAME=$P(NAME,",",1)
 S FNAME=$P(NAME,",",2)
 I $L(SNAME)=1 D LETTER
 I $L(SNAME)'=1 D WORD
 Q
LETTER ;
 I $E(LNAME)=SNAME DO WRREC^VECSG7
 Q
WORD ;
 I SNAME=LNAME DO WRREC^VECSG7
 Q
EXIT ;
 R !!,"PRESS ENTER TO RETURN TO THE MENU",ANS:DTIME
 K SNAME,LNAME,FNAME,RECNR,ANS,NAME,RECORD
 Q
  
  
  
  
  
