 ;ATL/ACE PROGRAMMER-EMPLOYEE SYSTEM
 ;;1
 ;       VARIABLE LIST
 ;
 ;       OPT         =    OPTION NUMBER AS ENTERED BY THE USER
 ;       NAME        =    THE EMPLOYEE'S NAME
 ;       NR          =    THE EMPLOYEE NUMBER
 ;       ^VECEMP(    =    THE EMPLOYEE'S FILE
  
MENU ;
 W !!,"EMPLOYEE SYSTEM"
 W !!,"OPTION   FUNCTION"
 W !!,"1        LOAD EMPLOYEES"
 W !!,"2        PRINT EMPLOYEES"
 R !!!,"ENTER OPTION NUMBER: ",OPT:DTIME G EXIT:OPT=""
 I '$T!(OPT["^") G EXIT
 I OPT<1!(OPT>2) W !,"ENTER 1 OR 2" G MENU
OPTIONS
 D LOAD:OPT=1
 D PRINT:OPT=2
 G MENU
EXIT ;
 K OPT,NAME,NR
 Q
LOAD ;
 R !!,"ENTER EMPLOYEE NUMBER: ",NR:DTIME G LOADEX:NR=""
 I '$T!(NR["^") G LOADEX
 R !,"ENTER EMPLOYEE NAME: ",NAME:DTIME
 I $T!(NAME["^") G LOADEX
 S ^VECEMP(NR)=NAME
 G LOAD
LOADEX ;
 Q
PRINT ;
 S NR=""
 F  S NR=$O(^VECEMP(NR)) Q:NR=""  D OUTPUT
 Q
OUTPUT ;
 W !!,"THE EMPLOYEE IS ",NR
 W !,"THE NAME IS ",^VECEMP(NR)
 Q
         
  
