ZCARL ;SCRATCH ROUTINE TO CLEAN UP DENVER TRANSMISSIONS CFB/TUSC ;1/26/96  07:32
 D DT^DICRW S QQS=$O(^XMB(3.7,.5,2,"B","S.AFJXNETP","")) Q:QQS'>0
 F QQP=0:0 S QQP=$O(^XMB(3.7,.5,2,QQS,1,QQP)) Q:QQP'>0  D WORK
 Q
WORK S XMZ=QQP D ^AFJXPNHT S ^AFJ("ZCARL",QQP)=$H Q
TASK ;VERIFY PRIORITIES FOR YOUR SYSTEM
 S ZTRTN="^ZCARL",ZTDESC="NHE FIXUP CFB/ISC-SF",ZTIO="",ZTPRI=5 D ^%ZTLOAD
