ZDDUTIL ;PROGRAM TO MANIPULATE THE DD [ 05/01/94  8:11 PM ] ;8/7/96  13:31
FILES ;GET A LIST OF FILES FOR THE UCI
 S FNAME=""
 K ^TMP($J)
 F  S FNAME=$O(^DIC("B",FNAME)) Q:FNAME=""  D GETFILES
 Q
GETFILES ;GET FILE NAMES
 ;AND NUMBERS
 S FNUM=""
 S FNUM=$O(^DIC("B",FNAME,FNUM)) Q:FNUM=""  D WRFILEN
 Q
WRFILEN ;WRITE THE FILENAME
 ;
 S ^TMP($J,FNUM)=FNAME
 ;W !,"FILE NUM=",FNUM,?18,"  FILE NAME=",FNAME
 Q
 ;***********************FIELD LISTER***********************
FIELDS ;
 ;R !,"Enter file number:",FILENUM
 K FLDLST S PASS=0,XXX="",FLDSTX="",LAYER=1,FLDLST(0)="",FLDLST(1)=""
 S FLDLST(2)=""
 I FILENUM="^"!(FILENUM="") S ERROR="FILE NOT SPECIFIED." Q
 S ORIGFIL=FILENUM ;SAVE ORIGINAL FILE NUMBER
 K ^TMP($J)
 S GLOB=$G(^DIC(FILENUM,0,"GL"))
 I GLOB="" S ERROR="File doesn't exist!" Q 
 S FILENAME=$P($G(^DIC(FILENUM,0)),"^",1)
 ;W !,"File selected is:",FILENAME,"  Global location is:",GLOB
 S ^TMP($J,"GLOBAL DATA")=FILENAME_GLOB
 ;R X:1 ;WASTE A SECOND
 S FIELDNAM=""
LOOP ;
 F  S SUBLEV=1 S FIELDNAM=$O(^DD(FILENUM,"B",FIELDNAM)) Q:FIELDNAM=""  D FINDFLD
 ;W !,"End of file..."
 K SUBLEV,FIELDREF,NFIELDNUM,PIECE5,XSTR,XPOS,NODE,NODPIECE
 K FLDATTR,FLDLEN,FIELDNAME,FIELDNUM,L,PIECE,ORIGFIL
 Q
FINDFLD ;GET THE FIELD DATA
 I $E(FIELDNAM,1,1)="*" Q  ;FIELD OBSOLETE THROW AWAY
 ;W !,"FIELD=",FIELDNAM
 S FIELDNUM=$O(^DD(FILENUM,"B",FIELDNAM,""))
MULT ;HERE YOU MIGHT HAVE A MULTIPLE FIELD
 S FIELDREF=$P(^DD(FILENUM,FIELDNUM,0),"^",1),FIELDX=$P(^(0),"^",2)
 I +FIELDX D  ;MULTIPLE FIELD
 .S ^TMP($J,FILENUM,FIELDNUM)=FIELDNAM_"^"_"*Top Multiple*"_"^"_FIELDX_"^"_FIELDNUM_"^"_FILENUM
 .S FLDLST(LAYER)=FLDLST(LAYER-1)_$S(FLDLST(LAYER-1)'="":",",1:"")_FIELDNUM
 .S LAYER=LAYER+1
 .;S ^TMP($J,"SUB",FIELDNUM)=FLDSTX
 .S SUBLEV=SUBLEV+1 
 .S SUB(SUBLEV)=$P($P(^DD(FILENUM,FIELDNUM,0),"^",4),";",1)
 .S SUBLEV=SUBLEV+1
 .S NFILENUM=FILENUM,NFIELDNUM=FIELDNUM,NFIELDNAME=FIELDNAM 
 .N FILENUM,FIELDNAM,FIELDNUM 
 .S FILENUM=+$P(^DD(NFILENUM,NFIELDNUM,0),"^",2),FIELDNAM="",N1=FILENUM 
 .S PIECE5=$P(^DD(FILENUM,.01,0),"^",5,999),SUBVAL="DA"
 .I PIECE5["DINUM" D  ;LOOK FOR A DINUM ENTRY IN DD
   ..S XPOS=$F(PIECE5,"DINUM")-5,XSTR=$E(PIECE5,XPOS,999)
   ..S SUBVAL=$P(XSTR," ",1)
 .S SUB(SUBLEV)=SUBVAL
 .D MORMULT
 .S FIELDNAM=$O(^DD(FILENUM,"B",FIELDNAM)) Q:FIELDNAM="" 
 I +$P(^DD(FILENUM,FIELDNUM,0),"^",2) Q  ;HAVE A MULTIPLE
 ;W " [",FIELDNUM,"]"
 S NODPIECE=$P($G(^DD(FILENUM,FIELDNUM,0)),"^",4)
 S NODE=$P(NODPIECE,";",1),PIECE=$P(NODPIECE,";",2)
 ;W ?35," NODE=",NODE,"  PIECE=",PIECE
 ;FIELD ATTRIBUTES
 S FLDATTR=$P($G(^DD(FILENUM,FIELDNUM,0)),"^",2)
 I FLDATTR["NJ" S L=$P(FLDATTR,"NJ",2),FLDLEN=+L,FLDATTR="$" G CURR
 S FLDLEN=$P($G(^DD(FILENUM,FIELDNUM,0)),"^",5)
 S L=$P(FLDLEN,">",2),L=$P(L,"!"),FLDLEN=L ;PULL LENGTH FROM M-STRING
CURR ;CURRENCY
 I +FLDLEN=0 S FLDLEN=30 ;ARBITRARY
SORT ;SORT THE DATA
 ;D SET
 S KEYNUM=$S(SUBLEV=1:1,SUBLEV=3:2,SUBLEV=5:3,SUBLEV=7:4,SUBLEV=9:5,SUBLEV=11:6,1:"SUBSCRIPT LEVEL ERROR")
 I +KEYNUM S OLDKEY=KEYNUM,KEYNUM="KEY"_KEYNUM
 S EX=$E(KEYNUM,4,99),FLDSTX=FLDLST(EX-1)_$S(FLDLST(EX-1)'="":",",1:"")_FIELDNUM
 S ^TMP($J,FILENUM,FIELDNUM)=FIELDNAM_"^"_FLDATTR_"^"_FLDLEN_"^"_ORIGFIL_"^"_FILENUM_"^"_FIELDNUM_"^"_KEYNUM_"^"_FLDSTX ;_"^"_FIELDXX ;_SUBS
 ;W ?65,"FIELD ATR:"_FLDATTR
 Q
SET ;BUILD SUBSCRIPTS FOR GETTING DATA
 S D=0,X="\\DA"
 F  S D=$O(SUB(D)) Q:D'>0  S X=X_"^"_SUB(D)
 S SUBS=X
 Q
MORMULT ;
 ;W !,"******* MULTIPLE FILE****>",FILENUM
 F  S FIELDNAM=$O(^DD(FILENUM,"B",FIELDNAM)) Q:FIELDNAM=""  D FINDFLD
 K SUB(SUBLEV),SUB(SUBLEV-1) S SUBLEV=SUBLEV-2
 Q
