ZZINR ;PROGRAM TO GET ALL INR VALUES FOR PATIENT IN THE INR CLINIC
 ;AMT 1/6/97
START ;
 S X=250 X ^%ZOSF("RM") ;SET RIGHT MARGIN TO AVOID CR/LF
 I $D(BCP)=0 S BCP=0 ;NO BCP OUTPUT, TO SCREEN ONLY AND IN READABLE FORMAT
 K ^XTEMP($J)
 K PCNT
 S %DT("A")="Enter clinic start date:",%DT="APE"
 D ^%DT I X="^" G EXIT
 S DTSTART=+Y
 S %DT("A")="Enter clinic end date:" d ^%DT
 I X="^" G EXIT
 S DTEND=+Y_".24"
 I DTEND<DTSTART W !,"Ending date must be greater than start!" G START
 I BCP=0 W !
 I BCP=1 H 20 ;GIVE THE USER 20SEC TO SET THE TERMINAL
CLINIC ;
 S CLN=411 ;U-ANTICOAG CLINIC
 S CLINDT=DTSTART
 F  S CLINDT=$O(^SC(CLN,"S",CLINDT)) G:CLINDT>DTEND EXIT D MORE
 G EXIT
MORE ;GET MORE DATA FOR PATINET LISTS
 ;W !,"CLINDT=",CLINDT
 S IND=0
 F  S IND=$O(^SC(CLN,"S",CLINDT,1,IND)) Q:IND=""  D GETPT
 Q
GETPT ;GET PATIENT DFN
 S X=$G(^SC(CLN,"S",CLINDT,1,IND,0))
 ;W !,X
 S DFN=$P(X,"^",1) S YY=$G(^DPT(DFN,0))
 S SSN=$P(YY,"^",9),PTNAME=$P(YY,"^",1)
 I BCP=0 W SSN,?14,PTNAME,?50,DFN,?64,CLINDT,!
 D LABRES
 Q
LABRES ;GET LAB RESULTS
 S TEST="INR%",NOOUTP=1 D LAB^ZPCMBCP
 F I=1:1:CNTTEST D  ;
 .I BCP=0 W $P(RECX(I),"^",4),?14,$P(RECX(I),"^",3),?30,$P(RECX(I),"^",2),!
 .I BCP=1 I $D(^XTEMP($J,DFN))=0 W RECX(I),!
 S ^XTEMP($J,DFN)=""
 Q
EXIT ;
 I BCP=0 W !,"Patient count:",PCNT
 I BCP=0 W " Exiting..."
 K ^XTEMP($J) ;CLEANUP
 Q
