ZPCMFUNC ; FUNCTIONS FOR SQL 11:49 ;7/18/97  10:39
 ;AMT
 ;TABLES
 ;
 I $D(U)=0 S U="^"
 I $D(DUZ)=0 S DUZ=1
 ;amt-to test sql
 ;
START ;  |FUNCTION|Func name|test name|all/list|table|
 S XIN=X
 I $D(DT)=0 S %DT="P",X="NOW" D ^%DT S DT=+Y W !,"DATE=",Y
 S FUNC=$P(XIN,"|",3)  ;FUNCTION NAME
 S TABLE=$P(XIN,"|",6) ;Table name
 S RANGE=$P(XIN,"|",5) ;GET ALL OR LIST
 S TESTIN=$P(XIN,"|",4) ;TEST NAME
 S PCNT=0
 I RANGE="All" D  ;ALL DFNS
 .S DFN=0 F  S DFN=$O(^DPT(DFN)) Q:+DFN=0!(PCNT>1000000)  D  ;PCNT=PATIENT CNT
 ..S SSN=$P($G(^DPT(DFN,0)),"^",9)
 ..S NAME=$P($G(^DPT(DFN,0)),"^",1)
 ..I SSN'="" S FLAGGOT=0 D @FUNC
INCLIST I RANGE="List" D  ;
 .S XSSN="" F  S XSSN=$O(^XTEMP($J,XSSN)) Q:XSSN=""  D  ;
 ..S SSN=XSSN
 ..I $A($E(XSSN,1,1))<32 S SSN=$E(XSSN,2,$L(XSSN)) ;GET RID OF BAD STUFF
 ..;W "XSSN=",XSSN,!,"SSN=",SSN,!
 ..S DFN=$O(^DPT("SSN",SSN,""))
 ..I DFN="" Q
 ..S NAME=$P($G(^DPT(DFN,0)),"^",1)
 ..S FLAGGOT=0 D @FUNC
 W "**ENDTX**",!
 Q
 ;Start to traverse patient file
 S DFN=0,RECTX=0
 I $D(^ZSQLINT("DFN"))=1 S DFN=$P(^ZSQLINT("DFN"),"^",1),RECTX=$P(^ZSQLINT("DFN"),"^",2)
 S EXIT=0 ;NO EXIT
 F  S OLDDFN=DFN S DFN=$O(^DPT(DFN)) Q:+DFN=0!(EXIT=1)  D DATA S ^ZSQLINT("DFN")=DFN
 S ^ZSQLINT("FINISHED")=$H
 Q
 ;
CHECK ;
 R XIN:3600 I '$T W "Timeout" S EXIT=1
 ;I XIN["*OK" S ^ZSQLINT1("DFN")=DFN_"^"_RECTX Q
 S EXIT=1 S ^ZSQLINT("DFN")=OLDDFN_"^"_"ERROR:"_$H Q  ;NO GOOD
 Q
 G EXIT
DEMOG I $D(^DPT(DFN,0))=0 Q
 ;
 K ANS ;CLEAR THE DATA ARRAY
 S X=$G(^DPT(DFN,0)),NAME=$P(X,"^",1),SSN=$P(X,"^",9)
 I X="" Q  ;GET RID OF INCOMPLETE RECORDS-GARBAGE DATA
 ;W "**BEG TX:PATIENT_UD",!
 W TABLE_".PATIENT_NAME=",NAME,!
 W TABLE_".SSN=",SSN,!
MOREDATA ;
 S DIC=2,DR=.06,DA=DFN,FILENUM=DIC D GETFM ;RACE
 I ANS="" S ANS="UNKNOWN"
 W TABLE_".RACE=",ANS,!
 S DR=.02 D GETFM ;SEX
 W TABLE_".SEX=",ANS,!
 S DR=.03 D GETFM ;DOB
 I $L(ANS,",")=1 S ANS="JAN 1, "_ANS
 I $L(ANS)>14 S ANS=""
 W TABLE_".DOB=",ANS,!
 S DR=.351 D GETFM ;EXPIRATION
 I ANS["@" S ANS=$P(ANS,"@",1)
 I ANS'="" I $L(ANS,",")=0 S ANS="JAN 1,"_ANS
 W TABLE_".EXPIRATION=",ANS,! ;I $L(ANS))>8
MARITAL ;S DR=.05 D GETFM ;MARITAL STATUS
 ;I ANS]"" W "PATIENT.MARITAL_STATUS:",ANS,!
 S DR=537025 D GETFM ;NETWORK IDENTIFIER
 W TABLE_".NET_ID=",ANS,!
 S DR=.131 D GETFM ;TELEPHONE
 W TABLE_".PHONE=",ANS,!
 S DR=.1112 D GETFM
 W TABLE_".ZIP_CODE=",ANS,!
 S DR=.323 D GETFM ;PERIOD OF SERVICE
 W TABLE_".PERIOD_SERVICE=",ANS,!
 S DR=.301 D GETFM ;SERVICE CONNECTED
 W TABLE_".SERVICE_CONNECTED=",ANS,!
 S DR=.07 D GETFM
 W TABLE_".OCCUPATION=",ANS,!
 S DR=.32102 D GETFM
 W TABLE_".AGENT_ORANGE=",ANS,!
 S DR=.32201 D GETFM
 W TABLE_".PERSIAN_GULF=",ANS,!
 W "*ENDREC*",!
 S PCNT=PCNT+1
 Q
TODO ;FIND ITEMS TO DO
 D ADM
 D LAB
 D MED
 I $D(^ZSQLINT("STOP"))=1 S EXIT=1 Q  ;WANT A GRACEFUL STOP AFTER RECORD DONE
 Q
LAB ;ENTRY POINT FOR LAB DATA EXTRACT
 ;W "**ENDTX",!
 ;NEED VARIABLE TEST DEFINED
 I $D(TESTIN)=0 Q
 S TEST=TESTIN ;SET BACK TO START VALUE
 S CNTTEST=0 K RECX
 I $D(DFN)=0 Q  ;NEED PATIENT
 S FLAGGOT=0 I $D(PCNT)=0 S PCNT=0 ;NEED TO SEE IF WE GOT A HIT
 I $D(^DPT(DFN,"LR"))=0 Q  ;NO LAB DATA
LABX ;GET KB name and all related fields SODIUM, SODIUM(cx-7) etc
 ;S TEST="SODIUM%"
 S GETOUT=0
 S TESTN=$E(TEST,1,$L(TEST)-1),TESTCOMP=TEST
 I $E(TEST,$L(TEST))="%" S TESTCOMP=$E(TEST,1,$L(TEST)-1),TESTN=$E(TESTN,1,$L(TESTN)-1)
 F  S TESTN=$O(^ZRKB(TESTN)) Q:TESTN=""!(GETOUT=1)  D LABXX
 I FLAGGOT=1 S PCNT=PCNT+1
 Q
LABXX ; CALL NL Interface to get choices array with data
 ;need Global and sub values
 ;W !,"*TESTN=",TESTN
 I $E(TESTN,1,$L(TESTCOMP))]TESTCOMP S GETOUT=1 Q  ;IN COMBAT-- INR
 I TESTN'[TESTCOMP Q
 ;need Global and sub values
 S TEST=TESTN
 S LRDFN=$G(^DPT(DFN,"LR")),CMD="GATHER",CNT=0,ARG=""
 I LRDFN="" Q  ;Patient doesn't have any lab data
 K CHOICES
 S KB=$G(^ZRKB(TEST,1)) Q:KB=""
 S GLB="^"_$P(KB,"^",5),CHC=""
 S NORMSS=$P(KB,"^",7)_";"_$P(KB,"^",15)_";"_$P(KB,"^",16)
 S SUB1=$P(KB,"^",7),SUB2=$P(KB,"^",15)_";"_$P(KB,"^",16)
 S LABNORM=$O(^LAB(60,"C",NORMSS,""))
 D BLDSUB^ZRESP ;D LABTST^ZRESUTIL
 ;W !,"CNT=",CNT
 I CNT=0 Q
 S FLAGGOT=1
 F I=1:1:CNT D  ;
 .W TABLE_".NAME="_NAME,!
 .W TABLE_".TEST="_TEST,!
 .W TABLE_".TEST_RESULT=",$P(CHOICES(I),"^",2),!
 .W TABLE_".DATE_OF_TEST=",$P(CHOICES(I),"^",3),!
 .S DINUM=$P(CHOICES(I),"^",1),SPECT=$P($G(^LR(LRDFN,SUB1,DINUM,0)),"^",5)
 .S LABINFO=$G(^LAB(60,LABNORM,1,SPECT,0))
 .S SPECTNM=$P($G(^LAB(61,SPECT,0)),"^",1)
 .W TABLE_".SSN=",SSN,!
 .W TABLE_".SPECIMEN_TYPE=",SPECTNM,!
 .S UNITS=$P(LABINFO,"^",7),HI=$P(LABINFO,"^",3),LO=$P(LABINFO,"^",2)
 .W TABLE_".UNITS=",UNITS,!
 .W TABLE_".REFRANGE=",LO,"-",HI,!
 .W "*ENDREC*",!
 Q
ADM ;ADMISSION TABLE
 I $D(^DGPM("APTT1",DFN))=0 Q  ;W !,"NO ADMISSIONS" Q
 S PCNT=PCNT+1
 S ADMDT=0
 F  S ADMDT=$O(^DGPM("APTT1",DFN,ADMDT)) Q:ADMDT=""  D ADMX ;
 Q
ADMX ;
 ;W !,"** ADMDT=",ADMDT
 S DAPM=0
 F  S DAPM=$O(^DGPM("APTT1",DFN,ADMDT,DAPM)) Q:DAPM'>0  D ADMXX ;DAPM INT PATIENT MOVMT NUMBER
 Q
ADMXX ;CONTINUE LOOP
 ;W !,"ADMDR=",ADMDT," ","DAPM=",DAPM
 S MOVDATA=$G(^DGPM(DAPM,0))
 S TXACT=$P(MOVDATA,"^",2)
 I TXACT=1 S TXACTN="ADMISSION"
 I TXACT=3 S TXACTN="DISCHARGE"
 ;W !,"MOVDATA=",$P(MOVDATA,"^",1)
 S DISDA=$P(MOVDATA,"^",17)
 D ICD
 S DISDT="" I DISDA]"" S DISDT=$P($G(^DGPM(DISDA,0)),"^",1)
 ;W !,"DISDT=",DISDT
 S DIAGSHORT=$P($G(^DGPM(DAPM,0)),"^",10)
ADMYY S X=ADMDT D DTC S ADMDTX=DTXX
 ;W "**BEG TX:ADMISSION_UD",!
 W TABLE_".NAME=",NAME,!
 W TABLE_".SSN=",SSN,!
 W TABLE_".ADMISSION_DATE=",ADMDTX,!
 S X=DISDT D DTC S DISCHDT=DTXX
 W TABLE_".DISCHARGE_DATE=",DISCHDT,!
 W TABLE_".DIAGSHORT=",DIAGSHORT,!
 W TABLE_".ICD9_NAME1=",ICD1DES,!
 W TABLE_".ICD9_NUM1=",ICD1N,!
 W TABLE_".ICD9_DRG1=",ICD1DRG,!
 W TABLE_".ICD9_NAME2=",ICD2DES,!
 W TABLE_".ICD9_NUM2=",ICD2N,!
 W TABLE_".ICD9_DRG2=",ICD2DRG,!
 W TABLE_".ICD9_NAME3=",ICD3DES,!
 W TABLE_".ICD9_NUM3=",ICD3N,!
 W TABLE_".ICD9_DRG3=",ICD3DRG,!
 W "*ENDREC*",!
 Q
MED ;MEDICATION PROFILE *****
 S MD=0,ANS="",MEDCNT=0
 I $D(^PS(55,DFN,"P","A"))=0 Q  ;W !,"No medication indicated..." q
 F  S MD=$O(^PS(55,DFN,"P",MD)) Q:MD'>0  S RX=^(MD,0) D RXGET I $D(ANYFL) Q
 I MEDCNT>0 S FLAGGOT=1,PCNT=PCNT+1
 I MEDCNT=0 Q  ;W !,"No active medications!" H 1 Q
 Q
RXGET ;
STAT ;
 S RX2=$G(^PSRX(RX,2)),RX0=$G(^PSRX(RX,0))
 S ST0=$P(RX0,"^",15)
 I ST0<12,$O(^PS(52.5,"B",RX,0)),$D(^PS(52.5,+$O(^(0)),0)),'$D(^("P")) S ST0=5
 I ST0<12&(DT>$P(RX2,"^",6)) S ST0=11
 S ST=$P("ERROR^ACTIVE^NON-VERIFIED^REFILL FILL^HOLD^^SUSPENDED^^^^^DONE^EXPIRED^CANCELLED","^",ST0+2) ;,$P(RX0,"^",15)=ST0
 I ST'="ACTIVE" Q
 S MEDCNT=MEDCNT+1
 S RX0=$G(^PSRX(RX,0)),Y=$P(RX0,"^",13) X ^DD("DD")
 S DRNUM=$P(RX0,"^",4),DRUGNUM=$P(RX0,"^",6),SIG=$P(RX0,"^",10)
 S DRNAME="" I DRNUM'="" S DRNAME=$P($G(^DIC(16,DRNUM,0)),"^",1)
 S QTY=$P(RX0,"^",7),DAYSUP=$P(RX0,"^",8),NUMREF=$P(RX0,"^",9)
RX S DRUGNAME="" I DRUGNUM'="" S DRUGNAME=$P($G(^PSDRUG(DRUGNUM,0)),"^",1) D  ;
 .W TABLE_".SSN=",SSN,!
 .W TABLE_".NAME=",NAME,!
 .W TABLE_".RX=",$P(RX0,"^",1),!
 .W TABLE_".DATE=",Y,!
 .W TABLE_".DR=",DRNAME,!
 .W TABLE_".SIG=",SIG,!
 .W TABLE_".DRUG=",DRUGNAME,!
 .W TABLE_".QUANTITY=",QTY,!
 .W TABLE_".DAYS_SUPPLY=",DAYSUP,!
 .W TABLE_".NUMBER_REFILLS=",NUMREF,!
 .W TABLE_".STATUS=",ST,!
 .W "*ENDREC*",!
 Q
GETFM ;GET FILEMAN DATA
 ;NEED DIQ,DA,DR FOR SUBFILE Need DR(SUbfile), DA(subfile)
 ;S FILENUM=DIC
 S DIQ="ANS",DIQ(0)="E" ;EXTERNAL VALUES
 D EN^DIQ1 S ANS=ANS(FILENUM,DA,DR,"E")
 Q
DTC ;DATE CONV
 S YR=$E(X,2,3),MO=$E(X,4,5),DAY=$E(X,6,7)
 S DTXX=MO_"/"_DAY_"/"_YR
 ;W "DTXX=",DTXX
 Q
ICD ;pulls ICD code info
 S ICD1DES="",ICD1N="",ICD1DRG="",ICD2DES=""
 S ICD2N="",ICD2DRG="",ICD3N="",ICD3DES="",ICD3DRG=""
 S PTF=$P($G(^DGPM(DAPM,0)),U,16)
 Q:PTF=""  ;PTF INTERNAL NUMBER
 S INC=0
 F  S INC=$O(^DGPT(PTF,"M",INC)) Q:+INC=0  D PTFX ;
 Q
PTFX ;
 S ICD1=$P($G(^DGPT(PTF,"M",INC,0)),"^",5)
 S ICD2=$P($G(^DGPT(PTF,"M",INC,0)),"^",6)
 S ICD3=$P($G(^DGPT(PTF,"M",INC,0)),"^",7)
 I ICD1]"" S ICD1N=$P($G(^ICD9(ICD1,0)),"^",1),ICD1DES=$P($G(^ICD9(ICD1,0)),"^",3)
 I ICD1]"" S ICD1DRG=$G(^ICD9(ICD1,"DRG"))
 I ICD2]"" S ICD2N=$P($G(^ICD9(ICD2,0)),"^",1),ICD2DES=$P($G(^ICD9(ICD2,0)),"^",3)
 I ICD2]"" S ICD2DRG=$G(^ICD9(ICD2,"DRG"))
 I ICD3]"" S ICD3N=$P($G(^ICD9(ICD3,0)),"^",1),ICD3DES=$P($G(^ICD9(ICD3,0)),"^",3)
 I ICD3]"" S ICD3DRG=$G(ICD9(ICD3,"DRG"))
 Q
APPT ;APPOINTMENT FUNCTION
 ;NOOP
 Q
