ZZBATH ; ;= [ 01/02/96  10:21 AM ]
 S DUZ=.5,XMDUZ=DUZ
 K M,N,CNT,JAS
 F I=0:1:21 S CNT(I)=0,TOT(I)=0
 S IOP="HOME" D ^%ZIS
 S N=0,U="^"
 S M=$O(^%ZTSK(N)) D EVAL
AGAIN G:$O(^%ZTSK(M))="" QUIT S M=$O(^%ZTSK(M)) D EVAL
 G AGAIN
QUIT ;
 ; THIS IS THE ARE WHERE THE MAIL MESSAGE IS PUT TOGETHER.
 ;
 S JAS(1)="Type               Description                                    Killed    Tot"
 S JAS(2)=" 0 INCOMPLETED OR STILL BEING CREATED TASKS                          "_CNT(2)_"       "_TOT(0)
 S JAS(3)=" 1 SCH FOR A DATE/TIME OR STOPPED IRR WHILE SCHEDULED TASKS          "_CNT(3)_"       "_TOT(1)
 S JAS(4)=" 2 BEING INSPECTED BY TASK MANAGER TASKS                             "_CNT(4)_"       "_TOT(2)
 S JAS(5)=" 3 WAIT FOR PART OR STOP IRR WHILE WAITING FOR A PARTITION TASKS     "_CNT(5)_"       "_TOT(3)
 S JAS(6)=" 4 BEING PREPARED TASKS                                              "_CNT(6)_"       "_TOT(4)
 S JAS(7)=" 5 CURRENTLY RUNNING STARTED RUNNING DATE/TIME STOPPED IRR TASKS     "_CNT(7)_"       "_TOT(5)
 S JAS(8)=" 6 COMPLETED TASK                                                    "_CNT(8)_"       "_TOT(6)
 S JAS(9)=" A WAITING DEVICE HUNT GROUP STOPPED WAITING FOR DEVICE TASKS        "_CNT(9)_"       "_TOT(7)
 S JAS(10)=" B REJECTED AND REJECTION MESSAGE TASKS                              "_CNT(10)_"       "_TOT(8)
 S JAS(11)=" C ERROR DATE/TIME AND ERROR MESSAGE TASKS                           "_CNT(11)_"       "_TOT(9)
 S JAS(12)=" D STOPPED BY USER TASKS                                             "_CNT(12)_"       "_TOT(10)
 S JAS(13)=" E INTERRUPTED WHILE RUNNING TASKS                                   "_CNT(13)_"       "_TOT(11)
 S JAS(14)=" F UNSCHEDULED BY SOMEONE TASKS                                      "_CNT(14)_"       "_TOT(12)
 S JAS(15)=" G WAITING FOR THE LINK TO VOLUME SET TO BE RESTORED TASKS           "_CNT(15)_"       "_TOT(13)
 S JAS(16)=" H EDITED WITHOUT BEING SCHEDULED TASKS                              "_CNT(16)_"       "_TOT(14)
 S JAS(17)=" I DISCARDED BY TASK MANAGER BECAUSE ITS RECORD WAS INCOMPLETE       "_CNT(17)_"       "_TOT(15)
 S JAS(18)=" J CURRENTLY BEING EDITED TASKS                                      "_CNT(18)_"       "_TOT(16)
 S JAS(19)=" K CREATED WITHOUT BEING SCHEDULED TASKS                             "_CNT(19)_"       "_TOT(17)
 S JAS(20)=" L PREPARING THIS TASK CAUSED THE SUBMANAGER AND ERROR TASKS         "_CNT(20)_"       "_TOT(18)
 S JAS(21)=" M WAITING FOR A PARTITION ON A COMPUTE SERVER TASKS                 "_CNT(21)_"       "_TOT(19)
 ;
 ; CHANGE THE VALUE IN THE XMY ARRAY TO THE DUZ OF THE PERSON YOU WANT TO RECEIVE THE
 ; MESSAGE.  YOU CAN HAVE MULTIPLE XMY(DUZ'S)
 ; JUST S XMY(.5)="",XMY(900)="",XMY(3)=""  AS AN EXAMPLE
 ; THEN EACH ONE OF THESE USERS WILL RECEIVE THE MESSAGE.
 ; CURRENT THE POSTMASTER (.5) WILL BE THE ONLY RECEIPIENT.
 ;
 S XMSUB="Clean TaskMan Log",XMY(.5)="",XMTEXT="JAS("
 D ^XMD
 K M,N,CNT,JAS,TOT
 Q
EVAL ;
 ; THIS LINE OF CODE ALLOWS FOR THE CLEANING UP OF THE %ZTSCH($H,TASK) NODE
 I '$D(^%ZTSK(M,0)) K ^%ZTSK(M,0) Q
 S VAL=$P(^%ZTSK(M,.1),"^",1) S %=$P(^%ZTSK(M,0),"^",6) S Y=$$H3(%)
 ; END OF COMMENT
 ;
 ;  THIS IS THE CODE TO UNCOMMENT FOR THE DIFFERENT TYPES OF TASKS TO BE CLEANED FROM %ZTSK
 ;  A LIST OF THE THE DIFFERENT TYPES IS INCLUDED AT THE END OF THIS PROGRAM
 ;
 ;I VAL="0" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(2)=CNT(2)+1
 ;I VAL="1" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(3)=CNT(3)+1
 ;I VAL="2" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(4)=CNT(4)+1
 ;I VAL="3" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(5)=CNT(5)+1
 ;I VAL="4" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(6)=CNT(6)+1
 ;I VAL="5" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(7)=CNT(7)+1
 I VAL="6" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(8)=CNT(8)+1
 ;I VAL="A" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(9)=CNT(9)+1
 I VAL="B" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(10)=CNT(10)+1
 ;I VAL="C" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(11)=CNT(11)+1
 ;I VAL="D" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(12)=CNT(12)+1
 I VAL="E" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(13)=CNT(13)+1
 ;I VAL="F" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(14)=CNT(14)+1
 ;I VAL="G" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(15)=CNT(15)+1
 ;I VAL="H" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(16)=CNT(16)+1
 ;I VAL="I" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(17)=CNT(17)+1
 ;I VAL="J" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(18)=CNT(18)+1
 ;I VAL="K" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(19)=CNT(19)+1
 ;I VAL="L" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(20)=CNT(20)+1
 ;I VAL="M" K ^%ZTSK(M),^%ZTSCH(Y,M) S CNT(21)=CNT(21)+1
 ;
 ; HERE I AM COUNTING THE NUMBER OF TASKS OF EACH TYPE REGUARDLESS OF WHERE IT IS SELECTED OR
 ; NOT.  THIS WILL BE INCLUDED IN THE MAIL MESSAGE SO YOU CAN SEE JUST HOW MANY DIFFERENT
 ; TASKS TYPES ARE ON YOUR SYSTEM.
 ;
 I VAL="0" S TOT(0)=TOT(0)+1
 I VAL="1" S TOT(1)=TOT(1)+1
 I VAL="2" S TOT(2)=TOT(2)+1
 I VAL="3" S TOT(3)=TOT(3)+1
 I VAL="4" S TOT(4)=TOT(4)+1 
 I VAL="5" S TOT(5)=TOT(5)+1
 I VAL="6" S TOT(6)=TOT(6)+1
 I VAL="A" S TOT(7)=TOT(7)+1
 I VAL="B" S TOT(8)=TOT(8)+1
 I VAL="C" S TOT(9)=TOT(9)+1
 I VAL="D" S TOT(10)=TOT(10)+1
 I VAL="E" S TOT(11)=TOT(11)+1
 I VAL="F" S TOT(12)=TOT(12)+1
 I VAL="G" S TOT(13)=TOT(13)+1
 I VAL="H" S TOT(14)=TOT(14)+1
 I VAL="I" S TOT(15)=TOT(15)+1
 I VAL="J" S TOT(16)=TOT(16)+1
 I VAL="K" S TOT(17)=TOT(17)+1
 I VAL="L" S TOT(18)=TOT(18)+1
 I VAL="M" S TOT(19)=TOT(19)+1
 Q
H3(%) ;Convert $H to seconds.
 Q 86400*%+$P(%,",",2)
 Q
0 ;;INCOMPLETED OR STILL BEING CREATED
1 ;;SCH FOR A DATE/TIME OR STOPPED IRR WHILE SCHEDULED
2 ;;BEING INSPECTED BY TASK MANAGER
3 ;;WAIT FOR PART OR STOP IRR WHILE WAITING FOR A PARTITION
4 ;;BEING PREPARED
5 ;;CURRENTLY RUNNING STARTED RUNNING DATE/TIME STOPPED IRR
6 ;;COMPLETED
A ;;WAITING DEVICE HUNT GROUP STOPPED WAITING FOR DEVICE
B ;;REJECTED AND REJECTION MESSAGE
C ;;ERROR DATE/TIME AND ERROR MESSAGE
D ;;STOPPED BY USER
E ;;INTERRUPTED WHILE RUNNING
F ;;UNSCHEDULED BY SOMEONE
G ;;WAITING FOR THE LINK TO VOLUME SET TO BE RESTORED
H ;;EDITED WITHOUT BEING SCHEDULED
I ;;DISCARDED BY TASK MANAGER BECAUSE ITS RECORD WAS INCOMPLETE
J ;;CURRENTLY BEING EDITED
K ;;CREATED WITHOUT BEING SCHEDULED
L ;;PREPARING THIS TASK CAUSED THE SUBMANAGER AND ERROR
M ;;WAITING FOR A PARTITION ON A COMPUTE SERVER
