ZZDSDIB ;ISC-A CHECK FOR RX EXEMPT ENTIRIES
 S IBCONVER=1,DFN=0
 F  S DFN=$O(^IBA(354,DFN,0)) Q:'DFN  I $P(^IBA(354,DFN,0),"^",3)="" D
 . S X=$$RXEXMT^IBARXEU0(DFN,DT)
 . W !,"Patient: ",DFN," - ",$P(^DPT(DFN,0),"^")," EXEMPTION UPDATED. "
 Q
