ZZGEBLDG ;BUILDS A GLOBAL TO BE USED IN MY TESTING AND RESEARCHORD
 ;COMMENTS
SETUP ;
 S STRT="^" W !,"START BUILDING PEOPLE GLOBALWITH SSN NUMBER: " R STRT:DTIME
 D BGLOB
BGLOB ;
 W !," ALL DONE - COMPLETE!!"
 Q
