A1BFLOG ;ALBANY ISC;ECF;17MAR92;13:10pm [ 03/19/93  1:49 PM ]
 ;;	V1.0
EN ;Logon routine
 K A1BFOUCH
 D SETUP
 D OPEN I I>4 D NOPEN G EXIT
 D LOOP I A1BFOUCH G EXIT
 D POST
 D EXIT Q
SETUP ;
 S A1BFDEV=100
 S A1BFACC="TIEDRTM",A1BFVER="TIEDRTM",A1BFREAD="READ",A1BFBASK="TST",A1BFONE="1",A1BFCR="$C(13)"
 S U="^" D ^%GUCI S A1BFUVOL=%UCI,A1BFUCI=$P(A1BFUVOL,",",1),A1BFVOL=$P(A1BFUVOL,",",2)
 S A1BFBASK="TST"
 S $P(A1BFX,"X",35)="X"
 Q
OPEN ;
 ;S A1BFDEV=$P(^%ZIS(1,A1BFDEV,0),U,1)
 F I=1:1:5 S %ZIS=0,IOP=A1BFDEV D ^%ZIS Q:'POP  HANG 10
 U IO(0) W !,"DEVICE LOOKS OPEN"
 U 100 X ^%ZOSF("EOFF"),^%ZOSF("TYPE-AHEAD") S X=80 X ^%ZOSF("RM")
 Q
LOOP ;
 S A1BFSTRT=$H,A1BFOUCH=0
 F I=1:1:10 S A1BFTXT=$T(TEXT+I) Q:A1BFTXT=""  D  I A1BFOUCH D NOREAD Q
 .S A1BFPRMT=$P(A1BFTXT,";",3),A1BFRESP=$P(A1BFTXT,";",4),A1BFRESP=@(A1BFRESP)
 .U IO(0) W !,"JUST SET PROMPT = ",A1BFPRMT," ANSWER = ",A1BFRESP,!
 .D READ I A1BFOUCH U IO(0) W !,"OUCH = ",A1BFOUCH Q
 S A1BFSTPT=$H
 Q
READ ;
 U IO(0) W !,"STARTING READ",!
 S A1BFOUCH=0,A1BFARR=$E(A1BFX,1,$L(A1BFPRMT))
 F J=1:1:75000 U 100:(::1) R *X:1 IF  S:X>0 A1BFARR=$E(A1BFARR,2,$L(A1BFPRMT))_$C(X) U IO(0) W X,"-",$C(X),"=" I A1BFARR=A1BFPRMT U IO(0) W !,"MATCH",! Q
 ;U IO:(::1) R *X IF X=10 U IO(0) W !,"GOT THE CR"
 I J>74999 S A1BFOUCH=$P(A1BFTXT,";",5) Q
SEND ;
 U IO(0) W !!,"GOING TO SEND RESPONSE"
 F L=1:1:$L(A1BFRESP) U 100 W $E(A1BFRESP,L) U IO(0) W $E(A1BFRESP,L),"*"
 U 100 W $C(13)
 U IO(0) W !,"SENT CR"
 Q
POST ;
 Q
EXIT ;
 Q
NOREAD ;
 Q
TEXT ;
 ;;ACCESS CODE:;A1BFACC;ACCESS CODE
 ;;VERIFY CODE:;A1BFVER;VERIFY CODE
 ;;Select TERMINAL TYPE NAME: C-VT220 //;A1BFCR;Terminal Type Prompt
 ;;Select MailMan Menu Option: ;A1BFREAD;MailMan Prompt
 ;;Read Mail Basket: IN// ;A1BFBASK;Basket Select Prompt
 ;;A1BFBASK_" Basket Message: 1// ";A1BFONE;Message Number Prompt
 ;;Select Mailman Option: ;A1BFCR;Close MailMan Menu
 ;;Do you really want to halt? YES//;"YES";Halt Prompt
