ZZTSET7C        ;ciofo-scramble patient data (cont) ;10/1/97
 ;;1.0;
 ;
 ; original concept/code taken from ZDWGTDM1 (author unknown)
 ;
 N ZZDATA
 S ZZDATA=$G(^DPT(DA,.21))
 I ZZDATA'="" D
 .S FNAME=""
 .I $S($P(ZZDATA,U,2)["WIFE":1,$P(ZZDATA,U,2)["SPOUSE":1,$P(ZZDATA,U,2)["MOTHER":1,$P(ZZDATA,U,2)["MOM":1,1:0) D
 ..S RND=$R(15)+1
 ..S LIN=$R(NFN)+1
 ..S FNAME=$P(^TMP($J,"FENAME",LIN),U,RND)
 ..S LNAME=$P($P(^DPT(DA,0),U,1),",",1)
 .I $S($P(ZZDATA,U,2)["SISTER":1,$P(ZZDATA,U,2)["DAU":1,$P(ZZDATA,U,2)["NIECE":1,$P(ZZDATA,U,2)["GIRL":1,1:0) D
 ..S RND=$R(15)+1
 ..S LIN=$R(NFN)+1
 ..S FNAME=$P(^TMP($J,"FENAME",LIN),U,RND)
 ..S RND=$R(15)+1
 ..S LIN=$R(20)+1
 ..S LNAME=$P(^TMP($J,"LNAME",LIN),U,RND)
 .I $S($P(ZZDATA,U,2)["HUSBAND":1,1:0) D
 ..S RND=$R(15)+1
 ..S LIN=$R(NMN)+1
 ..S FNAME=$P(^TMP($J,"FNAME",LIN),U,RND)
 ..S LNAME=$P($P(^DPT(DA,0),U,1),",",1)
 .I $S($P(ZZDATA,U,2)["FATHER":1,$P(ZZDATA,U,2)["BROTHER":1,$P(ZZDATA,U,2)["SON":1,1:0) D
 ..S RND=$R(15)+1
 ..S LIN=$R(NMN)+1
 ..S FNAME=$P(^TMP($J,"FNAME",LIN),U,RND)
 ..S LNAME=$P($P(^DPT(DA,0),U,1),",",1)
 .I FNAME="" D
 ..S RND=$R(15)+1
 ..S LIN=$R(NMN)+1
 ..S FNAME=$P(^TMP($J,"FNAME",LIN),U,RND)
 ..S RND=$R(15)+1
 ..S LIN=$R(89)+1
 ..S LNAME=$P(^TMP($J,"LNAME",LIN),U,RND)
 .S NNAME=FNAME_" "_LNAME
 .I $P(ZZDATA,U,1)]"" S $P(ZZDATA,U,1)=NNAME
 .I $P(ZZDATA,U,6)]"" S $P(ZZDATA,U,6)=NCITY
 .I $P(ZZDATA,U,7)]"" S $P(ZZDATA,U,7)=NSTATE
 .I $P(ZZDATA,U,8)]"" S Y=$P(ZZDATA,U,8) D SCRAM S $P(ZZDATA,U,8)=X
 .I $P(ZZDATA,U,9)]"" D PHONE S $P(ZZDATA,U,9)=X
 .S ^DPT(DA,.21)=ZZDATA
 .K ZZDATA
 ;
 S ZZDATA=$G(^DPT(DA,.211))
 I ZZDATA'="" D
 .S RND=$R(15)+1
 .S LIN=$R(NLN)+1
 .S LNAME=$P(^TMP($J,"LNAME",LIN),U,RND)
 .S RND=$R(15)+1  
 .I $P(ZZDATA,U,1)]"" D
 ..S FNAME=""
 ..S Y=$P(ZZDATA,U,2)
 ..I $S(Y["DAU":1,Y["SISTER":1,Y["NIECE":1,Y["MOTHER":1,Y["WIFE":1,1:"") S LIN=$R(NFN)+1,FNAME=$P(^TMP($J,"FENAME",LIN),U,RND) S:FNAME="" LIN=$R(NMN)+1,FNAME=$P(^TMP($J,"FNAME",LIN),U,RND)
 ..I $P(ZZDATA,U,1)]"" S $P(ZZDATA,U,1)=LNAME_","_FNAME
 ..I $P(ZZDATA,U,6)]"" S $P(ZZDATA,U,6)=NCITY
 ..I $P(ZZDATA,U,7)]"" S $P(ZZDATA,U,7)=NSTATE
 ..I $P(ZZDATA,U,8)]"" S $P(ZZDATA,U,8)=NZIP+$R(100)
 ..I $P(ZZDATA,U,9)]"" D PHONE S $P(ZZDATA,U,9)=X
 .S ^DPT(DA,.211)=ZZDATA
 .K ZZDATA
 ;
 S ZZDATA=$G(^DPT(DA,.25))
 I ZZDATA'="" D
 .I $P(ZZDATA,U,1)]"" S $P(ZZDATA,U,1)=$P("AB DICK^IBM^EATS CAFE^PENNY'S^IRON WORKS INC.^TRUCKING INC.^EAST MED. CENTER^CATERPILLAR^JOHN JONES & SON^SOUTH BANK^FUNPARK INC.^INTERWEST FARMERS^EPX CHEMICAL",U,$R(12)+1) D  
 .I $P(ZZDATA,U,5)]"" S $P(ZZDATA,U,5)=NCITY
 .I $P(ZZDATA,U,6)]"" S $P(ZZDATA,U,6)=NSTATE S:$P(ZZDATA,U,7)]"" $P(ZZDATA,U,7)=NZIP+$R(100)
 .I $P(ZZDATA,U,8)]"" D PHONE S $P(ZZDATA,U,8)=X
 .S ^DPT(DA,.25)=ZZDATA
 .K ZZDATA
 ;
 S ZZDATA=$G(^DPT(DA,.29))
 I $P(ZZDATA,U,4)'="" D
 .S RND=$R(15)+1
 .S LIN=$R(NMN)+1
 .S $P(ZZDATA,U,4)=$P(^TMP($J,"FNAME",LIN),U,RND)  
 .S:$P(ZZDATA,U,8)]"" $P(ZZDATA,U,8)=NCITY
 .S:$P(ZZDATA,U,9)]"" $P(ZZDATA,U,9)=NSTATE
 .S:$P(ZZDATA,U,10)]"" $P(ZZDATA,U,10)=NZIP+$R(100)
 .I $P(ZZDATA,U,11)]"" D PHONE S $P(ZZDATA,U,11)=X
 .S ^DPT(DA,.29)=ZZDATA
 .K ZZDATA
 ;
 S ZZDATA=$G(^DPT(DA,.31))
 I $P(ZZDATA,U,3)'="" D
 .S Y=$P(ZZDATA,U,3) D SCRAM S $P(ZZDATA,U,3)=X
 .S ^DPT(DA,.31)=ZZDATA
 .K ZZDATA
 ;
 S ZZDATA=$G(^DPT(DA,.311))
 I ZZDATA'="" D
 .I $P(ZZDATA,U,1)]"" S $P(ZZDATA,U,1)=$P("DELTA LINES^LEWIS & SON INC.^A&B AUTO^GENERAL MOTORS^ACME INSURANCE^SEARS^SECOND BANK^POP'S GROCERY^BOX CO. INC.^PAPER CO.",U,$R(9)+1)  
 .I $P(ZZDATA,U,6)]"" S $P(ZZDATA,U,6)=NCITY
 .I $P(ZZDATA,U,7)]"" S $P(ZZDATA,U,7)=NSTATE
 .I $P(ZZDATA,U,8)]"" S $P(ZZDATA,U,8)=NZIP+$R(100)
 .I $P(ZZDATA,U,9)]"" D PHONE S $P(ZZDATA,U,9)=X
 .S ^DPT(DA,.311)=ZZDATA
 .K ZZDATA
 ;
 S ZZDATA=$G(^DPT(DA,.312))
 I ZZDATA="" D
 S ZZX=0
 F  S ZZX=$O(^DPT(DA,.312,ZZX)) Q:'ZZX  D
 .S ZZDATA=$G(^DPT(DA,.312,ZZX,0))
 .I $P(ZZDATA,U,2)="" Q
 .S Y=$P(ZZDATA,U,2)
 .D SCRAM
 .S $P(ZZDATA,U,2)=X
 .I $P(ZZDATA,U,12)]"" S $P(ZZDATA,U,12)=NCITY
 .I $P(ZZDATA,U,13)]"" S $P(ZZDATA,U,13)=NSTATE
 .I $P(ZZDATA,U,14)]"" S $P(ZZDATA,U,14)=NZIP+$R(100)
 .I $P(ZZDATA,U,17)]"" S $P(ZZDATA,U,17)=NNAME
 .S ^DPT(DA,.312,ZZX,0)=ZZDATA
 .K ZZDATA
 ;
 S ZZDATA=$G(^DPT(DA,.32))
 I ZZDATA'="" D
 .S Y=$P(ZZDATA,U,8)
 .D SCRAM
 .S $P(ZZDATA,U,8)=X  
 .I $P(ZZDATA,U,13)]"" D
 ..S Y=$P(ZZDATA,U,13)
 ..D SCRAM
 ..S $P(ZZDATA,U,13)=X
 .I $P(ZZDATA,U,18)]"" D
 ..S Y=$P(ZZDATA,U,18)
 ..D SCRAM
 ..S $P(ZZDATA,U,18)=X
 .S ^DPT(DA,.32)=ZZDATA
 .K ZZDATA
 Q
 ;
PHONE S X="(800) "_(100+$R(900))_" "_(1000+$R(9000))
 Q
 ;
SCRAM S X="" 
 F K=1:1:$L(Y) D
 .S ST=$E(Y,K)
 .S X=X_$S(ST?1A:$C(($A(ST)-64+$R(26)#26)+65),ST?1N:$R(9),1:ST)
 Q        
