ZZTSETU3        ;ciofo-set temporary array of last names ;10/1/97
 ;;1.0;test system reset utilities;
 ;
 ; original concept/code taken from ZDWSTNM2 (author unknown)
 ;
 S ^TMP($J,"LNAME",75)="PUSER^HOWA^HOVORKA^HOVLEY^HICKOX^HIGGINSON^HIGBY^HICKOK^HICKMAN^HERNDON^HERRERA^HICKLER^HICKAM^HEYWOOD^HOLBROOK"
 S ^TMP($J,"LNAME",76)="PLOTT^PLEWE^POMEROY^POLSON^POMA^PEDLER^PENNA^PEEL^PRICHARD^PASSMAN^PARKS^PRINGLE^POWELSON^PRIGLE^PRESCOTT"
 S ^TMP($J,"LNAME",77)="QUAAL^QUACKENBUSH^RAINEY^QUINTERO^QUILLIN^RODERIK^ROBBS^QUIGLEY^QUIST^QUINTANS^QUINTINA^QUALEY^RAHMAN^QUEACUT^QUIRIN"
 S ^TMP($J,"LNAME",78)="URIBE^UECKER^UEDA^ULBRICH^ULIBARRI^ULLAND^USTRELL^ULRICH^UNDERWOOD^UNSELD^UPTON^URNESS^UREN^UTLEY^UTTER"
 S ^TMP($J,"LNAME",79)="XAIZ^XANOS^XANTHOS^XIQUES^XIRAS^ZANOLLI^ZAMBOS^ZABA^ZACHMAN^ZAVALA^ZEDAN^ZECCA^ZEIGLER^ZEISLER^ZEYER"
 S ^TMP($J,"LNAME",80)="NOWAK^NORTZ^NOSACK^NOSS^NOWERS^NOWELS^NYDAM^NYE^NUNN^NYGAARD^NOVELL^NOSKER^NOVAK^NUPERT^NURMI"
 S ^TMP($J,"LNAME",81)="OAR^OBERLIN^OBERST^OBLAD^OBORN^OCASIO^OCHOA^OCKEY^OCKLER^OCONNELL^ODAY^ODELL^ODERMAN^ODLAND^ODLE"
 S ^TMP($J,"LNAME",82)="OHRN^OKUDA^OLIN^OLEEN^OLAIZ^OLAFSSON^OOLEY^OLSCHEWSKI^ONION^ONO^ONSTOTT^OPENSHAW^ORCHARD^ORBIN^ORD"
 S ^TMP($J,"LNAME",83)="ORCUTT^PARISH^PARKEN^PAPPAS^PAPKE^BAUCOM^BAUMAN^AGRAZ^ADRION^AEBIG^AFFLECK^AGNOLI^AGRAZ^BARNECK^BANNER"
 S ^TMP($J,"LNAME",84)="POTHEN^BERNTSEN^KAUFMAN^GRAGG^REICHEL^TANG^BROUGHN^MORSE^AMOS^GARBOW^LYNESS^TINGY^CATTELL^GENZ^KAPER"
 S ^TMP($J,"LNAME",84)="BIRCHER^DIKIN^COLES^KECK^JESPERSEN^BAUER^BAHR^LANE^KIRKPATRIK^HENDRICKS^WARTHEN^GROSS^MANCHESTER^SPRAGUE^WILLIAMS"
 S ^TMP($J,"LNAME",85)="GRAHAM^WALLISCH^MOUNTAIN^HAWORTH^KODALEN^MOHRLANG^LANKFORD^TUTTLE^BRANAM^FLETCHER^DALY^SYLVESTER^FEASTER^BATEMEN^GORMAN"
 S ^TMP($J,"LNAME",86)="REINKING^TAUTGES^REYNOLDS^FOUTS^GLADSON^FEENEY^SEEHAN^MATLOCK^MUNOZ^GATES^SPILLDNER^SCHMIDT^RIVERA^RYFF^BOGGES"
 S ^TMP($J,"LNAME",87)="GALBAUGH^PACHECO^MORVILLO^BOYLE^DISER^CHITWOOD^DUGDALE^STUGELMAYER^RENTER^ROHRICK^FEGLER^HARDEE^ROTHBART^KISSINGER^JENSEN"
 S ^TMP($J,"LNAME",88)="SADLER^GOODWIN^GENTSCH^BISSELL^MOMAN^STUCKEY^SCHLATTER^SHATTNER^NIMOY^LOOKINGCLOUD^SHIERS^SKINNER^PENA^SAATHOFF^NEWMAN"
 S ^TMP($J,"LNAME",89)="INSKIP^DAVIS^DUGGAN^CONNERY^LYONS^TANNENBAUM^ARINA^DOXEY^PARAS^JOSEPHSON^LAPIERE^HESTON^ERRHART^DARWEN^NORTH"
 S ^TMP($J,"LNAME",90)="CLAYTON^ANDREWS^BURT^GOTTS^MALMROSE^FILMORE^TUCKER^SEEGER^WIGGINS^HUMPHREYS^HENDRY^FROMATTER^EBERT^BENDIX"
 S ^TMP($J,"LNAME",91)="BENTSON^LITTLEFIELD^DANGERFIELD^BROOKS^BOONE^NEWSON^WALKER^WIMMER^JORDAN^LENON^HARRISON^STARR^FORD^HUDSON^HIGLEY"
 S ^TMP($J,"LNAME",92)="SANCHEZ^CHAUVEZ^SANTANA^SAVANT^ROCKWELL^SPANGLER^WOOLEY^LINCOLN^HAYES^RUTHERFORD^HANDLEY^HELMSLEY^HERSHY^HEUBNER^HIMMLER"
 S ^TMP($J,"LNAME",93)="WALLACH^KESTLER^ZALEWSKI^MALDIN^DOUGLAS^SCHWARTZNEGER^STEVENSON^MUDD^BROKAW^CURTIN^PAULEY^PULLEY^PULSIFER^VAN BUREN^TILLOTSON"
 Q
