ZZTSETU4        ;ciofo-set temporary array of female first names ;10/1/97
 ;;1.0;test system reset utilities;
 ;
 ; original concept/code taken from ZDWFENAM (author unknown)
 ;
 S ^TMP($J,"FENAME",1)="JANET^IRENE^GERALDINE^GENEVA^MILDRED^LYNN^JUDY^KERRI^SHELLY^BIRGITTA^JODI^CAROL^CHRISTINE^CHRIS^SHARYL"
 S ^TMP($J,"FENAME",2)="OLGA^MINDY^TERRI^NANCY^BO^DEE DEE^JOY^VERA^MONICA^LINDA^MARTHA^LONNY^MAUREEN^SANDE^SUSAN"
 S ^TMP($J,"FENAME",3)="TWILA^LORI^LOREEN^JANA^IRMA^MELANIE^LEANNA^LYN^CORINA^VONDA^IDA^KIMBERLY^DEE ANN^EVA^EVE"
 S ^TMP($J,"FENAME",4)="SALLY^MICHELLE^KATHRYN^JULIE"
 S ^TMP($J,"FENAME",5)="ELIZABETH^JODY^MELINDA^MISTY^MARILYN^OPAL^REBECCA^LISA^MARINA^MARJORIE^MAUD^ORLA^ZEANA^MAE^MERNA"
 S ^TMP($J,"FENAME",6)="DEBBIE^TRACY^FRANCIS^CAROLYN^JADIE^SUZANNE^EMILY^LINDSEY^LAREE^ROSALIE^DARCIE^TRACIE^STACY^CHERYL^MELISSA"
 S ^TMP($J,"FENAME",7)="ANITA^VIRGINIA^ALISHA^TEVITA^DEBORAH^SHERRY^BECKY^JOHANNA^CLAUDIA^JAIME^CYNTHIA^BETTY^ALEXIS^RHEA^JAYNE"
 S ^TMP($J,"FENAME",8)="GEORGINIA^BILLIE^BRITT^PAMELA^LOIS^DONNA^MERL^IONA^KRISTEN^MABEL^MAREN^RUBY^MARCI^SAUNDRA^SHIRLEY"
 S ^TMP($J,"FENAME",9)="TERESA^JOAN^TERRIE^MADELYN^REGINA^ANN MARIE^ANGIE^LESLIE^LAUREL^LEONA^MARGIE^MARGARITA^DARLENE^HEILA^ROXANA"
 S ^TMP($J,"FENAME",10)="JANICE^JEAN^JEANENE^JACQUE^JACKY^PAULA^RACHELLE^VIVIAN^BEVERLY^CHRISSA^CHRYSTA^CLAIR^CLARA^JENNIFER^BRENDA"
 S ^TMP($J,"FENAME",11)="THELMA^EDNA^MOLLY^TOMI^DELLA^ILEEN^FRANKIE^SHARON^DONETTA^CORRINE^MARGARET^EVELYN^BARBARA^LAVETTA^ROSE"
 S ^TMP($J,"FENAME",12)="GRACE^LILLION^ETHEL^GAYLE^AUDREY^JOLENE^LILLY^DOROTHY^EUNICE^RUTH^EDRA^ELLINOR^ERIS^TANA^MARLENE"
 S ^TMP($J,"FENAME",13)="GERTRUDE^LARITA^PATRICE^PATRICA^MATTIE^GINGER^SHANA^TRICIA^DELORES^URSULA^LAVANDA^CARRIE^HAZEL^HEANETTE^RAMONA"
 S ^TMP($J,"FENAME",14)="JONI^CATHERINE^AGNES^BONNIE^CONNIE^JOSEPHINE^HEIDE^JAUNITA^CARMEN^PATTI^VELMA^LOUISE^ROSEMARY^SHALEEN^ARLENE"
 S ^TMP($J,"FENAME",15)="LONIE^NAOMI^WINONA^LUCY^VERONICA^JENNIE^JOYCE^VICKI^HARIETT^RUTHANNE^GENEVIEVE^ELENOR^SANDY^VERLYNN^JACKIE"
 S ^TMP($J,"FENAME",16)="OPHELIA^ADELA^ROBERTA^JOREENE^MARCIA^PAULINE^MYRTLE^TIRA^EMMA^HARRIOTT^ELSIE^HILLARY^LORRI^TAMMARA^HILDA"
 S ^TMP($J,"FENAME",17)="PEARL^FARA^DEVONNA^MARSHA^PENNY^ELAINE^VALENE^WENDY^PATSY^BETH^KATHLEEN^AMY^MELODI^JANEAL^HOLLY"
 S ^TMP($J,"FENAME",18)="HENRIETTA^MABYL^MADONNA^KAY^WILMA^BERNEDETTE^CRYSTAL^FLORENCE^TAMMY^FAYE^FANNY^SUZZIE^NADEEN^URSLA^PERSYLLA"
 S ^TMP($J,"FENAME",19)="MADDY^YOLINDA^MAY^NOREEN^VALERIE^LINDSY^FELICA^HERTHA^CANDY^COLLEEN^APRIL^CHERRY^OLIVIA^ELENORE^AMELIA"
 S ^TMP($J,"FENAME",20)="CINDY^DELILAH^ANNETTE^JILL^JULIA^CANDICE^MAURINE^GIGI^ALLISON^MARLENA^ROXANNE^ROSEANNE^SADIE^ELLEN^EILEEN"
 S ^TMP($J,"FENAME",21)="NILA^SHIELA^SONYA^MELODY^CONSTANCE^FELICIA^GEORGIA^JANETTE^LOU ANNE^LOLA^NOLA^TANYA^SHASHA^GAIL^LORAINE"
 S ^TMP($J,"FENAME",22)="TRUDY^COLISTA^JOYLENE^DEANN^DELORIS^ABIGALE^CAROLINE^HELEN^PAULENE^PENELOPE^ANDREA^HOPE^ALEXANDREA^ARVILLA^KITTY"
 S ^TMP($J,"FENAME",23)="CORNELIA^NELLIE^OPHILIA^FELINA^OLIVE^POLLY^LORETTA^CLAUDETTE^COLETTE^DAWN^HARIETTE^DOLLIE^ALBERTA^BURNEDETTE^BLANCH"
 Q
