DVBAUDDIQ ;ALB/CP - FM GETS^DIQ API Subroutine Calls ; 4/12/18 7:09pm
 ;;2.7;AMIE;**256**;;Build 19
 ; Per VHA Directive 6402 this routine should not be modified
 ;     $$GET1^DIQ      ; # 2056
 ;       GETS^DIQ      ; # 2056
 Q
 ;
EVENT(DVBIENEVENT) ; Retrieve fields from AMIE OPTION AUDIT EVENT file
 ;
 N DVBIENS,DVBDATA,DVBERRMSG
 ; ZEXCEPT: DVBEVENT,DVBQUIT
 ;
 K DVBEVENT ; Refresh output array
 S DVBQUIT=0 ; Indicates a successful data retrieval
 ;
 S DVBIENS=+$G(DVBIENEVENT)_","
 D GETS^DIQ(396.999,DVBIENS,"*","IE","DVBDATA","DVBERRMSG") ; EVENT rec
 D DIERR^DVBAUDDILG1(60,5,"DVBERRMSG","EVENT^"_$T(+0)) Q:DVBQUIT
 ;
 S DVBEVENT("DVBIENEVENT")=DVBIENEVENT
 S DVBEVENT("DTEVENT")=DVBDATA(396.999,DVBIENS,.01,"E") ;.. E-DATE/TIME
 S DVBEVENT("DTEVENTI")=DVBDATA(396.999,DVBIENS,.01,"I") ;. E-DATE/TIME
 S DVBEVENT("DVBIEN19")=DVBDATA(396.999,DVBIENS,2,"I") ;.......E-OPTION ACCESSED
 S DVBEVENT("OPTNAME")=DVBDATA(396.999,DVBIENS,2,"E") ;.....E-OPTION ACCESSED
 S DVBEVENT("DVBIEN200")=DVBDATA(396.999,DVBIENS,3,"I") ;......E-AUDITED USER
 S DVBEVENT("USERNAME")=DVBDATA(396.999,DVBIENS,3,"E") ;....E-AUDITED USER
 S DVBEVENT("TASKED")=DVBDATA(396.999,DVBIENS,4,"E") ;......E-TASKED AUDIT?
 S DVBEVENT("TASKEDI")=DVBDATA(396.999,DVBIENS,4,"I") ;.....E-TASKED AUDIT?
 S DVBEVENT("$JOB")=DVBDATA(396.999,DVBIENS,5,"E") ;........E-TASK NUMBER
 S DVBEVENT("DTENDED")=DVBDATA(396.999,DVBIENS,6,"E") ;...E-TASK END DATE/TIME
 S DVBEVENT("DTENDEDI")=DVBDATA(396.999,DVBIENS,6,"I") ;..E-TASK END DATE/TIME
 S DVBEVENT("PURGFLG")=DVBDATA(396.999,DVBIENS,7,"E") ;.....E-PURGE FLAG?
 S DVBEVENT("PURGFLGI")=DVBDATA(396.999,DVBIENS,7,"I") ;....E-PURGE FLAG?
 ;
 Q  ; EVENT
 ;
NEWPERS(DVBIEN200) ; Retrieve fields from NEW PERSON file #200
 ;
 N %Y,DVBIENS,DVBDATA,DVBERRMSG
 ; ZEXCEPT: DVBNEWPERS,DVBQUIT
 ;
 K DVBNEWPERS ;Refresh output array
 S DVBQUIT=0 ;. Indicates a successful data retrieval
 ;
 S DVBIENS=+$G(DVBIEN200)_","
 D GETS^DIQ(200,DVBIENS,".01;8;29","IE","DVBDATA","DVBERRMSG")
 D DIERR^DVBAUDDILG1(60,5,"DVBERRMSG","NEWPERS^"_$T(+0)) Q:DVBQUIT
 ;
 S DVBNEWPERS("DVBIEN200")=DVBIEN200 ;.................... DUZ of user lookup
 S DVBNEWPERS("USERNAME")=DVBDATA(200,DVBIENS,.01,"E") ; USERNAME external
 ;
 S DVBNEWPERS("TITLEI")=+DVBDATA(200,DVBIENS,8,"I") ; TITLE NAME internal
 S DVBNEWPERS("TITLE")=DVBDATA(200,DVBIENS,8,"E") ;.. TITLE NAME external
 S:DVBNEWPERS("TITLE")="" DVBNEWPERS("TITLE")="<TitleEmpty>"
 ;
 S DVBNEWPERS("SVCI")=+DVBDATA(200,DVBIENS,29,"I") ; SVC NAME internal
 S DVBNEWPERS("SVC")=DVBDATA(200,DVBIENS,29,"E") ;.. SVC NAME external
 S:DVBNEWPERS("SVC")="" DVBNEWPERS("SVC")="<ServiceEmpty>"
 ;
 Q  ; NEWPERS
 ;
OCCRMULT(DVBIEN19,DVBOCCURIEN) ; Retrieve fields from the OCCURANCES multiple
 ;
 N %Y,DVBIENS,DVBDATA,DVBERRMSG
 ; ZEXCEPT: DVBOCCRMULT,DVBQUIT
 ;
 K DVBOCCRMULT ; Refresh output array
 S DVBQUIT=0 ; Indicates a successful data retrieval
 ;
 ;Retrieve data related to the OCCURANCE multiple of file #396.9991201
 ;
 S DVBIENS=+$G(DVBOCCURIEN)_","_+$G(DVBIEN19)_","
 D GETS^DIQ(396.9991201,DVBIENS,"2;3","I","DVBDATA","DVBERRMSG")
 D DIERR^DVBAUDDILG1(60,5,"DVBERRMSG","OCCRMULT^"_$T(+0)) Q:DVBQUIT
 ;
 ; Set O-DATE/TIME TASKED AUDIT BEGAN & O-DATE/TIME TASKED AUDIT ENDED
 S DVBOCCRMULT("TIMEBEG")=DVBDATA(396.9991201,DVBIENS,2,"I")
 S DVBOCCRMULT("TIMEEND")=DVBDATA(396.9991201,DVBIENS,3,"I")
 S DVBQUIT=0 ; Indicates a successful data retrieval
 ;
 Q  ; OCCRMULT
 ;
OPTION(DVBIEN19) ; Retrieve fields from OPTION file #19
 ;
 N %Y,DVBIENS,DVBDATA,DVBERRMSG
 ; ZEXCEPT: DVBOPT,DVBQUIT
 ;
 K DVBOPT ;...Refresh output array
 S DVBQUIT=0 ; Indicates a successful data retrieval
 ;
 ; Verify input variable DVBIEN19, retrieve the data in the DVBDATA(array)
 ;
 S DVBIENS=+$G(DVBIEN19)_","
 D GETS^DIQ(19,DVBIENS,".01;2;4;15;20","IE","DVBDATA","DVBERRMSG") ;
 D DIERR^DVBAUDDILG1(60,5,"DVBERRMSG","OPTION^"_$T(+0)) Q:DVBQUIT
 ;
 S DVBOPT("NAME")=DVBDATA(19,DVBIENS,.01,"E") ;......OPTION NAME
 S DVBOPT("OOOMSG")=DVBDATA(19,DVBIENS,2,"E") ;......OUT OF ORDER MESSAGE
 S DVBOPT("TYPEI")=DVBDATA(19,DVBIENS,4,"I") ;.......OPTION TYPE internal
 S DVBOPT("TYPE")=DVBDATA(19,DVBIENS,4,"E") ;........OPTION TYPE
 S:DVBOPT("TYPE")="" DVBOPT("TYPE")="<TypeEmpty>"
 S DVBOPT("EXITACTION")=DVBDATA(19,DVBIENS,15,"E") ;.OPTION EXIT  ACTION
 S DVBOPT("ENTRYACTION")=DVBDATA(19,DVBIENS,20,"E") ;OPTION ENTRY ACTION
 ;
 Q  ; OPTION
 ;
OPTSCH(DVBIEN) ; Retrieve fields from a OPTION SCHEUDLING file #19.2 entry
 ;
 N %Y,DVBIENS,DVBDATA,DVBERRMSG
 ; ZEXCEPT: DVBOPTSCH,DVBQUIT
 ;
 K DVBOPTSCH ;Refresh output array
 S DVBQUIT=0 ; Indicates a successful data retrieval
 ;
 ; Verify input variable DVBIEN and store record in DVBDATA array
 ;
 S DVBIENS=+$G(DVBIEN)_","
 D GETS^DIQ(19.2,DVBIENS,"*","IE","DVBDATA","DVBERRMSG") ; EVENT rec
 D DIERR^DVBAUDDILG1(60,5,"DVBERRMSG","OPTSCH^"_$T(+0))
 Q:DVBQUIT
 ;
 ;Save the external and internal values needed in output DVBOPTSCH(array)
 ;
 S DVBOPTSCH("DVBIEN")=DVBIEN
 S DVBOPTSCH("DVBIEN19")=DVBDATA(19.2,DVBIENS,.01,"I")
 S DVBOPTSCH("OPTNAME")=DVBDATA(19.2,DVBIENS,.01,"E")
 S DVBOPTSCH("QTORUNTIME")=$$DATE^DVBAUDDT1(DVBDATA(19.2,DVBIENS,2,"I"),1)
 S DVBOPTSCH("QTORUNTIMEI")=DVBDATA(19.2,DVBIENS,2,"I")
 S DVBOPTSCH("DEVICE")=DVBDATA(19.2,DVBIENS,3,"E")
 S DVBOPTSCH("FREQ")=DVBDATA(19.2,DVBIENS,6,"E")
 S DVBOPTSCH("TASKID")=DVBDATA(19.2,DVBIENS,12,"E")
 ;
 Q  ; OPTSCH
 ;
PARSVC(DVBIEN49) ; Retrieve the PARENT SERVICE from SERVICE/SECTION file (#49)
 ;
 N %Y,DVBIENS,DVBDATA,DVBERRMSG,DVBQUIT,DVBSVC
 ; ZEXCEPT: DVBPARSVC,DVBQUIT
 ;
 K DVBPARSVC ; Refresh output array
 ;
 ; Set output array defaults in PARENT SERVICE cannot be determined.
 S DVBIEN49=$G(DVBIEN49,0) ; Return 0 or the internal value passed on input
 S DVBPARSVC("IEN49")=DVBIEN49
 S DVBPARSVC("NAME")="<ParentSvcEmpty>" ; Return if PARENT SERVICE not determined
 ;
 S DVBIENS=DVBIEN49_","
 S DVBSVC=$$GET1^DIQ(49,DVBIENS,.01)
 I DVBSVC]"" D  Q  ;
 . D GETS^DIQ(49,DVBIENS,1.6,"IE","DVBDATA","DVBERRMSG") ; PARENT SERVICE
 . D DIERR^DVBAUDDILG1(60,5,"DVBERRMSG","PARSVC^"_$T(+0)) Q:DVBQUIT
 . ;
 . S DVBPARSVC("IEN49")=+DVBDATA(49,DVBIENS,1.6,"I") ;. PARENT SERVICE int.
 . S DVBPARSVC("NAME")=DVBDATA(49,DVBIENS,1.6,"E") ;... PARENT SERVICE ext.
 . S:DVBPARSVC("NAME")="" DVBPARSVC("NAME")="<ParentSvcEmpty>"
 ;
 Q  ; PARSVC
 ;
SUMOPT(DVBIEN19) ; Retrieve fields from AMIE AUDIT SUMMARY BY OPTION
 ;
 N %Y,DVBIENS,DVBDATA,DVBERRMSG
 ; ZEXCEPT: DVBSUMOPT,DVBQUIT
 ;
 K DVBSUMOPT ; Refresh output array
 S DVBQUIT=0 ;. Indicates a successful data retrieval
 ;
 S DVBIENS=+$G(DVBIEN19)_","
 D GETS^DIQ(396.9991,DVBIENS,"*","IE","DVBDATA","DVBERRMSG") ; SUMMARY rec
 D DIERR^DVBAUDDILG1(60,5,"DVBERRMSG","SUMOPT^"_$T(+0)) Q:DVBQUIT
 ;
 S DVBSUMOPT("OPTNAME")=DVBDATA(396.9991,DVBIENS,.01,"E") ; OP-NAME [F]
 S DVBSUMOPT("DVBIEN19")=DVBDATA(396.9991,DVBIENS,.01,"I") ;.. OP-NAME [P19']
 S DVBSUMOPT("DTSTART")=DVBDATA(396.9991,DVBIENS,2,"E") ; OP-AUDIT BEGIN DATE
 S DVBSUMOPT("DTSTARTI")=DVBDATA(396.9991,DVBIENS,2,"I") ;OP-AUDIT BEGIN DATE
 S DVBSUMOPT("DT1ST")=DVBDATA(396.9991,DVBIENS,3,"E") ;OP-EARLIEST AUDIT DATE
 I DVBSUMOPT("DT1ST")="" S DVBSUMOPT("DT1ST")="<Empty>"
 S DVBSUMOPT("DT1STI")=DVBDATA(396.9991,DVBIENS,3,"I") ; OP-EARLIEST AUDIT DATE/TIME
 S DVBSUMOPT("DTLAST")=DVBDATA(396.9991,DVBIENS,4,"E") ; OP-LATEST AUDIT DATE/TIME
 I DVBSUMOPT("DTLAST")="" S DVBSUMOPT("DTLAST")="<Empty>"
 S DVBSUMOPT("DTLASTI")=DVBDATA(396.9991,DVBIENS,4,"I") ;OP-LATEST AUDIT DATE/TIME
 S DVBSUMOPT("LSTUSER")=DVBDATA(396.9991,DVBIENS,5,"E") ;OP-LAST USED BY
 S DVBSUMOPT("LSTUSERI")=DVBDATA(396.9991,DVBIENS,5,"I") ; OP-LAST USED BY
 S DVBSUMOPT("USAGE")=+DVBDATA(396.9991,DVBIENS,6,"E") ;.. OP-USAGE COUNT
 S DVBSUMOPT("ZTDTBEG")=DVBDATA(396.9991,DVBIENS,21,"E") ; ZTSK-LATEST BEGIN DATE/TIME
 S DVBSUMOPT("ZTDTBEGI")=DVBDATA(396.9991,DVBIENS,21,"I") ;ZTSK-LATEST BEGIN DATE/TIME
 S DVBSUMOPT("ZTDTEND")=DVBDATA(396.9991,DVBIENS,22,"E") ; ZTSK-LATEST END DATE/TIME
 S DVBSUMOPT("ZTDTENDI")=DVBDATA(396.9991,DVBIENS,22,"I") ;ZTSK-LATEST END DATE/TIME
 S DVBSUMOPT("ZTLSTUSR")=DVBDATA(396.9991,DVBIENS,23,"E") ;ZTSK-LATEST USE TASKED BY
 S DVBSUMOPT("ZTLSTUSRI")=DVBDATA(396.9991,DVBIENS,23,"I") ;ZTSK-LATEST USE TASKED BY
 S DVBSUMOPT("AUDDAYS")=DVBDATA(396.9991,DVBIENS,900,"E") ; OP-DAYS AUDITED
 S DVBSUMOPT("ACTIVE?")=DVBDATA(396.9991,DVBIENS,901,"E") ; OP-ACTIVE?
 S DVBSUMOPT("OOOMSG")=DVBDATA(396.9991,DVBIENS,902,"E") ;. OP-OUT OF ORDER MESSAGE
 S DVBSUMOPT("OPTTYPE")=DVBDATA(396.9991,DVBIENS,904,"E") ; OP-TYPE
 S:DVBSUMOPT("OPTTYPE")="" DVBSUMOPT("OPTTYPE")="<TypeEmpty>"
 S DVBSUMOPT("OPTTOBT")=DVBDATA(396.9991,DVBIENS,908,"E") ; OP-AUDIT TURNED-ON-BY TITLE
 I DVBSUMOPT("OPTTOBT")="" D  ;
 . S DVBSUMOPT("OPTTOBT")="<TitleEmpty>"
 S DVBSUMOPT("OPTAUDON")=DVBDATA(396.9991,DVBIENS,920,"E") ; OP-AUDIT CURRENTLY-TURNED?
 S DVBSUMOPT("OPTTOBS")=DVBDATA(396.9991,DVBIENS,929,"E") ;. OP-AUDIT TURNED-ON-BY SERE
 I DVBSUMOPT("OPTTOBS")="" D  ;
 . S DVBSUMOPT("OPTTOBS")="<ServiceSectionEmpty>"
 ;
 Q  ; SUMOPT
 ;
UOPTION(DVBIEN200,DVBIEN19) ; Retrieve fields from the
 ;
 N %Y,DVBIENS,DVBDATA,DVBERRMSG
 ; ZEXCEPT: DVBUOPTION,DVBQUIT
 ;
 K DVBUOPTION ; Refresh output array
 S DVBQUIT=0 ;.. Indicates a successful data retrieval
 ;
 ; Retrieve data related to the OPTION multiple of file #396.9992201
 ;
 S DVBIENS=+$G(DVBIEN19)_","_+$G(DVBIEN200)_","
 D GETS^DIQ(396.9992201,DVBIENS,"*","IE","DVBDATA","DVBERRMSG")
 D DIERR^DVBAUDDILG1(60,5,"DVBERRMSG","UOPTION^"_$T(+0)) Q:DVBQUIT
 ;
 S DVBUOPTION("OPTI")=DVBDATA(396.9992201,DVBIENS,.01,"I")
 S DVBUOPTION("OPTNAME")=DVBDATA(396.9992201,DVBIENS,.01,"E")
 S DVBUOPTION("DT1STI")=DVBDATA(396.9992201,DVBIENS,2,"I")
 S DVBUOPTION("DT1ST")=$$DATE^DVBAUDDT1(DVBUOPTION("DT1STI"),1,0,1) ;  mm/dd/yy
 S DVBUOPTION("DTLASTI")=DVBDATA(396.9992201,DVBIENS,3,"I")
 S DVBUOPTION("DTLAST")=$$DATE^DVBAUDDT1(DVBUOPTION("DTLASTI"),1,0,1) ;mm/dd/yy
 S DVBUOPTION("COUNTER")=DVBDATA(396.9992201,DVBIENS,4,"I")
 S DVBUOPTION("USERI")=DVBIEN200
 S DVBUOPTION("USER")=$$GET1^DIQ(396.9992,DVBIEN200,.01)
 ;
 Q  ; UOPTION
