DVBC256P2  ;ALB/CP - PATCH DVBA*2.7*256 POST-INSTALL ROUTINE2; DEC 18, 2024@16:00 ; 9/24/25 12:00pm
 ;;2.7;AMIE;**256**;Apr 10, 1995;Build 19
 ; Per VHA Directive 6402 this routine should not be modified
 ; Reference to File #18.12 in ICR #7204
 ; Reference to File #18.02 in ICR #7205
 ; Reference to File 19.2 ^DIC(19.2) in ICR #4078
 ; Reference to File 19 in ICR #10075
 ; Reference to FILE^DICN in ICR #10009
 ; Reference to XPDUTL in ICR #10141
 ; Reference to ^DIC in ICR #10006
 ; Reference to UPDATE^DIE in ICR #2053 
 ; Reference to REGREST^XOBWLIB in ICR #5421 
 ; 
 Q
 ;
SCHED ; Schedule the DVBA SUMMARIZE AUDIT RECS-AT option in DVBFILE #19.2
 ; the OPTION SCHEDULING DVBFILE.
 ;
 N DVBERRMSG,DVBFDA,DVBFILE,DVBIENS
 S (DVBERRMSG,DVBFDA,DVBFILE,DVBIENS)=""
 ; See ICR # 742 & 4497
 ;
 ; Quit if the option is already scheduled, is case of multiple runs
 Q:$$FIND1^DIC(19.2,"","BO","DVBA SUMMARIZE AUDIT RECS-AT")
 ;
 S DVBIENS="+1,",DVBFILE=19.2
 S DVBFDA(DVBFILE,DVBIENS,.01)="DVBA SUMMARIZE AUDIT RECS-AT"
 S DVBFDA(DVBFILE,DVBIENS,2)=$$FMADD^XLFDT(DT,1)_".133" ; TODAY+1@1:30AM
 S DVBFDA(DVBFILE,DVBIENS,6)="1D"
 D UPDATE^DIE("E","DVBFDA","","DVBERRMSG") ; Add an EVENT DVBFILE record
 I DVBERRMSG'="" D UPDMSG^DVBC256P("Scheduling AutoReports",DVBERRMSG) Q
 ;
 D UPDMSG^DVBC256P("DVBA SUMMARIZE AUDIT RECS-AT","scheduled to run daily at 1:30 am")
 ;
 Q  ; Quit SCHED 
 ;
ADDAUDIT  ;  CAPRI-28984 CP 8/4/26
 N X,DVBACTION,DVBOPTYPES,DVBCNT,DVBMAXLEN,DVBOPTNAME,DVBQUIT,DVBENACTION,DVBEXACTION,DVBDATA
 S X="DVBAUDOA" X ^%ZOSF("TEST") Q:'$T
 ;
 ; Validate that the following files exist:
 Q:'$$FIND1^DIC(1,"","BO","AMIE OPTION AUDIT EVENT")
 Q:'$$FIND1^DIC(1,"","BO","AMIE AUDIT SUMMARY BY OPTION")
 ;
 S DVBACTION="CREATE"
 S DVBOPTYPES="AEIPRXSC"
 ;
 S DVBCNT("SEL")=0 ; Number of options selected for auditing
 S DVBCNT("CRE")=0 ; Number of options where audits were created
 S DVBQUIT=0
 S DVBMAXLEN=229 ;.. Maximum length of ENTRY ACTION and EXIT ACTION
 N DVBI
 F DVBI=1:1 S DVBOPTNAME=$P($T(OPTLIST+DVBI),";;",2) Q:(DVBOPTNAME["$EXIT")  D
 . N DVBIEN19,DVBDATA
 . S DVBIEN19=""
 . S DVBIEN19=$O(^DIC(19,"B",DVBOPTNAME,DVBIEN19))
 . I DVBIEN19="" D UPDMSG^DVBC256P(DVBOPTNAME,"OPTION not found, could not add auditing") Q
 . S DVBEXACTION("BEF")=$$GET1^DIQ(19,DVBIEN19,"15","E") ;.OPTION EXIT  ACTION
 . S DVBENACTION("BEF")=$$GET1^DIQ(19,DVBIEN19,"20","E") ;OPTION ENTRY ACTION
 . ; Prevent ENTRY ACTION from exceeding maximum length, display msg
 . I $L(DVBENACTION("BEF"))>DVBMAXLEN D UPDMSG^DVBC256P(DVBOPTNAME,"OPTION's Entry Action length over MAX") Q
 . ; Prevent EXIT ACTION from exceeding maximum length, display msg.
 . I $L(DVBEXACTION("BEF"))>DVBMAXLEN D UPDMSG^DVBC256P(DVBOPTNAME,"OPTION's Exit Action length over MAX") Q
 . ;
 . I DVBENACTION("BEF")="" S DVBENACTION("AFT")="D AUDIT^DVBAUDOA"
 . I DVBENACTION("BEF")'="" S DVBENACTION("AFT")="D AUDIT^DVBAUDOA "_DVBENACTION("BEF")
 . I DVBEXACTION("BEF")="" S DVBEXACTION("AFT")="D PTIME^DVBAUDOA"
 . I DVBEXACTION("BEF")'="" S DVBEXACTION("AFT")="D PTIME^DVBAUDOA "_DVBEXACTION("BEF")
 . S DVBCNT("SEL")=DVBCNT("SEL")+1 ; Number of options selected for audit
 . D ENTRYACT^DVBAUDDIE(DVBIEN19,.DVBENACTION,.DVBEXACTION)
 . D SUMSTUB^DVBAUDDIE(DVBIEN19) ; Create the SUMMARY record stub
 . S DVBCNT("CRE")=DVBCNT("CRE")+1 ; Number of option audits created
 ;
 D UPDMSG^DVBC256P("AMIE Auditing","Number selected for update: "_$G(DVBCNT("SEL"))_" number updated: "_$G(DVBCNT("CRE")))
 Q
 ;
OPTLIST  ; CAPRI-28984 CP 8/4/26
 ;;DVBA 7131 DIVISIONAL TRANSFER
 ;;DVBA 7132 TASKMAN
 ;;DVBA AUTO FINALIZE 7131 TASK
 ;;DVBA C C&P LINK MANAGEMENT
 ;;DVBA C C&P MASTER MENU
 ;;DVBA C CHECK 2507 INTEGRITY
 ;;DVBA C CHECK 2507 INTEGRITY TM
 ;;DVBA C MANUAL C&P XFER RETURN
 ;;DVBA C NOT SCHEDULED IN 3 DAYS
 ;;DVBA C PRINT BLANK C&P WORKSHE
 ;;DVBA C PRINT FEE COVER SHEET
 ;;DVBA C PRINT NEW C&P REQ TM
 ;;DVBA C PROCESS MAIL MESSAGE
 ;;DVBA C REGIONAL OFF RPT MENU
 ;;DVBA C REGIONAL OFFICE MENU
 ;;DVBA C RO AMIS 290
 ;;DVBA C SCHEDULE EXAMS
 ;;DVBA C TRANSCRIBE REQUEST DATA
 ;;DVBA COMPETENCY EDIT
 ;;DVBA CONTRACTED 2507 EXAM GUI
 ;;DVBA DGPRE PRE-REGISTER OPTION
 ;;DVBA GENERATE 21-DAY CERTIF
 ;;DVBA HRC MENU
 ;;DVBA HRC MENU ISO
 ;;DVBA MANUAL NOTIFY
 ;;DVBA RADIOLOGY VARO
 ;;DVBA RE-ADMISSION REPORT
 ;;DVBA RE-GENERATE 21-DAY CERTIF
 ;;DVBA REG OFF PATIENT INQ
 ;;DVBA REGIONAL 7132 MENU
 ;;DVBA REGIONAL OFFICE MENU
 ;;DVBA REGIONAL PURGING PROGRAM
 ;;DVBA REGIONAL TASK
 ;;DVBA RELEASE 21-DAY CERT
 ;;DVBA REPORT PENSION/A&A
 ;;DVBA REPRINT NOTICE/DISCHARGE
 ;;DVBA RO PRINT 21-DAY CERT
 ;;DVBA RO REPRINT 21-DAY CERT
 ;;DVBA VARO REMOTE
 ;;DVBA VR BACKGROUND
 ;;$EXIT
 Q
