DVBC256P ;ALB/BG - PATCH DVBA*2.7*256 POST-INSTALL ROUTINE; SEP 7, 2022@16:20 ; 8/6/26 7:49am
 ;;2.7;AMIE;**256**;Apr 10, 1995;Build 19
 ; Per VHA Directive 6402 this routine should not be modified
 ; Reference to SUPPORTED PARAMETER TOOL ENTRY POINTS in ICR #2263
 ; Reference to ^XLFDT in ICR #10103
 Q
 ;CAPRI-27820 TO ADD PARAMETER SUBTASK FOR RELEASE
VUPDATE ; MINIMUM AND PREVIOUS CAPRI VERSION UPDATES
 N DVBVER,DVBTOG,DVBVAL,DVBVAL1,DVBVAL2
 D MES^XPDUTL("Patch DVBA*2.7*256 post install started")
 S DVBVER=$$ENXPARS("PKG","DVBAB CAPRI MINIMUM VERSION",1,"CAPRI GUI V2.7*256.38*1*A*3261015*1.3*1.3")
 D UPDMSG("CAPRI MINIMUM VERSION",DVBVER)
 S DVBVER=$$ENXPARS("PKG","DVBAB CAPRI PREVIOUS VERSION",1,"DVBA*2.7*255.32")
 D UPDMSG("DVBAB CAPRI PREVIOUS VERSION",DVBVER)
 ;CAPRI-28984 BG 7/31/26
 S DVBVER=$$ENXPARS("PKG","DVBAB MAX OCCURRENCES HISTORY",1,"100")
 D UPDMSG("DVBAB MAX OCCURRENCES HISTORY",DVBVER)
 ;
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",1,"https://api.va.ghe.com/repos/software/dbq-cmt-iepd/zipball/main")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",2,"dbq-cmt-iepd")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",3,"https://api.va.ghe.com/repos/software/dbq-cmt-iepd")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",4,"https://api.va.ghe.com/repos/software/CAPRIExamManagementIEPD/zipball/main")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",5,"CAPRIExamManagementIEPD")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",6,"https://api.va.ghe.com/repos/software/CAPRIExamManagementIEPD")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",7,"https://api.va.ghe.com/repos/software/dbq-cmt-iepd/commits")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",8,"https://api.va.ghe.com/repos/software/CAPRIExamManagementIEPD/commits")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB REPO",9,"https://api.va.ghe.com/app/installations/33626/access_tokens")  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB REPO",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI SP IEPD ISPROD",1,1)  ;NGC CAPRI-23866
 D UPDMSG("DVBAB CAPRI SP IEPD ISPROD",DVBVER)
 S DVBVAL="https://graph.microsoft.com/v1.0/drives/{{DRIVEID}}//root:/DMAIEPDTesting:/children(''{{FILENAME}}'')"
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI SP IEPD TEST",1,DVBVAL)  ;NGC CAPRI-23865
 D UPDMSG("DVBAB CAPRI SP IEPD TEST",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB LINK",1,"https://github.com/department-of-veterans-affairs/dbq-cmt-iepd") ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB LINK",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB APP ID",1,5101)  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB APP ID",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI GITHUB INSTALL ID",1,33626)  ;PLE 3/18/2026 CAPRI-25715
 D UPDMSG("DVBAB CAPRI GITHUB INSTALL ID",DVBVER)
 ;
 ;CAPRI-28721 CP 7/20/26
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",1,"10.0!NS_NIEM_XSD!http://niem.gov/niem/proxy/xsd/2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",2,"10.0!NS_S!http://niem.gov/niem/structures/2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",3,"10.0!NS_XSI!http://www.w3.org/2001/XMLSchema-instance")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",4,"10.0!DOCUMENT_TYPE_VERSION!2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",5,"10.0!NS_NC!http://niem.gov/niem/niem-core/2.1")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",6,"10.0!NS_VLER!http://domain.ext/vler/schemas/vlerSupersetSchema/1.2/vler")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",7,"10.0!NS_CLD!http://vler.domain.ext/vler/schemas/health/clinicalDocuments/clinicalAssessments/cpExams/Claim/")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",8,"10.4!NS_NIEM_XSD!http://niem.gov/niem/proxy/xsd/2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",9,"10.4!NS_S!http://niem.gov/niem/structures/2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",10,"10.4!NS_XSI!http://www.w3.org/2001/XMLSchema-instance")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",11,"10.4!DOCUMENT_TYPE_VERSION!2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",12,"10.4!NS_NC!http://niem.gov/niem/niem-core/2.2")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",13,"10.4!NS_VLER!http://domain.ext/vler/schemas/vlerSupersetSchema/1.3/vler")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",14,"10.4!NS_CLD!http://vler.domain.ext/vler/schemas/health/clinicalDocuments/clinicalAssessments/cpExams/Claim/")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",15,"11.0!NS_NIEM_XSD!http://niem.gov/niem/proxy/xsd/2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",16,"11.0!NS_S!http://niem.gov/niem/structures/2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",17,"11.0!NS_XSI!http://www.w3.org/2001/XMLSchema-instance")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",18,"11.0!DOCUMENT_TYPE_VERSION!2.0")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",19,"11.0!NS_NC!http://niem.gov/niem/niem-core/2.2")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",20,"11.0!NS_VLER!http://domain.ext/vler/schemas/vlerSupersetSchema/1.4/vler")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI XML RAP COMP",21,"11.0!NS_CLD!http://vler.domain.ext/vler/schemas/health/clinicalDocuments/clinicalAssessments/cpExams/Claim/")
 D UPDMSG("DVBAB CAPRI XML RAP COMP",DVBVER)
 D TOKEN  ;PLE 3/18/2026 CAPRI-25715
 D VSTBTN ;CAPRI-28984 BG 7/31/26
 ;
 S DVBVER=$$ENXPARS("PKG.AUTOMATED MED INFO EXCHANGE","DVBAB CAPRI CMT IEPD FLDR CHCK",1,"0!jsons!pdfs!XMLschemas!XMLschemas\exchange!XMLschemas\extension!XMLschemas\subset")  ;PLE 6/22/2026 CAPRI-28119
 D UPDMSG("DVBAB CAPRI CMT IEPD FLDR CHCK",DVBVER)
 ;
 D ADDAUDIT^DVBC256P2
 D SCHED^DVBC256P2
 ;
 D BMES^XPDUTL("Patch DVBA*2.7*256 post install finished")
 Q
 ;
ENXPARS(DVBENT,DVBPAR,DVBINS,DVBVAL) ;
 N DVBVER
 D EN^XPAR(DVBENT,DVBPAR,DVBINS,DVBVAL,.DVBVER)
 Q DVBVER
 ;
UPDMSG(DVBPAR,DVBVER) ;
 I DVBVER D
 . D BMES^XPDUTL(DVBPAR_" Update FAILURE.")
 . D MES^XPDUTL("  Failure reason: "_DVBVER)
 E  D
 . D BMES^XPDUTL(DVBPAR_" Updated Successfully")
 Q
 ;
TOKEN ;PLE 3/18/2026 CAPRI-25715 updated private key for GITHUB migration - hold for CAPRI-26318
 N DVBTOK,DVBVER
 S DVBTOK(1)="-----BEGIN RSA PRIVATE KEY-----"
 S DVBTOK(2)="MIIEowIBAAKCAQEAsPKMSR9m1o2ud46zdCfGqOAsLcmBmDN5/OGM+fps/y8xnO8+"
 S DVBTOK(3)="b1dEXGe8a+UNcFmzceh5S+7E2JYljH0+vmEGpxJEwCFV+en4maL90N1QLm5xaDNl"
 S DVBTOK(4)="W+VGg2+VC/khINqCzIuQXsD2CGj0zzlTnWjoHY5aKa4aOIJ775+cfc0uNG0TPKmV"
 S DVBTOK(5)="DEBv4VzbSb7ek5OiFwql56YJftp7vLSrTokrJYpOt2ekJKKKNPbCM6GG/xgneV4B"
 S DVBTOK(6)="aLFfoGa1iLILteQr7kVOyMN5l2u9WsJqe/nHICVjvSW5YgcVg1iPbK+h0hLGeBCm"
 S DVBTOK(7)="wJ03AfGeExb85kzI6wh5of1gaYkQwUgWT5NGRwIDAQABAoIBAHkSXJ6j18+yPdAc"
 S DVBTOK(8)="Wfl+RdXDHTdvCzdC8ZLwGW/pw66Pchj5MfUo9uNrL2d74EgheEDWWjh0dUfk5GhO"
 S DVBTOK(9)="QiItbUnfnB8CMDvBtZIaDiVdaMF8XCh6Ej5gkHDaZlc87Uf3e0vNqsjKqw1yEx+/"
 S DVBTOK(10)="D9FCuJ+QiWy/bb2AuqBoy8DgJV9EpqirQ2zxxOfth91/uijkTUYPuf/l4Afo6Tcd"
 S DVBTOK(11)="vHc8mAIqCa5zI+nALUlF+RK9QSiOt32OlG6O6d26uRlTaXqi9fQeBlU5qXCE7u8u"
 S DVBTOK(12)="1pgIkTSvCsFYBcWncw3JP0UYkR7LRMwQdfxDfe74sfT1az8QsCA903tEcSc2U8L4"
 S DVBTOK(13)="UIAJr3ECgYEA5dba+gEKwvnaBDYVagnBa1JmWT7J1FCR3cb7y+GdTYgOPaB7l2+M"
 S DVBTOK(14)="WOxe5piiA9Y/c6b6rVRmlEPE7bLoEkFrgBqbbW2rK3Bjn70y4b9muiATphJMcRkL"
 S DVBTOK(15)="AFX5OrQ8AX5wZy+oJ0bB3XfB7LcYDX3wBwAR2x5I2+MJZx4MLxSHSW0CgYEAxRaC"
 S DVBTOK(16)="qjSdjlcnCqsTm+0tQlIpGa5UftDbd5tprknxP3BrBVCfjyybwLfLyMjlY4tn/xNP"
 S DVBTOK(17)="QYHfiFLpd/pv+WXJFXhdz9hZVnDYmP8MN/BWHjMpr/a3Ts55taAex5rqIY7Ju18r"
 S DVBTOK(18)="Ec2h+U6vKBWV3ea8VGRwNatcHj8AwkgJ/6+K0gMCgYEAmjeuOq3UULthJA4+FCZz"
 S DVBTOK(19)="l9V0Q1G0Dzf4h/zqGwVJjSpLk+JIy3XXkBsaGlQz8asibDGQZhkJs1Y9nti6ivVG"
 S DVBTOK(20)="cnBn9ebuQXlp/1bt+zd4cE7xoC8LB6AsF4+YaWFiGgaC2VnK1H/PuRCQGItKIlNs"
 S DVBTOK(21)="aOYNFR+e95vBRWWN+1Ek7YkCgYA21nOW3jr0jwVa74zuNskAChJLhfkWrBBUsFZw"
 S DVBTOK(22)="WzyX9TSh7vPmh3fy4HEANf21e+V80Kedx4Al00QI0RL05sBTjAE2QrFg3tc1gsmo"
 S DVBTOK(23)="iuO7VWsE/fW1JLgytBG8YjtBCRTSYMGAG6I01xLfaVoguwGtzaB3Hm3sMIWKiTbX"
 S DVBTOK(24)="AMX0dwKBgFVVbSWq+ISmU/VUCFldLGMJkvm49hYO/o2arQ9yqolhdFcPM1OSg220"
 S DVBTOK(25)="4ryKAx7MjlZ04Se5FHL1uLx59G8pW+ZF9dCZVSh+7hpJ+3wNDrlHQf6wKS+37QOx"
 S DVBTOK(26)="5DK+LHOlHNFtkvyvgBKasFfu2ftbElHev9BWTCO1Cwq/IXbHBXvh"
 S DVBTOK(27)="-----END RSA PRIVATE KEY-----"
 D EN^XPAR("PKG","DVBAB CAPRI GITHUB TOKEN",1,.DVBTOK,.DVBVER)
 D UPDMSG("DVBAB CAPRI GITHUB TOKEN",DVBVER)
 Q
VSTBTN ;
 N DVBVMSG,DVBVER
 S DVBVMSG(1)="{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil\fcharset2 Symbol;}}"
 S DVBVMSG(2)="{\*\generator Riched20 10.0.26100}\viewkind4\uc1"
 S DVBVMSG(3)="\pard\b\f0\fs24 Important: This button and Associated VistA Menus Will Be Discontinued\par"
 S DVBVMSG(4)="\b0\fs20 As part of the VA's modernization of CAPRI, all associated VistA menu options are scheduled for discontinuation in 2028. Native CAPRI functionality will migrate to a modern web-based platform.\par"
 S DVBVMSG(5)="\fs20\par"
 S DVBVMSG(6)="\b What this means for you:\par"
 S DVBVMSG(7)=""
 S DVBVMSG(8)="\pard{\pntext\f1\'B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\'B7}}\fi-200\li200\b0 VistA Roll and Scroll access will no longer be used for CAPRI/AMIE functions.\par"
 S DVBVMSG(9)="{\pntext\f1\'B7\tab}This button providing access to Reflection terminal emulation software will no longer be available.\par"
 S DVBVMSG(10)="{\pntext\f1\'B7\tab}AMIE menu options will be placed ""Out of Order"" and will no longer be accessible.\par"
 S DVBVMSG(11)=""
 S DVBVMSG(12)="\pard\par"
 S DVBVMSG(13)="\b What you should do now:\par"
 S DVBVMSG(14)="\b0 Work with your local VistA Administrator to review your current access and register to use the \b VA WebVRAM \b0 site, which will support your VistA access needs going forward."
 S DVBVMSG(15)=" Registering early will help avoid interruptions as the transition approaches.\par"
 S DVBVMSG(16)="\par"
 S DVBVMSG(17)="}"
 D EN^XPAR("PKG","DVBAB CAPRI VISTA GUI MSG",1,.DVBVMSG,.DVBVER)
 D UPDMSG("DVBAB CAPRI VISTA GUI MSG",DVBVER)
 Q
