DVBCTXM2 ;ALB/BG - CAPRI XML RPCS; FEB 6, 2023@16:20 ; 8/9/23 10:17am
 ;;2.7;AMIE;**250**;Apr 10, 1995;Build 19
 ; Per VHA Directive 6402 this routine should not be modified
 ; Reference to SUPPORTED PARAMETER TOOL ENTRY POINTS in ICR #2263
 Q
 ;
NEWSFEED(DVBRTN) ;
 N DVBCLNT,DVBTNT,DVBTKN,DVBTKI,DVBTKS,DVBTKD,DVBTKF
 S DVBCLNT=$$GET^XPAR("PKG","DVBAB CAPRI NF CLIENT")
 S DVBTNT=$$GET^XPAR("PKG","DVBAB CAPRI NF TENANT")
 S DVBTKN=$$GET^XPAR("PKG","DVBAB CAPRI NF TOKEN")
 S DVBTKI=$$GET^XPAR("PKG","DVBAB CAPRI NF TOKEN URL")
 S DVBTKS=$$GET^XPAR("PKG","DVBAB CAPRI NF SITEID URL")
 S DVBTKD=$$GET^XPAR("PKG","DVBAB CAPRI NF DRIVEID URL")
 S DVBTKF=$$GET^XPAR("PKG","DVBAB CAPRI NF FILEINFO URL")
 S DVBRTN=DVBCLNT_U_DVBTNT_U_DVBTKN_U_DVBTKI_U_DVBTKS_U_DVBTKD_U_DVBTKF
 Q
