DVBC251P ;ALB/BG - PATCH DVBA*2.7*251 POST-INSTALL ROUTINE; SEP 20, 2023@10:20 ; 11/17/23 10:08am
 ;;2.7;AMIE;**251**;Apr 10, 1995;Build 8
 ; Per VHA Directive 6402 this routine should not be modified
 Q
 ;
OPEN ; 
 N DVBCT,DVBOPT
 F DVBCT=1:1 S DVBOPT=$T(OPT+DVBCT) Q:DVBOPT'[";;"  S DVBOPT=$P(DVBOPT,";;",2) D
 .S DIC="^DIC(19,",DIC(0)="MZ",X=DVBOPT
 .D ^DIC K DIC
 .I Y<0 D BMES^XPDUTL(" "_DVBOPT_" option update failed") Q
 .I Y>0 D
 ..S DIE="^DIC(19,",DIC(0)="MZ",DA=+Y,DR="2///@"
 ..D ^DIE
 ..D BMES^XPDUTL(" "_DVBOPT_" option updated")
 ..K DIE,DIC,DR
 ..Q
 .Q
 K DIC,DIE,X,Y,DVBCT,DVBOPT,DA,DR
 D POST
 Q
OPT ; 
 ;;DVBA HRC MENU PHARMACY
 ;;DVBA HRC MENU PHARMACY CC
 ;
POST ; 
 ;Pharmacy menu
 D BMES^XPDUTL("-> Adding options to HRC Pharmacy Customer Care Menu <-")
 D ADDMNU("DVBA HRC MENU PHARMACY CC","DVBA HRC MENU","HRC",5)
 D ADDMNU("DVBA HRC MENU PHARMACY CC","PSO P","MP",15)
 D ADDMNU("DVBA HRC MENU PHARMACY CC","PSO VIEW","VW",20)
 D ADDMNU("DVBA HRC MENU PHARMACY CC","OR MAIN MENU WARD CLERK","WC",25)
 D ADDMNU("DVBA HRC MENU PHARMACY CC","PSO HRC PROFILE/REFILL","PPR",30)
 D ADDMNU("DVBA HRC MENU PHARMACY CC","PRCA FP VETERAN CHRG RPT","VCR",35)
 ;
 D BMES^XPDUTL("-> Adding options to HRC Pharmacy Menu <-")
 D ADDMNU("DVBA HRC MENU PHARMACY","DVBA HRC MENU","HRC",1)
 D ADDMNU("DVBA HRC MENU PHARMACY","PSOCP RESET COPAY STATUS","RC",5)
 D ADDMNU("DVBA HRC MENU PHARMACY","PSO P","MP",10)
 D ADDMNU("DVBA HRC MENU PHARMACY","PSO VIEW","VW",15)
 D ADDMNU("DVBA HRC MENU PHARMACY","PSO LM BACKDOOR ORDERS","PP",7)
 D ADDMNU("DVBA HRC MENU PHARMACY","OR MAIN MENU WARD CLERK","WC",20)
 D ADDMNU("DVBA HRC MENU PHARMACY","PSO HRC PROFILE/REFILL","PPR",30)
 D ADDMNU("DVBA HRC MENU PHARMACY","PSOCP RESET COPAY STATUS LM","RCL",6)
 D ADDMNU("DVBA HRC MENU PHARMACY","PRCA FP VETERAN CHRG RPT","VCR",35)
 QUIT
 ;
ADDMNU(DVB1,DVB2,DVB3,DVB4) ; 
 ;Adds Items to Menu (#19.01) subfile in Option (#19) file
 N DVOK
 S DVOK=$$ADD^XPDMENU(DVB1,DVB2,DVB3,DVB4)
 I 'DVOK D  Q
  .D MES^XPDUTL("  Could not add "_DVB2_" to "_DVB1)
 D MES^XPDUTL("  "_DVB2_" added to "_DVB1)
 Q
