LRZCXR ;ISC/ALB - MJB RUNNING DOWN THE "C" INDEX IN 68  ; Compiled 05/05/98 08:52AM for M/WNT
 ;MAY 4, 1998
 ;
INIT  
 ;N LRAA,LRAD,LRAN 
 ;S MJB=0
 ;F  I $D(^LRO(68,"C",MJB)) S MJB=$O(^LRO(68,"C",MJB)),LRAA=$O(^LRO(68,"C",MJB,0)) I LRAA S LRAD=$O(^LRO(68,"C",MJB,LRAA,0)) I LRAD S LRAN=$O(^LRO(68,"C",MJB,LRAA,LRAD,0)) D  Q:MJB<1
 ;. S Y=$P($G(^LRO(68,LRAA,1,LRAD,1,LRAN,.1)),"^")
 ;. S Y(0)=+$G(^LRO(68,LRAA,1,LRAD,1,LRAN,0)) D
 ; .. S MJB1=$P(Y(0),"^",3)
 ; .. I LRAD'=MJB1 W !,"BAD INDEX AT:",MJB
 N LRAA,LRAD,LRAN I $D(^LRO(68,"C",X)) S LRAA=$O(^LRO(68,"C",X,0)) I LRAA S LRAD=$O(^LRO(68,"C",X,LRAA,0)) I LRAD S LRAN=$O(^LRO(68,"C",X,LRAA,LRAD,0))I LRAN S Y=$P($G(^LRO(68,LRAA,1,LRAD,1,LRAN,.1)),"^")
  Q
