A1BFTRR7 ;ALBANY ISC ; RESPONSE TIME REPORT FINAL AVERAGES ; ECF ; 23OCT [ 06/15/93  1:17 PM ]
 ;;V1.0
 ;;Called by A1BFTRR6
FINTOT ;Create final totals
 ;Sum all user counts
 S A1BFFTU=0
 F A1BFI=9:1:17 S A1BFFTU=A1BFFTU+$P(^UTILITY("A1BF",$J,"ZRTOT","USER"),U,A1BFI)
 S $P(^UTILITY("A1BF",$J,"ZRTOT","USER"),U,27)=A1BFFTU
 ;Sum all elapsed times
 S A1BFFTT=0
 F A1BFI=9:1:17 S A1BFFTT=A1BFFTT+$P(^UTILITY("A1BF",$J,"ZRTOT","TIME"),U,A1BFI)
 S $P(^UTILITY("A1BF",$J,"ZRTOT","TIME"),U,27)=A1BFFTT
 ;Sum all session counts
 S A1BFFTS=0
 F A1BFI=9:1:17 S A1BFFTS=A1BFFTS+$P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,A1BFI)
 S $P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,27)=A1BFFTS
 ;Sum all device counts
 S A1BFFTD=0
 F A1BFI=9:1:17 S A1BFFTD=A1BFFTD+$P(^UTILITY("A1BF",$J,"ZRTOT","DEV"),U,A1BFI)
 S $P(^UTILITY("A1BF",$J,"ZRTOT","DEV"),U,27)=A1BFFTD
 ;Sum all Taskman counts
 S A1BFFTJ=0
 F A1BFI=9:1:17 S A1BFFTJ=A1BFFTJ+$P(^UTILITY("A1BF",$J,"ZRTOT","TMJ"),U,A1BFI)
 S $P(^UTILITY("A1BF",$J,"ZRTOT","TMJ"),U,27)=A1BFFTJ
 Q
FINAVG ;Figure final report averages
 ;If there are sessions for an hour, figure average time and users
 F A1BFI=9:1:17 I $P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,A1BFI)>0 D
 .S $P(^UTILITY("A1BF",$J,"ZRTOT","ATIME"),U,A1BFI)=$J(($P(^UTILITY("A1BF",$J,"ZRTOT","TIME"),U,A1BFI)/$P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,A1BFI)),1,4)
 .S $P(^UTILITY("A1BF",$J,"ZRTOT","AUSR"),U,A1BFI)=$J(($P(^UTILITY("A1BF",$J,"ZRTOT","USER"),U,A1BFI)/$P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,A1BFI)),1,4)
 .S $P(^UTILITY("A1BF",$J,"ZRTOT","ADEV"),U,A1BFI)=$J(($P(^UTILITY("A1BF",$J,"ZRTOT","DEV"),U,A1BFI)/$P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,A1BFI)),1,4)
 .S $P(^UTILITY("A1BF",$J,"ZRTOT","ATMJ"),U,A1BFI)=$J(($P(^UTILITY("A1BF",$J,"ZRTOT","TMJ"),U,A1BFI)/$P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,A1BFI)),1,4)
 S A1BFRR=$P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,27)>0 I A1BFRR>0 D
 .S $P(^UTILITY("A1BF",$J,"ZRTOT","ATIME"),U,27)=$P(^UTILITY("A1BF",$J,"ZRTOT","TIME"),U,27)/A1BFRR
 .S $P(^UTILITY("A1BF",$J,"ZRTOT","AUSR"),U,27)=$P(^UTILITY("A1BF",$J,"ZRTOT","USER"),U,27)/A1BFRR
 .S $P(^UTILITY("A1BF",$J,"ZRTOT","ADEV"),U,27)=$P(^UTILITY("A1BF",$J,"ZRTOT","DEV"),U,27)/A1BFRR
 .S $P(^UTILITY("A1BF",$J,"ZRTOT","ATMJ"),U,27)=$P(^UTILITY("A1BF",$J,"ZRTOT","TMJ"),U,27)/A1BFRR
 Q
LAST ;
 S A1BFAS=$S($D(^UTILITY("A1BF",$J,"ZRTOT","SESS")):$P(^UTILITY("A1BF",$J,"ZRTOT","SESS"),U,27),1:1)
 W $J("REPORT AVERAGE RT",17),"  "
 F A1BFN=9:1:17 D
 .W $J($S($D(^UTILITY("A1BF",$J,"ZRTOT","ATIME")):$P(^UTILITY("A1BF",$J,"ZRTOT","ATIME"),U,A1BFN),1:"0"),11,1)
 W $J($P(^UTILITY("A1BF",$J,"ZRTOT","ATIME"),U,27)/A1BFAS,11,1),!,$J("# DEVICES",17),"  "
 F A1BFN=9:1:17 D
 .W $J($S($D(^UTILITY("A1BF",$J,"ZRTOT","AUSR")):$P(^UTILITY("A1BF",$J,"ZRTOT","AUSR"),U,A1BFN),1:"0"),11,0)
 W $J($P(^UTILITY("A1BF",$J,"ZRTOT","AUSR"),U,27)/A1BFAS,11,1),!,$J("# USERS",17),"  "
 F A1BFN=9:1:17 D
 .W $J($S($D(^UTILITY("A1BF",$J,"ZRTOT","ADEV")):$P(^UTILITY("A1BF",$J,"ZRTOT","ADEV"),U,A1BFN),1:"0"),11,0)
 W $J($P(^UTILITY("A1BF",$J,"ZRTOT","ADEV"),U,27)/A1BFAS,11,1),!,$J("# TM Jobs",17),"  "
 F A1BFN=9:1:17 D
 .W $J($S($D(^UTILITY("A1BF",$J,"ZRTOT","ATMJ")):$P(^UTILITY("A1BF",$J,"ZRTOT","ATMJ"),U,A1BFN),1:"0"),11,0)
 W $J($P(^UTILITY("A1BF",$J,"ZRTOT","ATMJ"),U,27)/A1BFAS,11,1)
 W !
 Q:'$D(^UTILITY("A1BF",$J,"ZRTOT","SESS"))
 W !,A1BFLINE,!
 W @IOF
 Q
EXIT ;
 K A1BFAS,A1BFFTD,A1BFFTJ,A1BFFTS,A1BFFTT,A1BFFTU,A1BFRR
 Q
