A1BFTRR3 ;ALBANY ISC ; ECF ; 8 OCTOBER 1992 [ 04/29/93  4:42 PM ]
 ;;V1.0
WEEKLY ;Do weekly calculations
AVG ;WEEKLY AVERAGES
 ;Hourly avgs for week
 S A1BFW=$P(^UTILITY("A1BF",$J,A1BFPDAY,"DAAY"),U,3)
 F A1BFI=9:1:17 I $P(^UTILITY("A1BF",$J,"WTSES",A1BFW),U,A1BFI)>0 D
 .S $P(^UTILITY("A1BF",$J,"WATIM",A1BFW),U,A1BFI)=$J(($P(^UTILITY("A1BF",$J,"WTTIM",A1BFW),U,A1BFI)/$P(^UTILITY("A1BF",$J,"WTSES",A1BFW),U,A1BFI)),1,4)
 .S $P(^UTILITY("A1BF",$J,"WAUSR",A1BFW),U,A1BFI)=$J(($P(^UTILITY("A1BF",$J,"WTUSR",A1BFW),U,A1BFI)/$P(^UTILITY("A1BF",$J,"WTSES",A1BFW),U,A1BFI)),1,4)
 .S $P(^UTILITY("A1BF",$J,"WADEV",A1BFW),U,A1BFI)=$J(($P(^UTILITY("A1BF",$J,"WTDEV",A1BFW),U,A1BFI)/$P(^UTILITY("A1BF",$J,"WTSES",A1BFW),U,A1BFI)),1,4)
 .S $P(^UTILITY("A1BF",$J,"WATMJ",A1BFW),U,A1BFI)=$J(($P(^UTILITY("A1BF",$J,"WTTMJ",A1BFW),U,A1BFI)/$P(^UTILITY("A1BF",$J,"WTSES",A1BFW),U,A1BFI)),1,4)
 ;Final averages for week
 S (A1BFWTI,A1BFWTS,A1BFWTU,A1BFWTD,A1BFWTM)=0 F A1BFI=9:1:17 D
 .S A1BFWTI=$P(^UTILITY("A1BF",$J,"WTTIM",A1BFW),U,A1BFI)+A1BFWTI
 .S A1BFWTS=$P(^UTILITY("A1BF",$J,"WTSES",A1BFW),U,A1BFI)+A1BFWTS
 .S A1BFWTU=$P(^UTILITY("A1BF",$J,"WTUSR",A1BFW),U,A1BFI)+A1BFWTU
 .S A1BFWTD=$P(^UTILITY("A1BF",$J,"WTDEV",A1BFW),U,A1BFI)+A1BFWTD 
 .S A1BFWTM=$P(^UTILITY("A1BF",$J,"WTTMJ",A1BFW),U,A1BFI)+A1BFWTM 
 I (A1BFWTS>0) D 
 .S $P(^UTILITY("A1BF",$J,"WATIM",A1BFW),U,27)=$J((A1BFWTI/A1BFWTS),1,4)
 .S $P(^UTILITY("A1BF",$J,"WAUSR",A1BFW),U,27)=$J((A1BFWTU/A1BFWTS),1,4)
 .S $P(^UTILITY("A1BF",$J,"WADEV",A1BFW),U,27)=$J((A1BFWTD/A1BFWTS),1,4)
 .S $P(^UTILITY("A1BF",$J,"WATMJ",A1BFW),U,27)=$J((A1BFWTM/A1BFWTS),1,4)
 S $P(^UTILITY("A1BF",$J,"WTSES",A1BFW),U,27)=A1BFWTS
EXIT ;
 K A1BFI,A1BFWTI,A1BFWTS,A1BFWTU,A1BFWTD,A1BFWTM
 Q
