RMPRMESS ;PHX/HPL-CHECK AND CLEAN PTR IN FILE 660 LB;5
 ;;Prosthetics;3.0V2;;12/18/95
 ;
 W !,"CHECKING FILE 660"
 S RMPRDA=0
 F  S RMPRDA=$O(^RMPR(660,RMPRDA)) Q:RMPRDA'>0  D
 .S RMPRA=$P($G(^RMPR(660,RMPRDA,"LB")),U,5)
 .I RMPRA'>0 Q
 .I $D(^RMPR(664.2,RMPRA,0)) K RMPRA Q
 .S DA=RMPRDA,DIK="^RMPR(660," D ^DIK K DA,DIK
 .W "."
 .K RMPRA Q
 K RMPRDA,RMPRA,DIK,DA
 W !!,"All done !"
 Q
