PXRMP32H ;SLC/PKR - Inits for PXRM*2.0*32. ;06/02/2014
 ;;2.0;CLINICAL REMINDERS;**32**;Feb 04, 2005;Build 194
 Q
 ;==========================================
HFLIST ;Health factor renaming list.
 ;;MH EVIDENCED BASED PSYCHOTHER  TEMPLATES^MH EVIDENCED BASED PSYCHOTHER TEMPLATES
 ;;MH EBP PLAN REFERRAL^MH EBP PLAN REFERRAL
 ;;MH EBP EARLY TERM AGREE^MH EBP EARLY TERM AGREE
 ;;MH EBP EARLY TERM NO CONTACT^MH EBP EARLY TERM NO CONTACT
 ;;MH EBP EARLY TERM DISCONT TX^MH EBP EARLY TERM DISCONT TX
 ;;MH EBP EARLY TERM SYMPTOMS REMIT^MH EBP EARLY TERM SYMPTOMS REMIT
 ;;MH EBP TEMPLATE^MH EBP TEMPLATE
 ;;MH EBP PLAN PT AGREE^MH EBP PLAN PT AGREE
 ;;MH EBP PLAN BOOSTER SESSION^MH EBP PLAN BOOSTER SESSION
 ;;MH EBP PLAN TX COMPLETE^MH EBP PLAN TX COMPLETE
 ;;SST 3 REVIEW PROGRESS DISCONTINUE^MH SST 3 REVIEW PROGRESS DISCONTINUE
 ;;SST 3 REVIEW PROGRESS TERMINATE^MH SST 3 REVIEW PROGRESS TERMINATE
 ;;SST 3 REVIEW PROGRESS COMPLETED^MH SST 3 REVIEW PROGRESS COMPLETED
 ;;SST 3 REVIEW PROGRESS ATTENDING NO^MH SST 3 REVIEW PROGRESS ATTENDING NO
 ;;SST THERAPY^MH SST THERAPY
 ;;SST LEVEL ACTIVE NO^MH SST LEVEL ACTIVE NO
 ;;SST LEVEL PROMPT^MH SST LEVEL PROMPT
 ;;SST LEVEL ACTIVE YES^MH SST LEVEL ACTIVE YES
 ;;SST PARTICIPATION LEVEL^MH SST PARTICIPATION LEVEL
 ;;SST PARTICIPATION NUMBER 4^MH SST PARTICIPATION NUMBER 4
 ;;SST PARTICIPATION NUMBER 3^MH SST PARTICIPATION NUMBER 3
 ;;SST PARTICIPATION NUMBER 2^MH SST PARTICIPATION NUMBER 2
 ;;SST PARTICIPATION NUMBER 1^MH SST PARTICIPATION NUMBER 1
 ;;SST PARTICIPATION NUMBER^MH SST PARTICIPATION NUMBER
 ;;SST SUGGESTIONS IMPROVE^MH SST SUGGESTIONS IMPROVE
 ;;SST POS FEEDBACK^MH SST POS FEEDBACK
 ;;SST SKILL MODELED GROUP^MH SST SKILL MODELED GROUP
 ;;SST SKILL MODELED ROLE^MH SST SKILL MODELED ROLE
 ;;SST SKILL STEPS^MH SST SKILL STEPS
 ;;SST SKILL RATIONALE^MH SST SKILL RATIONALE
 ;;SST ASSIGNMENT^MH SST ASSIGNMENT
 ;;SST ESTABLISHED AGENDA^MH SST ESTABLISHED AGENDA
 ;;SST SOCIAL SKILLS TAUGHT COPING^MH SST SOCIAL SKILLS TAUGHT COPING
 ;;SST SOCIAL SKILLS TAUGHT VOCATIONAL^MH SST SOCIAL SKILLS TAUGHT VOCATIONAL
 ;;SST SOCIAL SKILLS TAUGHT CONFLICT^MH SST SOCIAL SKILLS TAUGHT CONFLICT
 ;;SST SOCIAL SKILLS TAUGHT ASSERTIVENESS^MH SST SOCIAL SKILLS TAUGHT ASSERTIVE
 ;;SST SOCIAL SKILLS TAUGHT CONVERSATION^MH SST SOCIAL SKILLS TAUGHT CONVERSATION
 ;;SST SOCIAL SKILLS TAUGHT OTHER^MH SST SOCIAL SKILLS TAUGHT OTHER
 ;;SST SOCIAL SKILLS TAUGHT HEALTH^MH SST SOCIAL SKILLS TAUGHT HEALTH
 ;;SST SOCIAL SKILLS TAUGHT FRIENDSHIP^MH SST SOCIAL SKILLS TAUGHT FRIENDSHIP
 ;;SST SOCIAL SKILLS TAUGHT COMMUNAL^MH SST SOCIAL SKILLS TAUGHT COMMUNAL
 ;;SST SOCIAL SKILLS TAUGHT FOUR^MH SST SOCIAL SKILLS TAUGHT FOUR
 ;;SST SOCIAL SKILLS TAUGHT^MH SST SOCIAL SKILLS TAUGHT
 ;;SST ASSESSMENT NO^MH SST ASSESSMENT NO
 ;;MH EBP COLLABORATION HIGH^MH EBP COLLABORATION HIGH
 ;;MH EBP COLLABORATION MEDIUM^MH EBP COLLABORATION MEDIUM
 ;;MH EBP COLLABORATION LOW^MH EBP COLLABORATION LOW
 ;;MH EBP MOTIVATION ENHANCE BARRIERS^MH EBP MOTIVATION ENHANCE BARRIERS
 ;;MH EBP MOTIVATION ENHANCE ATTITUDES^MH EBP MOTIVATION ENHANCE ATTITUDES
 ;;MH EBP MOTIVATION ENHANCE BENEFITS^MH EBP MOTIVATION ENHANCE BENEFITS
 ;;MH EBP MOTIVATION ENHANCE CONSEQUENCES^MH EBP MOTIVATION ENHANCE CONSEQUENCES
 ;;MH EBP MOTIVATION ENHANCE GOALS^MH EBP MOTIVATION ENHANCE GOALS
 ;;SST 1 INITIAL^MH SST 1 INITIAL
 ;;SST TREATMENT GOALS SHORT^MH SST TREATMENT GOALS SHORT
 ;;SST TREATMENT GOALS^MH SST TREATMENT GOALS
 ;;SST TREATMENT GOALS NOT IDENTIFIED^MH SST TREATMENT GOALS NOT IDENTIFIED
 ;;IPT FOR DEPRESSION^MH IPT FOR DEPRESSION
 ;;IPT SESSION NUMBER COMPLETED 17+^MH IPT SESSION NUMBER COMPLETED 17+
 ;;IPT SESSION NUMBER COMPLETED 16^MH IPT SESSION NUMBER COMPLETED 16
 ;;IPT SESSION NUMBER COMPLETED 15^MH IPT SESSION NUMBER COMPLETED 15
 ;;IPT SESSION NUMBER COMPLETED 14^MH IPT SESSION NUMBER COMPLETED 14
 ;;IPT SESSION NUMBER COMPLETED 13^MH IPT SESSION NUMBER COMPLETED 13
 ;;IPT SESSION NUMBER COMPLETED 12^MH IPT SESSION NUMBER COMPLETED 12
 ;;IPT SESSION NUMBER COMPLETED 4^MH IPT SESSION NUMBER COMPLETED 4
 ;;IPT SESSION NUMBER COMPLETED 3^MH IPT SESSION NUMBER COMPLETED 3
 ;;IPT SESSION NUMBER COMPLETED 2^MH IPT SESSION NUMBER COMPLETED 2
 ;;IPT SESSION NUMBER COMPLETED 1^MH IPT SESSION NUMBER COMPLETED 1
 ;;IPT SESSION NUMBER COMPLETED 11^MH IPT SESSION NUMBER COMPLETED 11
 ;;IPT SESSION NUMBER COMPLETED 10^MH IPT SESSION NUMBER COMPLETED 10
 ;;IPT SESSION NUMBER COMPLETED 9^MH IPT SESSION NUMBER COMPLETED 9
 ;;IPT SESSION NUMBER COMPLETED 8^MH IPT SESSION NUMBER COMPLETED 8
 ;;IPT SESSION NUMBER COMPLETED 7^MH IPT SESSION NUMBER COMPLETED 7
 ;;IPT SESSION NUMBER COMPLETED 6^MH IPT SESSION NUMBER COMPLETED 6
 ;;IPT SESSION NUMBER COMPLETED 5^MH IPT SESSION NUMBER COMPLETED 5
 ;;IPT THERAPY^MH IPT THERAPY
 ;;IPT EARLY TERM OUTSIDE OF SSN^MH IPT EARLY TERM OUTSIDE OF SSN
 ;;IPT HOMEWORK NOT ASSIGNED NEXT SSN^MH IPT HOMEWORK NOT ASSIGNED NEXT SSN
 ;;IPT HOMEWORK NOT ASSIGNED LAST SSN^MH IPT HOMEWORK NOT ASSIGNED LAST SSN
 ;;IPT HOMEWORK NOT COMPLETE^MH IPT HOMEWORK NOT COMPLETE
 ;;IPT HOMEWORK COMPLETE^MH IPT HOMEWORK COMPLETE
 ;;IPT TECHNIQUE ROLE PLAY^MH IPT TECHNIQUE ROLE PLAY
 ;;IPT TECHNIQUE DECISION ANALYSIS^MH IPT TECHNIQUE DECISION ANALYSIS
 ;;IPT TECHNIQUE DIRECTIVE^MH IPT TECHNIQUE DIRECTIVE
 ;;IPT TECHNIQUE THERAPEUTIC RELATION^MH IPT TECHNIQUE THERAPEUTIC RELATION
 ;;IPT TECHNIQUE COMMUNICATION TECHNIQUE^MH IPT TECHNIQUE COMMUNICATION TECHNIQUE
 ;;IPT TECHNIQUE COMMUNICATION ANALYSIS^MH IPT TECHNIQUE COMMUNICATION ANALYSIS
 ;;IPT TECHNIQUE CLARIFICATION^MH IPT TECHNIQUE CLARIFICATION
 ;;IPT TECHNIQUE ENCOURAGE AFFECT^MH IPT TECHNIQUE ENCOURAGE AFFECT
 ;;IPT TECHNIQUE EXPLORATION^MH IPT TECHNIQUE EXPLORATION
 ;;IPT DEFICITS COMPARE THER^MH IPT DEFICITS COMPARE THER
 ;;IPT DEFICITS REPETITIVE^MH IPT DEFICITS REPETITIVE
 ;;IPT DEFICITS COMPARE^MH IPT DEFICITS COMPARE
 ;;IPT DEFICITS CONNECT^MH IPT DEFICITS CONNECT
 ;;IPT DEFICITS RELATION^MH IPT DEFICITS RELATION
 ;;IPT DEFICITS REDUCE ISOL^MH IPT DEFICITS REDUCE ISOL
 ;;IPT ROLE TRANSITION SKILL ENCOURAGE^MH IPT ROLE TRANSITION SKILL ENCOURAGE
 ;;IPT ROLE TRANSITION AFFECT^MH IPT ROLE TRANSITION AFFECT
 ;;IPT ROLE TRANSITION OPPORTUNITIES^MH IPT ROLE TRANSITION OPPORTUNITIES
 ;;IPT ROLE TRANSITION FEELINGS^MH IPT ROLE TRANSITION FEELINGS
 ;;IPT ROLE TRANSITION COMPARE^MH IPT ROLE TRANSITION COMPARE
 ;;IPT ROLE TRANSITION COPING^MH IPT ROLE TRANSITION COPING
 ;;IPT ROLE TRANSITION SKILL DEVELOP^MH IPT ROLE TRANSITION SKILL DEVELOP
 ;;IPT ROLE TRANSITION POSITIVE^MH IPT ROLE TRANSITION POSITIVE
 ;;IPT ROLE TRANSITION LET GO^MH IPT ROLE TRANSITION LET GO
 ;;IPT ROLE DISPUTE STAGE^MH IPT ROLE DISPUTE STAGE
 ;;IPT ROLE DISPUTE PARALLEL^MH IPT ROLE DISPUTE PARALLEL
 ;;IPT ROLE DISPUTE EXPECTATIONS^MH IPT ROLE DISPUTE EXPECTATIONS
 ;;IPT ROLE DISPUTE CONNECT^MH IPT ROLE DISPUTE CONNECT
 ;;IPT ROLE DISPUTE PATTERNS^MH IPT ROLE DISPUTE PATTERNS
 ;;IPT ROLE DISPUTE PLAN^MH IPT ROLE DISPUTE PLAN
 ;;IPT GRIEF INVOLVE^MH IPT GRIEF INVOLVE
 ;;IPT GRIEF RECONSTRUCT^MH IPT GRIEF RECONSTRUCT
 ;;IPT GRIEF DESCRIBE^MH IPT GRIEF DESCRIBE
 ;;IPT GRIEF ELICIT^MH IPT GRIEF ELICIT
 ;;IPT GRIEF LINK^MH IPT GRIEF LINK
 ;;IPT GRIEF FRIEND^MH IPT GRIEF FRIEND
 ;;IPT GRIEF MOURN^MH IPT GRIEF MOURN
 ;;IPT INTERPERSONAL DEFICIT  SECONDARY^MH IPT INTERPERSONAL DEFICIT SECONDARY
 ;;IPT ROLE TRANSITION SECONDARY^MH IPT ROLE TRANSITION SECONDARY
 ;;IPT ROLE DISPUTE SECONDARY^MH IPT ROLE DISPUTE SECONDARY
 ;;IPT GRIEF SECONDARY^MH IPT GRIEF SECONDARY
 ;;IPT INTERPERSONAL DEFICIT PRIMARY^MH IPT INTERPERSONAL DEFICIT PRIMARY
 ;;IPT ROLE TRANSITION PRIMARY^MH IPT ROLE TRANSITION PRIMARY
 ;;IPT ROLE DISPUTE PRIMARY^MH IPT ROLE DISPUTE PRIMARY
 ;;IPT GRIEF PRIMARY^MH IPT GRIEF PRIMARY
 ;;IPT ENCOURAGE GOAL DESCRIBE^MH IPT ENCOURAGE GOAL DESCRIBE
 ;;IPT GOAL SET^MH IPT GOAL SET
 ;;IPT PROBLEM REVIEW^MH IPT PROBLEM REVIEW
 ;;IPT SESSION NUMBER 1 MAINT^MH IPT SESSION NUMBER 1 MAINT
 ;;IPT SESSION NUMBER 2 MAINT^MH IPT SESSION NUMBER 2 MAINT
 ;;IPT SESSION NUMBER 3 MAINT^MH IPT SESSION NUMBER 3 MAINT
 ;;IPT SESSION NUMBER 12+ MAINT^MH IPT SESSION NUMBER 12+ MAINT
 ;;IPT SESSION NUMBER 11 MAINT^MH IPT SESSION NUMBER 11 MAINT
 ;;IPT SESSION NUMBER 10 MAINT^MH IPT SESSION NUMBER 10 MAINT
 ;;IPT SESSION NUMBER 9 MAINT^MH IPT SESSION NUMBER 9 MAINT
 ;;IPT SESSION NUMBER 8 MAINT^MH IPT SESSION NUMBER 8 MAINT
 ;;IPT SESSION NUMBER 7 MAINT^MH IPT SESSION NUMBER 7 MAINT
 ;;IPT SESSION NUMBER 6 MAINT^MH IPT SESSION NUMBER 6 MAINT
 ;;IPT SESSION NUMBER 5 MAINT^MH IPT SESSION NUMBER 5 MAINT
 ;;IPT SESSION NUMBER 4 MAINT^MH IPT SESSION NUMBER 4 MAINT
 ;;IPT 4 MAINTENANCE SESSION^MH IPT 4 MAINTENANCE SESSION
 ;;IPT 3 SKILLS^MH IPT 3 SKILLS
 ;;IPT 3 FOCUS^MH IPT 3 FOCUS
 ;;IPT 3 PROBLEM^MH IPT 3 PROBLEM
 ;;IPT 3 MOOD^MH IPT 3 MOOD
 ;;IPT 3 CONTINUE^MH IPT 3 CONTINUE
 ;;IPT 3 RESPOND^MH IPT 3 RESPOND
 ;;IPT 3 FUTURE^MH IPT 3 FUTURE
 ;;IPT 3 TRIGGER^MH IPT 3 TRIGGER
 ;;IPT 3 FEELINGS^MH IPT 3 FEELINGS
 ;;IPT MORE DEPRESSED^MH IPT MORE DEPRESSED
 ;;IPT LESS SOCIAL NETWORK^MH IPT LESS SOCIAL NETWORK
 ;;IPT SAME SOCIAL NETWORK^MH IPT SAME SOCIAL NETWORK
 ;;IPT SAME DEPRESSED^MH IPT SAME DEPRESSED
 ;;IPT LESS DEPRESSED^MH IPT LESS DEPRESSED
 ;;IPT SESSION NUMBER 17+^MH IPT SESSION NUMBER 17+
 ;;IPT SESSION NUMBER 16^MH IPT SESSION NUMBER 16
 ;;IPT SESSION NUMBER 15^MH IPT SESSION NUMBER 15
 ;;IPT SESSION NUMBER 14^MH IPT SESSION NUMBER 14
 ;;IPT SESSION NUMBER 13^MH IPT SESSION NUMBER 13
 ;;IPT SESSION NUMBER 12^MH IPT SESSION NUMBER 12
 ;;IPT SESSION NUMBER 11^MH IPT SESSION NUMBER 11
 ;;IPT SESSION NUMBER 10^MH IPT SESSION NUMBER 10
 ;;IPT SESSION NUMBER 9^MH IPT SESSION NUMBER 9
 ;;IPT SESSION NUMBER 8^MH IPT SESSION NUMBER 8
 ;;IPT SESSION NUMBER 7^MH IPT SESSION NUMBER 7
 ;;IPT SESSION NUMBER 6^MH IPT SESSION NUMBER 6
 ;;IPT SESSION NUMBER 5^MH IPT SESSION NUMBER 5
 ;;IPT SESSION NUMBER 4^MH IPT SESSION NUMBER 4
 ;;IPT 3 TERMINATION SESSION^MH IPT 3 TERMINATION SESSION
 ;;IPT SESSION NUMBER 3^MH IPT SESSION NUMBER 3
 ;;IPT 2 INTERMEDIATE SESSION^MH IPT 2 INTERMEDIATE SESSION
 ;;IPT 1 INITIAL SESSION^MH IPT 1 INITIAL SESSION
 ;;IPT SESSION NUMBER 2^MH IPT SESSION NUMBER 2
 ;;IPT SESSION NUMBER 1^MH IPT SESSION NUMBER 1
 ;;IPT INTERPERSONAL FORMULATION^MH IPT INTERPERSONAL FORMULATION
 ;;IPT INTERPERSONAL INVENTORY^MH IPT INTERPERSONAL INVENTORY
 ;;IPT SICK ROLE EXPLAIN^MH IPT SICK ROLE EXPLAIN
 ;;IPT DEP EDUC^MH IPT DEP EDUC
 ;;IBCT TEMPLATES^MH IBCT TEMPLATES
 ;;IBCT SESSION NUMBER COMPLETED 1^MH IBCT SESSION NUMBER COMPLETED 1
 ;;IBCT SESSION NUMBER COMPLETED >24^MH IBCT SESSION NUMBER COMPLETED >24
 ;;IBCT SESSION NUMBER COMPLETED 24^MH IBCT SESSION NUMBER COMPLETED 24
 ;;IBCT SESSION NUMBER COMPLETED 20^MH IBCT SESSION NUMBER COMPLETED 20
 ;;IBCT SESSION NUMBER COMPLETED 18^MH IBCT SESSION NUMBER COMPLETED 18
 ;;IBCT SESSION NUMBER COMPLETED 17^MH IBCT SESSION NUMBER COMPLETED 17
 ;;IBCT SESSION NUMBER COMPLETED 15^MH IBCT SESSION NUMBER COMPLETED 15
 ;;IBCT SESSION NUMBER COMPLETED 14^MH IBCT SESSION NUMBER COMPLETED 14
 ;;IBCT SESSION NUMBER COMPLETED 13^MH IBCT SESSION NUMBER COMPLETED 13
 ;;IBCT SESSION NUMBER COMPLETED 11^MH IBCT SESSION NUMBER COMPLETED 11
 ;;IBCT SESSION NUMBER COMPLETED 10^MH IBCT SESSION NUMBER COMPLETED 10
 ;;IBCT SESSION NUMBER COMPLETED 9^MH IBCT SESSION NUMBER COMPLETED 9
 ;;IBCT SESSION NUMBER COMPLETED 7^MH IBCT SESSION NUMBER COMPLETED 7
 ;;IBCT SESSION NUMBER COMPLETED 6^MH IBCT SESSION NUMBER COMPLETED 6
 ;;IBCT SESSION NUMBER COMPLETED 4^MH IBCT SESSION NUMBER COMPLETED 4
 ;;IBCT SESSION NUMBER COMPLETED 3^MH IBCT SESSION NUMBER COMPLETED 3
 ;;IBCT SESSION NUMBER COMPLETED 23^MH IBCT SESSION NUMBER COMPLETED 23
 ;;IBCT SESSION NUMBER COMPLETED 22^MH IBCT SESSION NUMBER COMPLETED 22
 ;;IBCT SESSION NUMBER COMPLETED 21^MH IBCT SESSION NUMBER COMPLETED 21
 ;;IBCT SESSION NUMBER COMPLETED 19^MH IBCT SESSION NUMBER COMPLETED 19
 ;;IBCT SESSION NUMBER COMPLETED 16^MH IBCT SESSION NUMBER COMPLETED 16
 ;;IBCT SESSION NUMBER COMPLETED 12^MH IBCT SESSION NUMBER COMPLETED 12
 ;;IBCT SESSION NUMBER COMPLETED 8^MH IBCT SESSION NUMBER COMPLETED 8
 ;;IBCT SESSION NUMBER COMPLETED 5^MH IBCT SESSION NUMBER COMPLETED 5
 ;;IBCT SESSION NUMBER COMPLETED 2^MH IBCT SESSION NUMBER COMPLETED 2
 ;;IBCT THERAPY^MH IBCT THERAPY
 ;;IBCT 7 EARLY TERMINATION^MH IBCT 7 EARLY TERMINATION
 ;;IBCT DIRECT CHANGE STRATEGY^MH IBCT DIRECT CHANGE STRATEGY
 ;;IBCT TOLERANCE BUILD^MH IBCT TOLERANCE BUILD
 ;;IBCT UNIFIED DETACHMENT^MH IBCT UNIFIED DETACHMENT
 ;;IBCT EMPATHIC JOIN^MH IBCT EMPATHIC JOIN
 ;;IBCT PRACTICE NOT ASSIGNED^MH IBCT PRACTICE NOT ASSIGNED
 ;;IBCT PRACTICE NOT COMPLETE^MH IBCT PRACTICE NOT COMPLETE
 ;;IBCT PRACTICE COMPLETE^MH IBCT PRACTICE COMPLETE
 ;;IBCT SESSION NUMBER 5^MH IBCT SESSION NUMBER 5
 ;;IBCT SESSION NUMBER 6^MH IBCT SESSION NUMBER 6
 ;;IBCT SESSION NUMBER 7^MH IBCT SESSION NUMBER 7
 ;;IBCT SESSION NUMBER >24^MH IBCT SESSION NUMBER >24
 ;;IBCT SESSION NUMBER 24^MH IBCT SESSION NUMBER 24
 ;;IBCT SESSION NUMBER 20^MH IBCT SESSION NUMBER 20
 ;;IBCT SESSION NUMBER 18^MH IBCT SESSION NUMBER 18
 ;;IBCT SESSION NUMBER 17^MH IBCT SESSION NUMBER 17
 ;;IBCT SESSION NUMBER 15^MH IBCT SESSION NUMBER 15
 ;;IBCT SESSION NUMBER 14^MH IBCT SESSION NUMBER 14
 ;;IBCT SESSION NUMBER 13^MH IBCT SESSION NUMBER 13
 ;;IBCT SESSION NUMBER 11^MH IBCT SESSION NUMBER 11
 ;;IBCT SESSION NUMBER 10^MH IBCT SESSION NUMBER 10
 ;;IBCT SESSION NUMBER 9^MH IBCT SESSION NUMBER 9
 ;;IBCT SESSION NUMBER 23^MH IBCT SESSION NUMBER 23
 ;;IBCT SESSION NUMBER 22^MH IBCT SESSION NUMBER 22
 ;;IBCT SESSION NUMBER 21^MH IBCT SESSION NUMBER 21
 ;;IBCT SESSION NUMBER 19^MH IBCT SESSION NUMBER 19
 ;;IBCT SESSION NUMBER 16^MH IBCT SESSION NUMBER 16
 ;;IBCT SESSION NUMBER 12^MH IBCT SESSION NUMBER 12
 ;;IBCT SESSION NUMBER 8^MH IBCT SESSION NUMBER 8
 ;;IBCT 6 TERMINATION^MH IBCT 6 TERMINATION
 ;;IBCT 5 THERAPY^MH IBCT 5 THERAPY
 ;;IBCT WEEKLY QUESTIONNAIRE^MH IBCT WEEKLY QUESTIONNAIRE
 ;;IBCT FOCUS OVERVIEW^MH IBCT FOCUS OVERVIEW
 ;;IBCT DEEP^MH IBCT DEEP
 ;;IBCT FEEDBACK OVERVIEW^MH IBCT FEEDBACK OVERVIEW
 ;;IBCT SESSION NUMBER 4^MH IBCT SESSION NUMBER 4
 ;;IBCT SESSION NUMBER 3^MH IBCT SESSION NUMBER 3
 ;;IBCT 4 FEEDBACK^MH IBCT 4 FEEDBACK
 ;;IBCT SESSION NUMBER 2^MH IBCT SESSION NUMBER 2
 ;;IBCT 3 NON VETERAN^MH IBCT 3 NON VETERAN
 ;;IBCT 2 INDIVIDUAL^MH IBCT 2 INDIVIDUAL
 ;;IBCT SESSION NUMBER 1^MH IBCT SESSION NUMBER 1
 ;;IBCT 1 INITIAL^MH IBCT 1 INITIAL
 ;;
 Q
 ;
