START ; PROGRAM1; S LESIEUR, 8/19/99
 ; VERSION 3
 ; 
 ; VARIABLE LIST
 ;
 ; PRICE = PURCHASE PRICE
 ; INT   = INTEREST RATE
 ; TIME = TIME PERIOD IN YEARS
 ; FINCOST = FINANCE COST
 ; PURCOST = PURCHASE COST
 ; MONCOST = MONTHLY LEASE COST
 ; NRPAYM = NUMBER OF PAYMENTS
 ; LUMP = LUMP SUM PAYMENT
 ; TLEASE = TOTAL LEASE PAYMENTS
 ; TLEASEPUR = TOTAL LEASE-PURCHASE COST
INPUT ;
 WRITE !,"THE PURCHASE OPTION:"
 READ !!,"ENTER PURCHASE PRICE:",PRICE
 READ !,"ENTER INTEREST RATE:",INT
 READ !,"ENTER TIME PERIOD YRS:",TIME        
 SET FINCOST=PRICE*INT*TIME
 SET PURCOST=PRICE+FINCOST
 SET PAYMENT=PURCOST/(TIME*12)
 WRITE !!,"THE TOTAL PURCHASE IS $",PURCOST
 WRITE !,"MONTHLY PAYMENT IS $",PAYMENT
LEASE ;
 WRITE !!,"THE LEASE-PURCHASE OPTION"
 READ !,"ENTER MONTHLY LEASE COST:",MONCOST
 READ !,"ENTER NUMBER OF PAYMENTS:",NRPAYM
 READ !,"ENTERLUMP SUM:",LUMP
 SET TLEASE=MONCOST*NRPAYM
 SET TLEASPUR=TLEASE+LUMP
 WRITE !!,"THE TOTAL COST OF LEASE-PURCHASE IS$",TLEASPUR
DECISION ;
 IF PURCOST>TLEASPUR WRITE !!,"LEASE IT"
 IF TLEASPUR>PURCOST WRITE !!,"PURCHASE IT"
 IF TLEASPUR=PURCOST WRITE !!,"IT DOESN'T MATTER"
CHECK ;
 READ !,"DO YOU WANT TO DO ANOTHER?  YES//",ANSWER
 IF ANSWER="" GOTO INPUT        
 IF ANSWER=YES GOTO INPUT
 IF ANSWER=Y GOTO INPUT
EXIT ;
 KILL PRICE,INT,TIME,FINCOST,PURCOST,MONCOST,NRPAYM
 KILL LUMP,TLEASE,TLEASPUR,ANSWER
 QUIT
