START ;PROGRAM 2; S LESIEUR, 8/23/99
 ;VERSION 1
 ;
 ;VARIABLE LIST
INPUT ;
 WRITE !,"K-MART PRICE"
 READ !!,"ENTER RETAIL PRICE:",PRICE
 READ !,"ENTER DISCOUNT:",DISCOUNT
 SET SAVINGS=PRICE*DISCOUNT
 SET KMART=PRICE-SAVINGS
 WRITE !!,"THE DISCOUNTED K-MART PRICE IS $:",KMART
INPUTB ;
 WRITE !,"WALMART PRICE"
 READ !!,"ENTER RETAIL PRICE:",PRICE
 READ !,"ENTER DISCOUNT:",DISCOUNT
 SET SAVINGS=PRICE*DISCOUNT
 SET WALMART=PRICE-SAVINGS
 WRITE !!,"THE DISCOUNTED WALMART PRICE IS $:",WALMART
