SDES2VALCONTEXT ;ALB/MGD - ACHERON CONTEXT VALIDATION UTILITIES ;JUNE 08,2023
 ;;5.3;Scheduling;**853**;Aug 13, 1993;Build 9
 ;;Per VHA Directive 6402, this routine should not be modified
 ;
 Q
 ;
VALCONTEXT(SDERRORS,SDCONTEXT) ; Validate SDCONTEXT Array
 ; Required Input Variables
 D VALACHERONID(.SDERRORS,$G(SDCONTEXT("ACHERON AUDIT ID")))
 ; Optional Input Variables
 I $G(SDCONTEXT("PATIENT DFN"))'="" D VALPATDFN^SDES2VAL2(.SDERRORS,SDCONTEXT("PATIENT DFN"))
 I $G(SDCONTEXT("PATIENT ICN"))'="" D VALPATICN^SDES2VAL2(.SDERRORS,SDCONTEXT("PATIENT ICN"))
 I $G(SDCONTEXT("USER DUZ"))'="" D VALUSERDUZ^SDES2VAL200(.SDERRORS,SDCONTEXT("USER DUZ"))
 I $G(SDCONTEXT("USER SECID"))'="" D VALSECID^SDES2VAL200(.SDERRORS,SDCONTEXT("USER SECID"))
 Q
 ;
VALACHERONID(SDERRORS,SDACHERONID) ; Validate Acheron EAS ID
 I SDACHERONID="" D ERRLOG^SDES2JSON(.SDERRORS,474) Q
 I $$VALACHERONID^SDES2UTIL(SDACHERONID)=-1 D ERRLOG^SDES2JSON(.SDERRORS,475)
 Q
 ;
