SDES ;ALB/MGD,TAW,LAB,ANU - VISTA SCHEDULING RPCS ;Oct 6, 2021
 ;;5.3;Scheduling;**788,790,792,794,797,799,800,801**;Aug 13, 1993;Build 13
 ;;Per VHA Directive 6402, this routine should not be modified
 Q
 ; This routine documents the entry points for the new VS GUI version 3.0.
 ;
DISPOSITION(RET,ARIEN,DISP,DISPBY,DISPDT,EAS) ;RPC: SDES ARCLOSE
 D DISPOSITION^SDESARCLOSE(.RET,$G(ARIEN),$G(DISP),$G(DISPBY),$G(DISPDT),$G(EAS)) Q
ARGETIENJSON(RET,IEN) ;RPC: SDES GET PAT APPT REQ BY IEN
 D ARGETIENJSON^SDESARGET(.RET,IEN) Q
ARGETPATJSON(RET,DFN) ;RPC: SDES PATIENT APPT REQ GET
 D ARGETPATJSON^SDESARGET(.RET,DFN) Q
APPTBLOCKMOVE(RETURN,APPTIEN,SDRES,APPTDTTM,EAS) ; RPC: SDES CREATE APPT BLK AND MOVE
 D APPTBLOCKMOVE^SDESBLKANDMOVE(.RETURN,$G(APPTIEN),$G(SDRES),$G(APPTDTTM),$G(EAS)) Q
APPTBYCLINIC(JSON,CLINICIEN,SDBEG,SDEND) ;SDES GET APPT BY CLINIC
 D APPTBYCLINIC^SDESAPPT(.JSON,$G(CLINICIEN),$G(SDBEG),$G(SDEND)) Q
APPTBYRESOURCE(JSON,RESIEN,SDBEG,SDEND) ;SDES GET APPT BY RESOURCE
 D APPTBYRESOURCE^SDESAPPT(.JSON,$G(RESIEN),$G(SDBEG),$G(SDEND)) Q
APPGETJSON(JSON,DFN,SDBEG,SDEND) ;
 D APPGETJSON^SDESAPPT(.JSON,$G(DFN),$G(SDBEG),$G(SDEND)) Q
APPGETONEJSON(JSON,APPTIEN) ;
 D APPGETONEJSON^SDESAPPT(.JSON,$G(APPTIEN)) Q
 ; Parameter list for APTREQCREATE and APTREQUPDATE   *MUST*  be kept in sync.
APTREQCREATE(JSON,ARIEN,DFN,AREDT,ARINST,ARTYPE,ARCLIN,ARUSER,ARREQBY,ARPROV,ARDAPTDT,ARCOMM,ARENPRI,ARMAR,ARMAI,AMRAN,ARPATCONT,ARSVCCON,ARSVCCOP,MRTCDT,ARSTOP,ARAPTYP,ARPATSTAT,MULTAPTMDE,ARPARENT,ARNLT,ARPRER,ARORDN,VAOSGUID,EAS) ;
 S ARIEN=""  ;There will never be an IEN when calling this RPC
 D ARSET Q
APTREQUPDATE(JSON,ARIEN,DFN,AREDT,ARINST,ARTYPE,ARCLIN,ARUSER,ARREQBY,ARPROV,ARDAPTDT,ARCOMM,ARENPRI,ARMAR,ARMAI,AMRAN,ARPATCONT,ARSVCCON,ARSVCCOP,MRTCDT,ARSTOP,ARAPTYP,ARPATSTAT,MULTAPTMDE,ARPARENT,ARNLT,ARPRER,ARORDN,VAOSGUID,EAS) ;
 S ARIEN=$G(ARIEN,"")
 S:ARIEN="" ARIEN=-1  ;Flag missing ARIEN when calling the update RPC
 D ARSET Q
ARSET ;Called from APTREQCREATE and APTREQUPDATE tags
 S DFN=$G(DFN),AREDT=$G(AREDT),ARINST=$G(ARINST),ARTYPE=$G(ARTYPE),ARCLIN=$G(ARCLIN),ARUSER=$G(ARUSER),ARREQBY=$G(ARREQBY),ARPROV=$G(ARPROV),ARDAPTDT=$G(ARDAPTDT),ARCOMM=$G(ARCOMM),ARENPRI=$G(ARENPRI)
 S ARMAR=$G(ARMAR),ARMAI=$G(ARMAI),AMRAN=$G(AMRAN),ARPATCONT=$G(ARPATCONT),ARSVCCON=$G(ARSVCCON),ARSVCCOP=$G(ARSVCCOP),MRTCDT=$G(MRTCDT),ARSTOP=$G(ARSTOP),ARAPTYP=$G(ARAPTYP),ARPATSTAT=$G(ARPATSTAT)
 S MULTAPTMDE=$G(MULTAPTMDE),ARPARENT=$G(ARPARENT),ARNLT=$G(ARNLT),ARPRER=$G(ARPRER),ARORDN=$G(ARORDN),VAOSGUID=$G(VAOSGUID)
 S EAS=$G(EAS)
 ; Because of an SAC limitation on the number of chars per line, addition of more parameters will require
 ; this to be changed over to passing an array.
 D ARSET^SDESAPTREQSET(.JSON,ARIEN,DFN,AREDT,ARINST,ARTYPE,ARCLIN,ARUSER,ARREQBY,ARPROV,ARDAPTDT,ARCOMM,ARENPRI,ARMAR,ARMAI,AMRAN,ARPATCONT,ARSVCCON,ARSVCCOP,MRTCDT,ARSTOP,ARAPTYP,ARPATSTAT,MULTAPTMDE,ARPARENT,ARNLT,ARPRER,ARORDN,VAOSGUID,EAS)
 Q
 ;
CANCELAPPT(SDECY,APPTIEN,STATUS,CANREAS,USER,EAS) ;SDES CANCEL APPT - cancel appointment
 D CANCELAPPT^SDESCANCELAPPT(.SDECY,APPTIEN,STATUS,CANREAS,USER,EAS) Q
 ;
CHECKIN(JSON,SDECAPTID,SDECCDT,SDECCC,SDECPRV) ;SDES APPT CHECKIN JSON
 D CHECKIN^SDES25(.JSON,$G(SDECAPTID),$G(SDECCDT),$G(SDECCC),$G(SDECPRV)) Q
 ;
 ;The parameter list for the clinic create and set use generic parameter names to ensure we stay in SAC compliance
 ;with the length of a single line.
CLINICCREATE(RET,CLINIEN,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30,P31,P32,P33,P34,P35,P36,P37,P38,P39) ;
 ;CLINICCREATE(RET,CLINIEN,R1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29) ;
 S CLINIEN=""  ;There will never be an IEN when calling this RPC
 D CLINICSET Q
CLINICEDIT(RET,CLINIEN,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30,P31,P32,P33,P34,P35,P36,P37,P38,P39) ;
 S CLINIEN=$G(CLINIEN,"")
 S:CLINIEN="" CLINIEN=-1  ;Flag missing ARIEN when calling the update RPC
 D CLINICSET Q
CLINICSET  ;Called from CLINICCREATE and CLINICUPDATE tags
 S P1=$G(P1),P2=$G(P2),P3=$G(P3),P4=$G(P4),P5=$G(P5),P6=$G(P6),P7=$G(P7),P8=$G(P8),P9=$G(P9),P10=$G(P10),P11=$G(P11),P12=$G(P12),P13=$G(P13),P14=$G(P14),P15=$G(P15),P16=$G(P16),P17=$G(P17)
 S P18=$G(P18),P19=$G(P19),P20=$G(P20),P21=$G(P21),P22=$G(P22),P23=$G(P23)
 S P24=$G(P24),P25=$G(P25),P26=$G(P26),P27=$G(P27),P28=$G(P28),P29=$G(P29),P30=$G(P30),P31=$G(P31),P32=$G(P32),P33=$G(P33),P34=$G(P34),P35=$G(P35),P36=$G(P36),P37=$G(P37),P38=$G(P38),P39=$G(P39)
 D CLINICSET^SDESCLINICSET(.RET,CLINIEN,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,P17,P18,P19,P20,P21,P22,P23,P24,P25,P26,P27,P28,P29,P30,P31,P32,P33,P34,P35,P36,P37,P38,P39)
 Q
 ;
CLINICSEARCH(SDECY,SEARCHSTRING) ;Given a search string return a clinic list that matches.
 D CLINICSEARCH^SDESSEARCH(.SDECY,SEARCHSTRING) Q
CLINICRSCSEARCH(SDECY,SEARCHSTRING) ;Given a search string return a clinic list that matches.
 D CLINICRSC^SDES01C(.SDECY,SEARCHSTRING) Q
GETREGA(SDECY,DFN) ;SDES GET REGISTRATION INFO
 D GETREGA^SDESGETREGA(.SDECY,DFN) Q
INSURVERIFYREQ(JSON,DFN) ;SDES GET INSRUANCE VERIFY REQ
 D INSURVERIFYREQ^SDESPATRPC(.JSON,$G(DFN)) Q
SPACEBAR(SDECY,SDECDIC,SDECVAL) ;EP Update ^DISV with most recent lookup value SDECVAL from file SDECDIC
 D SPACEBAR^SDES30(.SDECY,$G(SDECDIC),$G(SDECVAL)) Q
JSONINACTCLN(SDEC,CLINICIEN) ;EP RPC: SDES INACTIVATE CLINIC
 D JSONINACTCLN^SDESINACTCLINIC(.SDEC,CLINICIEN) Q
JSONCLNINFO(SDEC,CLINICIEN) ;EP RPC: SDES GET CLINIC INFO
 D JSONCLNINFO^SDESRTVCLN(.SDEC,CLINICIEN) Q
SETCLINAVAIL(RETURN,SDCLINIC,DATES,TIMES,SLOTS) ; RPC: SDES SET CLINIC AVAILABILITY
 D SETCLINAVAIL^SDESCLNSETAVAIL(.RETURN,SDCLINIC,DATES,TIMES,SLOTS) Q
GETCLNAVAILABLTY(RET,CLINICIEN,SDESSTART,SDESENDDATE) ;EP RPC: SDES GET CLINIC AVAILABILITY-retrieve clinic availablity in a given timeframe
 D GETCLAVAILABLTY^SDESCLINICAVAIL(.RET,CLINICIEN,SDESSTART,SDESENDDATE) Q
CANCLNAVAILABLTY(RET,SDCLNIEN,SDESCANDATE,SDESSTRTIM,SDESENDTIM,SDCANREM) ;Called from RPC: SDES CANCEL CLINIC AVAILABILITY
 D CANCLAVAIL^SDESCCAVAIL(.RET,SDCLNIEN,SDESCANDATE,SDESSTRTIM,SDESENDTIM,SDCANREM) Q
GETUSRDTL(RET,SDUSRVPID) ;Called from RPC: SDES GET USER PROFILE
 D GETUSRDTL^SDESGETUD(.RET,SDUSRVPID) Q
 ;
 Q
