SDES2CRTCLNAVAL2 ;ALB/BLB,JDJ/BLB,JDJ,AGW,JDJ,AGW,AGW,AGW,AGW - SDES2 CREATE CLINIC AVAIL 2 ; JULY 15, 2026
 ;;5.3;Scheduling;**904,914,919,920,922,909,941,944,945,947,959**;Aug 13, 1993;Build 1
 ;;Per VHA Directive 6402, this routine should not be modified
 ; Reference to DUZ^XUP is supported by IA #7487
 ;
 Q
 ;
CREATE(JSON,SDCONTEXT,AVAILABILITY) ;
 N ERRORS,RETURNAVAIL,CLINICIEN,CLINICSTARTHOUR,NUMBEROFENTRIES,INPUTS,INDEFINITEUNTIL,SDDISPPERHR,SDCLINSTARTHR,SLOTSTOCANCEL,%,%DT
 N DIIX,X
 M INPUTS=AVAILABILITY
 D VALCONTEXT^SDES2VALCONTEXT(.ERRORS,.SDCONTEXT)
 I $D(ERRORS) S ERRORS("clinicAvailability")="" K CNT,I D BUILDJSON^SDES2JSON(.JSON,.ERRORS) Q
 I $G(SDCONTEXT("USER DUZ"))'="" N DUZ D DUZ^XUP(SDCONTEXT("USER DUZ"))
 D VALIDATE(.ERRORS,.AVAILABILITY,.CLINICIEN,.CLINICSTARTHOUR,.NUMBEROFENTRIES,.INPUTS)
 I $D(ERRORS) S ERRORS("clinicAvailability")="" K CNT,I D BUILDJSON^SDES2JSON(.JSON,.ERRORS) Q
 D CREATEAVAIL(.AVAILABILITY,.SDCONTEXT,.SLOTSTOCANCEL,CLINICIEN,CLINICSTARTHOUR,$$GET1^DIQ(44,CLINICIEN,1917,"I"),$$GET1^DIQ(44,CLINICIEN,1914,"I"),NUMBEROFENTRIES,.INPUTS,.INDEFINITEUNTIL,.RETURNAVAIL,.ERRORS)
 I $L($G(SLOTSTOCANCEL("CancelledSlots",1,"BeginTime"))),$G(AVAILABILITY("KEEP CANCELLED SLOTS"))=1 D
 .D RECANCELSLOTS(.SLOTSTOCANCEL,CLINICIEN,.SDCONTEXT) K SLOTSTOCANCEL
 I '$D(RETURNAVAIL) S RETURNAVAIL("clinicAvailability")=""
 D BUILDJSON^SDES2JSON(.JSON,.RETURNAVAIL)
 K CNT,I
 Q
 ;
CREATEAVAIL(AVAILABILITY,SDCONTEXT,SLOTSTOCANCEL,CLINICIEN,CLINICSTARTHOUR,SDDISPPERHR,SDCLINSTARTHR,NUMBEROFENTRIES,INPUTS,INDEFINITEUNTIL,RETURNAVAIL,ERRORS) ;
 N TIMESLOTCNT,CNT,ENDDATE,DATES,TIMES,NUMBEROFSLOTS,SCHEDULEDDAYS,DATENEXTTIMESLOT,CANSLOTSENDDATE,DONE,SDRETURN,SDONE,J,SDSAV,SDST1,SM,SS,SEQ,%H,ENDATE,SB,STARTDATE,CNT1,CANCELTYPE
 ;
 S TIMESLOTCNT=0,DONE=0
 F  S TIMESLOTCNT=$O(AVAILABILITY("TIMESLOT",TIMESLOTCNT)) Q:'TIMESLOTCNT!(DONE=1)  D
 .S CNT=0
 .F  S CNT=$O(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)) Q:'CNT  D
 ..I $G(SCHEDULEDDAYS)[$P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)),"T") Q
 ..D CREATEDATESTIMES(.DATES,.TIMES,.NUMBEROFSLOTS,.INPUTS,$P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)),"T"),NUMBEROFENTRIES,.SLOTSTOCANCEL)
 ..I $D(SLOTSTOCANCEL("Error")) M RETURNAVAIL=SLOTSTOCANCEL S DONE=1 Q
 ..S CNT1=0 F  S CNT1=$O(SLOTSTOCANCEL("CancelledSlots",CNT1)) Q:CNT1=""  D
 ...S STARTDATE=$$ISOTFM^SDAMUTDT($G(SLOTSTOCANCEL("CancelledSlots",CNT1,"BeginTime")),CLINICIEN)
 ...Q:STARTDATE=""
 ...S CANCELTYPE=$S(STARTDATE[".":"P",1:"F")
 ...I ((CANCELTYPE="P")&($G(^SC(CLINICIEN,"SDCAN",STARTDATE,0))="")) K SLOTSTOCANCEL("CancelledSlots",CNT1) Q
 ...I ((CANCELTYPE="F")&($G(^SC(CLINICIEN,"FULL DAY CANCEL",STARTDATE,1))="")) K SLOTSTOCANCEL("CancelledSlots",CNT1) Q
 ...I CANCELTYPE="P" S SLOTSTOCANCEL("CancelledSlots",CNT1,"Remarks")=$G(^SC(CLINICIEN,"S",STARTDATE,"MES"))
 ...I CANCELTYPE="F" S SLOTSTOCANCEL("CancelledSlots",CNT1,"Remarks")=$G(^SC(CLINICIEN,"FULL DAY CANCEL",STARTDATE,1))
 ...Q
 ..D CREATEAVAIL^SDES2UTIL1(.SDRETURN,CLINICIEN,$G(DATES),$G(TIMES),$G(NUMBEROFSLOTS),.INDEFINITEUNTIL)
 ..I ($G(INPUTS("TIMESLOT",TIMESLOTCNT,"NUMBER OF SLOTS",CNT))="@")&($G(INPUTS("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT))=1) D
 ...N STARTDATE,TDAY
 ...S STARTDATE=$G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT))
 ...S STARTDATE=$P($G(STARTDATE),";",1),STARTDATE=$$ISOTFM^SDAMUTDT(STARTDATE)
 ...S TDAY=$$DOW^XLFDT(STARTDATE,1)
 ...S INDEFINITEUNTIL=$O(^SC(CLINICIEN,"T"_TDAY,STARTDATE))
 ...S:INDEFINITEUNTIL=9999999 INDEFINITEUNTIL=""
 ...S:INDEFINITEUNTIL'="" INDEFINITEUNTIL=$$FMTISO^SDAMUTDT(INDEFINITEUNTIL)
 ...Q
 ..K DATES,TIMES,NUMBEROFSLOTS
 ..S RETURNAVAIL("clinicAvailability",CNT,"Pattern")="Pattern Filed"
 ..S RETURNAVAIL("clinicAvailability",CNT,"DateIndefiniteScheduleEnds")=$G(INDEFINITEUNTIL) K INDEFINITEUNTIL
 ..S SCHEDULEDDAYS=$G(SCHEDULEDDAYS)_$P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)),"T")_U
 Q
 ;
CREATEDATESTIMES(DATES,TIMES,NUMBEROFSLOTS,INPUTS,AVAILABILITYDATE,NUMBEROFENTRIES,SLOTSTOCANCEL) ;
 N TIMESLOTCNT,CNT,SUBSCRIPT,STARTDATE,STARTTIME,ENDTIME,LASTTIMESLOTDATE,DONE,CANSLOTSENDDATE,DATENEXTTIMESLOT,TIME
 S TIMESLOTCNT=0,DONE=0
 F  S TIMESLOTCNT=$O(INPUTS("TIMESLOT",TIMESLOTCNT)) Q:'TIMESLOTCNT!(DONE=1)  D
 .S CNT=0
 .F  S CNT=$O(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)) Q:'CNT  D
 ..I $P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)),"T")'=AVAILABILITYDATE Q
 ..I $G(INPUTS("TIMESLOT",TIMESLOTCNT,"NUMBER OF SLOTS",CNT))="@" D  Q
 ...S DATES=$G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT))_$S($G(INPUTS("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT)):";9999999",1:"")
 ...S NUMBEROFSLOTS=""
 ..S LASTTIMESLOTDATE=0,LASTTIMESLOTDATE=$O(DATES(LASTTIMESLOTDATE))
 ..I $G(LASTTIMESLOTDATE)=$$ISOTFM^SDAMUTDT($P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)),"T"))!('$G(LASTTIMESLOTDATE)) D
 ...S DATES=$$ISOTFM^SDAMUTDT($P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)),"T"))
 ...S TIMES=$G(TIMES)_$P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)),"T",2)_"-"_$P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"END DATE TIME",CNT)),"T",2)_";"
 ...S NUMBEROFSLOTS=$G(NUMBEROFSLOTS)_$G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"NUMBER OF SLOTS",CNT))_";"
 ..I $G(INPUTS("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT)),'$D(DATES(9999999)) D
 ...S DATES=$G(DATES)_";9999999"
 ..S DATENEXTTIMESLOT=$$ISOTFM^SDAMUTDT($P($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)),"T"))
 ..S CANSLOTSENDDATE=$S($G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT)):$$GETLASTINDEFDATE(CLINICIEN,DATENEXTTIMESLOT),1:DATENEXTTIMESLOT)
 ..I $G(INPUTS("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT)) D  Q
 ...S DONE=0
 ...F  Q:(DATENEXTTIMESLOT>CANSLOTSENDDATE)  D
 ....D GETCANSLOTS(CLINICIEN,.SLOTSTOCANCEL,$G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT)),CANSLOTSENDDATE,CNT,$$FMTISO^SDAMUTDT(DATENEXTTIMESLOT),.INPUTS,.SDCONTEXT)
 ....S DATENEXTTIMESLOT=$$FMADD^XLFDT(DATENEXTTIMESLOT,7)
 ..D GETCANSLOTS(CLINICIEN,.SLOTSTOCANCEL,$G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT)),CANSLOTSENDDATE,CNT,$$FMTISO^SDAMUTDT(DATENEXTTIMESLOT),.INPUTS,.SDCONTEXT)
 S TIMES=$E($G(TIMES),1,$L($G(TIMES))-1)
 I $G(NUMBEROFSLOTS)'="" D
 .S NUMBEROFSLOTS=$E($G(NUMBEROFSLOTS),1,$L($G(NUMBEROFSLOTS))-1)
 Q
 ;
GETLASTINDEFDATE(CLINICIEN,DATE) ;
 N FOUND,OSTDATE,LASTSTDATE,STDATE,STDATE1
 ;
 S LASTSTDATE=$$FMADD^XLFDT(DT,1000)
 S LASTSTDATE=$O(^SC(CLINICIEN,"ST",LASTSTDATE),-1)
 S (STDATE,STDATE1)=DATE
 S FOUND=0
 F  Q:(STDATE1>LASTSTDATE)!(STDATE1=-1)  D
 .S STDATE1=$$FMADD^XLFDT(STDATE1,7)
 .I ($G(^SC(CLINICIEN,"ST",STDATE1,0))'="") S STDATE=STDATE1
 Q $G(STDATE)
 ;
RECANCELSLOTS(SLOTSTOCANCEL,CLINICIEN,SDCONTEXT) ;
 N CNT,CANCEL,CANCELRETURN
 ;
 S CNT=0
 F  S CNT=$O(SLOTSTOCANCEL("CancelledSlots",CNT)) Q:'CNT  D
 .K CANCEL
 .S CANCEL("CLINIC IEN")=CLINICIEN
 .S CANCEL("FULL PARTIAL FLAG")=$S($G(SLOTSTOCANCEL("CancelledSlots",CNT,"BeginTime"))["T":"P",1:"F")
 .S CANCEL("START DATE TIME")=$G(SLOTSTOCANCEL("CancelledSlots",CNT,"BeginTime"))
 .S CANCEL("END DATE TIME")=$G(SLOTSTOCANCEL("CancelledSlots",CNT,"EndTime"))
 .S CANCEL("REMARKS")=$G(SLOTSTOCANCEL("CancelledSlots",CNT,"Remarks"))
 .D CANCEL^SDES2CANCLNAVAIL(.CANCELRETURN,.SDCONTEXT,.CANCEL)
 Q
 ;
GETCANSLOTS(CLINICIEN,SLOTSTOCANCEL,INDEFINITE,ENDDATE,CNT,SCHEDULEDATE,INPUTS,SDCONTEXT) ;
 N CANSLOTS,JSON,SLOTS,NUM,SLOTNUM
 ;
 I $$GET1^DIQ(44.005,$$ISOTFM^SDAMUTDT(SCHEDULEDATE)_","_CLINICIEN_",",1,"I")["CANCELLED" D
 .S NUM=(+($O(SLOTSTOCANCEL("CancelledSlots",""),-1))+1)
 .S SLOTSTOCANCEL("CancelledSlots",NUM,"BeginTime")=SCHEDULEDATE
 .S SLOTSTOCANCEL("CancelledSlots",NUM,"EndTime")=SCHEDULEDATE
 S CANSLOTS("CLINICIEN")=CLINICIEN
 S CANSLOTS("SDESSTART")=SCHEDULEDATE_"T"_"0001"_$$GETTZOFFSET^SDESUTIL($$ISOTFM^SDAMUTDT(SCHEDULEDATE),CLINICIEN)
 S CANSLOTS("SDESENDDATE")=SCHEDULEDATE_"T"_2359_$$GETTZOFFSET^SDESUTIL($$ISOTFM^SDAMUTDT(SCHEDULEDATE),CLINICIEN)
 D GETCANCSLOTS^SDES2GETCANSLOTS(.JSON,.SDCONTEXT,.CANSLOTS) K CANSLOTS
 D DECODE^XLFJSON("JSON","SLOTS")
 I $D(SLOTSTOCANCEL("CancelledSlots",1,"BeginTime")),$L($G(SLOTS("CancelledSlots",1,"BeginTime"))) D  Q
 .S NUM="",NUM=$O(SLOTSTOCANCEL("CancelledSlots",NUM),-1)
 .S SLOTNUM=0
 .F  S SLOTNUM=$O(SLOTS("CancelledSlots",SLOTNUM)) Q:'SLOTNUM  D
 ..S NUM=NUM+1
 ..S SLOTSTOCANCEL("CancelledSlots",NUM,"BeginTime")=$G(SLOTS("CancelledSlots",SLOTNUM,"BeginTime"))
 ..S SLOTSTOCANCEL("CancelledSlots",NUM,"EndTime")=$G(SLOTS("CancelledSlots",SLOTNUM,"EndTime"))
 I $D(SLOTS("CancelledSlots",1,"BeginTime")) D
 .M SLOTSTOCANCEL=SLOTS
 S SCHEDULEDATE=$$FMADD^XLFDT(SCHEDULEDATE,7) K SLOTS
 Q
 ;
VALIDATE(ERRORS,AVAILABILITY,CLINICIEN,CLINICSTARTHOUR,NUMBEROFENTRIES,INPUTS) ;
 N FDATA,VAL,TIMESLOTCNT,DATETIMECNT
 ;
 D VALFILEIEN^SDES2VALUTIL(.VAL,.ERRORS,44,$G(AVAILABILITY("CLINIC IEN")),1,,18,19)
 I $D(ERRORS) Q
 S CLINICIEN=$G(AVAILABILITY("CLINIC IEN"))
 S CLINICSTARTHOUR=$$GET1^DIQ(44,CLINICIEN,1914,"I")
 S NUMBEROFENTRIES=$O(AVAILABILITY("TIMESLOT",""),-1)
 S TIMESLOTCNT=0
 F  S TIMESLOTCNT=$O(AVAILABILITY("TIMESLOT",TIMESLOTCNT)) Q:'TIMESLOTCNT  D
 .S DATETIMECNT=0
 .F  S DATETIMECNT=$O(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",DATETIMECNT)) Q:'DATETIMECNT  D
 ..S INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",DATETIMECNT)=$TR($G(INPUTS("TIMESLOT",TIMESLOTCNT,"START DATE TIME",DATETIMECNT)),":","")
 ..S INPUTS("TIMESLOT",TIMESLOTCNT,"END DATE TIME",DATETIMECNT)=$TR($G(INPUTS("TIMESLOT",TIMESLOTCNT,"END DATE TIME",DATETIMECNT)),":","")
 I $L($G(AVAILABILITY("KEEP CANCELLED SLOTS"))) D
 .I $G(AVAILABILITY("KEEP CANCELLED SLOTS"))'=1,$G(AVAILABILITY("KEEP CANCELLED SLOTS"))'=0 D ERRLOG^SDES2JSON(.ERRORS,656)
 D VALFILEIEN^SDES2VALUTIL(.VAL,.ERRORS,44,CLINICIEN,1,,18,19)
 D VALAPPTLENGTH(.ERRORS,$$GET1^DIQ(44,CLINICIEN,1912,"I"),CLINICIEN) Q:$D(ERRORS)
 D VALSTARTHOUR^SDES2VAL44(.ERRORS,.CLINICSTARTHOUR)
 D VALIDATEDATETIME^SDES2CRTCLNAVL2B(.ERRORS,CLINICIEN,.AVAILABILITY,NUMBEROFENTRIES)
 D VALIDATESLOTS(.ERRORS,.AVAILABILITY)
 D VALIDATEINDEF(.ERRORS,.AVAILABILITY)
 D PATTERNLENGTH^SDES2CRTCLNAVL2B(.ERRORS,.AVAILABILITY,CLINICIEN,CLINICSTARTHOUR,$$GET1^DIQ(44,CLINICIEN,1917,"I"))
 Q
 ;
VALIDATEINDEF(ERRORS,AVAILABILITY) ;
 N TIMESLOTCNT,CNT
 ;
 I '$D(AVAILABILITY("TIMESLOT",1,"INDEFINITE",1)) D ERRLOG^SDES2JSON(.ERRORS,592) Q
 S TIMESLOTCNT=0
 F  S TIMESLOTCNT=$O(AVAILABILITY("TIMESLOT",TIMESLOTCNT)) Q:'TIMESLOTCNT!($D(ERRORS))  D
 .S CNT=0
 .F  S CNT=$O(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)) Q:'CNT  D
 ..I $G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT))="" D ERRLOG^SDES2JSON(.ERRORS,592) Q
 ..I '$D(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT)) D ERRLOG^SDES2JSON(.ERRORS,592) Q
 ..I $G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT))'=1,$G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"INDEFINITE",CNT))'=0 D ERRLOG^SDES2JSON(.ERRORS,591) Q
 Q
 ;
VALAPPTLENGTH(ERRORS,LENGTH,CLINICIEN) ;
 I LENGTH="" D ERRLOG^SDES2JSON(.ERRORS,115) Q
 I ((LENGTH<10)!(LENGTH>240)) D ERRLOG^SDES2JSON(.ERRORS,116) Q
 I (LENGTH#10'=0),(LENGTH#15'=0) D ERRLOG^SDES2JSON(.ERRORS,116) Q
 Q
 ;
VALIDATESLOTS(ERRORS,AVAILABILITY) ;
 ;
 N TIMESLOTCNT,CNT,ISEMDEPT
 S ISEMDEPT=0
 I $$GET1^DIQ(40.7,$$GET1^DIQ(44,CLINICIEN,8,"I"),1,"I")="130" S ISEMDEPT=1
 I '$D(AVAILABILITY("TIMESLOT",1,"NUMBER OF SLOTS",1)) D ERRLOG^SDES2JSON(.ERRORS,309) Q
 S TIMESLOTCNT=0
 F  S TIMESLOTCNT=$O(AVAILABILITY("TIMESLOT",TIMESLOTCNT)) Q:'TIMESLOTCNT!($D(ERRORS))  D
 .S CNT=0
 .F  S CNT=$O(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"START DATE TIME",CNT)) Q:'CNT  D
 ..I $G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"NUMBER OF SLOTS",CNT))="@" Q
 ..I '$D(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"NUMBER OF SLOTS",CNT)) D ERRLOG^SDES2JSON(.ERRORS,309) Q
 ..I $G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"NUMBER OF SLOTS",CNT))=0,ISEMDEPT=1 Q
 ..I $G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"NUMBER OF SLOTS",CNT))<1!($G(AVAILABILITY("TIMESLOT",TIMESLOTCNT,"NUMBER OF SLOTS",CNT))>26) D ERRLOG^SDES2JSON(.ERRORS,125)
 Q
