SDMLST ;RGI/CBR - Lists Utils; 08/31/2012
 ;;5.3;scheduling;**260003**;08/13/93;Build 8
LSTCLNS(RETURN,SEARCH,START,NUMBER) ; Lists clinics
 S %=$$LSTCLNS^SDMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTPATS(RETURN,SEARCH,START,NUMBER) ; Lists patients
 S %=$$LSTPATS^SDMAPI3(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTCRSNS(RETURN,SEARCH,START,NUMBER) ; Lists cancellation reasons
 S %=$$LSTCRSNS^SDMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTETNS(RETURN,SEARCH,START,NUMBER) ; Lists ethnics
 S %=$$LSTETNS^SDMAPI3(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTRACES(RETURN,SEARCH,START,NUMBER) ; Lists races
 S %=$$LSTRACES^SDMAPI3(.RETURN,.SEARCH,.START,.NUMBER)
 Q
GETPRES(RETURN,SEARCH) ; Lists patient races
 S %=$$GETPRES^SDMAPI3(.RETURN,.DFN)
 Q
LSTAPCTM(RETURN,SEARCH,START,NUMBER) ; Lists active primary care teams
 S SEARCH(0)=1
 S %=$$LSTATMS^SCTMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTATMS(RETURN,SEARCH,START,NUMBER) ; Lists active teams
 S %=$$LSTATMS^SCTMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTAPRPO(RETURN,SEARCH,START,NUMBER) ; Lists active primary care practitioners
 S SEARCH(0)=SCTM,SEARCH(1)=1
 S %=$$LSTAPRPO^SCTMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTAPRS(RETURN,SEARCH,START,NUMBER) ; Lists active practitioners
 S SEARCH(0)=SCTM
 S %=$$LSTAPRPO^SCTMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTAPOS(RETURN,SEARCH,START,NUMBER) ; Lists active positions
 S SEARCH(0)=SCTM
 S %=$$LSTAPOS^SCTMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
LSTAPCPO(RETURN,SEARCH,START,NUMBER) ; Lists active primary care positions
 S SEARCH(0)=SCTM,SEARCH(1)=1
 S %=$$LSTAPOS^SCTMAPI1(.RETURN,.SEARCH,.START,.NUMBER)
 Q
