SDMRPC4 ;MTZ/CKU - APPOINTMENT RPC; 11/08/2012  3:03 PM
 ;;6.0;Scheduling;;11/08/2012;Build 9
 Q
CHECKO(RV,DFN,SD,SC) ; SD APPOINTMENT CHECK-OUT 
 N STATUS,RESULT S STATUS=$$CHECKO^SDMAPI4(.RESULT,DFN,SD,SC)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
DELCO(RV,DFN,SD) ; SD APPOINTMENT CHECK-OUT DEL
 N STATUS,RESULT S STATUS=$$DELCO^SDMAPI4(.RESULT,DFN,SD)
 D MERGE^SDMRPC(.RV,.RESULT)
 Q
